### PR TITLE
Switch async to defer for Chartbeat script

### LINKED ISSUE #6326: Chartbeat causes large increase in load event/fully loaded
**Describe the bug**
Time to load event and fully loaded shows 30-40% increase since Chartbeat was enabled. See the following graph taken from SpeedCurve (i.e. WebPageTest):

image

Tests run using:
- Chrome - Ireland
- 5000/1000 Kbps, 28ms Latency

This was raised with the vendor who recommended we use `defer` instead of `async` to mitgate this, giving this example:

```
<script defer="true" type="text/javascript" src="//static.chartbeat.com/js/chartbeat.js" data-react-helmet="true"></script>
```

**Testing notes**
- [ ] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by rebeccamcginn**
Resolves #6326

**Overall change:**
Chartbeat caused an increase in load event/fully loaded when added to our pages. This PR switches out the async attribute for the defer attribute.

**Code changes:**

- Change from async to defer attribute

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project
- [ ] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

File: src/app/containers/ChartbeatAnalytics/canonical/index.jsx [hunk 1]
```diff
@@ -29,7 +29,7 @@ const CanonicalChartbeatBeacon = ({ chartbeatConfig }) => {
         })();
       `}
       </script>
-      <script async type="text/javascript" src={chartbeatSource} />
+      <script defer type="text/javascript" src={chartbeatSource} />
```
Comment (pvaliani) [inline src/app/containers/ChartbeatAnalytics/canonical/index.jsx:32]: Just to clarify, with this change Chartbeat won't load until the full document has been parsed?

Comment (rebeccamcginn) [reply src/app/containers/ChartbeatAnalytics/canonical/index.jsx:32]: With `async`, we download the script in parallel to parsing the page, and execute it as soon as it is available.

With `defer`, we download the script in parallel to parsing the page, but don't execute it until after parsing is finished.

**Review by ryanmccombe — APPROVED** [review]

**Review by pvaliani — APPROVED** [review]
