### PR TITLE
Fix structured data errors

### LINKED ISSUE #2426: Frontpages structured data error
**Describe the bug**
https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fwww.stage.bbc.co.uk%2Figbo

**Expected behavior**
Value `@type` should be a known type, (to be confirmed)

**Additional context**

### PR DESCRIPTION
**Pull request by ghost**
Resolves #2426

**Overall change:** Change metadata type in front pages from `IDX` to more relevant values

**Code changes:**

- Don't use the `metadata.type` value from the data feed(s)
- Do set page type metadata using `pageType` from `RequestContext` to detect, well, page type

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [x] Test engineer approval

### CODE REVIEW

**Review by amywalkerdev — DISMISSED** [review]
This only fixes it for our example data, pulling in the metadata type from the data feed is incorrect as IDX is not a valid metadata type. Responsive news has the correct type of 'website', unsure if they hard code this? Can @jblaut see where we got the value from previously?

**Comment by ghost** [comment]
@amywalker1987 I also thought this was a data feed issue. But one way to go about it would be to check weather the `type` given to `Metadata` is `IDX`, if it is we set the `og:type` to `website`

**Comment by andrew-nowak** [comment]
The `schema.org` metadata `@type` is also wrong; not just the `og:type`

**Comment by amywalkerdev** [comment]
> The `schema.org` metadata `@type` is also wrong; not just the `og:type`

Good spot. schema.org one should be `WebPage` https://schema.org/WebPage

**Comment by andrew-nowak** [comment]
I'm not sure that taking the value from `metadata.type` is actually correct - CPS articles also don't fill that with `article` (they use eg. `STY`). I haven't seen/can't find optimo data specs, so don't know what that field is actually supposed to represent.

It might be better/safer to set these values ourselves based on the page type -

| pageType | `og:type` | `schema.org`/`ld+json`:`@type` |
| ----- | ---- | ----- |
| `article` | `article` | `Article` |
| `frontPage` | `website` | `WebPage` |

**Review by j-pendlebury — APPROVED** [review]

File: src/app/containers/Metadata/index.jsx [hunk 1]
```diff
@@ -179,9 +189,9 @@ const MetadataContainer = ({ metadata, promo }) => {
         title={getTitle(promo)}
         twitterCreator={twitterCreator}
         twitterSite={twitterSite}
-        type={assetType}
+        type={deepGet([pageType, 'openGraph'], pageTypeMetadata)}
```
Comment (dr3) [inline src/app/containers/Metadata/index.jsx:192]: Not the keenest, as this could return null for unknown page types, and the component has it as a required prop, but will do for now

**Review by dr3 — APPROVED** [review]

**Review by pjlee11 — APPROVED** [review]

**Comment by david-boydell** [comment]
Looks good, this is ready for merge.
