### PR TITLE
Make client side data fetch relative

### LINKED ISSUE #811: Client makes request to localhost for inline links
**Describe the bug**
We are currently getting a CORS error on www.test which breaking the E2E's on TEST. This is because [this PR](https://github.com/BBC-News/simorgh/pull/796) removed the use of relative URLs on the client requests which had the knock on affect of the application requesting data via an absolute URL. 

The screenshot below details this in the scenario where a user clicks the inline link from scenario 25 to scenario 27:

image

### PR DESCRIPTION
**Pull request by pjlee11**
Resolves #811 

This PR stabilises the build after the merge of https://github.com/BBC-News/simorgh/pull/796 broken the E2E tests on the TEST env. This was because the RAZZLE_BASE_PATH is not currently set on test and therefore the logic to remove relative data fetches caused a CORS error trying to request `localhost:/7080/data*` instead of `/data*`. This PR undoes the logic to make the data fetch path's absolute. 

- [x] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

File: src/app/routes/getInitialData/index.js [hunk 1]
```diff
@@ -4,9 +4,12 @@ const getInitialData = async ({ match }) => {
   try {
     const { id, service, amp } = match.params;
 
-    const url = `${
-      process.env.RAZZLE_BASE_PATH
-    }/${service}/articles/${id}.json`;
+    let url = `/data/${service}/articles/${id}.json`;
```
Comment (pjlee11) [inline src/app/routes/getInitialData/index.js:7]: For context this is just being changed back to what it was previously https://github.com/BBC-News/simorgh/pull/796/files#diff-0679334769cd96b7ad47b858903e3849L7

**Review by jtart — APPROVED** [review]

**Review by BogdanDogaru — APPROVED** [review]
