### PR TITLE
Front Page section margin

### LINKED ISSUE #3889: Wrong padding for section dividers
**Describe the bug**
There are wrong paddings for section dividers (one is 16px and another one is 32px).  It seems that the wrong padding is applied when there is only one story promo in the group.

See the screenshot below:
Screenshot 2019-09-19 at 11 12 43

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a WS front page of e.g. Thai service
2. Scroll down to a section with one story promo in the group
3. See error

**Expected behaviour**
Padding  should be 24 px between divider and item below. See the screenshot below or check Zeplin:

Screenshot 2019-09-19 at 11 16 01

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by DenisHdz**
Resolves #3889

**Overall change:** 
Fix margin issues with the front page sections when there is just one promo.

**Code changes:**
- Update margin values
- Refactor `MarginWrapper` logic.
- Create `FirstSectionTopMargin` styled component to apply the right margin-top to the first section of the page when there is one or multiple items.
- Create `TopMargin` styled component to apply the right margin-top between the section label and the promos when there is **one** item.

---

- [X] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [X] This PR requires manual testing

### CODE REVIEW

**Comment by DenisHdz** [comment]
Review and confirm with UX that the top story promo and the first promo in a section should have the following top margin:
- 16px
- 24px > 600px
- 32px > 1008px

**Comment by DenisHdz** [comment]
> Review and confirm with UX that the top story promo and the first promo in a section should have the following top margin:
> 
>     * 16px
> 
>     * 24px > 600px
> 
>     * 32px > 1008px

Reviewed with UX and agreed to leave it as follows:

- **Top story promo margin**
0-399px 8px
400-599px 16px
600-1007px 24px
1008+ 32px

- **Top margin between Section divider and promos (one promo or a list of promos)**
0-599px no margin
600+ 16px
1008px+ 24px

**Review by Bopchy — APPROVED** [review]

File: src/app/containers/FrontPageSection/index.jsx [hunk 1]
```diff
@@ -103,19 +126,21 @@ const FrontPageSection = ({ bar, group, sectionNumber }) => {
...
+                  sectionNumber={sectionNumber}
+                  storyNumber={index}
+                />
+              </StoryPromoLi>
+            ))}
+          </StoryPromoUl>
         </MarginWrapper>
       ) : (
-        <MarginWrapper addMargin={!isFirstSection}>
+        <MarginWrapper firstSection={isFirstSection} oneItem>
```
Comment (j-pendlebury) [inline src/app/containers/FrontPageSection/index.jsx:143]: I'm assuming `oneItem` is a boolean, if so could you rename it to `isOneItem`?

Comment (DenisHdz) [reply src/app/containers/FrontPageSection/index.jsx:143]: I didn't want to name it `isOneItem` because it doesn't get the right value from above (as `firstSection`), it is always set to true (oneItem={true}) because we pass it just when there is one promo.

**Review by AlistairGempf — APPROVED** [review]
Looks good to me.

**Review by j-pendlebury — APPROVED** [review]

**Comment by paruchurisilpa** [comment]
LGTM..
