### PR TITLE
Fix invalid css

### LINKED ISSUE #2188: Invalid css - Padding auto
**Describe the bug**
Introduced by https://github.com/bbc/simorgh/pull/1900, a padding value of `auto` isn't valid CSS 

**To Reproduce**
See https://github.com/bbc/simorgh/blob/latest/src/app/lib/layoutGrid/index.js#L132

**Expected behavior**
We dont use 'auto' for padding

**Additional context**
See https://www.w3.org/TR/CSS22/box.html#padding-properties for spec

### PR DESCRIPTION
**Pull request by jroebu14**
Resolves https://github.com/bbc/simorgh/issues/2188

**Overall change:** Remove invalid `auto` CSS value and replace with default value `0`

**Code changes:**

- Uses `deepGet` method to safely get padding value.
- Replace `auto` with `0` for default padding.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by dr3 — DISMISSED** [review]

File: src/app/lib/layoutGrid/index.js [hunk 1]
```diff
@@ -129,13 +130,13 @@ export const layoutGridItemMedium = css`
 
   grid-column: 1 / span 6;
   @media (max-width: ${GEL_GROUP_2_SCREEN_WIDTH_MAX}) {
-    padding: 0 ${props => (props.padding && props.padding.group2) || 'auto'};
+    padding: 0 ${props => deepGet(['padding', 'group2'], props) || ''};
```
Comment (sareh) [inline src/app/lib/layoutGrid/index.js]: It'd be clearer to change to this:
```suggestion
    padding: 0 ${({ padding }) => (padding && padding.group2) || ''};
```

File: src/app/lib/layoutGrid/index.js [hunk 2]
```diff
@@ -129,13 +130,13 @@ export const layoutGridItemMedium = css`
...
   }
 
   @media (min-width: ${GEL_GROUP_3_SCREEN_WIDTH_MIN}) {
     grid-column: 1 / span 5;
     max-width: ${fiveOfSixColumnsMaxWidthScaleable};
-    padding: 0 ${props => (props.padding && props.padding.group3) || 'auto'};
+    padding: 0 ${props => deepGet(['padding', 'group3'], props) || ''};
```
Comment (sareh) [inline src/app/lib/layoutGrid/index.js]:
```suggestion
    padding: 0 ${({ padding }) => padding.group3 || ''};
```

File: src/app/lib/layoutGrid/index.js [hunk 3]
```diff
@@ -158,7 +159,7 @@ export const layoutGridItemSmall = css`
   @media (max-width: ${GEL_GROUP_2_SCREEN_WIDTH_MIN}) {
     grid-column: 1 / span 6;
     padding: 0
-      ${props => (props.padding && props.padding.group2) || 'auto'};
+      ${props => deepGet(['padding', 'group2'], props) || ''};
```
Comment (sareh) [inline src/app/lib/layoutGrid/index.js]:
```suggestion
      ${({ padding }) => padding.group2 || ''};
```

File: src/app/lib/layoutGrid/index.js [hunk 4]
```diff
@@ -168,7 +169,7 @@ export const layoutGridItemSmall = css`
     grid-column: 1 / span 5;
     max-width: ${fiveOfSixColumnsMaxWidthScaleable};
     padding: 0
-      ${props => (props.padding && props.padding.group3) || 'auto'};
+      ${props => deepGet(['padding', 'group3'], props) || ''};
```
Comment (sareh) [inline src/app/lib/layoutGrid/index.js]:
```suggestion
      ${({ padding }) => padding.group3 || ''};
```

**Review by sareh — CHANGES_REQUESTED** [review]
Looks good so far. It'd be clearer to use destructured props, rather than deepGet for these functions.

File: src/app/lib/layoutGrid/index.js (hunk 4 above)
Comment (jroebu14) [reply src/app/lib/layoutGrid/index.js]: We would still need to check padding is not undefined though.

We can still use de-structuring but I don't see any benefit because it would make those lines of code longer.

Comment (sareh) [reply src/app/lib/layoutGrid/index.js]: Ah yes, apologies, it'd need to be ` ${({ padding }) => (padding && padding.group3) || ''};`.  Having discussed [an upcoming issue this morning](https://github.com/bbc/simorgh/issues/2149#issuecomment-507219978) that will shortly remove these bespoke props entirely, I'm happy to have this merged in as it currently is.

**Review by sareh — DISMISSED** [review]

**Comment by sareh** [comment]
**Testing notes for this PR:**
There should be no visual regression of padding on the square image, portrait image, and paragraphs here: http://localhost.bbc.com:7080/news/articles/c5jje4ejkqvo

**Comment by PriyaKR** [comment]
Testing:
http://localhost.bbc.com:7080/news/articles/c5jje4ejkqvo

For some reasons the images doesnt seem to appear on the page(issue is also on latest branch).But at smaller viewports there is no padding between the test and the margin.Refer latest and fix-invalid-css branch screenshot for comparisons.
fix-invalid-css
latest

**Comment by jroebu14** [comment]
Thanks @PriyaKR I'm taking a look into this.

**Comment by jamesbrumpton** [comment]
image
Finding issues with the padding on the text components at reduced viewport sizes. See screenshot for example. :)

**Comment by jroebu14** [comment]
On latest, because of the invalid CSS, it falls back to using the last relevant media query's padding value.

image

**Comment by jroebu14** [comment]
@sareh @pjlee11 I fixed the padding and margin issue by updating the code in `src/app/lib/layoutGrid/index.js` to only override the padding or margin values when the component is provided with them through props.

File: src/app/lib/layoutGrid/index.js [hunk 5]
```diff
@@ -129,13 +129,13 @@ export const layoutGridItemMedium = css`
 
   grid-column: 1 / span 6;
   @media (max-width: ${GEL_GROUP_2_SCREEN_WIDTH_MAX}) {
-    padding: 0 ${props => (props.padding && props.padding.group2) || 'auto'};
+    ${({ padding: { group2 } = {} }) => (group2 ? `padding: 0 ${group2}` : '')};
```
Comment (pjlee11) [inline src/app/lib/layoutGrid/index.js]: In this syntax how is the value being pulled from props?

Comment (pjlee11) [reply src/app/lib/layoutGrid/index.js]: `${({ padding = {} }) => (padding.group2 && `padding: 0 ${padding.group2}`)};`

I think this might be easier to read, but I'm happy either way

Comment (pjlee11) [inline src/app/lib/layoutGrid/index.js]: I think I prefer ```${({ padding = {} }) => (padding.group2 && `padding: 0 ${padding.group2}`)};```, but I'm happy either way if code maintainers are swayed one way or the other.

Comment (dr3) [reply src/app/lib/layoutGrid/index.js]: I prefer ```${({ padding = {} }) => (padding.group2 && `padding: 0 ${padding.group2}`)};``` too, thoughts @jroebu14? bare minimum the ternary can be a `&&`

Comment (jroebu14) [reply src/app/lib/layoutGrid/index.js]: Yeh I'm not a fan of deep destructuring either. That looks good. However the ternary is needed because of the string interpolation. Otherwise you'd end up with `undefined` in the CSS if `group2` is undefined.

Comment (dr3) [reply src/app/lib/layoutGrid/index.js]: Does styled-components not filter the undefined out for us?

Comment (jroebu14) [reply src/app/lib/layoutGrid/index.js]: Oh does it? Feels weird allowing something like that in the code though.

Comment (jroebu14) [reply src/app/lib/layoutGrid/index.js]: @dr3 I refactored the destructuring however I didn't like the idea of relying on styled-components to remove the `undefined` string so I stuck with the ternary. I wouldn't want to get used to doing that in case it catches me out in something outside of styled-components. If you feel strongly about it I can remove the ternary though 🙂

**Review by dr3 — APPROVED** [review]

**Review by ryanmccombe — APPROVED** [review]

**Comment by PriyaKR** [comment]
LGTM.
