### PR TITLE
Styled components 4

### LINKED ISSUE #1040: Simorgh unable to pull in styles from Psammead on AMP
**Describe the bug**
https://github.com/BBC-News/simorgh/pull/1026 highlighted that when we pull in a Psammead component, the component styles aren't pulled into AMP.

The styles work ok on canonical, suggesting that it's the Styled Components runtime that is adding the additional styles. (The runtime - along with all other scripts - are stripped out of the AMP version, as AMP doesn't support JavaScript).

Another factor is that the version of styled components differs between Simorgh and Psammead.

**To Reproduce**

1. Check out the branch on #1026
2. `npm run dev`
3. Visit http://localhost:7080/news/articles/c9rpqy7pmypo - styles work
4. Visit http://localhost:7080/news/articles/c9rpqy7pmypo.amp - no styles in heading

**Expected behavior**
Styles should work as per canonical version.

- [x] Initially labelled with ["bug"](https://github.com/BBC-News/simorgh/labels/bug)

### PR DESCRIPTION
**Pull request by dr3**
Resolves #1040 

Upgrades to Styled Components v4.1.2

- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Review by ChrisBAshton — DISMISSED** [review]
LGTM 👍 agreed `ForwardRef` doesn't look great, but is an unavoidable thing at the moment and we'll extract out in the move to Enzyme or react-test-library soon...

**Comment by sareh** [comment]
✅ Tested the storybook implementation
- `npm ci && npm run storybook` 
- visited http://localhost:9001/,
Inspected the components and saw that the global styles were being applied correctly

screen shot 2018-12-04 at 15 24 59

:x: Tested the application implementation
- `npm run dev` 
- visited http://localhost:7080/news/articles/c9rpqy7pmypo
The global styles seem to be added after the majority of the component styles:

screen shot 2018-12-04 at 15 32 33
Note the comment: `sc-global` indicating where the global styles start.


:x: Testing the application implementation in the prod version:
- `npm run build && npm run start`
- visited http://localhost:7080/news/articles/c9rpqy7pmypo
- I needed to turn JavaScript off, to see the styles in the `<style>` tag in the head: 
Same issue with the global styles being imported near the end of the list of items. 

I think it's important to investigate why the Global Styles are imported in the order that they are.  This is likely to do with how we use Helmet in our Document component.

File: src/app/components/Document/index.jsx [hunk 1]
```diff
@@ -32,6 +32,7 @@ const Document = ({ assets, app, data, styleTags, helmet }) => {
         {meta}
         <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon" />
         <link rel="manifest" href="/manifest.json" />
+        <GlobalStyle />
```
Comment (sareh) [inline src/app/components/Document/index.jsx]: I'd suggest putting the global styles below the resource hints. This is so that the browser can parse the resource hints before getting to any of the styles.

**Comment by sareh** [comment]
The point I raised in this comment https://github.com/BBC-News/simorgh/pull/1042#issuecomment-444144485 about the Global Styles being rendered after other components' styles, rather than being the first in the style tag, is solely due to how Helmet handles `styleTags` that are passed into the application. 

Even though `<GlobalStyle>` is imported in the `Document` on this line https://github.com/BBC-News/simorgh/pull/1042/files#diff-00a291acea0cc37f44c9f1daaa1fe90cR36 that is not where the styles are imported.  

I'll open another issue that focuses on addressing how to ensure global styles are in a style tag prior to the component styles, which is very relevant to the cascade and how CSS works. 

In the meantime, for clarity for developers looking at this code and refactoring it, it would be better to have the `<GlobalStyle>` at the top of the `Articles` container's render function.  https://github.com/BBC-News/simorgh/blob/latest/src/app/containers/Article/index.jsx#L74

**Review by sareh — DISMISSED** [review]
👍 Looks good!

**Review by ChrisBAshton — DISMISSED** [review]

**Review by sareh — DISMISSED** [review]

**Review by ChrisBAshton — APPROVED** [review]

**Review by sareh — APPROVED** [review]
Tested locally and it looks good. Global Styles all in the right place.

**Comment by jamesbrumpton** [comment]
LGTM
