### PR TITLE
Fixing Chapter and Page for MAPs ATI

### LINKED ISSUE #5927: Page and Chapter name being incorrectly reported in ATI
**Describe the bug**
We are currently reporting the wrong chapter name for MAPs in Simorgh. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.bbc.com/pidgin/51875041
2. Open the ATI tag inspector 
3. Click on the page load event
4. Note the chapter name 
5. Note the page name 

**Expected behaviour**
The chapter name should correlate to the CPS home of the asset. 
We get the chapter name in the countername in the analytics part of the ares payload. 
If there is no chapter included in the countername, we will not record chapter in the ATI pageload.

The page name label should match the countername. 

We need to make an exception for TC2 assets because they don't return a countername but where a countername exists we should respect it.  
See: afrique/nos_emissions/2014/11/141111_porno_vengeur_ouganda

e.g. 

Page on PAL: http://pal.test.bbc.com/pidgin/media-44221514
Page with embedded_media chapter in Simorgh: https://www.bbc.com/pidgin/media-44221514
Countername: pidgin.**embedded_media**.media_asset.44221514.page

Page in PAL with Africa chapter:https://www.bbc.com/afrique/region-51804055
Countername: afrique.**africa**.media_asset.51804055.page

Page in PAL with no chapter: http://pal.test.bbc.com/pidgin/51875041
Page in Simorgh with no chapter: https://www.bbc.com/pidgin/51875041
Countername: pidgin.media_asset.51875041.page

**Screenshots**
Screenshot 2020-03-19 at 09 44 16

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**
This JIRA has the full Media page requirements for pageload in ATI: https://jira.dev.bbc.co.uk/browse/WSMEDIA-59

### PR DESCRIPTION
**Pull request by rebeccamcginn**
Resolves #5927

**Overall change:** 
Chapter and Page now reporting correctly for non-legacy MAPs

**Code changes:**

- Check if counterName is in the Ares response
- Do not override if so

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

### CODE REVIEW

File: src/app/routes/cpsAsset/getInitialData/addAnalyticsCounterName/index.js [hunk 1]
```diff
@@ -1,7 +1,12 @@
 import assocPath from 'ramda/src/assocPath';
 import path from 'ramda/src/path';
 
+const hasCounterName = pagedata => {
+  return path(['metadata', 'analyticsLabels', 'counterName'], pagedata);
```
Comment (ryanmccombe) [inline src/app/routes/cpsAsset/getInitialData/addAnalyticsCounterName/index.js]: `hasPath` is slightly more explicit: https://ramdajs.com/docs/#hasPath

Can also be curried like this:
```
const hasCounterName = hasPath(['metadata', 'analyticsLabels', 'counterName'])
```

**Review by ryanmccombe — APPROVED** [review]
Nice 👍

**Review by jroebu14 — APPROVED** [review]

**Review by ryanmccombe — APPROVED** [review]

**Comment by ryanmccombe** [comment]
🐰

**Review by ryanmccombe — APPROVED** [review]

**Review by jroebu14 — APPROVED** [review]
