### PR TITLE
Set privacy policy domain

### LINKED ISSUE #3440: Cookie banner setting cookies to the wrong place
**Describe the bug**
The simorgh consent banner sets cookies to `www.bbc.com` whereas the pal sets them to `.bbc.com`. This causes weird behaviour where we read from 1 domain, but write to another. This means the cookie banner cant be dismissed in some cases

**Unconfirmed:**
It appears that our cookie banner will read cookies set on `.bbc.com` and set cookies on `www.bbc.com`, which means you cant correct the values, and it will show the banners on every refresh

**To Reproduce**

On Chrome and Firefox 
1. Go to bbc.com/pidgin
2. Click on "Yes I agree" to the cookie settings
3. Refresh the page
4. See the cookie banner is displayed again 

**Expected behavior**
When you "Yes click I agree" then you don't see the cookie banner again when the page is refreshed

Simorgh sets cookies the same place that the pal does

**Screenshots**
image

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by RichardPK**
Resolves #3440

**Overall change:** 

This change removes the restriction on privacy cookies being set specifically on the second level domain only (www.bbc.com) so that these cookies are consistent for the second level domain and sub domains - exactly as Orbit does.

Before these changes, the Simorgh app would show the consent banner multiple times because we are essentially setting 2 different cookies with the same name but with different values when transitioning between Simorgh and PAL pages.

Screenshot 2020-01-23 at 11 04 49

The cookie set in Simorgh was restricted to the second level domain www.bbc.com. The cookie set in PAL using Orbit is available on the second level domain and all subdomains. It does this by setting the domain to `.bbc.com` when storing the cookie.

By removing the second level domain restriction in Simorgh, we are aligning with Orbit and using one cookie available from www.bbc.com and all sub domains.

**Code changes:**
- Function `removeTLDRestriction` takes the `document.domain` result e.g. `www.bbc.com` and returns `.bbc.com`
- We then use the return value for setting the domain of the cookie

**NB**

- `document.domain` resolves to either ...com or ...co.uk, so will reflect whether it is the .co.uk or .com domain.
- It is difficult to test the success of this on live as `window.domain` points to 'localhost' in local development_

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

### CODE REVIEW

**Comment by LilyL0u** [comment]
Is this for the cookie banner as well as the privacy policy banner?

**Comment by RichardPK** [comment]
> Is this for the cookie banner as well as the privacy policy banner?

Yes, the `setCookie()` function where we have explicitly declared the domain is used in both. We haven't changed where the function is being called, just how the cookie domains are assigned.

File: src/app/containers/ConsentBanner/CanonicalLogic/index.js [hunk 1]
```diff
@@ -14,8 +14,29 @@ const PRIVACY_COOKIE_PREVIOUS_VALUES = ['0', '1'];
 
 const onClient = typeof window !== 'undefined';
 
+const removeTLDRestriction = domain => {
```
Comment (karinathomasbbc) [inline src/app/containers/ConsentBanner/CanonicalLogic/index.js]: Can this be renamed to `removeTopLevelDomainRestriction`? (just to avoid more abbreviations :) )

**Review by karinathomasbbc — CHANGES_REQUESTED** [review]

**Review by karinathomasbbc — APPROVED** [review]

**Comment by jroebu14** [comment]
@karinathomasbbc made some changes to handle being on test.bbc.com

**Review by karinathomasbbc — COMMENTED** [review]
Looks good to me!

**Comment by andrewscfc** [comment]
> It is difficult to test the success of this on live as window.domain points to 'localhost' in local development_

I think you can test this sort of thing by modifying your local host file @RichardPK ?
i.e. add a line to `/etc/hosts` 

e.g.
`127.0.0.1     localhost.bbc.co.uk localhost.bbc.com`

**Review by andrewscfc — APPROVED** [review]
LGTM, if possible try and test locally if my suggestion works: https://github.com/bbc/simorgh/pull/5231#issuecomment-577714475 (I may have overlooked something!)

**Review by pharingee — APPROVED** [review]
LGTM. Small suggestion, maybe we can write a test for `removeDomainRestriction` and ensure it's called during `setCookie` to help future-proof this code?

**Comment by jroebu14** [comment]
@pharingee thanks for the suggestion. Good point about adding a new test but I'm not a fan of tests that check certain functions are called because they are coupled to the code and break when code is refactored i.e. they are brittle. I'll write a test that checks the cookie is set with the correct domain.

**Comment by jroebu14** [comment]
@pharingee it's not actually possible to check which domain a cookie is stored against, you can only get the key name and value. However I've added tests that check the cookies are stored without domain restrictions
