### PR TITLE
Reserve additional 16px to prevent advert content shift

### LINKED ISSUE #7803: On largest breakpoint, not quite enough space is reserved for leaderboard ads
**Describe the bug**
We always reserve the space for the largest possible ad that could be served for leaderboard ads. It looks like we're a few pixels short on leaderboards on desktop screens, which causes a small amount of content shifting when the ad loads in.

We can see the computed values of the ad slot here:

Before ad is loaded:
Screenshot 2020-09-14 at 08 32 12

After ad is loaded:
Screenshot 2020-09-14 at 08 32 00

It looks like we need to reserve an extra 16px of vertical space in this case.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to www.bbc.com/hindi from outside the UK (probably using a proxy)
2. Take a look at the leaderboard ad at the top of the screen

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by rebeccamcginn**
Resolves #7803

**Overall change:**
On both canonical and AMP pages, we are seeing a slight layout shift when the advert loads in, due to the reserved space not being quite large enough. Reserving an additional 16px of vertical space on both AMP and canonical to prevent this shift.

**Code changes:**

- Increased placeholder vertical height by 16px for both canonical and AMP ad slots. 

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project
- [x] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by andrewscfc — APPROVED** [review]

File: src/app/containers/Ad/utilities/adSlotStyles.js [hunk 1]
```diff
@@ -48,7 +48,7 @@ const LEADERBOARD_HEIGHTS = {
   // 60px + AD_UNIT_MARGIN = 85px
   GROUP_3: `${5.625 + AD_UNIT_MARGIN}rem`,
   // 90px + AD_UNIT_MARGIN = 115px
-  LARGE: `${15.625 + AD_UNIT_MARGIN}rem`,
+  LARGE: `${16.625 + AD_UNIT_MARGIN}rem`,
   // 250px + AD_UNIT_MARGIN = 275px
```
Comment (HarryVerhoef) [inline src/app/containers/Ad/utilities/adSlotStyles.js]: Should this comment be `266px` instead of `250px` with this change?

**Review by HarryVerhoef — APPROVED** [review]
Nice one 🚀
