### PR TITLE
DRY approach for CPS Related Content, F&A, Top Stories containers

### LINKED ISSUE #5795: Investigation on finding a DRY approach for CPS Related Content, F&A, Top Stories containers
**Describe the bug**
To be implemented on Top Stories, Related Content, Features and Analysis:

- The Wrapper and StyledSectionLabel (see lines https://github.com/bbc/simorgh/pull/5751/files#diff-f93c9baefa363f1d9525e83dba7e6627R18-R27) are repeated across all three containers.
- The CPS Related Content container has specific logic for the grid wrapper. It'll need to be considered when implementing the DRY approach. https://github.com/bbc/simorgh/blob/8d6cd1a68854e3583b02bf99ccbcd2350d3d3f6c/src/app/containers/CpsRelatedContent/index.jsx#L46
- Remove the extra `Wrapper` component, following [this comment](https://github.com/bbc/simorgh/pull/5913#discussion_r397801139).

**Expected behaviour**
Those code sections shouldn't be repeated across the files

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**
- See also: https://github.com/bbc/simorgh/issues/6074

### PR DESCRIPTION
**Pull request by mykeels**
Resolves #5795

**Overall change:**
_Create CpsAsset container to be reused by._
- _CpsRelatedContent_
- _CpsTopStories_
- _CpsFeaturesAnalysis_

**Code changes:**

- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**

- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

File: src/app/containers/CpsAsset/index.jsx [hunk 1]
```diff
@@ -30,7 +28,7 @@ const StyledSectionLabel = styled(SectionLabel)`
   margin-top: 0;
 `;
 
-// Apply the right margin-top between the section label and the promos
+// Apply the right padding-top&bottom around the single story promo
```
Comment (andrewscfc) [inline src/app/containers/CpsAsset/index.jsx]:
```suggestion
// Apply the correct top & bottom padding around the single story promo
```
Just struggled to understand this comment, I thought it was referring to `padding-right`, just a reword suggestion

File: src/app/containers/CpsFeaturesAnalysis/index.jsx [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+    />
+  );
+};
+
+FeaturesAnalysis.propTypes = {
+  content: arrayOf(shape(storyItem)),
+};
+
+FeaturesAnalysis.defaultProps = {
+  content: featuresAnalysis, // @TODO: rm this
```
Comment (andrewscfc) [inline src/app/containers/CpsFeaturesAnalysis/index.jsx]: I think I may have commented on this before? Could the comment include the issue where we introduce the real data from Ares?

**Review by andrewscfc — COMMENTED** [review]
Two minor comments, looks great

File: src/app/containers/CpsAsset/index.jsx [hunk 3]
```diff
@@ -40,58 +38,72 @@ const SingleContentWrapper = styled.div`
   }
 `;
 
-const FeaturesAnalysis = ({ content }) => {
+const CpsAsset = ({
```
Comment (rhenshaw56) [inline src/app/containers/CpsAsset/index.jsx]: should we call this `StoryPageOnwardJourney` or `CpsOnwardJourney` container instead ? I don't have a preference but I think `CpsAsset` container might imply this is meant for housing cps assets

File: src/app/containers/CpsAsset/index.jsx [hunk 4]
```diff
@@ -40,58 +38,72 @@ const SingleContentWrapper = styled.div`
...
+  title,
+  content,
+  enableGridWrapper,
+  a11yAttributes,
```
Comment (rhenshaw56) [inline src/app/containers/CpsAsset/index.jsx]: since the `a11yAttributes` would mostly contain similar attributes apart from the `aria-labelledby` attrs would it be worth defining the common ones here and just passing a `labelledBy` prop for `aria-labelledby`  from each of the component using it ?

File: src/app/containers/CpsFeaturesAnalysis/index.jsx [hunk 5]
```diff
@@ -0,0 +1,55 @@
...
+
+const FeaturesAnalysis = ({ content }) => {
+  const { dir } = useContext(ServiceContext);
+  const a11yAttributes = {
+    as: 'section',
+    role: 'region',
+    'aria-labelledby': 'features-analysis-heading',
+  };
+
+  if (!content.length) return null;
```
Comment (rhenshaw56) [inline src/app/containers/CpsFeaturesAnalysis/index.jsx]: this same logic is still duplicated across `FeaturesAnalysis`, `CpsRelatedContent` and `CpsTopStories`, surely if we aim to make this a DRY approach, shouldn't it be encompassed within CpsAsset ?

File: src/app/containers/CpsAsset/index.jsx [hunk 6]
```diff
@@ -40,58 +38,72 @@ const SingleContentWrapper = styled.div`
...
+      <GridWrapper {...a11yAttributes}>
+        <Wrapper>{children}</Wrapper>
+      </GridWrapper>
+    ) : (
+      <Wrapper {...a11yAttributes}>{children}</Wrapper>
+    );
+  CpsAssetWrapper.propTypes = {
     children: node.isRequired,
   };
   if (!content.length) return null;
```
Comment (rhenshaw56) [inline src/app/containers/CpsAsset/index.jsx]: should this logic still be here ? if we're doing similar checks in each of the places where it's being used

File: src/app/containers/CpsAsset/index.jsx [hunk 7]
```diff
@@ -40,58 +38,72 @@ const SingleContentWrapper = styled.div`
...
-const FeaturesAnalysis = ({ content }) => {
+const CpsAsset = ({
+  title,
+  content,
+  enableGridWrapper,
+  a11yAttributes,
+  listTransform,
+  singleTransform,
+}) => {
   const { script, service, dir } = useContext(ServiceContext);
```
Comment (rhenshaw56) [inline src/app/containers/CpsAsset/index.jsx]: if we have access to the `script, service, dir` props from where this component is being used would it be worth passing them as props so this component doesn't also depend on the `ServiceContext` as well

File: src/app/containers/CpsAsset/index.jsx (hunk 3 above)
Comment (mykeels) [reply src/app/containers/CpsAsset/index.jsx]: I like `CpsOnwardJourney` 😄

File: src/app/containers/CpsAsset/index.jsx (hunk 4 above)
Comment (mykeels) [reply src/app/containers/CpsAsset/index.jsx]: How about an `id` prop? Since the `labelledBy` points to an element's id.

**Comment by mykeels** [comment]
## Update Snapshots Commands

```sh
npx jest src/app/pages/*Page/index.test.jsx -u
npx jest src/app/containers/Cps*/index.test.jsx -u
npm run test:integration -- -u
```

File: src/app/containers/CpsAsset/index.jsx (hunk 4 above)
Comment (mykeels) [reply src/app/containers/CpsAsset/index.jsx]: Updated to use `labelId` prop, since `id` already has an implicit meaning.

File: src/app/containers/CpsAsset/index.jsx (hunk 7 above)
Comment (mykeels) [reply src/app/containers/CpsAsset/index.jsx]: One advantage of using contexts is to reduce the props in components to a minimum. Does adding the props explicitly offer much of an advantage?

File: src/app/containers/CpsAsset/index.jsx (hunk 6 above)
Comment (mykeels) [reply src/app/containers/CpsAsset/index.jsx]: Thanks. I've taken out the line from the containers' code.

File: src/app/containers/CpsFeaturesAnalysis/index.jsx (hunk 5 above)
Comment (mykeels) [reply src/app/containers/CpsFeaturesAnalysis/index.jsx]: Thanks. I've taken out the line from the containers' code.

File: src/app/containers/CpsFeaturesAnalysis/index.jsx (hunk 2 above)
Comment (mykeels) [reply src/app/containers/CpsFeaturesAnalysis/index.jsx]: Yes, you did in the Top Stories PR. 

I've updated this to link [the related issue](https://github.com/bbc/simorgh/issues/5765).

File: src/app/containers/CpsAsset/index.jsx (hunk 7 above)
Comment (rhenshaw56) [reply src/app/containers/CpsAsset/index.jsx]: my concern was how they (parent and child components) are both tightly coupled to the same context. If we were testing both in isolation we would also have to mock that context in the tests.

**Review by andrewscfc — APPROVED** [review]

**Review by sareh — APPROVED** [review]
This refactor looks good. Thanks for the updates. 

I checked on Storybook http://localhost:9001/iframe.html?id=pages-story-page--mundo
Screenshot CPS STY Mundo

and also on a page http://localhost:7080/mundo/23263889

In the console on the page (http://localhost:7080/mundo/23263889), I saw errors due to fonts being fetched from a new route - 
Screenshot errors
I'm not sure if this is a known issue for CPS STY pages.

**Review by rhenshaw56 — APPROVED** [review]

**Comment by mykeels** [comment]
@sareh This is also happening in `latest` branch. 

image

I've traced the problem to https://github.com/bbc/simorgh/blob/latest/src/server/utilities/cspHeader/index.js#L203-L206

**Comment by mykeels** [comment]
I've created [this issue](https://github.com/bbc/simorgh/issues/6131) to track the font loading problem. https://github.com/bbc/simorgh/issues/6131

**Comment by paruchurisilpa** [comment]
Done Regression for topstories and F&A. LGTM..
