### PR TITLE
Don't encode ref parameter

### LINKED ISSUE #7852: Referral source attribution broken in ATI for Simorgh pages
**Describe the bug**
Since https://github.com/bbc/simorgh/pull/7775, ATI has been mis-attributing referrals as Direct instead of Search.

This appears to be because we have encoded the `ref` parameter.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.bbc.com/portuguese/geral-54185816
2. Open the network tab and filter on `a1.api`
3. Check the URL (not as displayed, the actual URL)
4. Observe the `ref` parameter's value is encoded
5. Repeat on PAL and see the `ref` parameter is not encoded

**Expected behaviour**
The `ref` parameter should not be encoded

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by andrewscfc**
Resolves #7852

_Note_
This PR reverts https://github.com/bbc/simorgh/pull/7853 (a revert of a revert!) that undid an accidental push to latest. It includes the changes for this bug that will now be properly reviewed in this PR.

**Overall change:**
No longer encodes the `ref` parameter as ATI is unable to decode the ref parameter.
Before the change the ati tag explorer showed the referrer with encoding:
image

This should show without encoding on live, I was unable to test the referrer locally.

**Code changes:**
- Added facility to not encode selected ati parameters
- Enabled it only for the `ref` parameter
- Updated test snapshots to reflect lack of encoding for the `ref` parameter

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project

**Testing:**

- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by rebeccamcginn — APPROVED** [review]

**Review by simonsinclair — APPROVED** [review]

**Comment by paruchurisilpa** [comment]
Testing:

* Installed http server from here - https://www.npmjs.com/package/http-server
* Create index.html file inside simorgh/public folder
* Run http-server 
* Visit http://127.0.0.1:8080

It works for mundo but ref doesn't seem to work for mundo.amp.

Discussed this with @andrewscfc , will move it back to In Progress..

**Comment by andrewscfc** [comment]
After making the following change https://github.com/bbc/simorgh/pull/7854/commits/c52505ed0c45b462caaefbb43994ad6fe5b68c19, I retested:

Steps to reproduce issue found:
1. Create index.html file inside simorgh/public folder with the following contents:
```
<html>
  <body>
    <a href="http://localhost:7080/mundo.amp">mundo</a>
  </body>
</html>
```

2. Run [http-server](https://www.npmjs.com/package/http-server) in simorgh directory
3. Visit http://127.0.0.1:8080
4. Click the mundo link
5. Observe hit in in ATI inspector:
image

- x6 variable is now correctly populated with the referrer for the amp page
- ref is incorrectly encoded but I don't believe this can be resolved without a change to ATI, variables substitutions resolved from ${documentReferrer} being url encoded; this being processed correctly for x6 but not for ref. @jimjohnsonrollings, is it acceptable to proceed with this bug or should we try and investigate further?

**Comment by jimjohnsonrollings** [comment]
@andrewscfc I think proceed as is.  Thanks

File: src/app/containers/ATIAnalytics/atiUrl/index.js [hunk 1]
```diff
@@ -50,7 +50,9 @@ export const buildATIPageTrackPath = ({
   // For canonical, we have a requirement to encode the x5 and x6 value twice. Source issue: https://github.com/bbc/simorgh/pull/6593
   const x5Value = platform === 'amp' ? href : href && encodeURIComponent(href);
   const x6Value =
-    platform === 'amp' ? referrer : referrer && encodeURIComponent(referrer);
+    platform === 'amp'
+      ? referrer
+      : referrer && encodeURIComponent(encodeURIComponent(referrer));
```
Comment (karinathomasbbc) [inline src/app/containers/ATIAnalytics/atiUrl/index.js:55]: Is this double encoding expected?

File: src/app/containers/ATIAnalytics/atiUrl/index.js [hunk 2]
```diff
@@ -50,7 +50,9 @@ export const buildATIPageTrackPath = ({
   // For canonical, we have a requirement to encode the x5 and x6 value twice. Source issue: https://github.com/bbc/simorgh/pull/6593
   const x5Value = platform === 'amp' ? href : href && encodeURIComponent(href);
   const x6Value =
-    platform === 'amp' ? referrer : referrer && encodeURIComponent(referrer);
+    platform === 'amp'
```
Comment (karinathomasbbc) [inline src/app/containers/ATIAnalytics/atiUrl/index.js:53]: Does it make sense to create a new variable `const isAmp = platform === 'amp'` & use it here?

**Review by karinathomasbbc — APPROVED** [review]

File: src/app/containers/ATIAnalytics/atiUrl/index.js (hunk 1 above)
Comment (andrewscfc) [reply src/app/containers/ATIAnalytics/atiUrl/index.js:55]: yeah see the comment above

File: src/app/containers/ATIAnalytics/atiUrl/index.js (hunk 2 above)
Comment (andrewscfc) [reply src/app/containers/ATIAnalytics/atiUrl/index.js:53]: I've done something similar in the follow-up PR, I'll put that out for review a bit later and see if I've addressed this point: https://github.com/bbc/simorgh/pull/7877

File: src/app/containers/ATIAnalytics/atiUrl/index.js (hunk 1 above)
Comment (karinathomasbbc) [inline src/app/containers/ATIAnalytics/atiUrl/index.js:55]: Could / should `encodeURIComponent` do the null check, so we don't have to?

e.g. instead of `referrer && encodeURIComponent(referrer)` it would just be `encodeURIComponent(referrer)` which would just return the referrer if it was null? (Just a suggestion, feel free to say no)

**Review by rhenshaw56 — APPROVED** [review]
quick question, since we use the same [getReferrer logic](https://github.com/bbc/simorgh/blob/latest/src/app/lib/analyticsUtils/index.js#L126-L140) for both ATI and chartbeat, does this mean that would need to not be encoded as well ?

**Comment by andrewscfc** [comment]
> quick question, since we use the same [getReferrer logic](https://github.com/bbc/simorgh/blob/latest/src/app/lib/analyticsUtils/index.js#L126-L140) for both ATI and chartbeat, does this mean that would need to not be encoded as well ?

I think the issue is specific to ATI, we are effectively working around a bug in ATI itself, it _should_ accept encoding parameters without issue.

**Comment by paruchurisilpa** [comment]
Retested and looks good to me..
