### PR TITLE
Revert inline link styling

### LINKED ISSUE #2370: Bump to revert inline-link changes
**Describe the bug**
The bug is described [here](https://github.com/bbc/simorgh/pull/2258#pullrequestreview-258785470). ~The solution is to version lock the inline-link component and the paragraph + caption because they use inline-link.~ Update: bump the inline-link, caption and paragraph to revert the new inline link styles that went live with dependabot.

These version locks can be removed when the [psammead bug](https://github.com/bbc/psammead/issues/936) is fixed. 

**To Reproduce**

1. On Firefox, create a link that ends very close to the end of the paragraphs column
2. Hover on the inline
3. See the content of the link jump to the next line due to additional padding/margin on hover

**Expected behavior**
The text content shouldn't jump to a new line. 

**Screenshots**
image

image

- Browser: FireFox

### PR DESCRIPTION
**Pull request by pjlee11**
Resolves #2370

**Overall change:** Bumps caption and paragraph which use inline-link and inline-link itself to pull in the styling revert for inline-link.

**Code changes:**

- Bumps to `psammead-caption@1.1.12`, `psammead-paragraph@2.0.1` and `psammead-inline-link@1.1.6`
- Passes required prop `service` to `psammead-paragraph`
- Updates snapshots 

Test notes:
- For both `npm run dev` and `npm run build && npm run start` check the inline link styling is as follows: 
  - Default style: red border 1px, color `#222222`
  - Hover/Focus style: red border 2px, color `red`
  - Visited style: grey color and border 1px

Check on an article and also error page 

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by rhenshaw56 — APPROVED** [review]
Looks good!

**Review by oluoluoxenfree — APPROVED** [review]

**Review by dr3 — APPROVED** [review]

File: scripts/bundleSize.sh [hunk 1]
```diff
@@ -2,8 +2,8 @@
 
 # Size limit for all bundles used by each service (K)
 # Keep these +/- 5K and update frequently!
-min=650
-max=675
+min=663
+max=681
```
Comment (pjlee11) [inline scripts/bundleSize.sh]: `latest` is currently 672K for `news` so this PR seemingly adds `4K` and news is now 676K

File: scripts/bundleSize.sh [hunk 2]
```diff
@@ -2,8 +2,8 @@
 
 # Size limit for all bundles used by each service (K)
 # Keep these +/- 5K and update frequently!
-min=604
-max=622
+min=613
+max=631
```
Comment (pjlee11) [inline scripts/bundleSize.sh:6]: This PR increases the bundle size by around 9KB because of the bump to `@bbc/psammead-styles`

It was previously [`@0.3.0`](https://packagephobia.now.sh/result?p=@bbc/psammead-styles@0.3.0) which had an install size of 27.6KB and this bumps it to [`@1.1.2`](https://packagephobia.now.sh/result?p=@bbc/psammead-styles@1.1.2) which has an install size os 51.2KB. Once gzipped that roughly explains the 9KB difference

Comment (dr3) [reply scripts/bundleSize.sh]: image
Why?!

**Review by dr3 — CHANGES_REQUESTED** [review]
Simorgh is on `"@bbc/psammead-styles": "^1.0.0",` though, so that doesnt explain the increase pulling in `@1.1.2` via a dep

File: scripts/bundleSize.sh (hunk 2 above)
Comment (pjlee11) [reply scripts/bundleSize.sh:6]: This can also be checked in the `webpackBundleReport` as per the following screenshots:

On this branch 

image


On latest

image

Comment (pjlee11) [reply scripts/bundleSize.sh:6]: Also there are multiple versions of `psammead-styles` which would explain why not all the 9KB is accounted for in the screenshots above

**Comment by pjlee11** [comment]
@dr3 that's because the simorgh's package-lock is pulling in `psammead-styles@1.0.0`. We obviously haven't installed recently to pick up `1.1.2`. 

See the screenshots in https://github.com/bbc/simorgh/pull/2418#discussion_r302144739

**Review by dr3 — APPROVED** [review]
Bleeeeeeeeh so many deps, this is fine, should get caught by the bumping soon anyway

**Comment by jamesbrumpton** [comment]
LGTM
