### PR TITLE
Fix amp media player placeholder

### LINKED ISSUE #9762: AMP media player placeholder srcset is 1 image source repeated multiple times
**Describe the bug**
The media player placeholder image srcset for AMP is 1 image repeated multiple times.

Screenshot 2021-12-30 at 12 38 18

This happens because in [this file](https://github.com/bbc/simorgh/blob/latest/src/app/lib/utilities/ichefURL/index.js#L22-L24) we are returning `locator` (the image url e.g. `'https://ichef.bbci.co.uk/images/ic/1024x576/p0bdk3xv.jpg'`) when `originCode` equals `'pips'` and this function is called in a map callback of multiple image size resolutions so just returns the same image url each time.

This is not a problem on canonical because we rely on SMP built-in image placeholder which uses the correct srcset. On canonical, only use our own placeholder in a noscript tag which is displayed when js is disabled. However, like with amp, the no js placeholder srcset is incorrect so this should be fixed too.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.bbc.com/hausa/media-59822286.amp
2. Inspect the media player placeholder image
3. See the repeated same sized image in the srcset attribute

**Expected behaviour**
The srcset uses different sized images so that the browser can choose the most appropriate image to download and render.

We need to either fix the srcset creation for the amp placeholder or, like canonical, we use SMPs built-in placeholder. The thinking with the amp placeholder must have been that we need to use `amp-img` so we need to create our own placeholder. It's worth investigating if we can use the built-in SMP placeholder since it is in an iframe meaning we don't need to use amp elements.

As mentioned above we still need to fix the placeholder srcset creation so that is correct on canonical when js is disabled.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

### PR DESCRIPTION
**Pull request by DarioR01**
Resolves #9762

**Overall change:**
Fix amp media player placeholder srcset for pips origin code by generating a new srcset instead of returning null. New srcset resolutions have been taken from what we currently have in canonical pages.

**Code changes:**

- Added resolutions array specific to pips.
- Updated buildPlaceholderSrc to work for both pips and mvc origin code.
- Updated jest tests to reflect above changes

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project
- [ ] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [x] This PR requires manual testing

### CODE REVIEW

**Comment by DarioR01** [comment]
Let me know what your thoughts on this solution are. I still need to investigate the use of the SMP built-in placeholder, but before proceeding I would like some reviews for what I did so far, thanks :)

File: src/app/lib/utilities/srcSet/index.js [hunk 1]
```diff
@@ -69,6 +87,17 @@ export const createSrcsets = ({
 export const getPlaceholderSrcSet = ({ originCode, locator, isWebP }) => {
   if (!originCode) return '';
   if (!locator) return '';
```
Comment (HarveyPeachey) [inline src/app/lib/utilities/srcSet/index.js]: I know it's not your code but might as well tidy this up
```suggestion
  if (!originCode || !locator) return '';
```

**Review by HarveyPeachey — DISMISSED** [review]
LGTM, just added a suggestion on existing the code that we could tidy up a little

File: src/app/lib/utilities/ichefURL/index.js [hunk 2]
```diff
@@ -18,9 +18,27 @@ const buildPlaceholderSrc = (src, resolution) => {
   return newUrl.join('/');
 };
 
+const buildPipsPlaceholderSrc = (src, resolution) => {
+  const parts = src.split('/');
+  const [protocol, blank, domain, type, imgService, ...extraParts] = parts;
+  if (protocol !== 'https:') return src;
+  const definedWidth = `${resolution[0]}x${resolution[1]}`;
+  extraParts.shift();
```
Comment (HarveyPeachey) [inline src/app/lib/utilities/ichefURL/index.js]: What's being shifted off `extraParts` here?

Comment (DarioR01) [reply src/app/lib/utilities/ichefURL/index.js]: The base resolution in the locator link. this gets replaced by the definedWidth.
Now that I think of it, definedWidth is the new resolution that gets substituted to the old one, so I will change the variable name to definedResolution to avoid confusion 👍

File: src/app/lib/utilities/srcSet/index.js (hunk 1 above)
Comment (DarioR01) [reply src/app/lib/utilities/srcSet/index.js]: > I know it's not your code but might as well tidy this up

Thanks for the suggestion 👍

**Review by jroebu14 — COMMENTED** [review]
Can you also please remove the amp-img placeholder? I don't think this is needed

File: src/app/lib/utilities/ichefURL/index.js [hunk 3]
```diff
@@ -18,9 +18,27 @@ const buildPlaceholderSrc = (src, resolution) => {
   return newUrl.join('/');
 };
 
+const buildPipsPlaceholderSrc = (src, resolution) => {
+  const parts = src.split('/');
+  const [protocol, blank, domain, type, imgService, ...extraParts] = parts;
```
Comment (jroebu14) [inline src/app/lib/utilities/ichefURL/index.js]: are you sure pips images all follow this format?

File: src/app/lib/utilities/srcSet/index.js [hunk 4]
```diff
@@ -1,6 +1,24 @@
 import buildIChefUrl from '#lib/utilities/ichefURL';
 
 const DEFAULT_RESOLUTIONS = [240, 320, 480, 624, 800];
+const PIPS_RESOLUTIONS = [
```
Comment (jroebu14) [inline src/app/lib/utilities/srcSet/index.js]: that's a lot of resolutions. where did you get these resolution requirements?

is this width / height? it would be better to work out one dimension using an aspect ratio. I'm assuming this is how DEFAULT_RESOLUTIONS works

File: src/app/lib/utilities/ichefURL/index.js (hunk 3 above)
Comment (DarioR01) [reply src/app/lib/utilities/ichefURL/index.js]: based on previous tests implemenation I am assuming yes. The format is as follows for all the links ichef.test.bbci.co.uk/images/ic/$widthxn/p01kdbpk.jpg, and https://ichef.test.bbci.co.uk/images/ic/$widthxn/p01kdbpk.jpg.

File: src/app/lib/utilities/srcSet/index.js (hunk 4 above)
Comment (DarioR01) [reply src/app/lib/utilities/srcSet/index.js]: I belive these are the resolution requirements for the SMP built-in image placeholder. Currently on live canonical we have the following resolutions under
 srcset: 
 Screenshot 2022-01-10 at 11 03 21

Comment (DarioR01) [reply src/app/lib/utilities/srcSet/index.js]: I just discovered a way to create a working link using only the width. I will make this change now 👍

Comment (DarioR01) [reply src/app/lib/utilities/srcSet/index.js:4]: > Can you also please remove the amp-img placeholder? I don't think this is needed

Yes I can do that 👍

**Comment by DarioR01** [comment]
> Can you also please remove the amp-img placeholder? I don't think this is needed

It seems that if I do it I get some a11y related e2e failures. I am not sure how srcset and a11y are related. Will investigate but I would suggest not to remove this.
https://github.com/bbc/simorgh/runs/4761431693?check_suite_focus=true

File: src/app/lib/utilities/ichefURL/index.js (hunk 3 above)
Comment (DarioR01) [reply src/app/lib/utilities/ichefURL/index.js]: and I take care of pips link of the form of urn:bbc:pips:pid:p054n8j6 by returning without making any changes as previous tests required.

File: src/app/lib/utilities/srcSet/index.js [hunk 5]
```diff
@@ -1,6 +1,10 @@
...
```
Comment (jroebu14) [inline src/app/lib/utilities/srcSet/index.js]: I don't think we need so many image sizes for our app. this will create a lot of markup. can we just have the same resolutions that we have for DEFAULT_RESOLUTIONS? These image sizes are all we really need for responsive images to be performant in simorgh

File: src/app/lib/utilities/ichefURL/index.js [hunk 6]
```diff
@@ -2,28 +2,27 @@
 const WEBP_ORIGIN_CODES = ['cpsdevpb', 'cpsprodpb'];
 
 const buildPlaceholderSrc = (src, resolution) => {
-  const parts = src.split('/');
-  const [domain, media, imgService, width, ...extraParts] = parts;
-  const definedWidth = width.replace('$width', resolution);
+  // return standard img url pips
```
Comment (jroebu14) [inline src/app/lib/utilities/ichefURL/index.js]: I don't really understand this comment

File: src/app/lib/utilities/ichefURL/index.js [hunk 7]
```diff
@@ -2,28 +2,27 @@
...
+  if (src.includes('urn:')) return src;
+  const noProtocolSrc = src.replace('https://', '');
+  const parts = noProtocolSrc.split('/');
```
Comment (jroebu14) [inline src/app/lib/utilities/ichefURL/index.js]: what is parts? urlParts?

File: src/app/lib/utilities/ichefURL/index.js [hunk 8]
```diff
@@ -2,28 +2,27 @@
...
+  const [domain, media, imgService, ...extraParts] = parts;
+  // shift is used to delete the old resolution.
+  extraParts.shift();
```
Comment (jroebu14) [inline src/app/lib/utilities/ichefURL/index.js]: are you removing the first item of the extraParts array? mutating data with methods like shift or pop is usually not a good idea. A quick google on the issue https://jaketrent.com/post/remove-array-element-without-mutating

[Slice](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice) does not mutate the original array.

instead of
```js
extraParts.shift();
```

you should do something like

```js
const newParts = extraParts.slice(1)
```

on a side-note, these variable names could be more readable

Comment (DarioR01) [reply src/app/lib/utilities/ichefURL/index.js]: Thanks for the resources. I changed it to slice

Comment (DarioR01) [reply src/app/lib/utilities/ichefURL/index.js]: I tried to make the variables more readable

File: src/app/lib/utilities/ichefURL/index.js (hunk 6 above)
Comment (DarioR01) [reply src/app/lib/utilities/ichefURL/index.js]: Changed the comment to a more specific one.

File: src/app/lib/utilities/srcSet/index.js (hunk 5 above)
Comment (DarioR01) [reply src/app/lib/utilities/srcSet/index.js]: Sure, I just reverted the file back to use only DEFAULT_RESOLUTIONS

File: src/app/lib/utilities/ichefURL/index.js (hunk 7 above)
Comment (DarioR01) [reply src/app/lib/utilities/ichefURL/index.js]: Yes, I changed the pre-existing variable name to be more specific

File: src/app/lib/utilities/ichefURL/index.js (hunk 6 above)
Comment (DarioR01) [reply src/app/lib/utilities/ichefURL/index.js]: I also changed a test descriptionto mirror the change.
This comment was previously based on that test description

File: src/app/lib/utilities/ichefURL/index.js [hunk 9]
```diff
@@ -2,28 +2,27 @@
...
+  const noProtocolSrc = src.replace('https://', '');
+  const urlParts = noProtocolSrc.split('/');
+  const [domain, mediaType, imgService, ...extraParts] = urlParts;
+  // Slice use to cut off the old resolution
+  const newExtraParts = extraParts.slice(1);
+  const newResolution = `${resolution}xn`;
   const newUrl = [
-    domainWithProtocol,
-    media,
+    'https:/',
```
Comment (nicola-d-bbc) [inline src/app/lib/utilities/ichefURL/index.js]: Should this be 'https://' rather than 'https:/'?

File: src/app/lib/utilities/ichefURL/index.js [hunk 10]
```diff
@@ -2,28 +2,27 @@
...
 const buildPlaceholderSrc = (src, resolution) => {
-  const parts = src.split('/');
-  const [domain, media, imgService, width, ...extraParts] = parts;
-  const definedWidth = width.replace('$width', resolution);
-  const domainWithProtocol = `https://${domain}`;
-
+  // return urn schemes unmodified
+  if (src.includes('urn:')) return src;
+  const noProtocolSrc = src.replace('https://', '');
+  const urlParts = noProtocolSrc.split('/');
```
Comment (jroebu14) [inline src/app/lib/utilities/ichefURL/index.js]:
```suggestion
  const urlParts = src.replace('https://', '').split('/');
```

File: src/app/lib/utilities/ichefURL/index.js [hunk 11]
```diff
@@ -2,28 +2,27 @@
 const WEBP_ORIGIN_CODES = ['cpsdevpb', 'cpsprodpb'];
 
 const buildPlaceholderSrc = (src, resolution) => {
-  const parts = src.split('/');
-  const [domain, media, imgService, width, ...extraParts] = parts;
-  const definedWidth = width.replace('$width', resolution);
-  const domainWithProtocol = `https://${domain}`;
-
+  // return urn schemes unmodified
+  if (src.includes('urn:')) return src;
```
Comment (jroebu14) [inline src/app/lib/utilities/ichefURL/index.js]: Can we make this comment unnecessary?

```suggestion
  const isUrnScheme = src.includes('urn:')

  if (isUrnScheme) {
    return src;
  }
```

File: src/app/lib/utilities/ichefURL/index.js [hunk 12]
```diff
@@ -2,28 +2,27 @@
...
+  const noProtocolSrc = src.replace('https://', '');
+  const urlParts = noProtocolSrc.split('/');
+  const [domain, mediaType, imgService, ...extraParts] = urlParts;
+  // Slice use to cut off the old resolution
+  const newExtraParts = extraParts.slice(1);
```
Comment (jroebu14) [inline src/app/lib/utilities/ichefURL/index.js]: Could maybe make this comment unnecessary

```suggestion
  const urlPartsWithoutResolution = extraParts.slice(1);
```

File: src/app/lib/utilities/ichefURL/index.js [hunk 13]
```diff
@@ -2,28 +2,27 @@
...
-  const parts = src.split('/');
-  const [domain, media, imgService, width, ...extraParts] = parts;
-  const definedWidth = width.replace('$width', resolution);
-  const domainWithProtocol = `https://${domain}`;
-
+  // return urn schemes unmodified
+  if (src.includes('urn:')) return src;
+  const noProtocolSrc = src.replace('https://', '');
+  const urlParts = noProtocolSrc.split('/');
+  const [domain, mediaType, imgService, ...extraParts] = urlParts;
```
Comment (jroebu14) [inline src/app/lib/utilities/ichefURL/index.js]: maybe a better var name could be

```suggestion
  const [domain, mediaType, imgService, ...remainingUrlParts] = urlParts;
```

File: src/app/lib/utilities/ichefURL/index.js (hunk 12 above)
Comment (jroebu14) [reply src/app/lib/utilities/ichefURL/index.js]: or `remainingUrlPartsWithoutResolution` nothing wrong with a long var name!

File: src/app/lib/utilities/ichefURL/index.js (hunk 13 above)
Comment (jroebu14) [reply src/app/lib/utilities/ichefURL/index.js]: I think you could actually remove the resolution part like this

```js
const [domain, mediaType, imgService, , ...remainingUrlParts] = urlParts;
```

then you wouldn't need the `.slice` later

Comment (jroebu14) [reply src/app/lib/utilities/ichefURL/index.js]: but what you have done with the slice may be clearer 🤷

File: src/app/lib/utilities/ichefURL/index.js (hunk 9 above)
Comment (DarioR01) [reply src/app/lib/utilities/ichefURL/index.js]: Notice how in line 21 we use `return newUrl.join('/');` This will join https:/ and the domain with a `/` leaving us with https://....

File: src/app/lib/utilities/ichefURL/index.js (hunk 11 above)
Comment (DarioR01) [reply src/app/lib/utilities/ichefURL/index.js]: Sure we can.

File: src/app/lib/utilities/ichefURL/index.js (hunk 9 above)
Comment (jroebu14) [reply src/app/lib/utilities/ichefURL/index.js]: I think the 1 slash https is a little bit eye catching and weird. a future dev might think it's a bug and sink some time into looking at it

What about
```
return 'https://'.concat(newUrl.join('/'));
```

File: src/app/lib/utilities/ichefURL/index.js [hunk 14]
```diff
@@ -2,28 +2,25 @@
...
 const buildPlaceholderSrc = (src, resolution) => {
-  const parts = src.split('/');
-  const [domain, media, imgService, width, ...extraParts] = parts;
-  const definedWidth = width.replace('$width', resolution);
-  const domainWithProtocol = `https://${domain}`;
-
+  if (src.includes('urn:')) return src;
+  const urlParts = src.replace('https://', '').split('/');
+  const [domain, mediaType, imgService, ...remainingUrlParts] = urlParts;
+  // Slice use to cut off the old resolution
```
Comment (jroebu14) [inline src/app/lib/utilities/ichefURL/index.js]: I think the new var name makes this comment unnecessary 🙂 

```suggestion
```

File: src/app/lib/utilities/ichefURL/index.js [hunk 15]
```diff
@@ -2,28 +2,23 @@
 const WEBP_ORIGIN_CODES = ['cpsdevpb', 'cpsprodpb'];
 
 const buildPlaceholderSrc = (src, resolution) => {
-  const parts = src.split('/');
-  const [domain, media, imgService, width, ...extraParts] = parts;
-  const definedWidth = width.replace('$width', resolution);
-  const domainWithProtocol = `https://${domain}`;
-
+  if (src.includes('urn:') || src.includes('localhost:')) return src;
+  const urlParts = src.replace(/https:\/\/|http:\/\//, '').split('/');
```
Comment (jroebu14) [inline src/app/lib/utilities/ichefURL/index.js]: I think this can be shortened to:

```suggestion
  const urlParts = src.replace(/https?:\/\//g, '').split('/');
```

**Comment by ryanmccombe** [comment]
This seems like it would conflict with this PR - https://github.com/bbc/simorgh/pull/9807

This PR is updating the `amp-img`; that one is removing it

cc @DarioR01 @MuhammadAHussain

**Comment by DarioR01** [comment]
> This seems like it would conflict with this PR - #9807



> This seems like it would conflict with this PR - #9807
> 
> This PR is updating the `amp-img`; that one is removing it
> 
> cc @DarioR01 @MuhammadAHussain

Regardless of the deletion of the amp-images, I believe this is still an issue when js is disabled.

From the issue linked to this PR:
> As mentioned above we still need to fix the placeholder srcset creation so that is correct on canonical when js is disabled.

**Review by MuhammadAHussain — APPROVED** [review]
LGTM 👍

**Review by jroebu14 — APPROVED** [review]
Looks great. Thanks for picking this one up!

**Comment by DarioR01** [comment]
> Looks great. Thanks for picking this one up!

Thank you for all the great suggestions 😄
