### PR TITLE
Make index alsos which are promo assets work

### LINKED ISSUE #7298: Front Pages: Index Alsos of type PRO are displayed without a URL or a Headline
**Describe the bug**
If the editorial team add an Index Also to the Top Story on their Front Page which is a LINK/PRO asset type, then we render the link as an `<a>` tag without any content or an href.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to `/persian?renderer_env=test` on Test
2. Observe that two index alsos are visible
3. Observe that three are present in the code, but the third shows as `<a class="StyledIndexAlsosLink-xsqyvb-5 bqlSOf"><span class="IndexAlsosText-xsqyvb-4 gvRfTv"></span></a>`

**Expected behaviour**
* The third index also should also render with headline and href

In the JSON response, the headline and url for a `link` type are in the `name` and `uri` fields.  These field names differ from those used in other types.

The code for extracting the url appears to be here: https://github.com/bbc/simorgh/blob/8b4f86d6091287caa13dc8bd91bda5496f19d72a/src/app/containers/StoryPromo/IndexAlsos/index.jsx#L88

And headlines: https://github.com/bbc/simorgh/blob/8b4f86d6091287caa13dc8bd91bda5496f19d72a/src/app/containers/StoryPromo/IndexAlsos/index.jsx#L86

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by jimjohnsonrollings**
Resolves #7298  

**Overall change:**
Fixes an issue where Promo assets would render incorrectly as Index Alsos (in Front Page Top Story)

**Code changes:**

- Updates fixture data for the Persian front page to include a promo asset as an index also
- Updates the IndexAlsos container to use the promo asset data which is totally different to a normal promo
- Adds new tests for promo asset as index also
- Updates existing tests

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project

**Testing:**

- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [x] This PR requires manual testing

### CODE REVIEW

File: src/app/containers/StoryPromo/IndexAlsos/index.jsx [hunk 1]
```diff
@@ -75,17 +75,26 @@ const IndexAlsosContainer = ({ alsoItems, script, service, dir }) => {
     <IndexAlsos offScreenText={relatedContent} data-e2e="index-alsos">
       <IndexAlsosWrapper>
         {alsoItems.slice(0, MAX_NUM_INDEX_ALSOS).map(item => {
-          const { id, cpsType, mediaType } = item;
+          const { cpsType, mediaType } = item;
+
+          const aresId = pathOr(null, ['id'], item);
+          const promoId = pathOr(null, ['uri'], item);
```
Comment (andrewscfc) [inline src/app/containers/StoryPromo/IndexAlsos/index.jsx]: For readability, I'd consider extracting the `LINK/PRO` 'indexalso' logic into it's own method, so it's more explicit there are two different formats you can expect 'indexalsos' to have e.g.
```javascript
let indexAlsoData;
if(item.uri) {
  indexAlsoData = extractLinkProData(item);
} else {
  indexAlsoData = extractStoryData(item);
}
const { id, indexAlsoHeadline, url } = indexAlosData;
```
Just makes the business requirements more explicity imo

File: src/app/containers/StoryPromo/IndexAlsos/index.jsx [hunk 2]
```diff
@@ -118,16 +127,18 @@ const IndexAlsosContainer = ({ alsoItems, script, service, dir }) => {
...
   summary: string,
   timestamp: number,
-  cpsType: string.isRequired,
-  id: string.isRequired,
+  cpsType: string,
+  id: string,
   type: string,
+  name: string,
+  url: string,
 });
```
Comment (andrewscfc) [inline src/app/containers/StoryPromo/IndexAlsos/index.jsx:156]: As above, rather than adapting the `alsoItemsPropTypes` proptype, create a seperate proptype for `LINK/PRO` 'indexAlsos' and `STY` 'indexAlsos'.

You can then adapt the proptypes [here](https://github.com/bbc/simorgh/pull/7317/files#diff-8f7a893a72652aaa6b9a0e35917269abR145) to say alsoItems can be of different kinds:
`alsoItems: arrayOf(oneOfType([linkProIndexAlso, styIndexAlso])).isRequired`

File: src/app/containers/StoryPromo/IndexAlsos/index.test.jsx [hunk 3]
```diff
@@ -72,5 +72,47 @@ describe('Index Alsos', () => {
       const headline = secondListItem.getElementsByTagName('span')[0].innerHTML;
       expect(headline).toEqual('Overtyped headline');
     });
+
+    it('should render a promo headline', () => {
```
Comment (andrewscfc) [inline src/app/containers/StoryPromo/IndexAlsos/index.test.jsx]: I'd put these new assertions into their own describe block to make clear they are testing functionality specific to `LINK/PRO` 'indexalsos` rather than `STY` index alsos.

**Review by andrewscfc — COMMENTED** [review]
Changes look good, just a suggestion to segregate logic represent the business domain more clearly in the codebase. Also allows the component to adhere more to the 'open closed principle', any future changes around each 'indexalso' type can be kept isolated to logic clearly related to that type of promo.

File: src/app/containers/StoryPromo/IndexAlsos/index.jsx [hunk 4]
```diff
@@ -118,16 +127,18 @@ const IndexAlsosContainer = ({ alsoItems, script, service, dir }) => {
...
     assetUri: string.isRequired,
     cpsUrn: string,
-  }).isRequired,
+  }),
   summary: string,
   timestamp: number,
-  cpsType: string.isRequired,
-  id: string.isRequired,
+  cpsType: string,
+  id: string,
```
Comment (chris-hinds) [inline src/app/containers/StoryPromo/IndexAlsos/index.jsx]: Was initially concerned about removing the required prop from these values, however I'd rather this than a duplicate component with different prop types

File: src/app/containers/StoryPromo/IndexAlsos/index.jsx [hunk 5]
```diff
@@ -75,17 +75,26 @@ const IndexAlsosContainer = ({ alsoItems, script, service, dir }) => {
     <IndexAlsos offScreenText={relatedContent} data-e2e="index-alsos">
       <IndexAlsosWrapper>
         {alsoItems.slice(0, MAX_NUM_INDEX_ALSOS).map(item => {
-          const { id, cpsType, mediaType } = item;
+          const { cpsType, mediaType } = item;
+
+          const aresId = pathOr(null, ['id'], item);
+          const promoId = pathOr(null, ['uri'], item);
+          const id = aresId || promoId;
```
Comment (chris-hinds) [inline src/app/containers/StoryPromo/IndexAlsos/index.jsx]: `id` is used as the react component key, is it worth us having an addition check to ensure `id` is not null before passing it to the component. That might be overkill so am happy to leave it as is.

File: src/app/containers/StoryPromo/IndexAlsos/index.jsx (hunk 4 above)
Comment (jimjohnsonrollings) [reply src/app/containers/StoryPromo/IndexAlsos/index.jsx]: Andrew has made a suggestion for how to avoid this.

File: src/app/containers/StoryPromo/IndexAlsos/index.test.jsx (hunk 3 above)
Comment (jimjohnsonrollings) [reply src/app/containers/StoryPromo/IndexAlsos/index.test.jsx]: Done

File: src/app/containers/StoryPromo/IndexAlsos/index.jsx (hunk 5 above)
Comment (jimjohnsonrollings) [reply src/app/containers/StoryPromo/IndexAlsos/index.jsx]: It's now a required prop again

File: src/app/containers/StoryPromo/IndexAlsos/index.jsx (hunk 1 above)
Comment (jimjohnsonrollings) [reply src/app/containers/StoryPromo/IndexAlsos/index.jsx]: Done

File: src/app/containers/StoryPromo/IndexAlsos/index.jsx (hunk 2 above)
Comment (jimjohnsonrollings) [reply src/app/containers/StoryPromo/IndexAlsos/index.jsx:156]: Done

**Review by andrewscfc — APPROVED** [review]
Thanks for the changes @jimjohnsonrollings

**Review by chris-hinds — APPROVED** [review]
