### PR TITLE
Changes useClickTrackerHandler to use currentTarget instead of target

### LINKED ISSUE #9510: Podcast links - links do not open on single click
**Describe the bug**
Inconsistent behaviour with opening podcast links: sometimes they open with a single click and sometimes only with a double click (i.e non-responsive after a single click). This is happening across the majority of desktop & mobile browsers (e.g Desktop - Firefox Chrome, Opera). 

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Live podcast page: https://www.bbc.com/portuguese/podcasts/p09qw1cn
2. Scroll down to podcast links: https://www.bbc.com/portuguese/podcasts/p09qw1cn#third-party-links
3. Click once on link/s (e.g Spotify, Arquivo.., RSS) 
4. New window does not always open. 

**Expected behaviour**
I would expect links to open with a single click.

**Testing notes**

- [x] This bug fix is expected to need manual testing.

### PR DESCRIPTION
**Pull request by HarveyPeachey**
Resolves #9510 

**Overall change:**
Changes the `useClickTrackerHandler` hook to use currentTarget to find the `nextPageUrl`.

**Code changes:**

- Switches target with currentTarget as our usage within Simorgh is different to the previous example docs.
- Updates `useClickTrackerHandler` docs

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project
- [x] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [x] This PR requires manual testing

### CODE REVIEW

File: src/app/hooks/useClickTrackerHandler/index.jsx [hunk 1]
```diff
@@ -52,7 +52,8 @@ const useClickTrackerHandler = (props = {}) => {
         ].every(Boolean);
 
         if (shouldSendEvent) {
-          const nextPageUrl = path(['target', 'href'], event);
+          const aTag = path(['currentTarget'], event).querySelector('a');
```
Comment (jroebu14) [inline src/app/hooks/useClickTrackerHandler/index.jsx]: would this not break where the ref is applied to the anchor in other components?

Comment (HarveyPeachey) [reply src/app/hooks/useClickTrackerHandler/index.jsx]: So like this you mean? Where the second link is clicked?
```html
<TrackerElement onClick={useClickTrackerHandler}>
  <Container1>
    <a href="nice.com">
      <span>
        first link
      </span>
    </a>
  </Container1>
  <Container2>
    <a href="nice.com">
      <span>
        second link
      </span>
    </a>
  </Container2>
</TrackerElement>
```

Comment (jroebu14) [reply src/app/hooks/useClickTrackerHandler/index.jsx]: No I mean this would break.

```jsx
    <a href="nice.com" onClick={useClickTrackerHandler}>
      <span>
        first link
      </span>
    </a>
```

Is the fix to just put `onClick={useClickTrackerHandler}` on the anchor rather than a parent node?

Comment (HarveyPeachey) [reply src/app/hooks/useClickTrackerHandler/index.jsx]: That shouldn't break I don't think because `currentTarget` should be `<a href="nice.com"><span>first link</span></a>` as `currentTarget` is the top level element that fires the `onClick` event, so when it queries for the anchor tag it should just return the anchor tag I think unless I'm understanding it wrong.

This would break:

```html
<a href="nice.com" onClick={useClickTrackerHandler}>
  <a href="notnice.com">
    <span>
      first link
    </span>
  </a>
<a href="nice.com">
```
As it wouldn't redirect to the inner href. But that's not really a use case I don't think

Comment (jroebu14) [reply src/app/hooks/useClickTrackerHandler/index.jsx]: If you query for an anchor element while the currentTarget is an anchor it would return null unless it contained an anchor. So this example would stop working https://github.com/bbc/simorgh/blob/latest/src/app/containers/MostRead/Canonical/Item/index.jsx#L108

I think it's correct to change to using currentTarget but the tracker ref should always be placed on the anchor if you want to click track an anchor

**Review by jroebu14 — APPROVED** [review]

**Comment by jroebu14** [comment]
Nice work!

**Review by mfonofm — APPROVED** [review]

**Comment by skwong25** [comment]
Tested locally across:

Desktop: Chrome, Safari, Opera, FF 
Mobile: Chrome, Firefox, Safari (iOS), Opera Mini (Android), Samsung Browser

Behaviour as expected: links open on single-click.
Will move this ticket into Ready to Merge.

(Same comment is on ticket #9510! Sorry about double commenting)

**Comment by skwong25** [comment]
Additional regression tests required on components that use the click tracker to make sure they still function the same / to check if the ATI is firing correctly upon click.

**Affected [Storybook components](https://5d28eb3fe163f6002046d6fa-vetuktwmmz.chromatic.com/?path=/story/moment-locales-editorial-view--afaanoromoo-om):**
- Features and Analysis - http://localhost:7080/igbo/articles/cr1lw620ygjo (Kọwaara m isi akụkọ)
- Recommendations - http://localhost:7080/mundo/23263889
- Related Content - (same link as above) 
- Most Read - (same link as above) 
- Recent Audio Episodes - http://localhost:7080/persian/bbc_persian_radio/w172x32355t5635
- Podcast Promo - https://www.bbc.com/persian/iran-53521826,  http://localhost:7080/arabic/world-57714779
- Related Topics - http://localhost:7080/mundo/deportes-36935058

~~**Above components are covered by following Live pages**~~
~~CPS Article: https://www.bbc.com/portuguese/geral-58957699~~
~~-Features and Analysis (RHS- Leia mais)~~
~~- Most Read (RHS - Mais lidas)~~
~~- Podcast Promo(RHS currently) --> http://localhost:7080/arabic/world-57714779~~
~~- Related Topics (below article - Tópicos relacionados)~~
~~- Related Content (below article - Histórias relacionadas)~~
~~- Recommendations - (WSOJ - Quizás también te interese)~~

~~- Recent Audio Episodes:~~
~~Podcasts: https://www.bbc.com/portuguese/podcasts/p07r3r3t , http://localhost:7080/arabic/podcasts/p09w8yvk~~
~~Radio: https://www.bbc.com/afrique/bbc_afrique_radio/w172y1fhvndyly8~~

~~For the above live webpages, the following commands Iets us run simorgh locally and pull in live data:~~
~~* 		Yarn run build:test:debug && npm start —> Test~~
~~* 		Yarn run build:live:debug && npm start —> Live~~

~~Alternative: Full list of pages to run locally with mock data [here](https://github.com/bbc/simorgh/blob/latest/docs/Simorgh-Release-Info.md).~~

~~**Tools**~~
~~Chrome ATI Tag Inspector plugin seems not to register hits and is known to be a bit odd with our implementation.~~
~~Alternative: Using Chrome Dev Tools Network tab and filtering by 'idclient' to verify hits.~~

**Comment by paruchurisilpa** [comment]
We have gone through the links above and they seem to be making nan ATI call, sometimes we have to refresh twice for a click event to be made but eventually it comes up.

LGTM..

**Comment by HarveyPeachey** [comment]
@paruchurisilpa @skwong25 Thanks for testing, will merge in now
