### PR TITLE
Error page font & lang attribute fix

### LINKED ISSUE #2449: Error page text is using Times New Roman
**Describe the bug**
The Text on the error page is using Times New Roman instead of Reith. 

**To Reproduce**

1. On latest branch
2. run `npm run dev`
3. visit http://localhost:7080/news/articles/cerrorpage1o

**Expected behavior**
The body text should render in Reith Sans. 

NB: The 404 already correctly renders in Reith Sans. The `Page cannot be found` is expected to render in Reith Serif and correctly does. 

**Screenshots**
image

**Additional context**
FireFox has good dev tools for checking the font in the console for each element.

### PR DESCRIPTION
**Pull request by sareh**
Resolves #2449

**Overall change:** Ensure Reith Sans is used for paragraphs and lang attribute is correct `en-GB`

404 (e.g. visit this non-existent page locally: `http://localhost.bbc.com:7080/news/articles/c0000000039o`)
Screenshot Page cannot be found - BBC News

500
Screenshot Internal server error - BBC News

**Code changes:**

- Ensure paragraphs on Error pages use Reith Sans font
- Use correct lang attribute for Error pages 

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by dr3 — APPROVED** [review]

File: src/app/components/ErrorPage/index.jsx [hunk 1]
```diff
@@ -45,21 +49,21 @@ const ErrorPage = ({
           <StatusCode script={script}>{statusCode}</StatusCode>
           {title}
         </ShortHeadline>
-        <Paragraph script={script}>{message}</Paragraph>
+        <StyledParagraph script={script}>{message}</StyledParagraph>
         <ul>
           {solutions.map(text => (
-            <Paragraph script={script} as="li" key={idSanitiser(text)}>
+            <StyledParagraph script={script} as="li" key={idSanitiser(text)}>
```
Comment (thekp) [inline src/app/components/ErrorPage/index.jsx]: Psammead paragraph has a required prop for `service` now.
https://github.com/bbc/psammead/tree/latest/packages/components/psammead-paragraph
I havn't tested it locally but would passing the current service here fix this, rather than creating a new styledParagraph ?

Comment (sareh) [reply src/app/components/ErrorPage/index.jsx]: Thanks. I've made the change.

**Review by thekp — APPROVED** [review]
thanks for the update 👍

**Comment by sareh** [comment]
This has been UX reviewed by @nataliesmart.

**Comment by paruchurisilpa** [comment]
This looks good to me, can be merged..
