### PR TITLE
fix: default variant redirects for amp

### LINKED ISSUE #4710: Variant redirects not working for amp urls
**Describe the bug**
The [default variant redirect feature](https://github.com/bbc/simorgh/pull/4567) does not work when the URL has the `.amp` suffix.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.test.bbc.com/ukchina.amp
2. Notice the 500 status code

**Expected behaviour**
The page should load in amp mode.

**Screenshots**

image

**Testing notes**
Regression tests for frontpage, and article urls, with expected redirects

- [x] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by mykeels**
Resolves #4710

**Overall change:** _Perform a server-side redirect when a `<Redirect />` is detected._

**Code changes:**

- _Perform a server-side redirect when a `<Redirect />` is detected._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [x] This PR requires manual testing

### CODE REVIEW

File: src/server/Document/index.jsx [hunk 1]
```diff
@@ -34,14 +36,19 @@ const renderDocument = async ({
...
-          context={{}}
+          context={context}
           service={service}
           isAmp={isAmp}
         />,
       ),
     ),
   );
 
+  if (context.url) {
```
Comment (andrewscfc) [inline src/server/Document/index.jsx:47]: I can't see anywhere `context.url` is set? Is it set as a side-effect of passing it into `<ServerApp>`?

**Review by andrewscfc — COMMENTED** [review]
Not fully understanding this yet, just a question to learn :)

File: src/server/index.jsx [hunk 2]
```diff
@@ -219,17 +219,21 @@ server
...
+        bbcOrigin,
+        data,
+        isAmp,
+        routes,
+        service,
+        url,
+        variant,
+      });
+
+      if (typeof result === 'object' && result.url) {
```
Comment (jroebu14) [inline src/server/index.jsx]: Is result ever not an object? How can you tell we should redirect by checking the presence of an url?

File: src/server/Document/index.jsx (hunk 1 above)
Comment (mykeels) [reply src/server/Document/index.jsx:47]: Yes, I provided [a link](https://alligator.io/react/react-router-ssr/) below this line. It seems to be the way to know that a redirect has occurred when rendering the application.

File: src/server/index.jsx (hunk 2 above)
Comment (mykeels) [reply src/server/index.jsx]: The result is usually a string. I modified the `renderDocument` function, to return the context, when a redirect occurs when rendering the app. This way, the express server . knows, and can perform a 301 redirect accordingly.

**Review by andrewscfc — APPROVED** [review]
Approach explained on a call LGTM

The code climate issues seem unrelated to this work?

File: src/server/Document/index.jsx [hunk 3]
```diff
@@ -34,14 +36,19 @@ const renderDocument = async ({
...
+    // https://alligator.io/react/react-router-ssr/
```
Comment (jroebu14) [inline src/server/Document/index.jsx]: That's a big article. You should quote with the only relevant sentence from that article 

> React Router automatically adds an url property with the redirected url to the context object when a Redirect component is used - https://alligator.io/react/react-router-ssr/

File: src/server/index.jsx (hunk 2 above)
Comment (jroebu14) [reply src/server/index.jsx]: I think any function that could return either a string or an object is confusing. I wonder if there's a better way 🤔

Comment (jroebu14) [reply src/server/index.jsx]: Even with the name of `renderDocument` I'm expecting a document to be rendered and not potentially an object with an url that should be recognised as an url to redirect to.

Comment (jroebu14) [reply src/server/index.jsx]: maybe a solution is to throw an error inside of `renderDocument` when it's a redirect? then in catch block below you could redirect. maybe not though because a redirect isn't really an error

Comment (jroebu14) [reply src/server/index.jsx]: or we could change the result of renderDocument to always return objects. So for a redirect:

```js
{
  status: 301,
  redirectUrl: 'someUrl'
}
```

and for a rendered document

```js
{
  status: 200,
  html: 'theDocumentHTMLString'
}
```

Comment (mykeels) [reply src/server/index.jsx]: I like changing the result of renderDocument to always return an object.

Comment (mykeels) [reply src/server/index.jsx]: I think introducing `status` adds complexity we do not need. When returning the html, we do not know that it'll be a success result, as it could be a 404 or 500 result, yet we'd be returning `200`.

`{ html: '' }` and `{ redirectUrl: '' }` alone, should offer enough context to the nature of the result.

**Review by jroebu14 — APPROVED** [review]
Looks good!
