### PR TITLE
Emotion SSR - All

### LINKED ISSUE #7772: [Parent Issue] Migrate from Styled Components to Emotion
## Outline
Following preliminary work (covered in Background 👇), we wish to migrate our CSS-in-JS library from Styled Components to Emotion. This will release us from the Styled Components shaped hole we've been stuck in since we learned we couldn't upgrade to the latest version.

In migrating to Emotion, we will leave behind Styled Components four, the stale issues with companion libraries preventing us from upgrading to Styled Components five, and likely see an exceptional increase in real-world server-side rendering time. Emotion's runtime is also smaller than Styled Components, so we will see a reduction in client-side bundle sizes.

### Psammead
- [x] Update README to notify users of move to Emotion https://github.com/bbc/psammead/issues/3765
- [x] [1/3] Install Emotion whilst being backwards compatible https://github.com/bbc/psammead/pull/3867
- [x] [2/3] Refactor "dynamic styles" and `attrs()` use for Emotion https://github.com/bbc/psammead/issues/3763
- [x] [3/3] To Emotion and beyond https://github.com/bbc/psammead/pull/3926

### Simorgh
- [x] Emotion SSR - All #8171

---

## Background
This work stemmed from the following root issue: Simorgh performance profiling #6922.
### Investigation
The following document is a living investigation, which has informed the direction of this work: [Dropbox Paper: Simorgh SSR Performance](https://paper.dropbox.com/doc/Simorgh-SSR-performance--A7TkHsPS9umCiPdfP6x~wqhVAg-z1ffIgMu97RMinpYS4blG)

#### Phase 1
- [1/2] Emotion PoC – SSR Perf. https://github.com/bbc/psammead/issues/3677
- https://github.com/simonsinclair/psammead
- https://github.com/simonsinclair/psammead-packages

#### Phase 2
- [2/2] Emotion PoC – SSR Perf. #7536
- https://github.com/simonsinclair/simorgh

#### Results

A single (non-clustered) Simorgh instance renders pages 35% faster with Emotion.

Screenshot 2020-09-14 at 17 32 12

### PR DESCRIPTION
**Pull request by simonsinclair**
Resolves https://github.com/bbc/simorgh/issues/7772.

### Overall change

The base branch branch including migrations from Ryan and Richard.

1. Environment
2. Migrations
    - [Modules](https://paper.dropbox.com/doc/Simorgh-module-checklist-for-Emotion-migration--A8GwBhgN8qjchv_TXdQhm1zeAQ-j29uePJ6RypZnB7zwOvRh)

### Code changes

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project

**Testing:**

- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

File: src/app/containers/CpsRelatedContent/RelatedContentPromoList/index.jsx [hunk 1]
```diff
@@ -35,7 +33,7 @@ const RelatedContentPromoList = ({ promoItems, dir, isMediaContent }) => {
         group4: 8,
         group5: 8,
       }}
-      as={isMediaContent ? MostWatchedOl : StoryPromoUl}
+      as={isMediaContent ? <MostWatchedOl role="list" /> : StoryPromoUl}
```
Comment (RichardPK) [inline src/app/containers/CpsRelatedContent/RelatedContentPromoList/index.jsx]: Is this implementation OK or should it be receiving children, rather than opening & closing the component in one declaration?

File: src/app/containers/Ad/Amp/index.jsx [hunk 2]
```diff
@@ -124,6 +124,7 @@ const AmpAd = ({ slotType }) => {
                 script={script}
                 service={service}
                 dir={dir}
+                tabIndex="-1"
```
Comment (chris-hinds) [inline src/app/containers/Ad/Amp/index.jsx:126]: Is this new? did we not have to declare this before?

File: src/app/pages/StoryPage/StoryPage.jsx [hunk 3]
```diff
@@ -239,14 +239,14 @@ const StoryPage = ({ pageData, mostReadEndpointOverride }) => {
     }
   `;
 
-  const MostReadSection = styled.section.attrs(() => ({
-    role: 'region',
-    'aria-labelledby': 'Most-Read',
-    'data-e2e': 'most-read',
-  }))``;
+  const MostReadSection = styled.section``;
```
Comment (chris-hinds) [inline src/app/pages/StoryPage/StoryPage.jsx]: Can this not be removed and we simply use the `as` prop when there are no styles to be applied? https://emotion.sh/docs/styled#as-prop

File: src/server/Document/component.test.jsx [hunk 4]
```diff
@@ -17,10 +17,10 @@ describe('Document Component', () => {
       <script src="igbo.js" />
     </>
   );
-  const styleTags = (
-    <style data-styled-components="abc">{'html { color: red; }'}</style>
-  );
-  const styleTagsAmp = <style amp-custom="">{'html { color: red; }'}</style>;
+  // const styleTags = (
```
Comment (chris-hinds) [inline src/server/Document/component.test.jsx]: Are these comments supposed to be here still?

File: src/server/Document/index.jsx [hunk 5]
```diff
@@ -1,15 +1,20 @@
-import React from 'react';
-import { ChunkExtractor } from '@loadable/server';
 import path from 'path';
+
+import React from 'react';
```
Comment (chris-hinds) [inline src/server/Document/index.jsx:2]: Tiny thing but why has the import order changed?

File: src/server/Document/index.jsx [hunk 6]
```diff
@@ -1,15 +1,20 @@
...
 import { renderToString, renderToStaticMarkup } from 'react-dom/server';
-import { ServerStyleSheet } from 'styled-components';
+import { ChunkExtractor } from '@loadable/server';
+import { CacheProvider } from '@emotion/core';
+import createEmotionServer from 'create-emotion-server';
+import createCache from '@emotion/cache';
 import { Helmet } from 'react-helmet';
+
```
Comment (chris-hinds) [inline src/server/Document/index.jsx]:
```suggestion
```

**Review by chris-hinds — COMMENTED** [review]
Left a few comments

File: src/app/containers/Ad/Amp/index.jsx (hunk 2 above)
Comment (jroebu14) [reply src/app/containers/Ad/Amp/index.jsx:126]: I think it's a substitute for this https://github.com/bbc/simorgh/pull/8171/files#diff-7949509f4f120c6aa52921597e989601ce67d06207e14e1aa9277572316de68aL52

File: src/app/containers/CpsRelatedContent/RelatedContentPromoList/index.jsx (hunk 1 above)
Comment (jroebu14) [reply src/app/containers/CpsRelatedContent/RelatedContentPromoList/index.jsx]: Yeh something doesn't seem right here. Worth looking into

Comment (RichardPK) [reply src/app/containers/CpsRelatedContent/RelatedContentPromoList/index.jsx]: Aye fixed this as part of the audit/bug-shooting PR https://github.com/bbc/simorgh/pull/8174/files#diff-9648cbb126e6fd0f5cf1ce1339a624d4498186ab8ab30813d19bf955f1d595bcR40

File: src/app/components/Grid/index.jsx [hunk 7]
```diff
@@ -216,7 +214,7 @@ export const GridItemMediumNoMargin = ({
 export const GridItemLarge = ({ as, ...props }) => (
```
Comment (jroebu14) [inline src/app/components/Grid/index.jsx]: we can just spread all the props

File: src/app/containers/App/App.jsx [hunk 8]
```diff
@@ -88,13 +99,17 @@ export const App = ({ location, initialData, bbcOrigin, history }) => {
...
 
-  return renderRoutes(routes, {
-    ...state,
-    bbcOrigin,
-    previousPath,
-    loading: routeHasChanged,
-    showAdsBasedOnLocation,
-  });
+  return (
+    <StyledApp darkMode={initialData.darkMode}>
```
Comment (jroebu14) [inline src/app/containers/App/App.jsx]: Not one for now but I think this sort of thing could be controlled with a theme context provider

File: src/app/containers/CpsRecommendations/index.jsx [hunk 9]
```diff
@@ -18,6 +29,27 @@ const RecommendationsWrapper = styled.div`
   background-color: ${C_LUNAR};
   padding-bottom: ${GEL_SPACING};
   margin-bottom: ${GEL_SPACING_TRPL};
+  margin: ${GEL_SPACING_TRPL} 0;
+  padding: ${GEL_SPACING_DBL} ${GEL_SPACING};
+  @media (min-width: ${GEL_GROUP_2_SCREEN_WIDTH_MIN}) and (max-width: ${GEL_GROUP_3_SCREEN_WIDTH_MAX}) {
```
Comment (jroebu14) [inline src/app/containers/CpsRecommendations/index.jsx:32]: makes me think psammed grid kind of has a bug

File: src/app/pages/LiveRadioPage/LiveRadioPage.jsx [hunk 10]
```diff
@@ -22,6 +24,12 @@ const staticAssetsPath = `${process.env.SIMORGH_PUBLIC_STATIC_ASSETS_ORIGIN}${pr
 
 const audioPlaceholderImageSrc = `${staticAssetsPath}images/amp_audio_placeholder.png`;
 
+const StyledGelPageGrid = styled(GelPageGrid)`
+  @media (min-width: ${GEL_GROUP_4_SCREEN_WIDTH_MIN}) {
+    width: 100%;
```
Comment (jroebu14) [inline src/app/pages/LiveRadioPage/LiveRadioPage.jsx]: does this not take care of this? https://github.com/bbc/simorgh/blob/cf1310650a137063d07ff410d5e207063bf81331/src/app/components/Grid/index.jsx#L73

File: src/app/pages/StoryPage/StoryPage.jsx [hunk 11]
```diff
@@ -238,14 +238,9 @@ const StoryPage = ({ pageData, mostReadEndpointOverride }) => {
...
 
-  const MostReadSection = styled.section.attrs(() => ({
-    role: 'region',
-    'aria-labelledby': 'Most-Read',
-    'data-e2e': 'most-read',
-  }))``;
-
   const MostReadWrapper = ({ children }) => (
-    <MostReadSection>
+    // eslint-disable-next-line jsx-a11y/no-redundant-roles
```
Comment (jroebu14) [inline src/app/pages/StoryPage/StoryPage.jsx]: should we listen to this lint error?

File: src/app/containers/OnDemandHeading/StyledRadioHeadingContainer.jsx [hunk 12]
```diff
@@ -1,12 +1,18 @@
...
   GEL_SPACING_QUAD,
 } from '@bbc/gel-foundations/spacings';
+import { MEDIA_QUERY_TYPOGRAPHY } from '@bbc/gel-foundations/breakpoints';
 import OnDemandHeading from '.';
 
 const StyledRadioHeadingContainer = styled(OnDemandHeading)`
   padding: ${GEL_SPACING_QUAD} 0 ${GEL_SPACING_DBL};
+
+  /* We need a media query here to explicitly overwrite the same media query within psammead-headings' Headline  */
+  ${MEDIA_QUERY_TYPOGRAPHY.LAPTOP_AND_LARGER} {
```
Comment (RichardPK) [inline src/app/containers/OnDemandHeading/StyledRadioHeadingContainer.jsx]: Note to change this media query

**Comment by karinathomasbbc** [comment]
I have noticed that Chromatic UI tests are now failing, due to the same reasons that they were failing on Psammead a week or so ago. I think it is in some way related to emotion, but can't be sure. It looks like it should be a simple matter of upgrading to `chromatic` from `storybook-chromatic`. I'll do this in a separate PR, so you don't need to worry https://github.com/bbc/simorgh/pull/8275

File: src/app/containers/App/App.jsx (hunk 8 above)
Comment (simonsinclair) [reply src/app/containers/App/App.jsx]: I've added that to the notes. 👍  P.S. This logic was moved to `src/app/Layouts/defaultPageWrapper.jsx` at the end of yesterday following the merge of Ryan's PR.

**Comment by RichardPK** [comment]
An update on some of the ongoing work here. I'll edit this comment as these checks finish:

- [x] A11y sense-check using NVDA, JAWS & talkback AT by @LilyL0u (✅  - passed)
- [x] UX review by Edmund & Fan. Issues being captured here https://github.com/bbc/simorgh/issues/8305 (✅  - some issues found but can be resolved after merge)
- [x] B-tier browser regression testing by @LilyL0u. Issues captured here https://github.com/bbc/simorgh/issues/8306
- [x] Respond to CR comments
- [x] Update snapshots https://github.com/bbc/simorgh/pull/8309

Some blue/green urls for testing:

map - http://simorgh-infrastructure.api.bbci.co.uk/pidgin/54776032
live radio - http://simorgh-infrastructure.api.bbci.co.uk/korean/bbc_korean_radio/liveradio
od radio (expired) - http://simorgh-infrastructure.api.bbci.co.uk/pashto/bbc_pashto_radio/w3ct0lz1
od tv - http://simorgh-infrastructure.api.bbci.co.uk/afrique/bbc_afrique_tv/tv_programmes/w13xttmz
most watched - http://simorgh-infrastructure.api.bbci.co.uk/sinhala/media/video
pgl - http://simorgh-infrastructure.api.bbci.co.uk/azeri/azerbaijan-44208474
most read - http://simorgh-infrastructure.api.bbci.co.uk/afrique/popular/read
article - http://simorgh-infrastructure.api.bbci.co.uk/amharic/articles/c0lgxqknqkdo
FIX - http://simorgh-infrastructure.api.bbci.co.uk/afrique/48465371
IDX - http://simorgh-infrastructure.api.bbci.co.uk/persian/afghanistan
front page - http://simorgh-infrastructure.api.bbci.co.uk/russian
sty - http://simorgh-infrastructure.api.bbci.co.uk/pidgin/tori-54782862

File: src/app/pages/LiveRadioPage/LiveRadioPage.jsx (hunk 10 above)
Comment (RichardPK) [reply src/app/pages/LiveRadioPage/LiveRadioPage.jsx]: Ah yes, I think it does - nice one. 

We added this because we had an issue where this `width: 100%;` wasn't being set unless wrapped in a media query - it was inheriting `width: initial`, which would make the player really narrow unless the text summary filled to the max width of the container.

Fixed in https://github.com/bbc/simorgh/pull/8171/commits/66c2c54769c74cd45ec6f62669055ca70172a44f

File: src/app/containers/CpsRecommendations/index.jsx (hunk 9 above)
Comment (RichardPK) [reply src/app/containers/CpsRecommendations/index.jsx:32]: @ryanmccombe implemented these styling tweaks, he'd be best to respond to this

File: src/app/components/Grid/index.jsx (hunk 7 above)
Comment (simonsinclair) [reply src/app/components/Grid/index.jsx]: I've made these changes.

File: src/app/pages/StoryPage/StoryPage.jsx (hunk 11 above)
Comment (simonsinclair) [reply src/app/pages/StoryPage/StoryPage.jsx]: I've pruned instances of this comment and added `'jsx-a11y/no-redundant-roles': 'off',` to our ruleset.

File: src/app/containers/CpsRecommendations/index.jsx (hunk 9 above)
Comment (simonsinclair) [reply src/app/containers/CpsRecommendations/index.jsx:32]: - I've pruned the unnecessary shorthand (`padding-bottom` and `margin-bottom`) rules as these are overwritten by the lines you've highlighted. There are no visual changes.
- We should investigate the possible bug with psammead-grid following the merge of this PR.

File: src/server/Document/component.test.jsx (hunk 4 above)
Comment (simonsinclair) [reply src/server/Document/component.test.jsx]: No, these have been long-pruned!

File: src/server/Document/index.jsx (hunk 5 above)
Comment (simonsinclair) [reply src/server/Document/index.jsx:2]: No real reason other than consistency 1. Node modules 2. third party modules 3. local modules. 🤩

File: src/app/containers/Ad/Amp/index.jsx (hunk 2 above)
Comment (simonsinclair) [reply src/app/containers/Ad/Amp/index.jsx:126]: It's not new-new. This would have come from an `.attrs()` call. Now we are applying it directly to the component.

**Comment by LilyL0u** [comment]
Here is my documentation of the cross browser testing I have done on Level B browsers as stated in this document https://confluence.dev.bbc.co.uk/display/news/January+2020+-+Agreed+browser+support+for+Simorgh

https://docs.google.com/spreadsheets/d/1Ud7c6U6u0yV1w-toLqxwK1wmzxcfx22kY1wYZY4ZNZM/edit?usp=sharing
You can access the sheet with your BBC Google Suite account

**Review by chris-hinds — APPROVED** [review]

**Review by jroebu14 — APPROVED** [review]
