### PR TITLE
fix grey box in most read

### LINKED ISSUE #9578: Most Read background colour does not match other headings
**Describe the bug**
The background colour of `Most Read` heading is different to other headings on the front page. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.bbc.com/mundo
2. Scroll down to `Most read` section of the page.
3. Most read heading has grey background.

**Expected behaviour**
Background  colour of `Most read` should be the same as other headings on the page

**Screenshot

Screenshot 2021-10-22 at 13 57 16

**Additional context**
Background colour prop is not passed to the FrontPage component.
https://github.com/bbc/simorgh/blob/latest/src/app/pages/FrontPage/FrontPage.jsx#L43

### PR DESCRIPTION
**Pull request by DarioR01**
Resolves #9578

**Overall change:**
Updated background colour for Most read from C_Grey_2 to C_Ghost

**Code changes:**

- Imported color C_GHOST
- Passed C_Ghost to MostReadSectionLabel

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project
- [x] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by MuhammadAHussain — APPROVED** [review]
LGTM 👍

File: src/app/containers/MostRead/label.jsx [hunk 1]
```diff
@@ -44,7 +44,7 @@ MostReadSectionLabel.propTypes = {
 
 MostReadSectionLabel.defaultProps = {
   mobileDivider: true,
-  backgroundColor: C_GREY_2,
+  backgroundColor: C_GHOST,
```
Comment (amoore108) [inline src/app/containers/MostRead/label.jsx]: I think this may need to stay as `C_GREY_2` as it is also used on ArticlePages which has a grey background, compared to the white on FrontPages.

Comment (HarveyPeachey) [inline src/app/containers/MostRead/label.jsx]: This will now introduce a similar bug to the label on the bottom of optimo pages http://localhost:7080/afaanoromoo/articles/c4g19kgl85ko

If you keep it as `C_GREY_2` then the value you've passed into the `MostReadSectionLabel` on `FrontPage.jsx` should work correctly

Comment (DarioR01) [reply src/app/containers/MostRead/label.jsx]: Yes, you are right. To be honest I though I had removed it in my last commit. Will remove it again.
Thank you

Comment (DarioR01) [reply src/app/containers/MostRead/label.jsx]: Yes, you are right. To be honest I though I had removed it in my last commit. Will remove it again.
Thank you

**Review by HarveyPeachey — APPROVED** [review]

**Review by amoore108 — APPROVED** [review]

**Comment by paruchurisilpa** [comment]
Testing:

Regression LGTM.. 

* https://localhost:7080/mundo

Screenshot 2021-10-26 at 09 55 26
