### PR TITLE
Fix firefox javascript preload

### LINKED ISSUE #9770: Javascript resources downloading twice on firefox
**Describe the bug**
When your visit www.bbc.com/mundo all javascript resources download twice:
image
Notice `https://static.files.bbci.co.uk/ws/simorgh-assets/public/static/js/modern.framework.13037174.js` is listed twice above.

_This will double javascript page weight on firefox_

We speculate this may be caused by the preload not functioning correctly as evidenced by the errors in the console:
image

**To Reproduce**
1. Visit www.bbc.com/mundo in Firefox
2. Observe the page functions as normal
3. Open dev tools
4. See console errors above
5. See network tab with duplicated script requests 

**Expected behaviour**
Javascript only loads once in the preload, this behaviour works correctly on Chrome.

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

### PR DESCRIPTION
**Pull request by andrewscfc**
Resolves https://github.com/bbc/simorgh/issues/9770

**Overall change:**
This PR changes our javascript preload links in the page `head` to use the correct preload attribute for javascript module dependencies; `rel: 'modulepreload'` rather than `rel: preload`, this article explains the need for the change: https://developers.google.com/web/updates/2017/12/modulepreload

Additionally, it removes preload links from Amp pages, the change to `rel: 'modulepreload'` made them invalid amp and highlighted that we were incorrectly including preload links for javascript on amp. Our javascript does not run on amp so declaring preload links is unnecessary.

**Code changes:**
- Extract out code that builds assembles attributes for link and script tags to make them easier to test
  - Simplify the logic for inline scripts that have no javascript chunk associated with them https://github.com/bbc/simorgh/pull/9771/commits/b07835daf4f2ada9eb0e4f0ec15ac7fce31f1d4e
  - Add explicit tests for existing and new functionality
- Add check to prevent preload link elements from rendering on amp pages in `component.jsx`
  - Add tests to cover this

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project
- [x] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [x] This PR requires manual testing

### CODE REVIEW

**Comment by amoore108** [comment]
Does this took need updated to be `modulepreload`?:
https://github.com/bbc/simorgh/blob/e799584287fb728674d6908b31fd9cbafbef9a43/src/server/Document/index.jsx#L23

**Review by jroebu14 — APPROVED** [review]
Tested on chrome, safari, firefox, ie11 and edge and it looks good.

More importantly the double fetch in firefox is gone

**Review by amoore108 — APPROVED** [review]

File: src/server/Document/attributeFunctions.js [hunk 1]
```diff
@@ -0,0 +1,25 @@
+import encodeChunkFilename from '../utilities/encodeChunkUri';
```
Comment (jroebu14) [inline src/server/Document/attributeFunctions.js]: This might be a personal opinion but the naming of this file is a little odd. We don't have the naming `{something}Functions` anywhere else in the codebase. If it were me I'd name this file `utils.js` or separate this file into 2 files `getScriptAttributes.js` and `getLinkAttributes.js` and you could even pop them into a `utils` folder but not really necessary.

Comment (andrewscfc) [reply src/server/Document/attributeFunctions.js]: I named them 'attribute functions' to reflect what their typescript types describe their functions as, `AttrFn`:
image
I'd be happy to move this to utilities.

Comment (jroebu14) [reply src/server/Document/attributeFunctions.js]: Ah ok. That's up to you. Just worried about `{something}Functions` spreading in our codebase if someone thinks it's a convention we have

Comment (andrewscfc) [reply src/server/Document/attributeFunctions.js]: Moved https://github.com/bbc/simorgh/pull/9771/commits/3846a569d0fcb04fb0a47918e421f6990c50d3b4

Comment (jroebu14) [reply src/server/Document/attributeFunctions.js]: I still find the naming of a file `{something}Functions` odd but this is probably more of a personal opinion. Thanks for addressing

**Review by jroebu14 — APPROVED** [review]

**Review by amoore108 — APPROVED** [review]

**Comment by paruchurisilpa** [comment]
Tested the following:

LEVEL A: 
Chrome on mobile and desktop
Latest  [ x ]
Safari on Last 2 IOS versions
Safari 13.x [ x ]
Safari 14.x  [ x ]
Opera Mini (Android) 
Including Extreme Mode
Latest Opera on Desktop [ x ]
Latest Firefox on Desktop [ x ]
Latest Samsung Browser (expected to behave like Chrome)  [ x ]

LGTM on above versions..Finishing off the rest..

**Comment by paruchurisilpa** [comment]
@LilyL0u checked the following and the tests have passed:

Android google pixel:
Chrome
Opera mini normal mode
Opera mini extreme mode
Firefox
Opera (edited)
