### PR TITLE
Incorrect chartbeat object

### LINKED ISSUE #2811: Chartbeat sending incorrect object
**Describe the bug**
There are a couple of issues with the objects we are sending to Chartbeat for both Canonical and AMP.

**Canonical**
- We are sending `_sf_async_config.contentType = "New Article";` to Chartbeat. This is incorrect. For canonical, we should be sending `_sf_async_config.type = "New Article"` instead. 
- We are not sending the `_sf_async_config.title` property. This should be the SEO headline of the article, the same as we do for ATI (we should use that helper method).
- When a user navigates to another article within an existing article, the Chartbeat object does not update.
- If a user is not signed in, we are sending `'null'`. We should not send this parameter at all.

**AMP**
- We are also not sending `title`. This should be the same as the `title` we send in the Canonical object. 

**To Reproduce**

1. Go to `https://www.test.bbc.co.uk/news/articles/cn7769kpk9mo`
2. Look for the Chartbeat config object in the `head`
3. See the incorrect object property as described above

**Expected behavior**
When loading an Article, the Chartbeat object should match the object defined in #1986.

**Additional context**

### PR DESCRIPTION
**Pull request by rhenshaw56**
Resolves #2811 and #2878 

**Overall change:** Fix issues with the objects been sent to Chartbeat for both Canonical and AMP.

**Code changes:**

- pass data prop to Chartbeat container in article main
- used analytics util helpers to get values for title and referrer in chartbeat container
- made amp & canonical chartbeat to use title and referrer, modified values to show if present
- added getTitle helper to chartbeat utils
- updated tests/snapshots
- added mock state for toggles in test
- fixed issue with multiple rendering of chartbeat script
---

- [X] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

File: src/app/containers/ChartbeatAnalytics/canonical/index.jsx [hunk 1]
```diff
@@ -20,11 +24,18 @@ const CanonicalChartbeatBeacon = ({
...
+          _sf_async_config.type = "${type}";
           _sf_async_config.sections = "${sections}";
-          _sf_async_config.idSync = {
-           bbc_hid: "${cookie}"
-          };
+          if (${hasReferrer}) {
+            _sf_async_config.virtualReferrer = "${referrer}";
+          }
+          if (${hasCookie}) {
+            console.log('yes', '${cookie}');
```
Comment (12) [inline src/app/containers/ChartbeatAnalytics/canonical/index.jsx]:
```suggestion
```

**Review by 12 — CHANGES_REQUESTED** [review]
When clicking through to a new link in an article (that is still on the bbc domain), I should expect to see the new article title (urlencoded) in this request to `ping.chartbeat.net`:
```
http://ping.chartbeat.net/ping?h=test.bbc.co.uk&p=%2Fnews%2Farticles%2Fc6v11qzyv8po&u=CrAdAKtKLWsCLGNcG&d=bbc.com&g=50924&g0=News%2C%20News%20-%20ART&g1=No%20Author&g4=New%20Article&n=0&f=00001&c=0.1&x=281&m=281&y=4598&o=1073&w=946&j=45&R=1&W=0&I=0&E=5&e=5&r=&KK=229::1018::BASnH4Sb8THDpu-VUCkMae7DTtUsC::::c::http%3A%2F%2Flocalhost.bbc.com%3A7080%2Fnews%2Farticles%2Fc0g992jmmkko::CS7qtqDniX1Bry8OfDKXe-nCdWzDq::&b=1024&_s=%7B%22bbc_hid%22%3A%22vJEW_8dnN_CYGH_XGfNA8mMyMc2tYUJFSX-u1V59gwY%22%7D&t=S1X_JCMJDyeI4z2CD4qK-VBgYADr&V=113&tz=-60&sn=2&sv=jyXQlDqrqXABhI4VCDsOBgWCtfFr&sd=3&im=040b071f&_
```

An example of the initial ping (from the first article):
```
http://ping.chartbeat.net/ping?h=test.bbc.co.uk&p=%2Fnews%2Farticles%2Fc6v11qzyv8po&u=CrAdAKtKLWsCLGNcG&d=bbc.com&g=50924&g0=News%2C%20News%20-%20ART&g1=No%20Author&g4=New%20Article&n=0&f=00001&c=0&x=0&m=0&y=4598&o=1073&w=946&j=45&R=1&W=0&I=0&E=0&e=0&r=&b=1024&_s=%7B%22bbc_hid%22%3A%22vJEW_8dnN_CYGH_XGfNA8mMyMc2tYUJFSX-u1V59gwY%22%7D&t=S1X_JCMJDyeI4z2CD4qK-VBgYADr&V=113&z=t%3DC_YdpQD9sfDHDszrufCn4oY7CWlJQc%26E%3D2%26x%3D0%26c%3D0.11%26y%3D4598%26w%3D946&i=Royal%20wedding%202018%3A%20Bouquet%20laid%20on%20tomb%20of%20unknown%20warrior&tz=-60&sn=1&sv=jyXQlDqrqXABhI4VCDsOBgWCtfFr&sd=3&im=040b071f&_
```

File: src/app/containers/ChartbeatAnalytics/canonical/index.jsx [hunk 2]
```diff
@@ -20,11 +24,17 @@ const CanonicalChartbeatBeacon = ({
...
-          _sf_async_config.contentType = "${type}";
+          _sf_async_config.title = "${title}";
+          _sf_async_config.type = "${type}";
           _sf_async_config.sections = "${sections}";
-          _sf_async_config.idSync = {
-           bbc_hid: "${cookie}"
-          };
+          if (${hasReferrer}) {
+            _sf_async_config.virtualReferrer = "${referrer}";
+          }
```
Comment (jamesdonoh) [inline src/app/containers/ChartbeatAnalytics/canonical/index.jsx]: Won't this mean that L31 will get output into the markup even if there is no referrer?

File: src/app/containers/ChartbeatAnalytics/canonical/index.jsx [hunk 3]
```diff
@@ -20,11 +24,17 @@ const CanonicalChartbeatBeacon = ({
...
+          if (${hasCookie}) {
+            _sf_async_config.idSync = {
+              bbc_hid: "${cookie}"
+             };
+          }
```
Comment (jamesdonoh) [inline src/app/containers/ChartbeatAnalytics/canonical/index.jsx]: Similar question as above.

**Review by jamesdonoh — COMMENTED** [review]
Is there unit test coverage for the changed behaviour when there is no cookie/no referrer? I can't see any but I might be missing it.

File: src/app/containers/ChartbeatAnalytics/canonical/index.jsx (hunk 2 above)
Comment (rhenshaw56) [reply src/app/containers/ChartbeatAnalytics/canonical/index.jsx]: yes @jamesdonoh , it will be in the markup but virtualReferrer won't be added to the config

**Review by twinlensreflex — APPROVED** [review]
Looks good to me!

**Review by 12 — COMMENTED** [review]
image

On page load, I'm getting two requests to `ping.chartbeat.net`. Surely we should only be expecting one?

**Comment by 12** [comment]
The HUD also doesn't update.

File: src/app/containers/ChartbeatAnalytics/canonical/index.jsx (hunk 2 above)
Comment (jamesdonoh) [reply src/app/containers/ChartbeatAnalytics/canonical/index.jsx]: So it will be output but just say `if (false) { _sf_async_config.virtualReferrer = "undefined" }` or similar if there is no referrer? We should not output redundant/unused JS code, it looks untidy and needlessly adds to the number of bytes the user has to download.

Can you think of a different approach to this and the `idSync` property below?

**Review by jamesdonoh — CHANGES_REQUESTED** [review]

**Comment by rhenshaw56** [comment]
> image
> 
> On page load, I'm getting two requests to `ping.chartbeat.net`. Surely we should only be expecting one?

@rhell I think it's actually more than 2 pings because chartbeat gets data in real time, a ping every 15seconds or so

File: src/app/containers/ChartbeatAnalytics/canonical/index.jsx (hunk 2 above)
Comment (rhenshaw56) [reply src/app/containers/ChartbeatAnalytics/canonical/index.jsx]: thanks @jamesdonoh I've refactored it

**Comment by rhenshaw56** [comment]
> The HUD also doesn't update.

@rhell HUD is working for me, are you signed in to chartbeat ?

File: src/app/containers/ChartbeatAnalytics/canonical/index.jsx [hunk 4]
```diff
@@ -10,21 +10,47 @@ const CanonicalChartbeatBeacon = ({
...
-    <script async type="text/javascript">
-      {`
+  hasCookie,
+  title,
+  referrer,
+  hasReferrer,
+}) => {
+  const optionalConfigValues = {
+    ...(hasReferrer && { virtualReferrer: referrer }),
+    ...(hasCookie && { idSync: { bbc_hid: cookie } }),
```
Comment (jamesdonoh) [inline src/app/containers/ChartbeatAnalytics/canonical/index.jsx]: Just realised this duplicates https://github.com/bbc/simorgh/pull/2837/files#diff-a6cb5242b50b07228921447ee534136aR11-R12

I think it would make more sense to move any configuration that is common to both AMP and canonical into https://github.com/bbc/simorgh/blob/latest/src/app/containers/ChartbeatAnalytics/index.jsx

File: src/app/containers/ChartbeatAnalytics/canonical/index.jsx [hunk 5]
```diff
@@ -10,21 +10,47 @@ const CanonicalChartbeatBeacon = ({
...
+  };
+
+  useEffect(() => {
+    if (typeof window !== 'undefined' && window.pSUPERFLY) {
+      window.pSUPERFLY.virtualPage({
```
Comment (jamesdonoh) [inline src/app/containers/ChartbeatAnalytics/canonical/index.jsx]: What is this trying to do?

File: src/app/containers/ChartbeatAnalytics/canonical/index.jsx [hunk 6]
```diff
@@ -10,21 +10,47 @@ const CanonicalChartbeatBeacon = ({
...
-          _sf_async_config.contentType = "${type}";
+          _sf_async_config.title = "${title}";
+          _sf_async_config.type = "${type}";
           _sf_async_config.sections = "${sections}";
-          _sf_async_config.idSync = {
-           bbc_hid: "${cookie}"
-          };
+          _sf_async_config = Object.assign(_sf_async_config, ${JSON.stringify(
+            optionalConfigValues,
+          )});
```
Comment (jamesdonoh) [inline src/app/containers/ChartbeatAnalytics/canonical/index.jsx]: This is a slight improvement, is there a reason we can't assemble the whole `_sf_async_config` this way? That would eliminate even more redundancy.

File: src/app/containers/ChartbeatAnalytics/index.jsx [hunk 7]
```diff
@@ -12,27 +15,39 @@ import {
...
   }
-
+  const referrer = getReferrer(platform, origin, previousPath);
+  const title = getTitle(pageType, data, brandName);
   const domain = env !== 'live' ? getDomain('test') : getDomain(service);
   const sections = buildSections(service, pageType);
   const cookie = getSylphidCookie();
   const type = getType(pageType);
+  const hasCookie = !!cookie;
+  const hasReferrer = !!referrer;
```
Comment (jamesdonoh) [inline src/app/containers/ChartbeatAnalytics/index.jsx]: Is it worth the overhead of the extra props? Can't we just check if the `cookie`/`referrer` props are falsy at the level of each component?

File: src/app/containers/ChartbeatAnalytics/canonical/index.jsx (hunk 5 above)
Comment (rhenshaw56) [reply src/app/containers/ChartbeatAnalytics/canonical/index.jsx]: this makes sure that that the config is updated when any of the values change

File: src/app/containers/ChartbeatAnalytics/canonical/index.jsx (hunk 4 above)
Comment (rhenshaw56) [reply src/app/containers/ChartbeatAnalytics/canonical/index.jsx]: yeah, @jamesdonoh we were doing that before but one of the things we needed to change was sending null values, so if we move those conditional logic down one prop level they'll be defined as null where their being used

Comment (rhenshaw56) [reply src/app/containers/ChartbeatAnalytics/canonical/index.jsx]: @jamesdonoh  on the ticket description [here](https://github.com/bbc/simorgh/issues/2811), it says `If a user is not signed in, we are sending 'null'. We should not send this parameter at all.`

File: src/app/containers/ChartbeatAnalytics/canonical/index.jsx [hunk 8]
```diff
@@ -10,35 +10,42 @@ const CanonicalChartbeatBeacon = ({
...
-          function loadChartbeat() {
-           var e = document.createElement('script');
-           var n = document.getElementsByTagName('script')[0];
-           e.type = 'text/javascript';
-           e.async = true;
-           e.src = "${chartbeatSource}";
-           n.parentNode.insertBefore(e, n);
-          }
-          loadChartbeat();
+          _sf_async_config = Object.assign(_sf_async_config, ${JSON.stringify(
```
Comment (HarveyPeachey) [inline src/app/containers/ChartbeatAnalytics/canonical/index.jsx]: https://caniuse.com/#search=object.assign. We might not be able to use `Object.assign` because we need to support the Opera Mini browser.

File: src/app/containers/ChartbeatAnalytics/canonical/index.jsx (hunk 5 above)
Comment (rhenshaw56) [reply src/app/containers/ChartbeatAnalytics/canonical/index.jsx]: https://chartbeat.zendesk.com/hc/en-us/articles/210271287-Handling-virtual-page-changes

File: src/app/containers/ChartbeatAnalytics/amp/index.test.jsx [hunk 9]
```diff
@@ -19,18 +19,60 @@ describe('AmpChartbeatAnalytics', () => {
...
+        'amp-analytics script[type="application/json"]',
+      ).length,
+    ).toEqual(1);
+    expect(
+      container.querySelector('amp-analytics script[type="application/json"]')
+        .innerHTML,
+    ).toMatch(JSON.stringify(expectedValue));
+  });
+
+  it('renders with with appropriate props without referrer or cookie', () => {
```
Comment (HarveyPeachey) [inline src/app/containers/ChartbeatAnalytics/amp/index.test.jsx:51]:
```suggestion
  it('renders with appropriate props without referrer or cookie', () => {
```

File: src/app/containers/ChartbeatAnalytics/canonical/index.jsx (hunk 8 above)
Comment (12) [reply src/app/containers/ChartbeatAnalytics/canonical/index.jsx]: I'm assuming this is because babel cannot transpile this piece of code as it's an interpolated string.

Comment (rhenshaw56) [reply src/app/containers/ChartbeatAnalytics/canonical/index.jsx]: thanks, @HarveyPeachey

Comment (jamesdonoh) [reply src/app/containers/ChartbeatAnalytics/canonical/index.jsx]: Can we avoid using assign completely and just assign the stringified JSON to the variables on L38?

File: src/app/containers/ChartbeatAnalytics/index.test.jsx [hunk 10]
```diff
@@ -91,35 +138,57 @@ describe('Charbeats Analytics Container', () => {
       .fn()
       .mockImplementation(() => 'secction1 section2');
 
+    const toggleState = {
+      live: {
+        chartbeatAnalytics: {
+          enabled: true,
+        },
```
Comment (jamesdonoh) [inline src/app/containers/ChartbeatAnalytics/index.test.jsx:146]: Confused here, the spec name says "toggle enabled for chartbeat on test" but we are changing the state for `live` in this fragment. How does this object relate to `mockToggleState`? The variable naming could make this clearer.

File: src/app/containers/ChartbeatAnalytics/canonical/index.test.jsx [hunk 11]
```diff
@@ -1,21 +1,57 @@
...
+          domain: 'test-domain',
+          type: 'article',
+          sections: 'section1 section2',
+          chartbeatUID: 1111,
+          useCanonical: true,
+          virtualReferrer: '/some-path',
+          title: 'This is another article',
+        },
+      });
+      expect(global.pSUPERFLY.virtualPage).toHaveBeenCalled();
```
Comment (jamesdonoh) [inline src/app/containers/ChartbeatAnalytics/canonical/index.test.jsx]: Can we be more precise and assert that it's called precisely once with the correct data rather than just called?

File: src/app/containers/ChartbeatAnalytics/canonical/index.jsx [hunk 12]
```diff
@@ -1,57 +1,44 @@
...
-  <Helmet>
-    <script async type="text/javascript">
-      {`
+const CanonicalChartbeatBeacon = ({ chartbeatConfig, chartbeatSource }) => {
+  useEffect(() => {
+    if (typeof window !== 'undefined' && window.pSUPERFLY) {
+      /*
+        This function is always called to update config values on page changes 
+        https://chartbeat.zendesk.com/hc/en-us/articles/210271287-Handling-virtual-page-changes
+      */
```
Comment (jamesdonoh) [inline src/app/containers/ChartbeatAnalytics/canonical/index.jsx:11]: Comment is a good idea 👍

File: src/app/containers/ChartbeatAnalytics/canonical/index.jsx [hunk 13]
```diff
@@ -1,57 +1,44 @@
...
+          function merge(obj, src) {
+            for (var key in src) {
+                if (src.hasOwnProperty(key)) obj[key] = src[key];
+            }
+            return obj;
           }
-          loadChartbeat();
+          _sf_async_config = merge(_sf_async_config, ${JSON.stringify(
+            chartbeatConfig,
+          )});
```
Comment (jamesdonoh) [inline src/app/containers/ChartbeatAnalytics/canonical/index.jsx]: For brevity, I would get rid of the function and inline the loop. I believe we can also omit the `hasOwnProperty` as we know the config has no inherited properties. Also means we can skip the assignment on L28

File: src/app/containers/ChartbeatAnalytics/index.jsx [hunk 14]
```diff
@@ -12,37 +15,53 @@ import {
...
     domain,
-    type,
     sections,
-    cookie,
-    chartbeatUID,
+    uid: chartbeatUID,
+    title,
+    ...(isAmp && { contentType: type }),
+    ...(!isAmp && { type }),
+    ...(!isAmp && { type }),
```
Comment (jamesdonoh) [inline src/app/containers/ChartbeatAnalytics/index.jsx]: Think this line is duplicated.

**Review by jamesdonoh — CHANGES_REQUESTED** [review]

File: src/app/containers/ChartbeatAnalytics/index.test.jsx (hunk 10 above)
Comment (rhenshaw56) [reply src/app/containers/ChartbeatAnalytics/index.test.jsx:146]: thanks @jamesdonoh, I think the spec needs to be clearer meant to be `on live`. the `mockToggleState` is a default just in case we don't pass in any `toggleState` would change to `defaultToggleState`

File: src/app/containers/ChartbeatAnalytics/amp/index.jsx [hunk 15]
```diff
@@ -21,36 +16,14 @@ const JsonInlinedScript = data => (
...
-  domain: string.isRequired,
-  type: string.isRequired,
-  sections: string.isRequired,
-  cookie: string,
-  chartbeatUID: number.isRequired,
-};
-
-AmpChartbeatBeacon.defaultProps = {
-  cookie: null,
+  chartbeatConfig: shape({}).isRequired,
```
Comment (12) [inline src/app/containers/ChartbeatAnalytics/amp/index.jsx]: Can we be anymore specific on the expected object that `chartbeatConfig` can be?

File: src/app/containers/ChartbeatAnalytics/canonical/index.jsx [hunk 16]
```diff
@@ -1,57 +1,39 @@
...
+};
 
 CanonicalChartbeatBeacon.propTypes = {
-  domain: string.isRequired,
-  type: string.isRequired,
-  sections: string.isRequired,
-  cookie: string,
-  chartbeatUID: number.isRequired,
-  useCanonical: bool.isRequired,
+  chartbeatConfig: shape({}).isRequired,
```
Comment (12) [inline src/app/containers/ChartbeatAnalytics/canonical/index.jsx]: Same as previous comment

File: src/app/containers/ChartbeatAnalytics/index.jsx [hunk 17]
```diff
@@ -12,37 +15,52 @@ import {
   getDomain,
   buildSections,
   getType,
+  getTitle,
 } from '../../lib/analyticsUtils/chartbeat';
 
-const ChartbeatAnalytics = () => {
-  const { service } = useContext(ServiceContext);
-  const { env, platform, pageType } = useContext(RequestContext);
+import { getReferrer } from '../../lib/analyticsUtils';
```
Comment (12) [inline src/app/containers/ChartbeatAnalytics/index.jsx]: Can you put this above the previous import for consistency / tidiness?

File: src/app/containers/ChartbeatAnalytics/index.jsx [hunk 18]
```diff
@@ -12,37 +15,52 @@ import {
...
+
+const ChartbeatAnalytics = ({ data }) => {
+  const { service, brandName } = useContext(ServiceContext);
+  const { env, platform, pageType, previousPath, origin } = useContext(
+    RequestContext,
+  );
   const { enabled } = useToggle('chartbeatAnalytics');
```
Comment (12) [inline src/app/containers/ChartbeatAnalytics/index.jsx]: Can this go above the previous `const` to keep things a bit tidier?

File: src/app/containers/ChartbeatAnalytics/index.jsx [hunk 19]
```diff
@@ -12,37 +15,52 @@ import {
...
 
   if (!enabled) {
     return null;
   }
-
+  const referrer = getReferrer(platform, origin, previousPath);
```
Comment (12) [inline src/app/containers/ChartbeatAnalytics/index.jsx:33]:
```suggestion

  const referrer = getReferrer(platform, origin, previousPath);
```

**Review by jamesdonoh — APPROVED** [review]
Thanks for the changes, looks good 👍

File: src/app/containers/ChartbeatAnalytics/index.jsx [hunk 20]
```diff
@@ -12,37 +15,52 @@ import {
...
+    title,
+    ...(isAmp && { contentType: type }),
+    ...(!isAmp && { type }),
+    ...(!isAmp && { useCanonical }),
+    ...(!!referrer && { virtualReferrer: referrer }),
+    ...(!!cookie && { idSync: { bbc_hid: cookie } }),
   };
-  return platform === 'amp' ? (
-    <AmpChartbeatBeacon {...commonProps} />
+  return isAmp ? (
```
Comment (12) [inline src/app/containers/ChartbeatAnalytics/index.jsx:51]:
```suggestion

  return isAmp ? (
```

File: src/app/containers/ChartbeatAnalytics/index.jsx [hunk 21]
```diff
@@ -12,37 +15,52 @@ import {
...
   }
-
+  const referrer = getReferrer(platform, origin, previousPath);
+  const title = getTitle(pageType, data, brandName);
   const domain = env !== 'live' ? getDomain('test') : getDomain(service);
   const sections = buildSections(service, pageType);
   const cookie = getSylphidCookie();
   const type = getType(pageType);
-  const commonProps = {
+
```
Comment (12) [inline src/app/containers/ChartbeatAnalytics/index.jsx]:
```suggestion
```

File: src/app/containers/ChartbeatAnalytics/index.jsx [hunk 22]
```diff
@@ -12,37 +15,52 @@ import {
...
     domain,
-    type,
     sections,
-    cookie,
-    chartbeatUID,
+    uid: chartbeatUID,
+    title,
+    ...(isAmp && { contentType: type }),
+    ...(!isAmp && { type }),
+    ...(!isAmp && { useCanonical }),
```
Comment (12) [inline src/app/containers/ChartbeatAnalytics/index.jsx]:
```suggestion
```

File: src/app/containers/ChartbeatAnalytics/index.jsx [hunk 23]
```diff
@@ -12,37 +15,52 @@ import {
...
+  const config = {
     domain,
-    type,
     sections,
-    cookie,
-    chartbeatUID,
+    uid: chartbeatUID,
+    title,
+    ...(isAmp && { contentType: type }),
+    ...(!isAmp && { type }),
```
Comment (12) [inline src/app/containers/ChartbeatAnalytics/index.jsx]:
```suggestion
    ...(!isAmp && { type, useCanonical }),
```

File: src/app/containers/ChartbeatAnalytics/index.jsx [hunk 24]
```diff
@@ -12,37 +15,52 @@ import {
...
+    ...(!isAmp && { useCanonical }),
+    ...(!!referrer && { virtualReferrer: referrer }),
```
Comment (12) [inline src/app/containers/ChartbeatAnalytics/index.jsx]: Do we need the double bang syntax here? I think we can just do
```suggestion
    ...(referrer && { virtualReferrer: referrer }),
```

File: src/app/containers/ChartbeatAnalytics/index.jsx [hunk 25]
```diff
@@ -12,37 +15,52 @@ import {
...
+    ...(!!cookie && { idSync: { bbc_hid: cookie } }),
```
Comment (12) [inline src/app/containers/ChartbeatAnalytics/index.jsx]: Same question as above

File: src/app/containers/ChartbeatAnalytics/amp/index.test.jsx [hunk 26]
```diff
@@ -12,28 +12,65 @@ describe('AmpChartbeatAnalytics', () => {
...
       chartbeatUID: 1111,
+      referrer: '/some-path',
+      title: 'This is an article',
+      idSync: {
+        bbc_hid: 'cookie',
+      },
+    };
+
+    const expectedValue = {
+      vars: {
```
Comment (12) [inline src/app/containers/ChartbeatAnalytics/amp/index.test.jsx]: I think the `{}` and spread operator cancel themselves out, so we should just be able to do:
```suggestion
      vars: config
```

File: src/app/containers/ChartbeatAnalytics/amp/index.test.jsx [hunk 27]
```diff
@@ -12,28 +12,65 @@ describe('AmpChartbeatAnalytics', () => {
...
     const expectedValue = {
       vars: {
-        uid: props.chartbeatUID,
-        sections: props.sections,
-        domain: props.domain,
-        contentType: props.type,
-        idSync: {
-          bbc_hid: props.cookie,
-        },
+        ...config,
```
Comment (12) [inline src/app/containers/ChartbeatAnalytics/amp/index.test.jsx]: Same question as above

**Review by 12 — CHANGES_REQUESTED** [review]
Getting there. Have a few picky requests to make this a bit neater, and also a few things that I think could/should be changed.

File: src/app/containers/ChartbeatAnalytics/index.test.jsx [hunk 28]
```diff
@@ -1,23 +1,46 @@
...
-import ChartBeatAnalytics from '.';
+import { ToggleContext } from '../../contexts/ToggleContext';
+import ChartbeatAnalytics from '.';
 import * as testUtils from '../../lib/analyticsUtils/chartbeat';
+import * as utils from '../../lib/analyticsUtils';
 import * as amp from './amp';
 import * as canonical from './canonical';
 
-const ContextWrap = ({ pageType, platform, origin, children }) => (
+const defualtToggleState = {
```
Comment (12) [inline src/app/containers/ChartbeatAnalytics/index.test.jsx]:
```suggestion
const defaultToggleState = {
```

File: src/app/containers/ChartbeatAnalytics/index.test.jsx [hunk 29]
```diff
@@ -27,12 +50,23 @@ ContextWrap.propTypes = {
   pageType: string.isRequired,
   origin: string.isRequired,
   platform: string.isRequired,
+  toggleState: shape,
+};
+
+ContextWrap.defaultProps = {
+  toggleState: defualtToggleState,
```
Comment (12) [inline src/app/containers/ChartbeatAnalytics/index.test.jsx]:
```suggestion
  toggleState: defaultToggleState,
```

**Review by 12 — APPROVED** [review]
Good work 👍

**Comment by amywalkerdev** [comment]
Going to put this on test instead of testing locally, so moving to ready for merge as no manual testing is required yet
