### PR TITLE
Fix env for Amp showing as "test" locally.

### LINKED ISSUE #2787: env for Amp showing as "test" locally
**Describe the bug**
`env` in the request context for amp pages always shows as `test` locally, this should be fixed to show the correct env enabling us target the right environment in code.

**To Reproduce**

1. run `npm run dev` locally
2. log the value of `env` in the request context
3. view amp page article on your browser eg. http://localhost.bbc.com:7080/news/articles/c0g992jmmkko.amp
4. see that the value of `env` is test (which shouldn't be the case)

**Expected behavior**
`env` should show as `local` locally, `test` on test.bbc.com and `live` on bbc.co.uk

**Additional context**
n/a

### PR DESCRIPTION
**Pull request by RayNjeri**
Signed-off-by: Rachael Njeri <rachael.njeri@andela.com>

Resolves #2787

**Overall change:** _Fixes the bug that shows amp local env as 'test' instead of 'local'_

**Code changes:**

- _Edited the getEnv index file to check is amp isLocal env._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

File: src/app/contexts/RequestContext/index.jsx [hunk 1]
```diff
@@ -17,7 +17,7 @@ export const RequestContextProvider = ({
   previousPath,
 }) => {
   const { isUK, origin } = getOriginContext(bbcOrigin);
-  const env = getEnv(origin);
+  const env = isLocal ? 'local' : getEnv(origin);
```
Comment (jamesdonoh) [inline src/app/contexts/RequestContext/index.jsx]: I don't quite follow why we need to do this. `getEnv` should return `local` if the origin includes the string `local`:
https://github.com/bbc/simorgh/pull/2815/files#diff-75a773bc6e656cc4f1f782712cd28c7eR2-R4

But at this level we're now looking at the output of `isLocal` (based on `process.env`) to override that value, so the logic seems split between two different places. Wouldn't it make more sense for it all to be in `getEnv`?

**Comment by jamesdonoh** [comment]
Do we know exhaustively where `env` is used from the `RequestContext` at present to help us understand what other code could be impacted? It's quite hard to search for unfortunately 😞 

I can see it's used in https://github.com/bbc/simorgh/blob/latest/src/app/containers/Toggle/useToggle.jsx to determine which set of toggle config to use, what other uses are there?

File: src/app/contexts/RequestContext/index.jsx (hunk 1 above)
Comment (dr3) [reply src/app/contexts/RequestContext/index.jsx]: >getEnv should return local if the origin includes the string local

The server render doesnt have an origin locally

Comment (jamesdonoh) [reply src/app/contexts/RequestContext/index.jsx]: Ah thanks @dr3, just to make sure we're clear, you're saying that in local development `bbcOrigin` is undefined here?

https://github.com/bbc/simorgh/blob/0aaaf30f5269c3b920375ec33b6ea26f62a4eae9/src/server/index.jsx#L173

In that case what is the purpose of this?

https://github.com/bbc/simorgh/blob/26ad706388e2605639944c5ac8187408e7679cd3/src/app/contexts/RequestContext/getEnv/index.js#L2-L4

Comment (dr3) [reply src/app/contexts/RequestContext/index.jsx]: Yep, locally `bbcOrigin` is undefined, so https://github.com/bbc/simorgh/blob/latest/src/app/contexts/RequestContext/getOriginContext/index.js#L10 sets origin to localhost 

And then getEnv reads origin as localhost here https://github.com/bbc/simorgh/blob/26ad706388e2605639944c5ac8187408e7679cd3/src/app/contexts/RequestContext/getEnv/index.js#L2-L4

**Comment by dr3** [comment]
Hey :) This can be done by changing https://github.com/bbc/simorgh/blob/latest/src/app/contexts/RequestContext/getOriginContext/index.js#L10 to ``` origin = process.env.SIMORGH_BASE_URL;```.

The original adding of `origin = 'https://www.test.bbc.co.uk';` was a slight mis-step, it could have been `http://localhost.bbc.com:7080` (`process.env.SIMORGH_BASE_URL`) all along, resolving this issue :P

Changing it to `http://localhost.bbc.com:7080` (`process.env.SIMORGH_BASE_URL`) will make a more accurate origin, which, when used by `getEnv`, will produce a more accurate `env` :)

File: src/app/contexts/RequestContext/index.jsx (hunk 1 above)
Comment (dr3) [reply src/app/contexts/RequestContext/index.jsx]: https://github.com/bbc/simorgh/pull/2815#issuecomment-516851453 :)

**Comment by jamesdonoh** [comment]
We should also remove the misleading (?) comments:
```
    // For local dev, set origin to Test
    // Ensures analytics are sent to Test bucket
```

File: src/app/contexts/RequestContext/getOriginContext/index.js [hunk 2]
```diff
@@ -5,9 +5,7 @@ const getOriginContext = bbcOrigin => {
   if (bbcOrigin) {
     origin = bbcOrigin;
   } else if (process && process.env && process.env.APP_ENV === 'local') {
-    // For local dev, set origin to Test
-    // Ensures analytics are sent to Test bucket
-    origin = 'https://www.test.bbc.co.uk';
+    origin = 'http://localhost.bbc.com:7080';
```
Comment (jamesdonoh) [inline src/app/contexts/RequestContext/getOriginContext/index.js]: I'd rather we used `process.env.SIMORGH_BASE_URL` unless anyone can suggest any reason not to, to avoid repeating this value multiple times throughout the codebase.

File: src/app/contexts/RequestContext/getOriginContext/index.test.js [hunk 3]
```diff
@@ -64,8 +64,8 @@ describe('getOriginContext - localhost', () => {
       description: 'should return test if local & undefined bbcOrigin',
       bbcOrigin: undefined,
       expected: {
-        isUK: true,
-        origin: 'https://www.test.bbc.co.uk',
+        isUK: false,
+        origin: 'http://localhost.bbc.com:7080',
```
Comment (jamesdonoh) [inline src/app/contexts/RequestContext/getOriginContext/index.test.js:69]: Test value can remain literal string.

**Review by jamesdonoh — CHANGES_REQUESTED** [review]

**Review by dr3 — APPROVED** [review]

**Review by sareh — APPROVED** [review]
👍 Looks good!

**Review by jamesdonoh — APPROVED** [review]

**Comment by jamesbrumpton** [comment]
lgtm
