### PR TITLE
#5065 Both timestamps displayed on CPS Maps pages

### LINKED ISSUE #5065: Both timestamps displayed on CPS Maps when asset is first published
**Describe the bug**
Newly published MAP pages are showing both firstUpdated and lastUpdated timestamps when a CPS MAP is first published. 

We expect just the first published timestamp to be displayed when a MAP is first published and then the lastUpdated value to be displayed thereafter. 

This follows the same behaviour as Optimo articles. 

This appears to be a new issue. This page for example: https://ares-broker.test.api.bbci.co.uk/api/asset/pidgin/media-23256554  was published just once. 
It displays just one timestamp. 

For all recently published stories from CPS that are only published once, we're seeing the tiniest difference in firstPublished and lastPublished timestamp in the ares response See: https://ares-broker.test.api.bbci.co.uk/api/asset/pidgin/media-23261118  

ares.firstPublished	1578567328000
ares.lastPublished	1578567329000

As a possible solution could we ensure that we only 
display the last updated part of the timestamp is displayed 
where the difference between ares.firstPublished and ares.lastPublished is greater than 60seconds?  

**To Reproduce**
Steps to reproduce the behaviour:

1. Publish a CPS map page or go to https://www.test.bbc.com/pidgin/media-23261118 (published just once) 
2. Note that two timestamps are displayed. 

**Expected behaviour**

This is the timestamp on a MAP we are referring to: 
Screenshot 2019-11-26 at 11 39 30

**We expect the following behaviour: **
**Scenario 1: MAP has been published for the first time**
MAP with no changes: https://www.test.bbc.com/pidgin/media-23256554 

How long ago was it published | Example of what we display
-- | --
< 2 mins ago | 1 minute ago
2 mins ago - 1 hour ago | 42 minutes ago
1 hour ago - 2 hours ago | 1 hour ago
2 hours ago - 10 hours ago | 4 hours ago
More than 10 hours ago, but still today | 9 April 2018, 11:59 BST(or relevant timezone to service)
2 hours ago - 24 hours ago | N/A
More than 10 hours ago, and not today | 9 April 2018(using, but not displaying, relevant timezone)
More than 24 hours ago | N/A

**Scenario 2: MAP has been published with minor changes**
MAP updated with minor changes: https://www.test.bbc.com/pidgin/media-23256554

How long ago was it published | Example of what we display
-- | --
< 2 mins ago | 1 minute ago
2 mins ago - 1 hour ago | 42 minutes ago
1 hour ago - 2 hours ago | 1 hour ago
2 hours ago - 10 hours ago | 4 hours ago
More than 10 hours ago, but still today | 9 April 2018, 11:59 BST(or relevant timezone to service)
2 hours ago - 24 hours ago | N/A
More than 10 hours ago, and not today | 9 April 2018(using, but not displaying, relevant timezone)
More than 24 hours ago | N/A

**Scenario 3: MAP has been published and has had 'News Updates' or major changes**
MAP with news update: https://www.test.bbc.com/pidgin/media-23256550

< 2 mins ago | 9 April 2018, 11:59 BST*Updated 1 minute ago
-- | --
2 mins ago - 1 hour ago | 9 April 2018, 11:59 BST - Updated M minutes ago
1 hour ago - 2 hours ago | 9 April 2018, 11:59 BST - Updated 1 hour ago
2 hours ago - 10 hours ago | 9 April 2018, 11:59 BST - Updated H hours ago
More than 10 hours ago | 9 April 2018, 11:59 BST - Updated HH:MM XXT

**Scenario 4: MAP published yesterday or earlier and has had news updates**
MAP with news update: https://www.test.bbc.com/pidgin/media-23256550

How long ago was the most recent ‘News Update’ | Example of what we display
-- | --
< 2 mins ago | 9 April 2018Updated 1 minute ago
2 mins ago - 1 hour ago | 9 April 2018 - Updated M minutes ago
1 hour ago - 2 hours ago | 9 April 2018 - Updated 1 hour ago
2 hours ago - 10 hours ago | 9 April 2018 - Updated H hours ago
2 hours ago - 24 hours ago | N/A
More than 10 hours ago | 9 April 2018 - Updated D Mmm YYYY

### PR DESCRIPTION
**Pull request by rebeccamcginn**
Resolves #5065 

**Overall change:** 
Stopped two timestamps being displayed on Maps when time last updated time is very close to first uploaded time.

**Code changes:**
- Added delta prop to article timestamp to stop last updated time being shown when delta < 1 minute

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

### CODE REVIEW

File: src/app/containers/ArticleTimestamp/index.jsx [hunk 1]
```diff
@@ -51,10 +51,12 @@ const ArticleTimestamp = ({ firstPublished, lastPublished, popOut }) => {
 
   const Wrapper = popOut ? PopOutGridItemMedium : GridItemConstrainedMedium;
 
+  const timestampDifference = (lastPublished - firstPublished) / 1000 / 60;
```
Comment (karinathomasbbc) [inline src/app/containers/ArticleTimestamp/index.jsx]: Can we rename the variable such that it is clear that the difference is in minutes?

File: src/app/containers/ArticleTimestamp/index.jsx [hunk 2]
```diff
@@ -65,10 +67,12 @@ ArticleTimestamp.propTypes = {
   firstPublished: number.isRequired,
   lastPublished: number.isRequired,
   popOut: bool,
+  delta: number,
 };
 
 ArticleTimestamp.defaultProps = {
   popOut: true,
+  delta: 0,
```
Comment (karinathomasbbc) [inline src/app/containers/ArticleTimestamp/index.jsx]: Might need a second opinion on this, but again, can we rename this prop to be something like `deltaMinutes`?

**Review by karinathomasbbc — CHANGES_REQUESTED** [review]

File: src/app/containers/ArticleTimestamp/index.jsx (hunk 1 above)
Comment (karinathomasbbc) [reply src/app/containers/ArticleTimestamp/index.jsx]: Alternatively, you could use Moment.js e.g https://momentjs.com/docs/#/durations/diffing/

File: src/app/containers/ArticleTimestamp/index.jsx (hunk 2 above)
Comment (jroebu14) [reply src/app/containers/ArticleTimestamp/index.jsx]: what about `minutesTolerance` or `timeDifferenceLimit`?

**Review by ryanmccombe — APPROVED** [review]
yay 🚀 

Agree with Karina - `deltaMinutes` is a better name

May also be worth adding a specific assertion to the `CpsAssetPageMain` tests that sets up the scenario described in the bug, and ensures only one timestamp is rendered

Looks great though 👍

File: src/app/containers/ArticleTimestamp/index.test.jsx [hunk 3]
```diff
@@ -145,6 +145,30 @@ describe('ArticleTimestamp', () => {
     expect(firstChild(renderedWrapper)).toMatch(regexDate);
   });
 
+  it('should render one timestamp with date when firstPublished before today and lastPublished was published less than 1 minute after firstPublished', () => {
+    const renderedWrapper = renderedTimestamps(
+      <WrappedArticleTimestamp
+        firstPublished={1530947280000}
+        lastPublished={1530947286000}
+        delta={1}
```
Comment (jroebu14) [inline src/app/containers/ArticleTimestamp/index.test.jsx]: is it a requirement for this to be configurable through a prop? If not then I think it should be a constant in the component.

Comment (rebeccamcginn) [reply src/app/containers/ArticleTimestamp/index.test.jsx]: It is to ensure that we don't alter the behaviour of the articles' timestamp.

Comment (jroebu14) [reply src/app/containers/ArticleTimestamp/index.test.jsx]: Not sure I understand

Comment (pharingee) [reply src/app/containers/ArticleTimestamp/index.test.jsx]: Because the articles pages also use this component, the delta prop has been added so it doesn't change for them too. Maybe we need to talk to the stories team to see if this behavior should be the same for them as well (which I think it should).

File: src/app/containers/ArticleTimestamp/index.jsx (hunk 2 above)
Comment (karinathomasbbc) [reply src/app/containers/ArticleTimestamp/index.jsx]: I prefer `minutesTolerance` over `deltaMinutes`

File: src/app/containers/ArticleTimestamp/index.test.jsx (hunk 3 above)
Comment (ryanmccombe) [reply src/app/containers/ArticleTimestamp/index.test.jsx]: This fix was for a bug where `firstPublished` and `lastPublished` were slightly different values for CPS assets, even when the asset was only published once.  This caused a second "Updated on..." timestamp to appear, even when the MAP was never updated.

Optimo doesn't have this bug, and to roll the change out to articles would mean that if an Article was updated shortly after being published, we'd hide the "Updated on" notification

That would seem to be a defect - it's admittedly minor, but given it's pretty easy to avoid changing articles by adding this `deltaTime` prop, it does seem worth doing.

In general, we don't want to change the product behaviour of another team without consulting them

**Review by jroebu14 — APPROVED** [review]
Looks good. Conflicts though

File: src/app/containers/ArticleTimestamp/index.jsx (hunk 1 above)
Comment (rebeccamcginn) [reply src/app/containers/ArticleTimestamp/index.jsx]: Done :)

File: src/app/containers/ArticleTimestamp/index.jsx (hunk 2 above)
Comment (rebeccamcginn) [reply src/app/containers/ArticleTimestamp/index.jsx]: Changed to minutesTolerance :)

**Review by jroebu14 — APPROVED** [review]
Looks good!

**Review by ryanmccombe — APPROVED** [review]

**Review by karinathomasbbc — APPROVED** [review]
