### PR TITLE
Fix nested spans bug on TalkBack on RadioSchedule

### LINKED ISSUE #9561: TalkBack incorrectly reading links in nested spans
**Describe the bug**
When using TalkBack on Android, links with role text and nested spans aren't read as one item as intended to be. Content is also repeated in additional blocks/gestures.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.bbc.com/portuguese/podcasts/p07r3r3t
2. Navigate to the 'O podcast está disponível em' header on TalkBack
3. Swipe to the list on TalkBack
4. TalkBack should read 'Spotify, Que Historia, externo, link'
5. Swipe through the links and TalkBack should read an additional 'Spotify', and the text highlighted
6. Swipe again and TalkBack will read out 'Que Historia' as well as highlight a separate 'block' on the screen.

**Expected behaviour**
TakBack should only read out 'Spotify, Que Historia, externo, link' before moving on to the next link.

**Screenshots**
image

**Smartphone (please complete the following information):**

- Device: Samsung S10
- OS: Android 11
- Browser: Chrome
- Version: 94.0.4606.85

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Checklist**
- [x] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

### PR DESCRIPTION
**Pull request by nicola-d-bbc**
Resolves #9561

**Overall change:**
Uses ID from radio schedule data as ID on span to be used by link with aria-labelledby. 

**Code changes:**

- Reuses ID to use as id in span with role="text" and also in aria-labelled by on styled link.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project
- [x] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [x] This PR requires manual testing

### CODE REVIEW

File: src/app/components/RadioSchedule/ProgramCard/index.jsx [hunk 1]
```diff
@@ -128,6 +129,11 @@ ProgramCard.propTypes = {
     link: string.isRequired,
     brandTitle: string.isRequired,
   }).isRequired,
+  id: string,
+};
+
+ProgramCard.defaultProps = {
+  id: '1',
```
Comment (ryanmccombe) [inline src/app/components/RadioSchedule/ProgramCard/index.jsx]: Is there ever a scenario where `id` is not passed to this component?

If there is, I think there will be issues in the ScheduleItemHeader component, because it will then emit multiple elements with the same ID (`scheduleItem-1`)

If ID is always passed, I think this prop can just be marked as `.isRequired` above and the default deleted :)

**Review by ryanmccombe — APPROVED** [review]
👍

**Comment by greenc05** [comment]
Is there somewhere we can make a note/comment in the code saying why we have added the aria-labelledby attribute?

File: src/app/components/RadioSchedule/ProgramCard/__snapshots__/index.test.jsx.snap [hunk 2]
```diff
@@ -507,6 +509,7 @@ exports[`ProgramCard should render correctly for next 1`] = `
         class="emotion-4 emotion-5"
       >
         <span
+          id="scheduleItem-1"
```
Comment (greenc05) [inline src/app/components/RadioSchedule/ProgramCard/__snapshots__/index.test.jsx.snap:512]: Is this needed in this example if there is no link? Think I can see a few others like this in the other snapshots aswell.

**Review by pvaliani — APPROVED** [review]
Nice!

File: src/app/components/RadioSchedule/ProgramCard/index.jsx (hunk 1 above)
Comment (nicola-d-bbc) [reply src/app/components/RadioSchedule/ProgramCard/index.jsx]: I set it with a default as there is a snapshot test that uses an undefined ID. Might be better to pass in a test ID for it and change to isRequired :)

**Review by amoore108 — APPROVED** [review]
