### PR TITLE
Fix event tracking on client side navigation

### LINKED ISSUE #9341: No event tracking following clientside navigation
**Describe the bug**
When a user navigates using an inline link to another Optimo article, the feature toggles fetch fails with the following error:
image

The impact of this is we will not honour the current toggle state and just use the source controlled defaults here: https://github.com/bbc/simorgh/blob/latest/src/app/lib/config/toggles/liveConfig.js

So current live impact would be that event tracking would be disabled for Optimo pages reached via an inline link from another Optimo page. All other toggles set to false don't apply:
- ads, no ads support for optimo
- cpsRecommendations, only for CPS assets

There is no impact on Amp pages

**To Reproduce**
Steps to reproduce the behaviour:

1. Visit http://localhost:7080/news/articles/c0g992jmmkko
2. Open dev tools
3. Click the 'placed on the tomb of the unknown warrior' inline link
4. Witness error above in console

**Expected behaviour**
As above with no error, a fetch should be made to the toggles service in the network tab:
image

Event tracking should function on the page visited via clientside navigation.

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

### PR DESCRIPTION
**Pull request by MuhammadAHussain**
Resolves https://github.com/bbc/simorgh/issues/9341

**Overall change:**
Event tracking was broken due to `process` running client side. Introduce a check to only run the `hrtime` on the server.

**Code changes:**

- Add logic to only run `hrtime` and logger on server.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project
- [ ] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by DarioR01 — APPROVED** [review]

**Comment by DarioR01** [comment]
LGTM. Something I thought is that the cache might "break" something by caching the check. But I am not sure if that is how our cache works :D

File: src/app/lib/utilities/getToggles/index.js [hunk 1]
```diff
@@ -12,6 +12,27 @@ import getOriginContext from '#contexts/RequestContext/getOriginContext';
 const logger = nodeLogger(__filename);
 const NS_PER_SEC = 1e9;
 
+const logResponseTime = async (url, origin, service, timeout) => {
+  const isBrowser =
+    typeof window !== 'undefined' && typeof window.document !== 'undefined';
```
Comment (pvaliani) [inline src/app/lib/utilities/getToggles/index.js:17]: Is there another way to implement `isBrowser` without passing in 'undefined' as a value? I can see we are using `undefined` as a value elsewhere in Simorgh to get contexts, it just feels strange.

**Review by pvaliani — APPROVED** [review]
Looks good just wondered if we can set the condition without explicitly referencing undefined 👍

**Comment by MuhammadAHussain** [comment]
> LGTM. Something I thought is that the cache might "break" something by caching the check. But I am not sure if that is how our cache works :D

Not sure what you mean. What would break by setting the cache?

**Comment by DarioR01** [comment]
> > LGTM. Something I thought is that the cache might "break" something by caching the check. But I am not sure if that is how our cache works :D
> 
> Not sure what you mean. What would break by setting the cache?

Is there a possibility that we cache this check for client-side (false): 
```
const isBrowser =
    typeof window !== 'undefined' && typeof window.document !== 'undefined'; 
```
and this could lead to us never running hrtime on the server due to the cache storing the false value?

**Comment by MuhammadAHussain** [comment]
> > > LGTM. Something I thought is that the cache might "break" something by caching the check. But I am not sure if that is how our cache works :D
> > 
> > 
> > Not sure what you mean. What would break by setting the cache?
> 
> Is there a possibility that we cache this check for client-side (false):
> 
> ```
> const isBrowser =
>     typeof window !== 'undefined' && typeof window.document !== 'undefined'; 
> ```
> 
> and this could lead to us never running hrtime on the server due to the cache storing the false value?

The client/browser cache is separate from the server one.

File: src/app/lib/utilities/getToggles/index.js (hunk 1 above)
Comment (MuhammadAHussain) [reply src/app/lib/utilities/getToggles/index.js:17]: Tried different approaches but doesn't look like there is as `window` isn't defined.

**Review by Louis-Matsika — APPROVED** [review]

**Comment by LilyL0u** [comment]
Followed the reproduction steps by @andrewscfc on https://github.com/bbc/simorgh/issues/9341 and when on this branch I do not see the mentioned console error. Pass.

File: src/app/lib/utilities/getToggles/index.js [hunk 2]
```diff
@@ -12,6 +12,27 @@ import getOriginContext from '#contexts/RequestContext/getOriginContext';
 const logger = nodeLogger(__filename);
 const NS_PER_SEC = 1e9;
 
+const logResponseTime = async (url, origin, service, timeout) => {
+  const isBrowser =
```
Comment (amoore108) [inline src/app/lib/utilities/getToggles/index.js:16]: We have a utility class called `onClient` in `src/app/lib/utilities/onClient` which appears to do a similar check, just thinking it could be used here too?

Comment (MuhammadAHussain) [reply src/app/lib/utilities/getToggles/index.js:16]: Sweet, I'll update it to use that instead.

Comment (MuhammadAHussain) [reply src/app/lib/utilities/getToggles/index.js:16]: Sticking with the current implementation as I wasn't able to mock/spy on `onClient` properly.

**Review by amoore108 — APPROVED** [review]
