### PR TITLE
Fix error in live stream schema

### LINKED ISSUE #5708: Error in Video Object Schema on Persian Live Stream
**Describe the bug**
There are errors in the video object schema on the Live Stream Pages. 
This can affect google's ability to index these pages as video. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://search.google.com/structured-data/testing-tool/
2. Test this Persian Live TV URL: https://www.bbc.com/persian/media-49522521
3. Note the errors in the video object with the name, description thumbnail URL 

Screenshot 2020-02-28 at 12 01 26

This is where it's being rendered within the html:
Screenshot 2020-03-03 at 15 52 47

**Expected behaviour**
The video object should have no errors. 
See the PAL example of the live stream: http://pal.test.bbc.com/persian/media-49522521
See a clip example on Simorgh: https://www.bbc.com/pidgin/media-44221514

Live stream assets on Simorgh TEST:
https://www.test.bbc.com/pidgin/media-23256547
https://www.test.bbc.com/pidgin/media-23256548
https://www.test.bbc.com/pidgin/media-23256549
https://www.test.bbc.com/pidgin/media-23256550
https://www.test.bbc.com/pidgin/media-23256552
https://www.test.bbc.com/pidgin/media-23256553
https://www.test.bbc.com/pidgin/media-23256554

Live stream assets on LIVE: 
(PAL) https://www.bbc.com/arabic/media-49522519
(PAL) https://www.bbc.com/hindi/india-48336189 

**Additional context**
- `thumbnailUrl`, `description` & `name` are being handled within `/src/app/containers/MediaPlayer/helpers/metadata/index.js`

- The _transformer_ handling the video block metadata is `src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/version/index.js`

**Resources**
- Miro with example mapping https://miro.com/app/board/o9J_kvZ2wMk=/?moveToWidget=3074457347306292500
- A previous issue looking at SEO & distinguishing between videoObject & audioObject  https://github.com/bbc/simorgh/issues/4707
- SEO spec https://confluence.dev.bbc.co.uk/display/WSMEDIA/MAP+%7C+SEO

### PR DESCRIPTION
**Pull request by RichardPK**
Resolves #5708 

**Overall change:** 
In live video and live audio streams (distinguished by `type: version`):

* The `image.href` in ARES' response starts with 'http://'. When creating thumbnailUris, our current logic prefixes all uris with 'https://'. This meant 'http://' was repeated twice before all video and audio stream uris - invalidating them. New logic has been added to `getThumbnailUri` to look out for 'http' within the ARES response and remove it if found. 

* The page's videoBlock is now using its headline for `title` and `synopses` (short, medium and long). Previously this was using `caption`, which is option in CPS and not widely used by editorial. 

**Code changes:**
- Pass full ARES json into blockType converters within `.../convertToOptimoBlocks/index.js` to give these converters access to other blocks' properties if necessary.
- Within `.../convertToOptimoBlocks/blocks/version/index.js` get `promo.headlines.headline` and use that to set the VideoBlock's title & synopses, rather than `block.caption`.
- Added condition for when `imageUrl` includes "http" within `getThumbnailUri` function. If condition is true, then the function now removes the http:// section from the url. 
- Updated MediaPlayer fixture data within `.../containers/MediaPlayer/fixtureData.jsx` to capture both `validAresMediaVideoLiveStreamBlock` and `validAresMediaLiveAudioBlock`s
- Added tests for the `getThumbnailUri` function changes within `.../containers/MediaPlayer/helpers/metadata/index.test.js` for both video and audio fixture data.
- Changed references to `CpsAssetMediaPlayerContainer` within `CpsAssetMediaPlayer/index.jsx` to `CpsAssetMediaPlayer`.
- Inadvertent formatting changes to `.../uzbek/cpsAssets/sport-23248721.json` and `.../thai/cpsAssets/thailand-23248713.json` 🙄 

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

### CODE REVIEW

File: src/app/containers/MediaPlayer/helpers/metadata/index.js [hunk 1]
```diff
@@ -4,7 +4,15 @@ import pathOr from 'ramda/src/pathOr';
 const DEFAULT_IMAGE_RES = '1024x576';
 
 export const getThumbnailUri = aresMetadataBlock => {
-  const imageUrl = pathOr('', ['model', 'imageUrl'], aresMetadataBlock);
+  let imageUrl = pathOr('', ['model', 'imageUrl'], aresMetadataBlock);
+
+  if (imageUrl.includes('http')) {
```
Comment (karinathomasbbc) [inline src/app/containers/MediaPlayer/helpers/metadata/index.js]: What if the imageUrl includes `https` - will this still work?

File: src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/version/index.js [hunk 2]
```diff
@@ -1,8 +1,15 @@
 import pick from 'ramda/src/pick';
 import path from 'ramda/src/path';
+import pathOr from 'ramda/src/pathOr';
 import isNil from 'ramda/src/isNil';
 
-const generateVideoBlock = block => {
+const generateVideoBlock = (block, json) => {
+  const headline = pathOr(
```
Comment (karinathomasbbc) [inline src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/version/index.js:7]: Nice, I like this solution 👍

File: src/app/containers/MediaPlayer/helpers/metadata/index.js (hunk 1 above)
Comment (RichardPK) [reply src/app/containers/MediaPlayer/helpers/metadata/index.js]: It will - but this is a good test scenario

File: src/app/containers/MediaPlayer/helpers/metadata/index.js [hunk 3]
```diff
@@ -4,7 +4,15 @@ import pathOr from 'ramda/src/pathOr';
 const DEFAULT_IMAGE_RES = '1024x576';
 
 export const getThumbnailUri = aresMetadataBlock => {
-  const imageUrl = pathOr('', ['model', 'imageUrl'], aresMetadataBlock);
+  let imageUrl = pathOr('', ['model', 'imageUrl'], aresMetadataBlock);
```
Comment (karinathomasbbc) [inline src/app/containers/MediaPlayer/helpers/metadata/index.js:7]: Is it worth trying out the the 'url-parse' library to make this a little bit simpler? See https://github.com/bbc/simorgh/blob/76b89386a36e51298d889be6f208d37fa4544469/src/app/lib/utilities/urlParser/index.js#L5

```
const thumbnailUrl = pathOr('', ['model', 'imageUrl'], aresMetadataBlock).replace('$recipe', DEFAULT_IMAGE_RES);

if (thumbnailUrl) {
  let url = new Url(thumbnailUrl);
  url.protocol = 'https';
  return url.toString();
}
```

(Although I have technically broken rules of immutability with the `let url =`.. statement - maybe get a second opinion on this)

File: src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/version/index.js (hunk 2 above)
Comment (ryanmccombe) [reply src/app/routes/cpsAsset/getInitialData/convertToOptimoBlocks/blocks/version/index.js:7]: ⬆️ this guy with the ramda

**Review by ryanmccombe — APPROVED** [review]

File: src/app/containers/MediaPlayer/helpers/metadata/index.js (hunk 3 above)
Comment (RichardPK) [reply src/app/containers/MediaPlayer/helpers/metadata/index.js:7]: So this approach conflicts with a few (13) snapshots for local fixtures: the url-parse library seems to prefix the url with the host/host name, so when using it you start to see urls prefixed with 'localhost'. i.e. 

expected : `https://ichef.test.bbci.co.uk/images/ic/1024x576/p01k6mtv.jpg`
received : `https://localhost/ichef.test.bbci.co.uk/images/ic/1024x576/p01k6mtv.jpg`

Looking at methods of eliminating this you either end up with no '//' after https. i.e.
```
const url = new Url(imageUrl, {});
// https:ichef.test.bbci.co.uk/images/ic/1024x576/p01k6mtv.jpg
```

or an extra '/' i.e.
```
const url = new Url(imageUrl);
url.host = '';
// https:///ichef.test.bbci.co.uk/images/ic/1024x576/p01mr7dp.jpg;
```

Not sure if you know a way around this? If not I'll just stick with the PR's implementation.

File: src/app/containers/MediaPlayer/helpers/metadata/index.js (hunk 1 above)
Comment (RichardPK) [reply src/app/containers/MediaPlayer/helpers/metadata/index.js]: I've added a test for this - 'should return a valid thumbnail Uri for https assets'. See if you think it's robust enough?

Comment (ryanmccombe) [inline src/app/containers/MediaPlayer/helpers/metadata/index.js]: Chance this could break based on `http` appearing later in the path
```suggestion
  if (imageUrl.startsWith('http')) {
```

File: .env [hunk 4]
```diff
@@ -1,4 +1,9 @@
...
\ No newline at end of file
+## NB only variables prefixed with SIMORGH_ are available on both the server and client
+SIMORGH_BASE_URL=http://localhost:7080
+SIMORGH_PUBLIC_STATIC_ASSETS_ORIGIN=http://localhost:7080
+SIMORGH_PUBLIC_STATIC_ASSETS_PATH=/
+SIMORGH_ATI_BASE_URL=https://logws1363.ati-host.net?
+SIMORGH_MPULSE_API_KEY=JLSEX-R76DK-JXL3A-UB7YH-NPSEW
+LOG_DIR='log'
+LOG_LEVEL='debug'
+SIMORGH_APP_ENV=local
```
Comment (karinathomasbbc) [inline .env]: Oops

File: data/thai/cpsAssets/thailand-23248713.json [hunk 5]
```diff
@@ -253,4 +253,4 @@
       },
       "groups": []
     }
-  }
\ No newline at end of file
+}
```
Comment (karinathomasbbc) [inline data/thai/cpsAssets/thailand-23248713.json]: Did you mean to commit this?

File: data/uzbek/cpsAssets/sport-23248721.json [hunk 6]
```diff
@@ -35,12 +35,7 @@
       },
       "tags": {},
       "version": "v1.1.2",
-      "blockTypes": [
-        "version",
-        "paragraph",
-        "list",
-        "image"
-      ],
+      "blockTypes": ["version", "paragraph", "list", "image"],
```
Comment (karinathomasbbc) [inline data/uzbek/cpsAssets/sport-23248721.json]: Did you mean to commit this?

File: src/app/containers/CpsAssetMediaPlayer/index.jsx [hunk 7]
```diff
@@ -37,7 +37,7 @@ const Wrapper = styled(GridItemConstrainedLarge)`
   }
 `;
 
-const CpsAssetMediaPlayerContainer = ({ blocks, assetUri, isLegacyMedia }) => {
+const CpsAssetMediaPlayer = ({ blocks, assetUri, isLegacyMedia }) => {
```
Comment (karinathomasbbc) [inline src/app/containers/CpsAssetMediaPlayer/index.jsx:40]: Is this part of these changes?

File: src/app/containers/MediaPlayer/helpers/metadata/index.js (hunk 3 above)
Comment (karinathomasbbc) [reply src/app/containers/MediaPlayer/helpers/metadata/index.js:7]: Na, leave it. It's fine as is.

File: src/app/containers/MediaPlayer/helpers/metadata/index.js (hunk 1 above)
Comment (RichardPK) [reply src/app/containers/MediaPlayer/helpers/metadata/index.js]: Considered that - didn't know about `startsWith`, nice! 👍

**Review by ryanmccombe — APPROVED** [review]

File: .env (hunk 4 above)
Comment (RichardPK) [reply .env]: omg

File: src/app/containers/CpsAssetMediaPlayer/index.jsx (hunk 7 above)
Comment (RichardPK) [reply src/app/containers/CpsAssetMediaPlayer/index.jsx:40]: Yep - it was bothering me...

> Changed references to `CpsAssetMediaPlayerContainer` within CpsAssetMediaPlayer/index.jsx to `CpsAssetMediaPlayer`.

File: .env (hunk 4 above)
Comment (RichardPK) [reply .env]: Fixed. Looking forward to .env's reappearance in my next PR... 🤦‍♂

File: data/uzbek/cpsAssets/sport-23248721.json (hunk 6 above)
Comment (RichardPK) [reply data/uzbek/cpsAssets/sport-23248721.json]: Negative. Rolled back to latest

File: data/thai/cpsAssets/thailand-23248713.json (hunk 5 above)
Comment (RichardPK) [reply data/thai/cpsAssets/thailand-23248713.json]: Negative. Rolled back to latest

**Review by karinathomasbbc — APPROVED** [review]
