### PR TITLE
Spacing of map timestamp

### LINKED ISSUE #5053: Spacing Incorrect on Timestamps on MAPs
**Describe the bug**
On a MAP page the spacing below the timestamp is incorrect. 

**To Reproduce**

1. Go to https://www.test.bbc.com/pidgin/media-23259752
2. Note the timestamp - and see that the updated time does not respect the spacing.
Spacing appears to fine on assets that have just the firstPublished date only (single timestamp) 

**Expected behavior**
The spacing of the timestamp should sit centrally between the headline and story body. 
See the design for reference: https://app.zeplin.io/project/5d4d77b1fcbfc79bf47e0294/dashboard?seid=5e14855290299456375c16ac

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by RichardPK**
Resolves [#5053](https://github.com/bbc/simorgh/issues/5053)

**Overall change:** 
Added 1rem padding-botton to the ArticleTimestamp Wrapper within CpsAssetPageMain

**Code changes:**
- Added className props to ArticleTimestamp, passing this down to the styled component 'Wrapper' within this component.
- Within CpsAssetPageMain, pass the Timestamp component into a StyledTimestamp component, giving it the padding-bottom: property GEL_SPACING_DBL} (adding an extra rem)

---

- [ √] I have assigned myself to this PR and the corresponding issues
- [ √] I have added labels to this PR for the relevant pod(s) affected by these changes
- [√ ] I have assigned this PR to the Simorgh project

**Testing:**
- [ √] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [√] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [√] This PR requires manual testing

### CODE REVIEW

**Review by ryanmccombe — APPROVED** [review]
tenor

File: src/app/containers/ArticleTimestamp/index.jsx [hunk 1]
```diff
@@ -52,7 +57,7 @@ const ArticleTimestamp = ({ firstPublished, lastPublished, popOut }) => {
   const Wrapper = popOut ? PopOutGridItemMedium : GridItemConstrainedMedium;
 
   return (
-    <Wrapper>
+    <Wrapper className={className}>
```
Comment (karinathomasbbc) [inline src/app/containers/ArticleTimestamp/index.jsx:60]: Would it be possible to add a snapshot test for the article timestamp - I checked the code quickly, and there doesn't appear to be one.  It would be nice to have one as a fallback.

**Review by karinathomasbbc — CHANGES_REQUESTED** [review]

File: src/app/containers/ArticleTimestamp/index.jsx (hunk 1 above)
Comment (RichardPK) [reply src/app/containers/ArticleTimestamp/index.jsx:60]: Added two snapshot tests - one for when there's only a 'created' timestamp, another for when there's both a 'created' and 'updated' timestamps.

File: src/app/containers/ArticleTimestamp/index.test.jsx [hunk 2]
```diff
@@ -42,6 +46,24 @@ describe('ArticleTimestamp', () => {
     Date.now = originalDate;
   });
 
+  describe('snapshot tests', () => {
```
Comment (karinathomasbbc) [inline src/app/containers/ArticleTimestamp/index.test.jsx]: I think you can omit this line - we don't really need to know that we're running snapshot tests

**Review by karinathomasbbc — CHANGES_REQUESTED** [review]

**Review by karinathomasbbc — APPROVED** [review]

File: src/app/containers/ArticleTimestamp/index.test.jsx (hunk 2 above)
Comment (RichardPK) [reply src/app/containers/ArticleTimestamp/index.test.jsx]: Good shout. I've removed in [#89874f0](https://github.com/bbc/simorgh/pull/5072/commits/89874f0500e827854056638c0d529517429dcdcc)
