### PR TITLE
Remove list wrapper from CPSRelatedContent when it has a single item

### LINKED ISSUE #6047: CPSRelatedContent promos should only output as a list if more than one promo
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

1. Create a story where only one item is passed to the CPSRelatedContent container component
2. Note that the produced DOM structure contains a `<ul>` tag. 

**Expected behaviour**
If the component only contains one item, the StoryPromo component should be rendered directly without a wrapping `<ul>` element.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by mykeels**
Resolves #6047

**Overall change:** 
Remove `<ul><li>` in related content when it has only one item.

**Code changes:**
- _Remove `<ul><li>` in related content when it has only one item._
- _Add tests_

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

### CODE REVIEW

**Comment by mykeels** [comment]
Here is a screenshot, showing the DOM structure when the CPSRelatedContent component has only one item in its `content` prop.

image

File: src/app/containers/CpsRelatedContent/index.jsx [hunk 1]
```diff
@@ -63,6 +77,8 @@ const CpsRelatedContent = ({ content, enableGridWrapper }) => {
     children: node.isRequired,
   };
   if (!content.length) return null;
+  const hasSingleRelatedContent = content.filter(Boolean).length === 1;
```
Comment (chris-hinds) [inline src/app/containers/CpsRelatedContent/index.jsx]: What is the use-case for using `content.filter(Boolean).length === 1` could we just have a conditional in the render with something like `if(content.length > 1)`

Comment (mykeels) [reply src/app/containers/CpsRelatedContent/index.jsx]: The use-case was in case the data somehow, is `[null, null]`, but I guess the propTypes takes care of that.

File: src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap [hunk 2]
```diff
@@ -453,3 +453,112 @@ exports[`CpsRelatedContent should render Story Promo components when given appro
...
+                  class="Link-sc-1dvfmi3-5 yQgSu"
+                  href="/pidgin/44508901"
+                >
+                  <span
+                    role="text"
+                  >
+                    <span
+                      class="VisuallyHiddenText-sc-1yjwwa5-0 jFfEvX"
+                    >
+                      ,
```
Comment (greenc05) [inline src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap:538]: Is this just an example?

File: src/app/containers/CpsRelatedContent/index.jsx [hunk 3]
```diff
@@ -75,40 +91,47 @@ const CpsRelatedContent = ({ content, enableGridWrapper }) => {
...
-                dir={dir}
-              >
-                <StoryPromo item={item} dir={dir} />
-              </Grid>
-            ))}
-        </Grid>
+
+        {hasSingleRelatedContent ? (
+          <SpacingDiv>
+            <StoryPromo item={singleRelatedContent} dir={dir} />
```
Comment (ryanmccombe) [inline src/app/containers/CpsRelatedContent/index.jsx]: We have  ticket to remove `formatItem`, but may as well keep the behavior the same for now, regardless of how many items there are
```suggestion
            <StoryPromo item={formatItem(singleRelatedContent, env)} dir={dir} />
```

File: src/app/containers/CpsRelatedContent/index.test.jsx [hunk 4]
```diff
@@ -51,6 +51,24 @@ describe('CpsRelatedContent', () => {
...
+  it('should render Story Promo components without <ul> when given single item in collection', () => {
+    const topRelatedContentsOneItem = [promos[0]];
+
+    expect(topRelatedContentsOneItem.filter(Boolean).length).toBe(1);
+
+    const { asFragment } = renderRelatedContent({
+      content: [promos[0]],
+    });
+
+    expect(document.querySelectorAll(`li[class^='StoryPromoLi']`).length).toBe(
```
Comment (ryanmccombe) [inline src/app/containers/CpsRelatedContent/index.test.jsx]:
```suggestion
    expect(document.querySelector('li[class^='StoryPromoLi')).toBeNull();
```
or `.not.toBeInTheDocument()`

File: src/app/containers/CpsRelatedContent/index.test.jsx [hunk 5]
```diff
@@ -51,6 +51,24 @@ describe('CpsRelatedContent', () => {
...
+      0,
+    );
+
+    expect(document.querySelectorAll(`ul`).length).toBe(0);
```
Comment (ryanmccombe) [inline src/app/containers/CpsRelatedContent/index.test.jsx]:
```suggestion
    expect(document.querySelector('ul')).toBeNull();
```
or `.not.toBeInTheDocument()`

**Review by ryanmccombe — APPROVED** [review]
👍 LGTM - some minor optional suggestions

File: src/app/containers/CpsRelatedContent/index.test.jsx [hunk 6]
```diff
@@ -51,6 +51,24 @@ describe('CpsRelatedContent', () => {
     expect(asFragment()).toMatchSnapshot();
   });
 
+  it('should render Story Promo components without <ul> when given single item in collection', () => {
+    const topRelatedContentsOneItem = [promos[0]];
+
+    expect(topRelatedContentsOneItem.filter(Boolean).length).toBe(1);
```
Comment (ryanmccombe) [inline src/app/containers/CpsRelatedContent/index.test.jsx]: If this is just null checking `promos[0]`,  it's probably clearer to do it directly
```suggestion
    expect(promos[0]).toBeTruthy();
```

File: src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap (hunk 2 above)
Comment (mykeels) [reply src/app/containers/CpsRelatedContent/__snapshots__/index.test.jsx.snap:538]: Following our conversations on slack, I've created [this issue](https://github.com/bbc/simorgh/issues/6064) to track this.

File: src/app/containers/CpsRelatedContent/index.jsx [hunk 7]
```diff
@@ -32,6 +36,16 @@ const StyledSectionLabel = styled(SectionLabel)`
   margin-top: 0;
 `;
 
+// Apply the right margin-top between the section label and the promos
+const SpacingDiv = styled.div`
```
Comment (rhenshaw56) [inline src/app/containers/CpsRelatedContent/index.jsx]: would it be worth renaming this to `SingleContentWrapper` or something else with less ambiguity ?

File: src/app/containers/CpsRelatedContent/index.jsx [hunk 8]
```diff
@@ -63,6 +77,8 @@ const CpsRelatedContent = ({ content, enableGridWrapper }) => {
     children: node.isRequired,
   };
   if (!content.length) return null;
+  const hasSingleRelatedContent = content.length === 1;
+  const [singleRelatedContent] = content;
```
Comment (rhenshaw56) [inline src/app/containers/CpsRelatedContent/index.jsx:81]: is there another need for `singleRelatedContent` if we can just do `content[0]` on line 98 ?

Comment (mykeels) [reply src/app/containers/CpsRelatedContent/index.jsx:81]: If we're going for readability, `singleRelatedContent` is more readable than `content[0]`.

**Review by rhenshaw56 — APPROVED** [review]

**Review by chris-hinds — APPROVED** [review]
