### PR TITLE
fix timezone issues in ArticleTimestamp tests

### LINKED ISSUE #1855: Timezone dependant tests
**Describe the bug**
The unit tests on latest for `src/app/containers/ArticleTimestamp/index.test.jsx` fail based on the current timezone/time near to midnight (haven't been able to pinpoint the exact problem yet).

**To Reproduce**

1. Go to `Date & Time` on you local device
2. Set your timezone ahead 3+ hours (might need to try different locations to get this right)
3. `npm run test` or specifically `npm run test:unit src/app/containers/ArticleTimestamp/index.test.jsx`

**Expected behavior**
Our tests shouldn't fail based on timezone. 

**Screenshots**
Failure with timezone non-english
image

Pass with timezone english
image

**Additional context**
Some initial debugging showed that `console.log(firstChild(renderedWrapper));` in `src/app/containers/ArticleTimestamp/index.test.jsx` the passing tests return with `31 May 2017, 03:00 BST` whereas the failing tests return with `31 May 2017`. This makes me believe it's to do with the BST logic in the code or tests. 

It also could be due to the test using regex (EG `regexDatetime` and `regexUpdatedDatetime`) which are expecting a `,` and `BST`

### PR DESCRIPTION
**Pull request by billy-reilly**
Resolves #1855

**Overall change:** This is a change to the `ArticleTimestamp` component's unit tests, so that they can run on any machine regardless of its timezone settings. Does not touch application code.

**Reproduction steps: (on mac)**
- check out onto `latest`
- change your timezone in system preferences to roughly +12 (the furthest zone east)
- run the tests for `ArticleTimestamp` (in `src/app/containers/ArticleTimestamp/index.test.jsx`)
- you should see 4 test failures where the test is expecting date and time format but is instead receiving date format

**Code changes:**
- refactored the tests for same day timestamps - to ensure that the timestamps are on the same day according to local time
- extracted the logic into a helper which reuses logic from `timestampGenerator`

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Comment by dr3** [comment]
Hey @billy-reilly, thanks for doing this PR. I can see you're trying to kick off travis, apologies for the weird process, it appears our travis pipeline for forks has issues from code climate which we will take a look at fixing.

**Comment by billy-reilly** [comment]
@dr3 cheers! Sorry thought I'd made a mistake somewhere along the line - will stop pushing notifications now aha

Just for reference, Travis has run green on my forked version https://travis-ci.org/billy-reilly/simorgh/jobs/544463727

**Comment by dr3** [comment]
Ah brilliant @billy-reilly, we should be able to review/merge your PR around the broken pipeline, I'll highlight it needs reviewing in the morning and hopefully we can get it moving :D

**Comment by dr3** [comment]
@billy-reilly One thing I forgot, we actually moved `src/app/containers/Timestamp` to `https://github.com/bbc/psammead/tree/latest/packages/containers/psammead-timestamp-container`. ArticleTimestamp does still live here though, you may be able to move the changes in `src/app/containers/Timestamp/helpers/testHelpers.js` to `src/app/containers/ArticleTimestamp/testHelpers.js`

**Comment by billy-reilly** [comment]
@dr3 okay sweet! I’m on holiday without my laptop for a few days but can make that change on Monday :)

**Comment by jamesdonoh** [comment]
Regarding the CC error on forks we have an open issue to resolve this but it's blocked on some changes that are needed to Jenkins. Will discuss other workarounds.

**Comment by billy-reilly** [comment]
thanks @jamesdonoh 

@dr3 this is now updated

I've created a PR on my fork where the CI tests run green https://github.com/billy-reilly/simorgh/pull/1

File: src/app/containers/ArticleTimestamp/testHelpers.js [hunk 1]
```diff
@@ -1,21 +1,69 @@
...
+   * not provided it will use the current date.
+   */
+
+  if (!intervals || !Array.isArray(intervals)) {
+    throw new Error(
+      'Invalid intervals argument passed to sameDayTimestampsGenerator',
+    );
+  }
+
+  const firstTimestamp = moment(date)
```
Comment (sareh) [inline src/app/containers/ArticleTimestamp/testHelpers.js]: I suggest renaming `firstTimestamp` here to `startOfDayTimestamp` since if `date` is undefined, this value is not related to an input timestamp, but to the start of today.

File: src/app/containers/ArticleTimestamp/testHelpers.js [hunk 2]
```diff
@@ -1,21 +1,69 @@
...
+    .startOf('day')
+    .valueOf();
+  const lastTimestamp = addTimeDifference(firstTimestamp, intervals[0]);
```
Comment (sareh) [inline src/app/containers/ArticleTimestamp/testHelpers.js]: This `lastTimestamp` could be `mockCurrentTimestamp` since it's starting from midnight on the day and adding the first interval value to it. Assuming that the first interval is the largest, to ensure all of the timestamps will be during the same day.

File: src/app/containers/ArticleTimestamp/index.test.jsx [hunk 3]
```diff
@@ -34,13 +38,16 @@ describe('ArticleTimestamp', () => {
...
-    const daylightSavingsBehaviour = ({ descriptor, dateTime, longName }) => {
+    const daylightSavingsBehaviour = ({ descriptor, date, longName }) => {
       it(`should produce ${descriptor} as a descriptor when in ${longName}`, () => {
-        Date.now = jest.fn(() => dateTime);
-        const moreThanTenHoursAgo = timestampGenerator({
-          hours: 10,
-          seconds: 25,
+        const [
+          moreThanTenHoursAgo,
+          currentTimestamp,
```
Comment (sareh) [inline src/app/containers/ArticleTimestamp/index.test.jsx]: Instead of referring to this final return value as being `currentTimestamp` throughout this file, it would be more accurate to call this `mockCurrentTimestamp`, so it's clear that it isn't based on the actual timestamp when the test is run.  This value is the start of current day plus the first interval provided.

**Review by sareh — COMMENTED** [review]
Thank you for your PR! It's great to ensure these tests work regardless of the time of day.

There are just a couple of naming changes I'd suggest - to make understanding and using this test helper easier.

**Comment by billy-reilly** [comment]
thanks for the suggestions @sareh I've added them into the PR 😃

**Review by sareh — APPROVED** [review]
👍 Looks great. Thanks for making the changes, @billy-reilly! 
thumbs up

**Review by 12 — APPROVED** [review]
Looks good. Thanks for resolving this! 🙂

**Comment by staylos92** [comment]
this does not need formal testing by a tester

**Comment by dr3** [comment]
Thanks for doing this PR @billy-reilly, awesome work! You were actually our first contributor from outside the BBC 🎉

**Comment by billy-reilly** [comment]
Oh nice, cheers @dr3!
