### PR TITLE
Suppress rendering of secondary column

### LINKED ISSUE #6521: Suppress rendering for secondary column containers with missing data
**Describe the bug**
When containers in the secondary column are missing data we should not render them to prevent a less than ideal whitespace from appearing.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to [storybook](https://5d28eb3fe163f6002046d6fa-wbgadcibkm.chromatic.com/?path=/story/pages-story-page--mundo)
2. Inspect the page
3. See Feature & Analysis and Top Stories render, but with no content

**Expected behaviour**
When the secondary column data for Feature & Analysis and Top Stories is missing, the container should not render.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

Screenshot 2020-05-14 at 17 51 07

### PR DESCRIPTION
**Pull request by rhenshaw56**
Resolves #6521 

**Overall change:**
_Suppress rendering of secondary column when data is missing._

**Code changes:**

- _Suppress rendering of secondary column when data is missing._
- _Add storbook knob to show case the different secondary column options._

---

- [X] I have assigned myself to this PR and the corresponding issues
- [X] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

File: src/app/pages/StoryPage/index.jsx [hunk 1]
```diff
@@ -70,11 +70,22 @@ const StoryPage = ({ pageData, mostReadEndpointOverride }) => {
...
+  const featuresInitialData = pathOr(
+    [],
+    ['secondaryColumn', 'features'],
+    pageData,
+  );
+
+  const hasTopStoriesData = !!topStoriesInitialData.length;
+  const hasFeaturesData = !!featuresInitialData.length;
+  const removeMostReadLabelTopMargin = !(
+    hasTopStoriesData && hasTopStoriesData
```
Comment (HarveyPeachey) [inline src/app/pages/StoryPage/index.jsx]: Is one of these meant to be `hasFeaturesData`?

File: src/app/pages/StoryPage/index.jsx [hunk 2]
```diff
@@ -70,11 +70,22 @@ const StoryPage = ({ pageData, mostReadEndpointOverride }) => {
   const lastPublished = getLastPublished(pageData);
   const aboutTags = getAboutTags(pageData);
   const mostReadInitialData = path(['mostRead'], pageData);
-  const topStoriesInitialData = path(
+  const topStoriesInitialData = pathOr(
```
Comment (HarveyPeachey) [inline src/app/pages/StoryPage/index.jsx]: Do we need to use `pathOr()`? Doesn't `path()` return `undefined` if it can't retrieve a value at that path?

File: src/app/pages/StoryPage/index.jsx (hunk 1 above)
Comment (rhenshaw56) [reply src/app/pages/StoryPage/index.jsx]: Good spot @HarveyPeachey, Thanks

File: src/app/pages/StoryPage/index.jsx (hunk 2 above)
Comment (rhenshaw56) [reply src/app/pages/StoryPage/index.jsx]: we do not necessarily need `pathOr` I just assumed in the case that it's missing an empty array would be returned for `topStories` or `features`

Comment (rhenshaw56) [reply src/app/pages/StoryPage/index.jsx]: @HarveyPeachey I have removed the use of `pathOr`

**Review by oluoluoxenfree — APPROVED** [review]

File: src/app/pages/StoryPage/fixtureData/mundo.json [hunk 3]
```diff
@@ -2131,5 +2131,337 @@
     },
     "id": "urn:bbc:ares::asset:mundo/23263889",
     "type": "cps"
+  },
+  "secondaryColumn": {
```
Comment (andrewscfc) [inline src/app/pages/StoryPage/fixtureData/mundo.json]: Wasn't immediately obvious to me but this fixture data is added to facilitate the new storybook stories added to test the layout with various data missing.

File: src/app/pages/StoryPage/index.stories.jsx [hunk 4]
```diff
@@ -1,16 +1,44 @@
...
+import { withKnobs, select } from '@storybook/addon-knobs';
 import { BrowserRouter } from 'react-router-dom';
 import WithTimeMachine from '#testHelpers/withTimeMachine';
 
 import { StoryPage } from '..';
 import mundoPageData from './fixtureData/mundo';
 import persianPageData from './fixtureData/persian';
 
-const styStories = storiesOf('Pages|Story Page', module);
+const withSecondaryColumnsKnob = pageData => storyFn => {
```
Comment (andrewscfc) [inline src/app/pages/StoryPage/index.stories.jsx:11]: Great idea to add the stories, made it really easy to review this PR, running the stories from chromatic 👍

File: src/app/pages/StoryPage/index.jsx [hunk 5]
```diff
@@ -148,16 +152,25 @@ const StoryPage = ({ pageData, mostReadEndpointOverride }) => {
     'data-e2e': 'most-read',
   }))``;
 
+  const SectionLabelWrapper = styled(SectionLabel)`
+    ${({ removeTopMargin }) =>
+      removeTopMargin &&
+      css`
+        margin-top: 0;
+      `}
+  `;
```
Comment (andrewscfc) [inline src/app/pages/StoryPage/index.jsx]: I don't like the way we have to break encapsulation here to remove the top margin, I think it'd be cleaner if `SectionLabel` supported something like a `topItem` prop; `SectionLabel` taking responsibility for how it looks when it is the top item in the secondary column.

This means that if the css is changed for `SectionLabel` we don't also have update the logic here in the Story page.

**Review by andrewscfc — COMMENTED** [review]
One suggestion to decrease coupling between the Story page and `SectionLabel` component, otherwise looks great to me.

File: src/app/pages/StoryPage/fixtureData/mundo.json (hunk 3 above)
Comment (andrewscfc) [reply src/app/pages/StoryPage/fixtureData/mundo.json]: (just leaving this comment to help others, not suggesting any change)

File: src/app/pages/StoryPage/index.jsx [hunk 6]
```diff
@@ -256,18 +268,22 @@ const StoryPage = ({ pageData, mostReadEndpointOverride }) => {
...
-              parentColumns={gridColsSecondary}
-            />
-          </ResponsiveComponentWrapper>
-          <ResponsiveComponentWrapper>
-            <FeaturesAnalysis
-              content={featuresInitialData}
-              parentColumns={gridColsSecondary}
-            />
-          </ResponsiveComponentWrapper>
+          {topStoriesInitialData && (
```
Comment (HarveyPeachey) [inline src/app/pages/StoryPage/index.jsx:258]: Just an after-thought from the first review. Do we want to be doing the suppression on page level or would it be better to do the suppression at the container level? Not sure what the general practice is for this.

Comment (FK78) [reply src/app/pages/StoryPage/index.jsx:258]: I agree with @HarveyPeachey, we've got conditional statements in several containers where we `return null` if certain conditions are not met. Here is an [example](https://github.com/bbc/simorgh/blob/latest/src/app/containers/Image/index.jsx#L31).

Comment (rhenshaw56) [reply src/app/pages/StoryPage/index.jsx:258]: I think we're already suppressing [at the container level](https://github.com/bbc/simorgh/blob/latest/src/app/containers/CpsOnwardJourney/index.jsx#L122), but just doing that doesn't stop the the [padding/margin in the responsive wrapper](https://github.com/bbc/simorgh/blob/latest/src/app/pages/StoryPage/index.jsx#L138-L143) from being applied

File: src/app/pages/StoryPage/index.jsx (hunk 5 above)
Comment (rhenshaw56) [reply src/app/pages/StoryPage/index.jsx]: removed this change as it's already been identified and reported by UX in a standalone issue.

**Review by HarveyPeachey — APPROVED** [review]
LGTM

**Review by FK78 — APPROVED** [review]
Nice work :+1:

**Review by andrewscfc — APPROVED** [review]

**Comment by paruchurisilpa** [comment]
Testing steps:

1. Run the branch on storybook
2. Go to the story page
3. Within storybook, you would see a knob dropdown on the right that says default.
4. Switch through the different knob values

**Comment by paruchurisilpa** [comment]
Looks good to me..
