### PR TITLE
TV / Radio Episode Availability check

### LINKED ISSUE #7059: Available episodes showing as not available
**Describe the bug**
We are displaying an episode is no longer available error where episodes are available but do not have an expiry date. 
This is because we display the expiry where availableUntil is not present in the endpoint. 
However, some episodes do not have an expiry date. 
Every available episode will have an availableFrom date, only some episodes versions will have no availableUntil Date. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'https://www.test.bbc.com/korean/bbc_korean_radio/w3ct0kfm'
2. Note the error 
3. Look at the availability flag in ARES endpoint: https://ares-api.api.bbci.co.uk/api/ws-media/radio/korean/bbc_korean_radio/w3ct0kfm
4. Note that the episode is available from the 26th of June 

**Expected behaviour**
Given episode w3ct0kfm is available from the 26th of June 2020
When I visit https://www.test.bbc.com/korean/bbc_korean_radio/w3ct0kfm'
then the episode is available to play

Given I visit brand page: https://www.test.bbc.com/korean/bbc_korean_radio/programmes/w13xttlm
then the lastest available episode is available to play 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by karinathomasbbc**
Resolves #7059

**Overall change:**
Ensure that episode availability check is correct, based on the availableFrom and availableUntil metadata in page data.
See https://github.com/bbc/simorgh/issues/7059#issuecomment-651207713 for analysis on expected behaviour

**Code changes:**
- Updated tests to reflect desired behaviour
- Ensure episodeAvailability logic is correct

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] I have added labels to this PR for the relevant pod(s) affected by these changes
- [ ] I have assigned this PR to the Simorgh project

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by RichardPK — COMMENTED** [review]
Looks great! 👌 

Really like the structure, very semantic.

I guess the 'because availableFrom and availableUntil are in the past' tests are pending being written?

**Comment by karinathomasbbc** [comment]
> I guess the 'because availableFrom and availableUntil are in the past' tests are pending being written?

Oops forgot, have added it now.

File: src/app/lib/utilities/episodeAvailability/index.js [hunk 1]
```diff
@@ -39,7 +39,7 @@ const getEpisodeAvailability = pageData => {
   const availableFrom = getEpisodeAvailableFrom(pageData);
   const availableUntil = getEpisodeAvailableUntil(pageData);
 
-  if (!availableUntil) {
+  if (!availableFrom || availableUntil < timeNow) {
```
Comment (rebeccamcginn) [inline src/app/lib/utilities/episodeAvailability/index.js]: `availableUntil` will not be returned if the episode has expired

Comment (karinathomasbbc) [reply src/app/lib/utilities/episodeAvailability/index.js]: Not always - there are some examples where `availableUntil` is not returned, but episode is still available - seems to be mostly Korean, learning english radio brand. 

If an episode is genuinely expired, `versions` is returned as an empty array, therefore both `availableFrom` and `availableUntil` are undefined, which is why the `!availableFrom` check is better to use for the expired check.

See https://github.com/bbc/simorgh/issues/7059#issuecomment-651207713 for analysis.

File: src/app/lib/utilities/episodeAvailability/index.test.js [hunk 2]
```diff
@@ -8,98 +9,244 @@ import onDemandRadioBrandJson from '#data/indonesia/bbc_indonesian_radio/w13xtt0
...
-    jest.clearAllMocks();
-  });
+describe('Episode Availability', () => {
+  describe('getUrl', () => {
+    it('should return a valid url for radio episode page', () => {
+      const url = getUrl(onDemandRadioEpisodeJson);
+      const service = path(
+        ['relatedContent', 'site', 'name'],
+        onDemandRadioEpisodeJson,
+      ).toLowerCase();
```
Comment (ryanmccombe) [inline src/app/lib/utilities/episodeAvailability/index.test.js]: the `toLowerCase()` is negating the use of `path` here - `path` will safely return undefined, but calling a function on undefined will cause an exception anyway 🙂

File: src/app/lib/utilities/episodeAvailability/index.js (hunk 1 above)
Comment (rebeccamcginn) [reply src/app/lib/utilities/episodeAvailability/index.js]: No, I mean that `availableUntil < timeNow` will never apply as `availableUntil` will not be returned for expired episodes. It will be undefined.

Comment (karinathomasbbc) [reply src/app/lib/utilities/episodeAvailability/index.js]: Gotcha. I couldn't find any examples of where `availableUntil < timeNow` anyway, so should I just remove and leave the `!availableFrom` check?

File: src/app/lib/utilities/episodeAvailability/index.test.js (hunk 2 above)
Comment (karinathomasbbc) [reply src/app/lib/utilities/episodeAvailability/index.test.js]: Who wrote this????!!!! I will remove

Comment (RichardPK) [reply src/app/lib/utilities/episodeAvailability/index.test.js]: ✋ 

When this is fixed I think it's good to 🚢 ?

File: src/app/lib/utilities/episodeAvailability/index.test.js [hunk 3]
```diff
@@ -1,105 +1,185 @@
...
-    const masterBrand = path(
-      ['metadata', 'createdBy'],
-      onDemandRadioEpisodeJson,
-    );
-    const pid = path(['promo', 'locators', 'pid'], onDemandRadioEpisodeJson);
-    expect(url).toEqual(`${service}/${masterBrand}/${pid}`);
-  });
+    it('should return a valid url for radio brand page', () => {
+      const url = getUrl(onDemandRadioBrandJson);
+      expect(url).toEqual('indonesia/bbc_indonesian_radio/programmes/w13xtt0s');
```
Comment (RichardPK) [inline src/app/lib/utilities/episodeAvailability/index.test.js:20]: This makes much more sense, not sure what I was smoking 🤦

**Review by RichardPK — APPROVED** [review]

**Review by ryanmccombe — APPROVED** [review]
