### PR TITLE
ATI Non-JS Tracking

### LINKED ISSUE #4711: Non-JS tracking is not working on new front pages (and maybe other page types?)
**Describe the bug**
Non-js tracking is not tracking any page views of new Simorgh front pages in ATI. 
The existing front pages on PAL are tracking page views in ATI. 

This means it is not tracking anything on the following pages:
igbo.page
pidgin.page
yoruba.page
punjabi.page
thai.page
azeri.page
kyrgyz.page

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by itimirichard**
Resolves #4711

**Overall change:** _Added the `x8` param to the ATI URL parameters for all page types to track js/nonjs requests._

**Code changes:**

- _Created a `getLibraryVersion` util function that returns `simorgh` for both AMP and canonical JS 
 enabled pages and `simorgh-nojs` for nojs pages._
- _modified `buildParams.js` for all page types to accommodate the new `libraryVersion` (`x8`) key and corresponding value _

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [x] This PR requires manual testing

### CODE REVIEW

File: src/app/lib/analyticsUtils/index.js [hunk 1]
```diff
@@ -127,20 +126,12 @@ export const getReferrer = (platform, origin, previousPath) => {
 };
 
 export const getAtUserId = () => {
-  if (!onClient()) return null;
```
Comment (samora) [inline src/app/lib/analyticsUtils/index.js]: Doesn't this seem to undo the work I did [here](https://github.com/bbc/simorgh/pull/4812)?

File: src/app/lib/analyticsUtils/index.js [hunk 2]
```diff
@@ -203,3 +194,13 @@ export const getClickInfo = (elem, { service, component, label, type }) => {
 
   return `PUB-[${service}-${component}]-[=${type}]-[${label}]-[${format}]-[]-[]-[]-[${url}]`;
 };
+
+export const getLibraryVersion = platform => {
+  if (platform === 'amp') {
```
Comment (samora) [inline src/app/lib/analyticsUtils/index.js]: I think we can refactor this to be...
```suggestion
  if (platform === 'amp' || onClient()) {
    return 'simorgh';
  }
  return 'simorgh-nojs';
```

**Review by samora — CHANGES_REQUESTED** [review]

File: src/app/lib/analyticsUtils/index.js (hunk 1 above)
Comment (samora) [reply src/app/lib/analyticsUtils/index.js]: I think once you merge in changes from `latest` you might be good.

File: src/app/lib/analyticsUtils/index.js [hunk 3]
```diff
@@ -203,3 +203,11 @@ export const getClickInfo = (elem, { service, component, label, type }) => {
 
   return `PUB-[${service}-${component}]-[=${type}]-[${label}]-[${format}]-[]-[]-[]-[${url}]`;
 };
+
+export const getLibraryVersion = platform => {
+  if (platform === 'amp' || onClient()) {
+    return 'simorgh';
+  }
+
+  return 'simorgh-nojs';
```
Comment (jroebu14) [inline src/app/lib/analyticsUtils/index.js]: reading this code I'm thinking we can get here if:

- is canonical
- is requested from server

Is that expected?

**Review by samora — APPROVED** [review]

File: src/app/lib/analyticsUtils/index.js (hunk 3 above)
Comment (itimirichard) [reply src/app/lib/analyticsUtils/index.js]: I'm not 100% sure that is expected. I'll need to ask some questions and get back to you

**Review by andrewscfc — COMMENTED** [review]
Just taken a look over this but I'm struggling to understand how this _enables_ non-js tracking? My understanding was there would be some kind of 'tracking pixel' you'd have to add to the page, I don't understand how the extra parameter enables it?

Sorry I'm missing something :confused:

File: src/app/lib/analyticsUtils/index.js (hunk 3 above)
Comment (itimirichard) [reply src/app/lib/analyticsUtils/index.js]: @jroebu14 I believe this is expected

**Comment by itimirichard** [comment]
> Just taken a look over this but I'm struggling to understand how this _enables_ non-js tracking? My understanding was there would be some kind of 'tracking pixel' you'd have to add to the page, I don't understand how the extra parameter enables it?
> 
> Sorry I'm missing something 😕

@andrewscfc https://github.com/bbc/simorgh/blob/4901428d5204d6c44a8da76017dca46c0037dae4/src/app/containers/ATIAnalytics/canonical/index.jsx

File: src/app/lib/analyticsUtils/index.test.js [hunk 4]
```diff
@@ -541,3 +542,42 @@ describe('getAtUserId', () => {
...
+        summary: 'should return `simorgh` for amp',
+      },
+      {
+        platform: 'canonical',
+        expected: 'simorgh',
+        summary: 'should return `simorgh` for canonical',
+      },
+    ];
+
+    libraryVersionScenarios.forEach(({ platform, expected, summary }) => {
```
Comment (jroebu14) [inline src/app/lib/analyticsUtils/index.test.js]: I'm not sure I'm a fan of this. Can we keep these 2 tests explicit rather than being generated with a forEach. I think it's better not to add to the cognitive load when reading tests.

Comment (itimirichard) [reply src/app/lib/analyticsUtils/index.test.js]: @jroebu14  This has been fixed.

Comment (jroebu14) [reply src/app/lib/analyticsUtils/index.test.js]: Thanks :)

File: src/app/lib/analyticsUtils/index.js (hunk 3 above)
Comment (jroebu14) [reply src/app/lib/analyticsUtils/index.js]: I've been thinking - maybe this function should always return `'simorgh'` and then [here](https://github.com/bbc/simorgh/blob/4901428d5204d6c44a8da76017dca46c0037dae4/src/app/containers/ATIAnalytics/canonical/index.jsx#L24) we can do `src={atiPageViewUrl.replace('x8=[simorgh]', 'x8=[simorgh-nojs]')}` since it's inside a `<noscript>`.

Comment (itimirichard) [reply src/app/lib/analyticsUtils/index.js]: Okay, that'll be a better approach, ensuring that `simorgh-nojs` always get sent from the client.

Comment (itimirichard) [reply src/app/lib/analyticsUtils/index.js]: @jroebu14 this has been fixed

**Review by jroebu14 — COMMENTED** [review]
Looks good but can we have a test for `x8=[simorgh-nojs]` in the tracking pixel?

**Comment by itimirichard** [comment]
> Looks good but can we have a test for `x8=[simorgh-nojs]` in the tracking pixel?

This has been added @jroebu14

File: src/app/containers/ATIAnalytics/params/frontpage/buildParams.test.js [hunk 5]
```diff
@@ -32,6 +33,7 @@ const validURLParams = {
   producerId: serviceContext.atiAnalyticsProducerId,
   timePublished: analyticsUtils.getPublishedDatetime(),
   timeUpdated: analyticsUtils.getPublishedDatetime(),
+  libraryVersion: analyticsUtils.getLibraryVersion(requestContext.platform),
```
Comment (jroebu14) [inline src/app/containers/ATIAnalytics/params/frontpage/buildParams.test.js]: no need to pass in any arguments anymore

**Review by jroebu14 — APPROVED** [review]
just one more tidy up. other than that it looks good 🙂
