### PR TITLE
Fix duplicate timestamp bug

### LINKED ISSUE #1470: Duplicated timestamps
**Describe the bug**
On certain devices, like iPhone 6S iOS, v9, timestamps get duplicated

image

This has **not** been fixed by the recent timestamp work, and it infact now duplicates it twice
image

**To Reproduce**

1. Open an article on iPhone 6S iOS, v9
2. See error

**Expected behavior**
It displays the timestamp once, twice if its updated.

**Screenshots**
See above

**Smartphone (please complete the following information):**

- Device: iPhone 6s
- OS: iOS9
- Browser: Safari
- Version: Unknown

**Additional context**

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

### PR DESCRIPTION
**Pull request by dr3**
Resolves #1470

**Overall change:** Fix duplicate timestamp bug

**Code changes:**

- Removes reliance on `toLocaleDateString`'s options object, which has poor support

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Review by pjlee11 — DISMISSED** [review]
Looks sensible 👍

File: src/app/containers/Timestamp/index.jsx [hunk 1]
```diff
@@ -6,35 +6,37 @@ import relativeTime from './relativeTimestamp';
 // if the date is invalid return null - https://stackoverflow.com/questions/1353684/detecting-an-invalid-date-date-instance-in-javascript#answer-1353711
 const isValidDateTime = dateTime => !isNaN(dateTime); // eslint-disable-line no-restricted-globals
 
+const leadingZero = val => (val < 10 ? `0${val}` : val);
+
+const months = [ 'January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December' ]; // eslint-disable-line
```
Comment (ChrisBAshton) [inline src/app/containers/Timestamp/index.jsx:11]: Can we add a `months` property to the service context config?

File: src/app/containers/Timestamp/index.jsx [hunk 2]
```diff
@@ -6,35 +6,37 @@ import relativeTime from './relativeTimestamp';
...
-    day: formatType.day,
-  });
+  const year = formatType.year(dateObj);
+  const month = formatType.month(dateObj);
+  const day = formatType.day(dateObj);
 
   const orderedDate = formatType.reverse
-    ? [day, month, fullYear].reverse()
-    : [day, month, fullYear];
+    ? [year, month, day]
```
Comment (sareh) [inline src/app/containers/Timestamp/index.jsx]: Instead of having a ternary here, I think it would be much more readable to define things explictly. e.g. in `shortAlphaNumeric` remove the `reverse: true` `reverse: false` and explicitly add a `format: [year, month, day]`.

File: src/app/containers/Timestamp/index.jsx (hunk 1 above)
Comment (dr3) [reply src/app/containers/Timestamp/index.jsx:11]: IMO, as this PR is a bug fix, not a feature, that should be a separate issue, as this was previously hardcoded to `en-GB`

Im keen on smaller PRs where possible

Happy to raise an issue/do it if you disagree though

File: src/app/containers/Timestamp/index.jsx (hunk 2 above)
Comment (dr3) [reply src/app/containers/Timestamp/index.jsx]: Chatted IRL and pushed change

**Review by sareh — APPROVED** [review]
👍 Looks good!

File: src/app/containers/Timestamp/index.jsx (hunk 1 above)
Comment (ChrisBAshton) [reply src/app/containers/Timestamp/index.jsx:11]: Fair point 👍 happy to leave it.

**Review by ChrisBAshton — APPROVED** [review]

**Comment by jamesbrumpton** [comment]
👍
