### PR TITLE
Polyfill IE11 IE10 and drop IE9 bundle support

### LINKED ISSUE #1444: JS Bundle broken on IE 9-11
**Describe the bug**
An error is logged, and the bundle doesnt run on IE

**To Reproduce**

1. Go to 'article in IE 9 - 11
2. See errors 

**Expected behavior**
It doesnt error

**Screenshots**
image

image

**Desktop (please complete the following information):**

- OS: windows 7 and 10, probably 8 too
- Browser IE
- Version 9-11

**Additional context**

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

### PR DESCRIPTION
**Pull request by dr3**
Resolves #1444

**Overall change:** Polyfill IE11 IE10 and drop IE9 bundle support

**Code changes:**
```
import 'core-js/es6/map';
import 'core-js/es6/set';
```
Added due to [React 16](https://reactjs.org/docs/javascript-environment-requirements.html) needing them as it depends on the collection types Map and Set

```
import 'core-js/es6/symbol';
```
Needed by Styled Components for IE11 and below

```
import getRandomValues from 'polyfill-crypto.getrandomvalues';`

if (!window.crypto && !window.msCrypto) {
  window.crypto = { getRandomValues };
}

```
Needed in IE10 throughout our application 

**Testing notes:** 
To check the bundle is loading and executing as expected, a good tell tale is the canonical cookie banner.

There should also be no console errors/logs.

ADR for this will be written in https://github.com/bbc/simorgh/issues/1478

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [x] Test engineer approval
- [x] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

**Review by pjlee11 — DISMISSED** [review]
🎉 awesome stuff!

**Review by sareh — DISMISSED** [review]
👍 Looks good!
Viewed with Browser Stack in IE 9, IE 10 & IE 11 - had no console errors & the client-side JS for the cookie banners works as expected.

**Comment by jamesbrumpton** [comment]
image
There are several issues on IE9.
1 - The footer links are all the way to the left
2 - The text next to the inline link at the bottom of the page has turned black
3 - There is extra white padding at the base of the page

**Comment by ChrisBAshton** [comment]
Discussed IRL. IE9 and IE10 have dropped off our support stats for News, so it's perfectly suitable to give them the core experience. IE9 and below support IE conditional comments, and IE10 is working ok, so we'll just use IE conditional comments to not deliver JS to <=IE9.

File: src/app/components/LimitIE9Comment/index.jsx [hunk 1]
```diff
@@ -0,0 +1,13 @@
+import React from 'react';
+
+/*
+ * These, when used together, stop anything within them from loading on IE9 and below.
+ */
+
+export const IE9LimitOpen = () => (
+  <div dangerouslySetInnerHTML={{ __html: '<!--[if !IE]> -->' }} /> // eslint-disable-line react/no-danger
```
Comment (sareh) [inline src/app/components/LimitIE9Comment/index.jsx]:
```suggestion
  <div dangerouslySetInnerHTML={{ __html: '<!--[if !IE]><!-->' }} /> // eslint-disable-line react/no-danger
```

File: src/app/components/LimitIE9Comment/index.jsx [hunk 2]
```diff
@@ -0,0 +1,13 @@
...
+);
+
+export const IE9LimitClose = () => (
+  <div dangerouslySetInnerHTML={{ __html: '<!-- <![endif]-->' }} /> // eslint-disable-line react/no-danger
```
Comment (sareh) [inline src/app/components/LimitIE9Comment/index.jsx]:
```suggestion
  <div dangerouslySetInnerHTML={{ __html: '<!--<![endif]-->' }} /> // eslint-disable-line react/no-danger
```

File: src/app/components/LimitIE9Comment/index.jsx (hunk 1 above)
Comment (dr3) [reply src/app/components/LimitIE9Comment/index.jsx]: Hmm this doesn't match `<!--[if !IE]> -->` on https://www.quirksmode.org/css/condcom.html

File: src/app/components/LimitIE9Comment/index.jsx (hunk 2 above)
Comment (dr3) [reply src/app/components/LimitIE9Comment/index.jsx]: Hmm this doesn't match `<!-- <![endif]-->` on https://www.quirksmode.org/css/condcom.html

File: src/app/components/LimitIE9Comment/index.jsx (hunk 1 above)
Comment (sareh) [reply src/app/components/LimitIE9Comment/index.jsx]: I was referring to https://css-tricks.com/how-to-create-an-ie-only-stylesheet/#article-header-id-3 

Seems like the version you used is a special syntax for down-level conditional comments: https://www.sitepoint.com/internet-explorer-conditional-comments/

In which case, you'll still need to remove the space, but not necessarily add the `<!`

Comment (dr3) [reply src/app/components/LimitIE9Comment/index.jsx]: Ahh fair, I have more faith in css-tricks :P

File: src/app/components/LimitIE9Comment/index.jsx [hunk 3]
```diff
@@ -0,0 +1,13 @@
...
+/*
+ * These, when used together, stop anything within them from loading on IE9 and below.
+ */
+
+export const IE9LimitOpen = () => (
+  <div dangerouslySetInnerHTML={{ __html: '<!--[if !IE]><!-->' }} /> // eslint-disable-line react/no-danger
+);
+
+export const IE9LimitClose = () => (
+  <div dangerouslySetInnerHTML={{ __html: '<!--<![endif]-->' }} /> // eslint-disable-line react/no-danger
```
Comment (ChrisBAshton) [inline src/app/components/LimitIE9Comment/index.jsx]: Any reason we didn't make this generic? Could be a neat little component.

```jsx
export const HTMLComment = ({ children }) => (
  <div dangerouslySetInnerHTML={{ __html: `<!--${children}-->` }} />
);
```

Usage:

```jsx
<HTMLComment>[if !IE]><!</HTMLComment>
  <script>bla</script>
<HTMLComment><![endif]</HTMLComment>

<footer>
  <HTMLComment>Reading this? Join the BBC! http://careerssearch.bbc.co.uk/ </HTMLComment>
</footer>
```

Comment (dr3) [reply src/app/components/LimitIE9Comment/index.jsx]: I think we can expand it if we decide to that, but it seems a stretch IMO and having the specific IE comment syntax in a file like `Document/component.jsx` doesn't seem great IMO

Comment (ChrisBAshton) [reply src/app/components/LimitIE9Comment/index.jsx]: It feels better than making a specific IE component IMO!

Comment (dr3) [reply src/app/components/LimitIE9Comment/index.jsx]: Chatted IRL, I think we will leave it as it is due to desire to reduce brittleness and unique use case

File: src/app/components/LimitIE9Comment/index.jsx [hunk 4]
```diff
@@ -0,0 +1,13 @@
+import React from 'react';
+
+/*
+ * These, when used together, stop anything within them from loading on IE9 and below.
+ */
+
+export const IE9LimitOpen = () => (
```
Comment (pjlee11) [inline src/app/components/LimitIE9Comment/index.jsx]:
```suggestion
export const ifNotIE9Open = () => (
```

This feels more explicitly in what the component is doing

Comment (dr3) [reply src/app/components/LimitIE9Comment/index.jsx]: Done :)

File: src/app/components/IfNotIE9Comment/index.test.jsx [hunk 5]
```diff
@@ -0,0 +1,12 @@
+import React from 'react';
+import { shouldMatchSnapshot } from '../../helpers/tests/testHelpers';
+import { IfNotIE9Open, IfNotIE9Close } from '.';
+
+describe('Timestamp', () => {
+  shouldMatchSnapshot('should render IE9 limit comment open', <IfNotIE9Open />);
```
Comment (pjlee11) [inline src/app/components/IfNotIE9Comment/index.test.jsx]:
```suggestion
  shouldMatchSnapshot('should render if not IE9 open comment open', <IfNotIE9Open />);
```

File: src/app/components/IfNotIE9Comment/index.test.jsx [hunk 6]
```diff
@@ -0,0 +1,12 @@
...
+
+  shouldMatchSnapshot(
+    'should render IE9 limit comment close',
```
Comment (pjlee11) [inline src/app/components/IfNotIE9Comment/index.test.jsx]:
```suggestion
    'should render if not IE9 comment close',
```

File: src/app/components/IfNotIE9Comment/index.test.jsx (hunk 5 above)
Comment (dr3) [reply src/app/components/IfNotIE9Comment/index.test.jsx]: done :)

File: src/app/components/IfNotIE9Comment/index.test.jsx (hunk 6 above)
Comment (dr3) [reply src/app/components/IfNotIE9Comment/index.test.jsx]: done :)

File: src/app/components/IfNotIE9Comment/index.test.jsx (hunk 5 above)
Comment (pjlee11) [reply src/app/components/IfNotIE9Comment/index.test.jsx]: ^ lies 😝

**Review by pjlee11 — DISMISSED** [review]
LGTM 👍

**Review by ChrisBAshton — CHANGES_REQUESTED** [review]
Hate to rename it again, but I think `<IfAboveIE9>` would be better than `<IfNotIE9>`. Otherwise it's ambiguous what happens on IE8, IE7 etc.

Also, can we change the API to take children, so that we don't accidentally omit the closing tag:

```jsx
<IfAboveIE9>
  <script>bla</script>
</IfAboveIE9>
```

Implementation could be:

```jsx
<Fragment>
  <div dangerouslySetInnerHTML={{ __html: '<!--[if !IE]><!-->' }} />
    {props.children}
  <div dangerouslySetInnerHTML={{ __html: '<!--<![endif]-->' }} />
</Fragment>
```

**Review by ChrisBAshton — DISMISSED** [review]
Confirmed tested and working on IE9. However, it does mean we're not displaying a cookie banner.

Screen Shot 2019-03-27 at 09 20 52

But this is comparable to the current News offering on IE8:

Screen Shot 2019-03-27 at 09 22 02

I'll double-check with @jimjohnsonrollings and legal whether this is ok or not. From a code perspective I'm happy with our general fix for IE, but we may need to go and raise an issue to ensure cookie banner presentation on <IE10 separately.

**Comment by ChrisBAshton** [comment]
Argh, although CodeClimate diff-coverage drops 20% because of poly.js!!

Screen Shot 2019-03-27 at 09 24 34

File: package.json [hunk 7]
```diff
@@ -112,6 +113,7 @@
     "morgan": "^1.9.1",
     "nanoid": "^2.0.0",
     "path-to-regexp": "^2.4.0",
+    "polyfill-crypto.getrandomvalues": "^1.0.0",
```
Comment (pjlee11) [inline package.json]:
```suggestion
    "polyfill-crypto.getrandomvalues": "1.0.0",
```

Considering [polyfill-crypto.getrandomvalues](https://www.npmjs.com/package/polyfill-crypto.getrandomvalues) has a single contributor and less than a 1000 weekly downloads should we limit to using v1.0.0? This would stop something potential malicious coming through in a patch version without us explicitly bumping the package. 

cc @ChrisBAshton @sareh - thoughts?

Comment (ChrisBAshton) [reply package.json]: Seems fair 👍

Comment (dr3) [reply package.json]: Done :)

**Review by ChrisBAshton — DISMISSED** [review]

File: src/server/Document/component.jsx [hunk 8]
```diff
@@ -14,15 +15,21 @@ const Document = ({ assets, app, data, styleTags, helmet }) => {
...
-      key={asset}
-      type="text/javascript"
-      src={asset}
-      defer
-    />
-  ));
+  const scripts = (
+    <Fragment>
+      <IfAboveIE9>
+        {assets.map(asset => (
```
Comment (sareh) [inline src/server/Document/component.jsx:21]: On IE 9 using browserstack, I still see the scripts being added:

Screen Shot page on browserstack using IE9

Comment (sareh) [reply src/server/Document/component.jsx:21]: Resolving this - when installing from branch again, these scripts are not being pulled in.

Comment (sareh) [reply src/server/Document/component.jsx:21]: Before:
Screen Shot with scripts

After: 
Screen Shot without scripts
👍

**Review by sareh — APPROVED** [review]
👍 Brilliant work, Drew.

**Review by ChrisBAshton — APPROVED** [review]

**Review by pjlee11 — APPROVED** [review]
