### PR TITLE
Fix podcast page design

### LINKED ISSUE #9352: Incorrect line height on synopsis on On Demand Audio pages
The line height on the synopsis is incorrect. The specs on the original design are: font size 24px and line height 28px.

Screenshot 2021-08-23 at 11 11 29

### PR DESCRIPTION
**Pull request by nicola-d-bbc**
Resolves #9352

**Overall change:**
Some of the styling on podcast pages does not reflect the styles shown in Zeplin. This ticket fixes the incorrect spacing between elements and updates incorrect font size and line height on the subtitle.

Examples:
https://www.bbc.com/portuguese/podcasts/p07r3r3t/p09clrrg
https://www.bbc.com/russian/podcasts/p05607v8

Designs:
https://app.zeplin.io/project/5d4d77b1fcbfc79bf47e0294/dashboard?tag=podcast%20page

Changes:
- Above 1008px
image

- Between 360-600px
image

- Between 240-360px
image

**Code changes:**

- Removed line height from spans to fix line height bug shown on original issue.
- Removed padding from timestamp to better reflect the spacing shown in UI designs.
- Updated padding of synopsis element to better reflect spacing shown in UI designs.
- Added font size page breaks to lower font size on smaller screens as per the UI designs.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project
- [ ] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

File: src/app/containers/OnDemandHeading/index.jsx [hunk 1]
```diff
@@ -17,16 +26,29 @@ const BrandTitle = styled.span`
...
   }
 `;
 
 const Subheading = styled.span`
+  display: inline-block;
+  margin: 0;
   ${({ script }) => script && getDoublePica(script)}
   ${({ service }) => getSansRegular(service)}
-  margin: 0;
+  ${MEDIA_QUERY_TYPOGRAPHY.LAPTOP_AND_LARGER} {
```
Comment (HarryVerhoef) [inline src/app/containers/OnDemandHeading/index.jsx]: This is really cool, I wasn't aware of this feature of gel-foundations where it gives us the actual media queries 🙂 Although inspecting the package, think this will give us `@media (min-width: 600px)` and I can't find a breakpoint in the designs for > 600px?

File: src/app/containers/OnDemandHeading/index.jsx [hunk 2]
```diff
@@ -17,16 +26,29 @@ const BrandTitle = styled.span`
...
+    font-size: ${GEL_SPACING_TRPL};
+    line-height: 1.75rem;
+  }
+  ${GEL_GROUP_2_SCREEN_WIDTH_MAX} {
```
Comment (HarryVerhoef) [inline src/app/containers/OnDemandHeading/index.jsx]: I think this will become `37.4375rem {` instead of `@media (max-width: 37.4375rem) {`, which means I'm not sure the CSS inside this block will behave expectedly 👍

**Review by HarryVerhoef — COMMENTED** [review]
This looks good 🙂 Just a couple comments regarding the media queries 👍 I think the best way to do media queries is to do them mobile-first, so like:
```css
{
  <mobile/default-styles>
  @media (min-width: ${GEL_GROUP_1_SCREEN_WIDTH_MIN}) { ... }
  @media (min-width: ${GEL_GROUP_2_SCREEN_WIDTH_MIN}) { ... }
  @media (min-width: ${GEL_GROUP_4_SCREEN_WIDTH_MIN}) { ... }
  etc.
}
```
So that the media queries are sequential but not necessarily consecutive. In my opinion this is the most readable way of doing them - we can see what the default styles are (which are applied when the screen width is below `${GEL_GROUP_1_SCREEN_WIDTH_MIN}` in this case) and we can see what the effect of enlarging the screen width is 👍 Hope that helps, happy to hop on a call if need be 🙂

File: src/app/containers/OnDemandHeading/index.jsx (hunk 1 above)
Comment (pvaliani) [reply src/app/containers/OnDemandHeading/index.jsx]: We haven't been given a specification for breakpoint >600px but have requested this from UX so will address if appropriate. Thanks!

File: src/app/containers/OnDemandHeading/index.jsx [hunk 3]
```diff
@@ -17,16 +26,29 @@ const BrandTitle = styled.span`
...
   }
 `;
 
 const Subheading = styled.span`
+  display: inline-block;
+  margin: 0;
   ${({ script }) => script && getDoublePica(script)}
   ${({ service }) => getSansRegular(service)}
-  margin: 0;
+  @media (max-width: 22.5rem) and (min-width: ${GEL_GROUP_1_SCREEN_WIDTH_MIN}) {
```
Comment (HarveyPeachey) [inline src/app/containers/OnDemandHeading/index.jsx:41]: Is `@media (max-width: 22.5rem)` targeting a non-GEL defined screen size? Or should this be targeting [GEL group 1](https://www.bbc.co.uk/gel/guidelines/grid#grid-sizes)? Here are the defined breakpoints if it helps https://github.com/bbc/psammead/blob/latest/packages/utilities/gel-foundations/src/breakpoints.js

Comment (emilysaffron) [reply src/app/containers/OnDemandHeading/index.jsx:41]: Hey Harvey, yeah following the design specs from UX this is targeting the right size, it was a non-GEL defined screen size of 360px.

Comment (HarveyPeachey) [reply src/app/containers/OnDemandHeading/index.jsx:41]: Do we know why UX has defined a custom breakpoint for 360px? Just thinking for maintainability it could be quite confusing for future maintainers why there's a random breakpoint media query, as I'm not sure I've seen it done before in Simorgh/Psammead

File: src/app/containers/OnDemandHeading/index.jsx (hunk 2 above)
Comment (pvaliani) [reply src/app/containers/OnDemandHeading/index.jsx]: Have addressed this in latest commits :)

File: src/app/containers/OnDemandHeading/index.jsx (hunk 3 above)
Comment (pvaliani) [reply src/app/containers/OnDemandHeading/index.jsx:41]: @HarveyPeachey From UX:

Usually we don't specify a different treatment for the 360px breakpoint, as we treat Group 1 (0-399px) as one treatment and Group 2 (400-599px) as another. However, in World Service we have seen the 360px breakpoint become one of our most used by users (as its international users) so we sometimes offer another design at 360px in order to offer more users a better experience.

It may be worth refactoring `MEDIA_QUERY_TYPOGRAPHY` as a separate issue to accommodate other breakpoints.

Comment (HarveyPeachey) [reply src/app/containers/OnDemandHeading/index.jsx:41]: @pvaliani Thanks for asking UX about that. I think that's a good idea would be nice to have some form of const to use if it's WS specific breakpoint, doesn't have to be part of this PR.

**Review by HarveyPeachey — APPROVED** [review]
Great work guys! 🚀

**Comment by HarryVerhoef** [comment]
Looking good! Just to clarify my earlier review, one way to format the media queries which I think functions identically is like so:
```css
/* Default styles */
display: inline-block;
margin: 0;

@media (min-width: ${GEL_GROUP_1_SCREEN_WIDTH_MIN}) {
  font-size: 1.125rem;
  line-height: 1.375rem;
}

@media (min-width: 22.5rem) {
  font-size: 1.25rem;
  line-height: ${GEL_SPACING_DBL};
}

@media (min-width: ${GEL_GROUP_3_SCREEN_WIDTH_MIN}) {
  font-size: ${GEL_SPACING_TRPL};
  line-height: 1.75rem;
}
```
Current implementation in this PR is fine but I personally think this makes it easier to work out what styles are being applied at a given viewport width, without the mixing of both min and max 👍 Not a blocker, just a suggestion 🙂

**Review by HarryVerhoef — APPROVED** [review]
Nice one! 🚀

**Comment by paruchurisilpa** [comment]
Checked using the URl's:

https://localhost:7080/portuguese/podcasts/p07r3r3t/p09clrrg
https://localhost:7080/russian/podcasts/p05607v8
https://localhost:7080/arabic/podcasts/p02pc9qc

Checked that the styling are updated as per the zeplin design here --> https://app.zeplin.io/project/5d4d77b1fcbfc79bf47e0294/dashboard?tag=podcast%20page

**Comment by LilyL0u** [comment]
http://localhost:7080/portuguese/podcasts/p07r3r3t/p083x9gr

When I check this on Chrome, the largest window width looks fine (above 1008px)


Screenshot 2021-09-08 at 16 33 42

But the 360-600px looks like the gap between the lines is now smaller than on the designs 😱 

Screenshot 2021-09-08 at 16 34 49

And the same with 240-360px

Screenshot 2021-09-08 at 16 36 08

**Comment by LilyL0u** [comment]
Also on most window sizes for Russian now, the title height goes above the top of the image

Not sure if this is considered a problem, but it is different from designs and from on live.
The spacing between the lines of the title is now better though!

The below screenshots have windows both at 1009px width

http://localhost:7080/russian/podcasts/p05607v8
Screenshot 2021-09-08 at 16 41 53


vs

https://www.bbc.com/russian/podcasts/p05607v8

Screenshot 2021-09-08 at 16 42 01

File: src/app/containers/OnDemandHeading/StyledRadioHeadingContainer.jsx [hunk 4]
```diff
@@ -12,6 +12,7 @@ import OnDemandHeading from '.';
 
 const StyledRadioHeadingContainer = styled(OnDemandHeading)`
   padding: ${GEL_SPACING_QUAD} 0 ${GEL_SPACING_DBL};
+  display: inline-block;
```
Comment (greenc05) [inline src/app/containers/OnDemandHeading/StyledRadioHeadingContainer.jsx:15]: As we have introduced some new CSS, let's do a developer a11y swarm please - just our supported screen readers need checking in this case, to make sure we haven't introduced any bugs

File: src/app/containers/OnDemandHeading/__snapshots__/index.test.jsx.snap [hunk 5]
```diff
@@ -82,13 +84,33 @@ exports[`AudioPlayer blocks OnDemandHeading should render correctly - dark mode
...
+  .emotion-6 {
+    font-size: 1.5rem;
+    line-height: 1.75rem;
+  }
+}
+
 <div>
   <h1
     class=" emotion-0 emotion-1"
+    role="text"
```
Comment (greenc05) [inline src/app/containers/OnDemandHeading/__snapshots__/index.test.jsx.snap]: Unsure why this has moved? Role text removes semantics of the HTML element it is applied to, this would result in this element no longer being acknowledged as a h1 with AT. Role text should only be used on non semantic HTML elements please e.g. span/div

File: src/app/containers/OnDemandHeading/index.jsx [hunk 6]
```diff
@@ -62,7 +86,7 @@ const OnDemandHeadingContainer = ({
       {...(idAttr === 'content' && { tabIndex: '-1' })}
       {...(ariaHidden && { as: 'strong', 'aria-hidden': 'true' })}
     >
-      <TextWrapper {...(ariaHidden ? {} : { role: 'text' })}>
```
Comment (greenc05) [inline src/app/containers/OnDemandHeading/index.jsx]: Did we have aria-hiddent here before? Is this now elsewhere?

File: src/app/containers/OnDemandHeading/StyledRadioHeadingContainer.jsx (hunk 4 above)
Comment (greenc05) [reply src/app/containers/OnDemandHeading/StyledRadioHeadingContainer.jsx:15]: https://bbc.github.io/accessibility-news-and-you/assistive-technology/testing.html

File: src/app/containers/OnDemandHeading/index.jsx (hunk 6 above)
Comment (nicola-d-bbc) [reply src/app/containers/OnDemandHeading/index.jsx]: Added this back in.

File: src/app/containers/OnDemandHeading/__snapshots__/index.test.jsx.snap (hunk 5 above)
Comment (nicola-d-bbc) [reply src/app/containers/OnDemandHeading/__snapshots__/index.test.jsx.snap]: Role has been added back to the span 👍

**Comment by greenc05** [comment]
A11y swarm - Screen readers only need testing

- [x] Talkback
- [ ] VoiceOver iPhone
- [x] VoiceOver Mac
- [ ] NVDA
- [ ] Jaws

**Comment by paruchurisilpa** [comment]
Checked using the links:

https://192.168.0.xx:7080/russian/podcasts/p05607v8

- [x] Talkback
- [x] VoiceOver iPhone
- [x] VoiceOver Mac
- [x] NVDA
- [x] Jaws

LGTM..
