### PR TITLE
Image placeholder canonical transparency fix

### LINKED ISSUE #8811: [PS AMP] Transparent images show the BBC blocks placeholder behind
**Describe the bug**
A transparent image still hows the BBC blocks placeholder behind which means it can be seen through the image.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.bbc.co.uk/news/uk-55808266.amp
3. Scroll down to `Doubts over UK's medium-term vaccine roll-out`
4. See the transparent image below

**Expected behaviour**
Transparent images should not show the placeholder image behind it.

**Screenshots**
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [X] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by HarveyPeachey**
Part of https://github.com/bbc/simorgh/issues/8811

**Overall change:**
Fixes canonical onLoad placeholder removal functionality. This doesn't fix amp images, this is because `onLoad` won't fire on `amp-img`. I'm working on a draft PR to try and resolve the amp issue.

Emotion does support the [`css`](https://emotion.sh/docs/object-styles#with-the-css-prop) prop. Not sure if an import is worth it just for a slight syntax change. Happy to switch to it though.

**Code changes:**

- Switched `css` to `style` within `<ImagePlaceholder>`
- Added fixture data with transparent image for testing at `/news/uk-55808266`

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [x] This PR requires manual testing

### CODE REVIEW

File: src/app/containers/ImageWithPlaceholder/index.jsx [hunk 1]
```diff
@@ -57,7 +57,10 @@ const ImageWithPlaceholder = ({
           />
         </Helmet>
       )}
-      <ImagePlaceholder css={isLoaded && `background: none`} ratio={ratio}>
+      <ImagePlaceholder
+        style={{ background: isLoaded && 'none' }}
```
Comment (simonsinclair) [inline src/app/containers/ImageWithPlaceholder/index.jsx]: If `isLoading` equals `false` this expression will return `false` – that could in turn mean we set `background: false`.

I think React is intelligent enough to omit Boolean values, but I would not leave this to chance. If you pass it a Number it actually stringifies and appends "px" to it automagically! See https://reactjs.org/docs/dom-elements.html#style.

We could instead return our style to apply if `isLoading` is truthy e.g. `style={isLoading ? { background: 'none' } : null}`

Incidentally, https://kentcdodds.com/blog/use-ternaries-rather-than-and-and-in-jsx is also a good one on this topic.

Comment (HarveyPeachey) [reply src/app/containers/ImageWithPlaceholder/index.jsx]: You're right, this is what I was trying to do. Just couldn't figure out the syntax, danke 👍

File: src/app/containers/ImageWithPlaceholder/index.jsx [hunk 2]
```diff
@@ -57,7 +57,10 @@ const ImageWithPlaceholder = ({
           />
         </Helmet>
       )}
-      <ImagePlaceholder css={isLoaded && `background: none`} ratio={ratio}>
+      <ImagePlaceholder
+        style={isLoaded ? { background: 'none' } : null}
```
Comment (andrewscfc) [inline src/app/containers/ImageWithPlaceholder/index.jsx:61]: Do we normally use the [styled components](https://emotion.sh/docs/styled) approach to apply css to React components? Is this literally just an inline style?

I don't know if there are any downsides with use an inline style this way but I wonder why we've taken this approach here compared to other places; it seems the `css` prop wouldn't exist if `style` was the correct way to go?

**Review by simonsinclair — APPROVED** [review]
Thanks for addressing my comment!

File: src/app/containers/ImageWithPlaceholder/index.jsx (hunk 2 above)
Comment (simonsinclair) [reply src/app/containers/ImageWithPlaceholder/index.jsx:61]: - `style` sets an inline style.
- `css` will add a style to the stylesheet and generate a class, which Emotion will then attach to this component.

The only difference is specificity and, for a style override like this, both approaches work effectively if `background` should always be `none` when the image has loaded.

From the React Docs:
> `style` is most often used in React applications to add dynamically-computed styles at render time.

**Review by joshcoventry — APPROVED** [review]

File: src/app/containers/ImageWithPlaceholder/index.jsx (hunk 2 above)
Comment (andrewscfc) [reply src/app/containers/ImageWithPlaceholder/index.jsx:61]: Just quoting @jroebu14 here:
> with inline styles you don't get media-queries, psuedo selectors, you have to use !important or write more inline styles to override, debugging UI bugs can become more difficult, inline styles can't be reused like class names can, can't be minified 

Seems we should consider using the css prop on that basis but with 2 approvals please go ahead with this PR if you wish, I have no major concerns.

Comment (jroebu14) [reply src/app/containers/ImageWithPlaceholder/index.jsx:61]: Simon is right that an inline style here is OK and seems harmless but I worry that we then open the gates to a wee display:block here, a wee !important there or nested selectors, or somebody new starts and begins doing the same because it's how we do things and it all gets out of hand!

Comment (andrewscfc) [reply src/app/containers/ImageWithPlaceholder/index.jsx:61]: That's the reason for my reluctance here, doesn't seem very hard to be consistent with everywhere else in this case and will form the basis for someone else's choice in the future.

**Review by ryanmccombe — APPROVED** [review]

**Comment by paruchurisilpa** [comment]
Testing URL:

* http://localhost:7080/news/uk-55808266.amp

I am still seeing the issue in ff, please find the screenshot attached.
Screenshot 2021-02-11 at 16 36 07

**Comment by andrewscfc** [comment]
> Testing URL:
> 
>     * http://localhost:7080/news/uk-55808266.amp
> 
> 
> I am still seeing the issue in ff, please find the screenshot attached.
> Screenshot 2021-02-11 at 16 36 07

Hey @paruchurisilpa this PR doesn't cover amp, it'll be covered a seperate PR, @HarveyPeachey mentions this in the PR description:
> This doesn't fix amp images, this is because onLoad won't fire on amp-img. I'm working on a draft PR to try and resolve the amp issue.

**Comment by paruchurisilpa** [comment]
Thanks @andrewscfc ,got it. Will check amp as part of the other PR..

**Comment by paruchurisilpa** [comment]
This is what i see in ff on http://localhost:7080/news/uk-55808266
Screenshot 2021-02-11 at 16 47 57

**Comment by paruchurisilpa** [comment]
ok Images are not lazy loading because JS wasn't loading..It may be because of the way I was running live build by using npm run build:live:debug && npm start.. Its ok when I run npm run build && npm start.

LGTM..
