### PR TITLE
Move page containers to new pages dir and create new cps containers

### LINKED ISSUE #5040: Split CPS Asset page type containers
A proposal to move to separate top level containers for each page type. Currently in Simorgh articles and front pages have their own page type container whereas all other assets (STY, FIX, PGL, MAPs) fall into the CpsAsset container. 

This is fine when those page types are all generally the same however with the addition of CPS STY's we will be adding a second column to the layout, we may have different meta data to apply for the different page types as well. Given this I'd like to switch to giving each page type its own top level container, this will add a small amount of duplication however will provide more flexibility and improve the readability of the code base.

**Current**

| PageType  | Container |
|-----------|-----------|
| Frontpage | Frontpage |
| Article   | Articles  |
| MAP       | CpsAsset  |
| STY       | CpsAsset  |
| PGL       | CpsAsset  |
| FIX       | Frontpage |

**Proposed**

| PageType  | Container |
|-----------|-----------|
| Frontpage | Frontpage |
| Article   | Articles  |
| MAP       | CpsMap       |
| STY       | CpsSty       |
| PGL       | CpsPgl       |
| FIX       | CpsFix       |

**Testing Notes**

This PR is primarily changing the file structure. it introduces a few new containers for our different CPS page types instead of having one large CpsAsset container for all CPS page types.

I would imagine just a simple regression of the different page types would be enough.

### PR DESCRIPTION
**Pull request by chris-hinds**
Resolves #5040 

**Overall change:** 
- Creates new Top Level containers for each page type Simorgh supports.
- Moves page containers to a new pages dir to separate from the actual data and presentational containers, this improves the readability IMO i.e.

```
/src
  > /app
    > /components
    > /containers
    > /pages
```

Each CPS page Type still uses the `CpsAssetPageMain` container. This new setup enables us to change this per asset type if required.

The switch statement in the routes file will fall through to a default (404 error page) so if the asset type does not match something Simorgh supports or is undefined we will return a 404 error page.

**Testing Notes**

This PR is primarily changing the file structure. it introduces a few new containers for our different CPS page types instead of having one large CpsAsset container for all CPS page types.

I would imagine just a simple regression of the different page types would be enough.

### CODE REVIEW

File: src/app/routes/index.js [hunk 1]
```diff
@@ -13,10 +19,23 @@ import {
...
+
+  switch (type) {
+    case 'STY':
+      return CpsSty({ ...props, pageType: type });
+    case 'PGL':
+      return CpsPgl({ ...props, pageType: type });
+    case 'MAP':
+      return CpsMap({ ...props, pageType: type });
+    case 'FIX': // TODO: Create FIX Page if required
+      return FrontPage({ ...props, pageTyp: type });
```
Comment (karinathomasbbc) [inline src/app/routes/index.js]: Typo here - should be  `return FrontPage({ ...props, pageType: type });`

File: src/app/routes/index.js [hunk 2]
```diff
@@ -13,10 +19,23 @@ import {
...
+    // default:
```
Comment (karinathomasbbc) [inline src/app/routes/index.js]: Should we include the ErrorPage as the fallback?

**Review by karinathomasbbc — CHANGES_REQUESTED** [review]

File: src/app/routes/index.js (hunk 1 above)
Comment (chris-hinds) [reply src/app/routes/index.js]: good spot

File: src/app/pages/CpsMap/index.jsx [hunk 3]
```diff
@@ -0,0 +1,23 @@
...
+import compose from 'ramda/src/compose';
+import CpsAssetPageMain from '../../containers/CpsAssetPageMain';
+import withContexts from '../../containers/PageHandlers/withContexts';
+import withPageWrapper from '../../containers/PageHandlers/withPageWrapper';
+import withError from '../../containers/PageHandlers/withError';
+import withLoading from '../../containers/PageHandlers/withLoading';
+import withData from '../../containers/PageHandlers/withData';
+
+const CpsMapContainer = props => {
+  console.log(`MAP Container`);
```
Comment (karinathomasbbc) [inline src/app/pages/CpsMap/index.jsx]: Should we use the node logger instead of the console (or is this just temporary)?

File: src/app/routes/index.js (hunk 2 above)
Comment (chris-hinds) [reply src/app/routes/index.js]: Ive commented this out here for debugging, but I thin it is a good idea. as if we cannot determine to the asset type we need something to fall back to

File: src/app/pages/CpsMap/index.jsx (hunk 3 above)
Comment (chris-hinds) [reply src/app/pages/CpsMap/index.jsx]: this was just temporary to ensure that the correct pagetype was being rendered. have removed these now.

File: src/app/routes/index.js [hunk 4]
```diff
@@ -13,10 +19,23 @@ import {
   radioAndTvPath,
 } from './regex';
 
+// CPS Asset Mapping to PageType
 const CpsAsset = props => {
-  const type = pathOr('STY', ['pageData', 'metadata', 'type'], props);
-  const Page = type === 'FIX' ? FrontPage : CpsAssetPage;
-  return Page({ ...props, pageType: type });
+  const type = path(['pageData', 'metadata', 'type'], props);
+
```
Comment (karinathomasbbc) [inline src/app/routes/index.js:33]: I thought the logging was quite useful - I had actually added this in another PR (#4967) but it would be much simpler here?

**Review by karinathomasbbc — APPROVED** [review]

File: src/app/routes/index.js (hunk 4 above)
Comment (chris-hinds) [reply src/app/routes/index.js:33]: I like the more centralised approach your PR is taking for the logging. I wonder if react router accepts some form of middleware or something similar we can hook into for logging purposes

File: src/app/pages/Article/index.test.jsx [hunk 5]
```diff
@@ -33,7 +33,7 @@ jest.mock('../PageHandlers/withPageWrapper', () => Component => {
   return PageWrapperContainer;
 });
 
-jest.mock('../PageHandlers/withLoading', () => Component => {
+jest.mock('../../containers/PageHandlers/withLoading', () => Component => {
```
Comment (andrewscfc) [inline src/app/pages/Article/index.test.jsx:36]: This repeated change makes me wonder whether, `PageHandlers` should also be moved to a top level directory in `app` as well? Feels a bit messy to drill out of pages and into containers somehow? 

Also, was this change done by an automated refactoring tool, just wondering if any path changes could have been missed?

Comment (andrewscfc) [reply src/app/pages/Article/index.test.jsx:36]: Or better yet, maybe move `PageHandlers` into `pages`, would actually reduce the amount of changes in this PR.

Comment (chris-hinds) [reply src/app/pages/Article/index.test.jsx:36]: I was thinking about moving the page handlers too. Just wasn't 100% sure, but if you think its a good idea I am up for it.

Might be worth doing it in a different PR as to not make this one any bigger. thoughts?

File: src/app/routes/index.js [hunk 6]
```diff
@@ -13,10 +19,23 @@ import {
...
+  switch (type) {
+    case 'STY':
+      return CpsSty({ ...props, pageType: type });
+    case 'PGL':
+      return CpsPgl({ ...props, pageType: type });
+    case 'MAP':
+      return CpsMap({ ...props, pageType: type });
+    case 'FIX': // TODO: Create FIX Page if required
+      return FrontPage({ ...props, pageType: type });
```
Comment (simonsinclair) [inline src/app/routes/index.js]: As an aside, do you think it'd make sense to maintain a common module in which we export a list of page type constants to aid readability and reduce the chance of fragmentation? It could also be used here: https://github.com/bbc/simorgh/blob/latest/src/app/routes/getInitialData/utils/getPreprocessorRules/index.js#L8-L14.

**Review by simonsinclair — COMMENTED** [review]
Nice work, @hindsc52.
I was thinking, should `PageHandlers` exist within `pages` too. But, I prefer this/your approach, because it's crystal clear what's a page (because it's in the pages directory) and what's not.

File: src/app/routes/index.js (hunk 6 above)
Comment (chris-hinds) [reply src/app/routes/index.js]: ohh nice, I did not know we had those, will update this PR. Thanks @simonsinclair

Comment (chris-hinds) [reply src/app/routes/index.js]: I think a new PR to move pageHandlers out of containers and put them at the same dir level is good idea. Similar to what Andrew mentioned earlier.

Comment (simonsinclair) [reply src/app/routes/index.js]: I was making a case _against_ moving them, but can see both sides of the argument. 😄

File: src/app/routes/pageTypes.js [hunk 7]
```diff
@@ -0,0 +1,7 @@
+export const ARTICLE_PAGE = 'article';
```
Comment (karinathomasbbc) [inline src/app/routes/pageTypes.js:1]: Nice

**Review by karinathomasbbc — APPROVED** [review]

File: src/app/routes/index.js (hunk 6 above)
Comment (chris-hinds) [reply src/app/routes/index.js]: made that change @simonsinclair

File: src/app/pages/Article/index.test.jsx (hunk 5 above)
Comment (andrewscfc) [reply src/app/pages/Article/index.test.jsx:36]: I was wrong to say it would reduce the changes but it would be a lot less changes and lot more straight file moves without any paths changing, i.e. this line would no long need to change. 

I'd perhaps think about doing it in this PR in case any path changes were missed in the refactor, getting that sorted before merging would make it less likely we have any regressions. It's not a strong opinion though, maybe a follow-up PR would allow us to discuss the move's merits seperately re @simonsinclair 's point.

Comment (chris-hinds) [reply src/app/pages/Article/index.test.jsx:36]: I would prefer a follow up PR and more discussion as keeping this new dir strictly about page types will be very useful I think.

**Review by simonsinclair — APPROVED** [review]
Sweet. 👍

File: src/app/pages/Article/index.test.jsx (hunk 5 above)
Comment (andrewscfc) [reply src/app/pages/Article/index.test.jsx:36]: Cool, how do we go about the follow-up, just make the PR or raise an issue etc?

Comment (chris-hinds) [reply src/app/pages/Article/index.test.jsx:36]: can just raise an issue and pick it up.

**Review by ryanmccombe — APPROVED** [review]
Looks great 👍  - thanks for the heads up - this had a lot fewer changes to our page than I was expecting :)

File: src/app/routes/index.js [hunk 8]
```diff
@@ -1,10 +1,16 @@
...
+import path from 'ramda/src/path';
 import getInitialData from './getInitialData';
+
+// Pages
+import Article from '../pages/Article';
+import FrontPage from '../pages/FrontPage';
+import RadioPage from '../pages/RadioPage';
+import CpsMap from '../pages/CpsMap';
+import CpsSty from '../pages/CpsSty';
+import CpsPgl from '../pages/CpsPgl';
```
Comment (jamesdonoh) [inline src/app/routes/index.js:10]: I know we can't do anything about CPS's cryptic 3-letter asset types at the lowest level, but we aren't obliged to  replicate them in our component naming, i.e. if these were called `CpsMediaAssetPage`, `CpsPhotoGallery` etc. might that be easier for newcomers to make sense of without sacrificing anything?

Comment (chris-hinds) [reply src/app/routes/index.js:10]: very true, happy to make this change. Are you thinking the files names should be changed too or just the import names?

Comment (chris-hinds) [reply src/app/routes/index.js:10]: As this is already in ready for test, I'll raise a new PR with naming changes and discuss it with the team.

**Review by andrewscfc — APPROVED** [review]
Raised an issue to consider `PageHandlers` https://github.com/bbc/simorgh/issues/5063 otherwise looks great

**Comment by paruchurisilpa** [comment]
Did regression on few page types and LGTM.
