### PR TITLE
Cypress fix - Consent banner

### LINKED ISSUE #3465: Failing Consent banner Cypress test
**Describe the bug**
Failing consent banner tests
Screenshot 2019-08-30 at 10 29 08

Screenshot 2019-08-30 at 10 30 22

**To Reproduce**

1. `CYPRESS_SMOKE=false npm run test:e2e`
2. See error

**Expected behavior**
No such error

**Screenshots**
Screenshots above

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by sareh**
Resolves #3465

**Overall change:** Be more specific when selecting elements (this was failing for Thai since the text for `Accept` was also in the Heading text of the component, so Cypress was trying to click on the heading instead of the button).

**Code changes:**

- Change to use frontPage for Thai for smoke tests instead of Igbo (since Thai has more complexity in its page config than Igbo does)
- Change to run `specialFeatures/cookieBanner` tests for Thai instead of Persian as the example WS service
- Specifically find the button / link elements for the getCookieBannerAccept/Reject
---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by dr3 — APPROVED** [review]

File: cypress/support/config/services.js [hunk 1]
```diff
@@ -388,7 +388,7 @@ module.exports = {
             : '/igbo/articles/cxvxrj8tvppo',
         smoke: true,
       },
-      frontPage: { path: '/igbo', smoke: true },
+      frontPage: { path: '/igbo', smoke: false },
```
Comment (EinsteinCarrey) [inline cypress/support/config/services.js]: 🤔 Why are we turning smoke off for `igbo`?

Comment (benjaminhobbs) [reply cypress/support/config/services.js]: Because we're turning it on for Thai :) It's already off for Yoruba and Pidgin, we only need the most complex front page smoke tested.

**Review by jamesbhobbs — APPROVED** [review]

**Review by EinsteinNjoroge — APPROVED** [review]
