### PR TITLE
Fix for AV UX duration

### LINKED ISSUE #4654: AV duration needs to match SMP and designs
**Describe the bug**
At the moment, a duration of X minutes XX seconds is displayed as M:SS. It should be displayed as MM:SS, with "0" in use when it is a single digit of minutes.

**To Reproduce**

1. Go to https://www.test.bbc.co.uk/news/articles/c3wmq4d1y3wo
2. Scroll to any of the video or audio items
3. See duration displayed as M:SS, e.g. 2.42
4. Click play, see SMP's duration displayed MM:SS, e.g. 02.42

**Expected behaviour**
Duration on the placeholder should match SMP and our designs. It should be in MM:SS format.

**Screenshots**
Current duration:
image
SMP duration:
image
Duration on designs:
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by RayNjeri**
Resolves  #4654

**Overall change:** _Fixes current AV duration to match SMP and Designs while maintaining front-pages designs._

**Code changes:**

- _Adds a conditional to the `formatDuration` function._

Screenshot 2019-11-21 at 12 39 27 PM

Screenshot 2019-11-21 at 12 38 43 PM

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

### CODE REVIEW

File: src/app/lib/utilities/formatDuration/index.js [hunk 1]
```diff
@@ -1,16 +1,16 @@
 /* eslint-disable prefer-template */
-
 const lpad = s => s.toString().padStart(2, '0');
-
 // the duration argument should be a moment duration!
-const formatDuration = (duration, separator = ':') => {
+const formatDuration = (duration, separator = ':', articlesPage = false) => {
```
Comment (EinsteinNjoroge) [inline src/app/lib/utilities/formatDuration/index.js]: You might want to change the `params` type to an `object` instead of having multiple optional parameters.

**Review by rhenshaw56 — APPROVED** [review]

**Review by oluoluoxenfree — APPROVED** [review]

File: src/app/lib/utilities/formatDuration/index.js (hunk 1 above)
Comment (RayNjeri) [reply src/app/lib/utilities/formatDuration/index.js]: Refactored as suggested

File: src/app/containers/StoryPromo/LinkContents/index.jsx [hunk 2]
```diff
@@ -38,7 +38,7 @@ const LinkContents = ({ item }) => {
 
   // hilariously, this works. according to moment, null seconds == 0 seconds!
   const duration = moment.duration(rawDuration, 'seconds');
-  const durationString = formatDuration(duration, ',');
+  const durationString = formatDuration({ duration });
```
Comment (rhenshaw56) [inline src/app/containers/StoryPromo/LinkContents/index.jsx]: I think I prefered `formatDuration` not taking in an object bcos now you'd have to change all it's usages which might lead to missing some passed arguments. the separator is not passed in here as it was before and the snapshots changed as well

**Review by rhenshaw56 — CHANGES_REQUESTED** [review]

File: src/app/containers/StoryPromo/LinkContents/index.jsx (hunk 2 above)
Comment (RayNjeri) [reply src/app/containers/StoryPromo/LinkContents/index.jsx]: Updated

File: src/app/lib/utilities/formatDuration/index.js (hunk 1 above)
Comment (RayNjeri) [reply src/app/lib/utilities/formatDuration/index.js]: This introduced a lot of complexity to the PR than need be so had to revert back

**Review by rhenshaw56 — APPROVED** [review]

File: src/app/lib/utilities/formatDuration/index.js (hunk 1 above)
Comment (EinsteinNjoroge) [reply src/app/lib/utilities/formatDuration/index.js]: Looks good now, thanks for updating.
https://github.com/bbc/simorgh/blob/9dd2671597a34621bb385850e3e859342b340b00/src/app/lib/utilities/formatDuration/index.js#L4-L8

**Review by EinsteinNjoroge — APPROVED** [review]

File: src/app/containers/StoryPromo/LinkContents/index.jsx [hunk 3]
```diff
@@ -37,8 +37,9 @@ const LinkContents = ({ item }) => {
   const rawDuration = pathOr(null, ['media', 'versions', 0, 'duration'], item);
 
   // hilariously, this works. according to moment, null seconds == 0 seconds!
```
Comment (jamesdonoh) [inline src/app/containers/StoryPromo/LinkContents/index.jsx]: Does this comment make sense/provide any value to anyone else? I reckon we should delete it.

File: src/app/containers/MediaPlayer/index.jsx [hunk 4]
```diff
@@ -64,10 +64,11 @@ const MediaPlayerContainer = ({
   );
   const duration = moment.duration(rawDuration, 'seconds');
 
+  const separator = ',';
   const mediaInfo = {
     title: path(['model', 'blocks', 0, 'model', 'title'], aresMediaBlock),
-    duration: formatDuration(duration),
-    durationSpoken: formatDuration(duration, ','),
+    duration: formatDuration({ duration, isArticlesPage: true }),
```
Comment (jamesdonoh) [inline src/app/containers/MediaPlayer/index.jsx]: Sorry, this doesn't seem ideal to me. Firstly `MediaPlayer` could be used on other pages (like media pages) not just articles, so the prop name is misleading. It also makes the logic in https://github.com/bbc/simorgh/pull/4741/files#diff-1e66e0f443ec8f1573b72f18496fb023R13-R20 harder to follow

**Review by jamesdonoh — DISMISSED** [review]

File: src/app/containers/MediaPlayer/index.jsx (hunk 4 above)
Comment (jamesdonoh) [reply src/app/containers/MediaPlayer/index.jsx]: To keep `formatDuration` a simple formatter function free of business rules, perhaps call the boolean prop `zeroPadMinutes` which the caller can set to true of they want that behaviour? Also that might allow us to make https://github.com/bbc/simorgh/pull/4741/files#diff-1e66e0f443ec8f1573b72f18496fb023R13-R20 more readable.

File: src/app/containers/StoryPromo/LinkContents/index.jsx (hunk 3 above)
Comment (RayNjeri) [reply src/app/containers/StoryPromo/LinkContents/index.jsx]: Deleted.

File: src/app/containers/MediaPlayer/index.jsx (hunk 4 above)
Comment (RayNjeri) [reply src/app/containers/MediaPlayer/index.jsx]: Refactored, let me know if its still not clear

Comment (jamesdonoh) [reply src/app/containers/MediaPlayer/index.jsx]: Looks good, but I can't see any test coverage for `padMinutes`?

Comment (RayNjeri) [reply src/app/containers/MediaPlayer/index.jsx]: on it

Comment (RayNjeri) [reply src/app/containers/MediaPlayer/index.jsx]: done

**Review by j-pendlebury — APPROVED** [review]
LGTM

**Comment by RayNjeri** [comment]
Checked with UX, and they are happy to have this merged in CC: @lizcameron
