### PR TITLE
Use system colours when using high contrast on PC

### LINKED ISSUE #10051: Pagination SVGs not visible when using high contrast mode on PC
**Describe the bug**
When using high contrast mode on PC, SVGs don't retain the colour of the numbers in the pagination component, meaning they aren't visible against the background.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'https://www.test.bbc.com/pidgin/new_topics/c1gdqg448w1t'
2. Turn on High Contrast Mode on IE11/Edge
3. Scroll down to the pagination component

**Expected behaviour**
Arrow SVGs should retain the same colour as the numbers in the pagination component.

**Desktop (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Checklist**
- [x] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**
These SVGs likely need the font color and fill=currentColor CSS properties.

### PR DESCRIPTION
**Pull request by nicola-d-bbc**
Resolves [#10051](https://github.com/bbc/simorgh/issues/10051)

**Overall change:**
Uses system colours instead of current colour for SVGs when using high contrast on PC.

**Code changes:**

- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project
- [x] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by pvaliani — APPROVED** [review]

**Review by ryanmccombe — APPROVED** [review]
👍

File: src/app/pages/TopicPage/Pagination/index.jsx [hunk 1]
```diff
@@ -90,6 +93,12 @@ const Block = styled.li`
 
 const EllipsisBlock = styled(Block)`
   color: ${C_PHILIPPINE_GREY};
+  svg {
+    @media screen and (forced-colors: active) {
+      fill: canvasText;
+    }
+    fill: currentColor;
```
Comment (greenc05) [inline src/app/pages/TopicPage/Pagination/index.jsx]: Don't think we need this line
