### PR TITLE
Rmv status check tests and overwrites the visit() command to test there's not Mozart fallback

### LINKED ISSUE #2122: Remove redundant test and revise poor Mozart fallback test coverage
**Describe the bug**
Following the merge of https://github.com/bbc/simorgh/pull/2087 @PriyaKR noticed that the cypress/integration/statusSpec.js had issues in that one was redundant (covered by the other PR) and that the test for the Mozart fallback was only being run against one URL.

**To Reproduce**
Run E2E tests against any env.

**Expected behavior**
Remove redundant test.

Remove the custom check on only 1 URL for the Mozart fallback and instead change the visit() Cypress Command to always check for the fallback header.

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

**Smartphone (please complete the following information):**
n/a

**Additional context**
Probably important to test the revised visit() Command against a real mozart fallback URL. I do not know of a URL we can do this against. But once we have it it's a really easy and really important manual test.

### PR DESCRIPTION
**Pull request by jamesbhobbs**
Resolves #2122

**Overall change:** Removes redundant tests, adds overwrite to default Cypress visit() command to always check for the Mozart header.

**Code changes:**

- All described above

---

- [x] I have assigned myself to this PR and the corresponding issues
~~- [ ] Tests added for new features~~
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

File: cypress/integration/statusSpec.js [hunk 1]
```diff
@@ -1,17 +1,12 @@
 import config from '../support/config';
-import {
-  testContentTypeContains,
-  mozartFallbackStatus,
-} from '../support/metaTestHelper';
-
-describe('Service worker', () => {
```
Comment (jamesbhobbs) [inline cypress/integration/statusSpec.js:7]: this is already tested in sw.js

**Review by chris-hinds — APPROVED** [review]

**Review by jroebu14 — APPROVED** [review]
I'm not too familiar with Cypress but this looks ok to me

**Comment by jamesbhobbs** [comment]
This has now been manually tested by @jamesbrumpton and I.
