### PR TITLE
Fix storybook console warnings.

### LINKED ISSUE #2711: Multiple console errors when viewing components in Storybook
**Describe the bug**
There are multiple console errors when viewing components in Storybook, found when testing the `latest` branch.

**To Reproduce**

1. Go to http://localhost:9001/?path=/story/articlefigure-amp--with-a-caption
2. View the console errors

**Expected behavior**
No console errors received

**Screenshots**
image

**Desktop (please complete the following information):**

- OS: OS SX
- Browser Multiple

### PR DESCRIPTION
**Pull request by Bopchy**
Resolves #2711 

**Overall change:** _Fix multiple console warnings on Storybook._

**Code changes:**

- _Fix prop warnings for required but not provided props._
- _Fix ArticleMain not rendering on Storybook._
---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Comment by Bopchy** [comment]
Added `width: imageWidth` to fix the `width is required and not provided` prop warning - however, I need to figure out why `generateFixtureData.defaultProps` are not being used

**Comment by ghost** [comment]
`generateFixtureData.defaultProps` is not being used because `generateFixtureData` is used as a normal function `generateFixtureData()` instead of jsx `<GenerateFixtureData ...>`.

**Comment by Bopchy** [comment]
Thanks @sadickisaac. Don't know why I wasn't seeing that before

**Comment by Bopchy** [comment]
This doesn't fix the AMP related console errors

Screenshot 2019-08-01 at 16 34 42

**Comment by ghost** [comment]
Have you considered having `id's` on the generated blocks outside of the components (fixtureData)? By doing this you would avoid introducing `uuid` dependancy on the components i.e `Block` and `renderParagraph`

**Comment by ghost** [comment]
Screenshot 2019-08-01 at 17 50 49

on [ArticleFigure](http://localhost.bbc.com:9001/?path=/story/articlefigure--with-a-caption)

**Review by ghost — CHANGES_REQUESTED** [review]
`ArticleMain` still not rendering. 
Screenshot 2019-08-01 at 17 59 11

**Comment by chris-hinds** [comment]
ArticleMain is rendering for me on localhost. I checked out this branch, ran `npm install` & `npm run storybook`

image

**Comment by ghost** [comment]
@hindsc52 for some strange reason its not working for me on localhost. @Bopchy you can ignore https://github.com/bbc/simorgh/pull/2800#pullrequestreview-269687748 I will try to see if i can get it working.

**Comment by chris-hinds** [comment]
> @hindsc52 for some strange reason its not working for me on localhost. @Bopchy you can ignore [#2800 (review)](https://github.com/bbc/simorgh/pull/2800#pullrequestreview-269687748) I will try to see if i can get it working.

Did a fresh clone of simorgh and a checkout of this branch just to be sure and it is working. Hopefully you find the issue your end.

**Comment by ghost** [comment]
@hindsc52 I did a fresh clone as well, `ArticleMain` now renders.

File: src/app/containers/Blocks/index.jsx [hunk 1]
```diff
@@ -19,7 +20,7 @@ const Blocks = ({ blocks, componentsToRender }) =>
 
     return (
       <Block
-        key={id}
+        key={id || uuid()}
```
Comment (rhenshaw56) [inline src/app/containers/Blocks/index.jsx]: this will generate a new key after every render, which isn't performance friendly and besides `id` is already a uuid because it's generated [here](https://github.com/bbc/simorgh/blob/latest/src/app/lib/utilities/preprocessor/rules/addIdsToBlocks.js#L12), thing is the fixture data blocks used in storybook don't go through the pre-processor rules,  hence `id`'s don't get added, maybe modifying the fixture data to make use of uuids instead of adding it here

File: src/app/containers/Caption/index.jsx [hunk 2]
```diff
@@ -30,7 +31,7 @@ const chooseOffscreenText = (
 };
 const renderParagraph = paragraphBlock => {
   return (
-    <p key={pathOr(null, ['0', 'id'], paragraphBlock)}>
+    <p key={pathOr(uuid(), ['0', 'id'], paragraphBlock)}>
```
Comment (rhenshaw56) [inline src/app/containers/Caption/index.jsx]: same here, the `id` is actually a `uuid` already

**Review by rhenshaw56 — CHANGES_REQUESTED** [review]

**Comment by Bopchy** [comment]
Now assigning ids - without using uuid(); to the fixture data blocks as suggested.

File: src/app/models/blocks/index.js [hunk 3]
```diff
@@ -3,7 +3,7 @@ export const imageType = 'image';
 export const videoType = 'video';
 export const rawImageType = 'rawImage';
 
-export const singleTextBlock = text => ({
+export const singleTextBlock = (text, id = null) => ({
```
Comment (rhenshaw56) [inline src/app/models/blocks/index.js:6]: a bit concerned about the `id's` appearing as null in snaps, perhaps we could set it to `"testId"` but looks good generally

**Review by rhenshaw56 — APPROVED** [review]

**Comment by j-pendlebury** [comment]
image

I'm still seeing console errors on Article Main after checking out this branch and re-installing all the dependencies.

**Review by RayNjeri — APPROVED** [review]

**Review by 12 — COMMENTED** [review]
Great work fixing the `ArticleMain` container. I can see it now works in Storybook and Chromaticqa. I'm still getting console errors in `ArticleMain` however, the same ones as @jblaut.

**Review by dr3 — APPROVED** [review]

**Review by dr3 — CHANGES_REQUESTED** [review]
https://github.com/bbc/simorgh/pull/2800#issuecomment-518603495

**Comment by Bopchy** [comment]
The `ArticleMain` error should be gone now

File: src/app/models/blocks/index.js (hunk 3 above)
Comment (Bopchy) [reply src/app/models/blocks/index.js:6]: Now using `testId` as id in src/app/models/blocks/index.test.js

**Review by jamesdonoh — APPROVED** [review]

**Review by 12 — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by dr3 — APPROVED** [review]

**Comment by staylos92** [comment]
This is not the kind of thing which needs testing by a tester as all they would be doing is checking if the errors have gone, which should be part of the developement process anyway. Assuming that's the case then feel free to merge it.
