### PR TITLE
Fixed react warnings

### LINKED ISSUE #2763: Fix React warnings in src/app/containers/FrontPage/index.test.jsx
**Describe the bug**
There are React warnings in unit tests.

**To Reproduce**

1. Go to simorgh in terminal
2. Run npm run test:unit
3. Observe React warnings:

```
    console.error src/testHelpers/setupTests.js:30
      Warning: Failed prop type: Invalid prop `error` of type `string` supplied to `ErrorContainer`, expected `boolean`.
          in ErrorContainer

```

**Expected behaviour**

No React warning for test suite.

**Testing notes**

No testing required.

### PR DESCRIPTION
**Pull request by hotinglok**
Resolves #2763 

**Overall change:** 
Fixed react warnings.

**Code changes:**
- Changed ```error``` props into booleans.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by thekp — APPROVED** [review]

File: src/app/containers/FrontPage/index.jsx [hunk 1]
```diff
@@ -10,9 +10,10 @@ import withLoading from '../PageHandlers/withLoading';
 import withError from '../PageHandlers/withError';
 import withData from '../PageHandlers/withData';
 
-const FrontPageContainer = ({ pageData }) => (
-  <FrontPageMain frontPageData={pageData} />
-);
+const FrontPageContainer = props => {
+  const { pageData } = props;
```
Comment (dr3) [inline src/app/containers/FrontPage/index.jsx]: This file can be reverted back :)

**Review by dr3 — APPROVED** [review]

**Comment by dr3** [comment]
Doesnt need testing

**Comment by hotinglok** [comment]
This only affects test, can be merged without manual testing.
