### PR TITLE
Audio Placeholder - Respond to Edge High Contrast Mode

### LINKED ISSUE #9065: Audio Placeholder not visible in Edge on Windows when high contrast theme is used
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by ryanmccombe**
Resolves https://github.com/bbc/simorgh/issues/9065

**Overall change:**
_Update audio placeholder._

**Code changes:**

- Add ms media query to change colour of loader based on high contrast mode
- Add default stroke colour for no-css scenarios

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [ ] I have assigned this PR to the Simorgh project

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

File: src/app/components/MediaPlayer/AudioLoader/index.jsx [hunk 1]
```diff
@@ -32,7 +32,12 @@ const spin = keyframes`
 const Spinner = styled.svg`
   width: 64px;
   height: 64px;
+
   stroke: currentColor;
+  @media screen and (-ms-high-contrast: active) {
```
Comment (andrewscfc) [inline src/app/components/MediaPlayer/AudioLoader/index.jsx:37]: Just had a look at the newer standards compliant replacement for `ms-high-contrast`: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/forced-colors 

Just sometimes emotion translates these styles back to browser specific ones but can't see a mention of `force-colors` in the emotion codebase.

File: src/app/components/MediaPlayer/AudioLoader/index.jsx [hunk 2]
```diff
@@ -32,7 +32,12 @@ const spin = keyframes`
...
+    stroke: windowText;
```
Comment (andrewscfc) [inline src/app/components/MediaPlayer/AudioLoader/index.jsx:38]: I can't actually find any clear docs for `windowText` what color is this, does it come from the user's preferences?

**Review by andrewscfc — APPROVED** [review]
Looks good, just one or two questions for my understanding

File: src/app/components/MediaPlayer/AudioLoader/index.jsx (hunk 2 above)
Comment (ryanmccombe) [reply src/app/components/MediaPlayer/AudioLoader/index.jsx:38]: I think it's just a MS specific one that gets injected - duplicated this from the BBC logo CSS, which seems to work like how we want

File: src/app/components/MediaPlayer/AudioLoader/index.jsx (hunk 1 above)
Comment (ryanmccombe) [reply src/app/components/MediaPlayer/AudioLoader/index.jsx:37]: Not supported in IE it seems - this media query is supported by both IE and Edge

File: src/app/components/MediaPlayer/AudioLoader/index.jsx [hunk 3]
```diff
@@ -49,6 +54,7 @@ const AudioLoader = ({ children, isLoading }) => (
           height="38"
           viewBox="0 0 38 38"
           focusable="false"
+          stroke="black"
```
Comment (greenc05) [inline src/app/components/MediaPlayer/AudioLoader/index.jsx:57]: Is this for no CSS?

Comment (greenc05) [reply src/app/components/MediaPlayer/AudioLoader/index.jsx:57]: Guess that means it will always have a black stroke? Or will the stroke above with current colour take presidence when you have CSS? Just wondering what it will look like in Firefox when the user changes their colour preferences...

Comment (ryanmccombe) [reply src/app/components/MediaPlayer/AudioLoader/index.jsx:57]: > Is this for no CSS?

Yep :)

**Review by jroebu14 — APPROVED** [review]

File: src/app/components/MediaPlayer/AudioLoader/index.jsx (hunk 3 above)
Comment (ryanmccombe) [reply src/app/components/MediaPlayer/AudioLoader/index.jsx:57]: > Guess that means it will always have a black stroke? Or will the stroke above with current colour take presidence when you have CSS? Just wondering what it will look like in Firefox when the user changes their colour preferences...

CSS overrides the attribute, so with CSS enabled the spinner will look the same as it does now
