### PR TITLE
Fix cypress tests on live

### LINKED ISSUE #1433: Fix Live cypress errors
**Describe the bug**
There are live cypress test errors due to moving data to `bbc.com`

**To Reproduce**

1. Run the live cypress tests

**Expected behavior**
They run what they can, and pass

**Screenshots**
```
routingSpec.js

1) Routing tests accepts different service params:

     CypressError: cy.visit() failed trying to load:

https://simorgh.api.bbci.co.uk/news/articles/c85pqyj5m2ko

The response we received from your web server was:

  > 404: Not Found
```
```
Running: persianBodySpec.js... 

1) Article Body Tests "before all" hook for "should render an H1, which contains/displays a styled headline":

   CypressError: cy.visit() failed trying to load:

https://simorgh.api.bbci.co.uk/persian/articles/c5ml5n7w4m3o

The response we received from your web server was:

  > 502: Bad Gateway

```

**Additional context**
The first error is because the asset used in `routingSpec.js` wasnt made to be env dynamic and is trying to use test assets on live

The second error is because persian isnt routed for data via bbc.com/articles/*.json

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

### PR DESCRIPTION
**Pull request by dr3**
Resolves #1433

**Overall change:** Fixes issues currently on live

**Code changes:**

- Stops persian tests from running on live
- Removes routing test that uses wrong config and adds same tests to existing file

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Tests added for new features
- [ ] Test engineer approval
- [ ] I have followed [the merging checklist](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/MERGE_PROCESS.md) and this is ready to merge.

### CODE REVIEW

File: cypress/support/skipLiveDescribe.js [hunk 1]
```diff
@@ -0,0 +1,7 @@
+const skipLiveDescribe = (name, func) => {
```
Comment (ChrisBAshton) [inline cypress/support/skipLiveDescribe.js:4]: Maybe add a comment to this file explaining that this is necessary because Persian isn't live yet. When Persian is live, we can remove this hack.

File: cypress/integration/metaPersianSpec.js [hunk 2]
```diff
@@ -9,12 +10,16 @@ import {
...
 
-describe('Persian Article Meta Tests', () => {
+skipLiveDescribe('Persian Article Meta Tests', () => {
   // eslint-disable-next-line no-undef
   before(() => {
     cy.visit(`/persian/articles/${config.assets.persian}`);
   });
 
+  it('should have the correct lang attribute', () => {
+    cy.get('html').should('have.attr', 'lang', 'fa');
```
Comment (ChrisBAshton) [inline cypress/integration/metaPersianSpec.js:20]: Can we make this config-driven?

I guess it does mean duplicating _exactly_ the same test in two files. But we can then refactor that further later.

File: cypress/support/skipLiveDescribe.js (hunk 1 above)
Comment (dr3) [reply cypress/support/skipLiveDescribe.js:4]: done :)

File: cypress/integration/metaPersianSpec.js (hunk 2 above)
Comment (dr3) [reply cypress/integration/metaPersianSpec.js:20]: There currently isnt really any config place for this to go per service. We have per env config but not per service. I think this should be part of a greater piece of work in https://github.com/bbc/simorgh/issues/1371

Comment (ChrisBAshton) [reply cypress/integration/metaPersianSpec.js:20]: Agreed

**Review by ChrisBAshton — APPROVED** [review]

**Comment by jamesbrumpton** [comment]
Happy for this to be merged once this had been CR'd

**Review by jamesbrumpton — APPROVED** [review]
