### PR TITLE
Reduce number of MAP E2E tests

### LINKED ISSUE #5826: Test / Live E2Es failing - unable to play media.
1. Test E2Es failing
- [x] Disable test E2Es for Gahuza, Urdu, Swahili, Tamil - https://github.com/bbc/simorgh/pull/5817

2. Investigate

*Test* 
-  10 Mar 10:10: 404 errors on Test for Gahuza, Swahili, Igbo, Tamil - something has happened - changes in Mozart / issues with https://polling.test.bbc.co.uk?
- 10 Mar 10:40: Test assets for Gahuza, Swahili, Igbo, Tamil now seem to be OK. Weird.

*Live*
- 10 Mar: Live E2Es failing - Gujarati, Tamil, Igbo, Sinhala

- [x] https://github.com/bbc/simorgh/pull/5828 Increased Cypress timeout for media play to 20 seconds 
- [x] https://github.com/bbc/simorgh/pull/5847 Reduced number of MAP tests running in Test / Live environment & increase timeout to 30 seconds - now restricted to 4 services - pidgin, persian, pashto and gahuza

### PR DESCRIPTION
**Pull request by karinathomasbbc**
**Overall change:** 
E2E tests are taking a long time to run, and fail often, so we need to get them into a more stable state.
We have decided to reduce the number of MAP tests that we run on Test / Live E2Es by ensuring we are covering the essential variations in the media playback:
- CPS video
- CPS audio
- RTL 
- LTR

Eventually we will do the same for TC2 MAPs (but this is dependent on https://github.com/bbc/simorgh/issues/5782)

**Code changes:**
- Comment out test / live URLs for MAP pages which are no longer required (I have taken the decision to comment out rather than delete, for eng X - if you need to easily find a page type for a service, you don't need to go digging in commit history, plus the entry can be uncommented for running locally)

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

### CODE REVIEW

File: cypress/support/config/services.js [hunk 1]
```diff
@@ -2813,8 +2853,12 @@ const genServices = {
       liveRadio: { paths: undefined, smoke: false },
       mediaAssetPage: {
         paths: {
-          live: ['/yoruba/afrika-51116686'], // CPS MAP with video
-          test: ['/yoruba/media-23256797'],
+          live: [
+            // '/yoruba/afrika-51116686'
+          ], // CPS MAP with video
```
Comment (sareh) [inline cypress/support/config/services.js]:
```suggestion
            // '/yoruba/afrika-51116686' // CPS MAP with video
          ],
```

File: cypress/support/config/services.js [hunk 2]
```diff
@@ -39,8 +39,12 @@ const genServices = {
       },
       mediaAssetPage: {
         paths: {
-          live: ['/afaanoromoo/oduu-51248626'],
-          test: ['/afaanoromoo/23149891'],
+          live: [
```
Comment (jroebu14) [inline cypress/support/config/services.js]: beginning to think something like this would be a good idea 🤔one for the future possibly!

```js
      mediaAssetPage: {
        envs: {
          live: {
            paths: ['/afaanoromoo/oduu-51248626'],
            enabled: true,
          },
          test: {
            paths: ['/afaanoromoo/23149891'],
            enabled: false,
          },
          local: {
            paths: ['/afaanoromoo/23149891'],
            enabled: true,
          },
        },
        smoke: false,
      },
```

**Review by RichardPK — COMMENTED** [review]
I wonder if it's worth standardising the MAP path comments across every path, regardless of whether they're being commented out, as well as tidying up the existing comments? Currently we have:

- no comment
- // CPS MAP
- // CPS MAP with video
- // CPS MAP with audio clip
- // CPS MAP with video clip
- // CPS MAP with video clip & related content

**Comment by karinathomasbbc** [comment]
> I wonder if it's worth standardising the MAP path comments across every path, regardless of whether they're being commented out, as well as tidying up the existing comments? Currently we have:
> 
>     * no comment
> 
>     * // CPS MAP
> 
>     * // CPS MAP with video
> 
>     * // CPS MAP with audio clip
> 
>     * // CPS MAP with video clip
> 
>     * // CPS MAP with video clip & related content

Done 👍

File: cypress/support/config/services.js (hunk 2 above)
Comment (karinathomasbbc) [reply cypress/support/config/services.js]: I like that idea - definitely one for a future PR

File: cypress/support/config/services.js [hunk 3]
```diff
@@ -1237,67 +2377,130 @@ const genServices = {
...
-          ],
-          local: [
-            '/nepali/media-23269034', // CPS MAP
-            // '/nepali/multimedia/2016/07/160725_tc2_testmap1', // TC2 MAP
-          ],
+        environments: {
+          live: {
+            paths: [
+              '/nepali/news-51675223', // CPS MAP with video clip
+              // '/nepali/multimedia/2013/08/130806_boudhavideo', // TC2 MAP with video clip
```
Comment (sareh) [inline cypress/support/config/services.js]: Can these comments be removed since you have `enabled: false` on these routes?

Comment (karinathomasbbc) [reply cypress/support/config/services.js]: For some of the services where that environment is enabled, it will still need to remain commented out (there's an AMP validation bug with TC2 MAPs, so tests fail).  I'll update the ones which are disabled.

File: cypress/support/config/services.js (hunk 2 above)
Comment (karinathomasbbc) [reply cypress/support/config/services.js]: I have implemented this now

**Review by RichardPK — APPROVED** [review]
🚢

**Review by sareh — APPROVED** [review]
:+1: Looks great. Thanks for the refactor.
