### PR TITLE
Integrate Index Alsos

### LINKED ISSUE #2752: Integrate index alsos
Blocked on https://github.com/bbc/psammead/issues/1512
WSFRONTPGS-84

Add Index Alsos.
Pull in package created in https://github.com/bbc/psammead/issues/1512
The data for each Index Also is found in the `relatedItems` field of the item in the data.
You should cap the number of Index Alsos at 3.

If the related article is of type "cpsType": "MAP",  with no `mediaType` field
then show a video icon

If the related article is of type `cpsType: "MAP"`, 
and `mediaType: "Video"` then show the video icon

If the related article is of type `cpsType: "MAP"`, 
and `mediaType: "Audio"` then show the audio icon

You will need to add translations for 'Related Content' to the service config - these may be available in the config for the old site (ongoing question)
If there are more than one items of related content, they should be contained within an html list.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

### PR DESCRIPTION
**Pull request by DenisHdz**
Resolves https://github.com/bbc/simorgh/issues/2752

**Overall change:** 
Integrate `Index Alsos` in Simorgh.

**Code changes:**
- Create `IndexAlsos` container
- Add it to the `StoryPromo`
- Add tests

---

- [X] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] This PR requires manual testing

### CODE REVIEW

**Comment by DenisHdz** [comment]
Blocked on https://github.com/bbc/psammead/pull/1832

**Comment by thekp** [comment]
FYI: 
I am bumping all the psammead packages to their latest versions here: https://github.com/bbc/simorgh/pull/3274/files

will your PR cover the changes required to use `story-promo` ?

**Comment by DenisHdz** [comment]
> FYI:
> I am bumping all the psammead packages to their latest versions here: https://github.com/bbc/simorgh/pull/3274/files
> 
> will your PR cover the changes required to use `story-promo` ?

I am bumping in this PR to "@bbc/psammead-story-promo": "^2.4.0".

**Comment by andrew-nowak** [comment]
There seems like a lot of spacing beneath top stories with index alsos

with
Screen Shot 2019-08-21 at 17 23 35

without
Screen Shot 2019-08-21 at 17 24 02

is this expected?

**Comment by DenisHdz** [comment]
> There seems like a lot of spacing beneath top stories with index alsos

My understanding is that there should be a separation of 24px, but as the `StoryPromoLi` has a padding-bottom of 16px, it turns out is 32px at the moment. I will double-check with UX, but we might have to remove the padding-bottom from the `StyledIndexAlsos`.

index-alsos

File: src/app/containers/StoryPromo/IndexAlsos/index.jsx [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+
+    const type = isPGL ? 'photogallery' : media.toLowerCase();
+
+    return type;
+  };
+
+  const IndexAlsosMediaIndicator = (cpsType, mediaType) => {
+    const indexAlsosMediaType = getMediaType(cpsType, mediaType);
+
+    return indexAlsosMediaType ? (
```
Comment (ghost) [inline src/app/containers/StoryPromo/IndexAlsos/index.jsx]:
```jsx
return indexAlsosMediaType && <MediaIndicator 
  service={service} 
  type={indexAlsosMediaType} 
  indexAlsos 
/>
```

**Review by ghost — CHANGES_REQUESTED** [review]

File: src/app/containers/StoryPromo/IndexAlsos/index.jsx [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+            const headline = pathOr(null, ['headlines', 'headline'], item);
+            const url = pathOr(null, ['locators', 'assetUri'], item);
+
+            return (
+              <IndexAlsosLi
+                key={id}
+                script={script}
+                service={service}
+                url={url}
+                mediaIndicator={IndexAlsosMediaIndicator(
```
Comment (ghost) [inline src/app/containers/StoryPromo/IndexAlsos/index.jsx]: Could we store this in a variable and pass it in. Instead of calling the function in both conditions.

File: src/app/containers/StoryPromo/IndexAlsos/index.jsx [hunk 3]
```diff
@@ -0,0 +1,118 @@
...
+                  cpsType,
+                  mediaType,
+                  service,
+                )}
+                mediaType={mediaTranslations[getMediaType(cpsType, mediaType)]}
```
Comment (ghost) [inline src/app/containers/StoryPromo/IndexAlsos/index.jsx]: Same to this.

**Review by ghost — CHANGES_REQUESTED** [review]

**Review by ghost — APPROVED** [review]

**Comment by DenisHdz** [comment]
Blocked on https://github.com/bbc/psammead/pull/1845

**Review by Bopchy — APPROVED** [review]

File: src/app/containers/StoryPromo/IndexAlsos/index.jsx [hunk 4]
```diff
@@ -0,0 +1,130 @@
...
+          type={indexAlsosMediaType}
+          indexAlsos
+        />
+      )
+    );
+  };
+
+  return (
+    <IndexAlsos offScreenText="Related content">
+      {alsoItems.length > 1 ? (
```
Comment (dr3) [inline src/app/containers/StoryPromo/IndexAlsos/index.jsx]: This is alot of duplicated code for `< 1` & `> 1`. Could you maybe do the same logic, but do like
```
const IndexAlsosUlComponent = alsoItems.length > 1 ? IndexAlsosUl : Fragment;
const IndexAlsoComponent = alsoItems.length > 1 ? IndexAlsosLi : IndexAlso;
```
And loop over them the exact same way with `{alsoItems.slice(0, 3).map(item => {`

**Review by dr3 — DISMISSED** [review]

File: src/app/containers/StoryPromo/IndexAlsos/index.jsx [hunk 5]
```diff
@@ -0,0 +1,105 @@
...
+  IndexAlsosLi,
+} from '@bbc/psammead-story-promo/index-alsos';
+import { ServiceContext } from '../../../contexts/ServiceContext';
+
+const IndexAlsosContainer = ({ alsoItems, script, service }) => {
+  const {
+    translations: { media: mediaTranslations },
+  } = useContext(ServiceContext);
+
+  const getMediaType = (cpsType, mediaType) => {
```
Comment (andrew-nowak) [inline src/app/containers/StoryPromo/IndexAlsos/index.jsx]: this function can move outside of the container, which will give a (possibly very slight) performance boost - the function only gets defined once in the app, rather than on each render of an `IndexAlsosContainer`

File: src/app/containers/StoryPromo/IndexAlsos/index.jsx [hunk 6]
```diff
@@ -0,0 +1,105 @@
...
+    if (!isPGL && !isMedia) {
+      return null;
+    }
+
+    const type = isPGL ? 'photogallery' : media.toLowerCase();
+
+    return type;
+  };
+
+  const IndexAlsosMediaIndicator = (cpsType, mediaType) => {
```
Comment (andrew-nowak) [inline src/app/containers/StoryPromo/IndexAlsos/index.jsx]: this is a function, not a component, so should start with a lower case character
```suggestion
  const buildIndexAlsosMediaIndicator = (cpsType, mediaType) => {
```

File: src/app/containers/StoryPromo/IndexAlsos/index.jsx [hunk 7]
```diff
@@ -0,0 +1,105 @@
...
+  const IndexAlsoItem = alsoItems.length > 1 ? IndexAlsosLi : IndexAlso;
+
+  return (
+    <IndexAlsos offScreenText="Related content">
+      <IndexAlsosWrapper>
+        {alsoItems.slice(0, 3).map(item => {
+          const { id, cpsType, mediaType } = item;
+          const headline = pathOr(null, ['headlines', 'headline'], item);
+          const url = pathOr(null, ['locators', 'assetUri'], item);
+          const indexAlsoMediaIndicator = IndexAlsosMediaIndicator(
```
Comment (andrew-nowak) [inline src/app/containers/StoryPromo/IndexAlsos/index.jsx]:
```suggestion
          const indexAlsoMediaIndicator = buildIndexAlsosMediaIndicator(
```

File: src/app/containers/StoryPromo/IndexAlsos/index.jsx [hunk 8]
```diff
@@ -0,0 +1,105 @@
...
+    );
+  };
+
+  const IndexAlsosWrapper = alsoItems.length > 1 ? IndexAlsosUl : Fragment;
+  const IndexAlsoItem = alsoItems.length > 1 ? IndexAlsosLi : IndexAlso;
+
+  return (
+    <IndexAlsos offScreenText="Related content">
+      <IndexAlsosWrapper>
+        {alsoItems.slice(0, 3).map(item => {
```
Comment (andrew-nowak) [inline src/app/containers/StoryPromo/IndexAlsos/index.jsx]: could the `3` get moved into a `const` near the top of the file? Should make it easier to find & change in the future

File: src/app/containers/StoryPromo/IndexAlsos/index.jsx [hunk 9]
```diff
@@ -0,0 +1,105 @@
...
+  }).isRequired,
+  summary: string,
+  timestamp: number,
+  cpsType: string.isRequired,
+  id: string.isRequired,
+  type: string,
+});
+
+IndexAlsosContainer.propTypes = {
+  alsoItems: oneOfType([arrayOf(alsoItemsPropTypes), alsoItemsPropTypes])
```
Comment (andrew-nowak) [inline src/app/containers/StoryPromo/IndexAlsos/index.jsx]: is it really valid to have a single `alsoItem` not be in an array? ares seems to show single `relatedItems` in an array of length 1

File: src/app/containers/StoryPromo/index.test.jsx [hunk 10]
```diff
@@ -382,5 +406,25 @@ describe('StoryPromo Container', () => {
...
+          <WrappedStoryPromo item={indexAlsosItem} topStory />,
+        );
+
+        expect(container.getElementsByTagName('ul')).toHaveLength(1);
+        expect(container.getElementsByTagName('li')).toHaveLength(2);
+      });
+
+      it('should render a related item not contained within a list', () => {
+        const { container } = render(
+          <WrappedStoryPromo item={indexAlsosItem[0]} topStory />,
```
Comment (andrew-nowak) [inline src/app/containers/StoryPromo/index.test.jsx]: ? `indexAlsosItem` isn't an array...

**Review by andrew-nowak — CHANGES_REQUESTED** [review]

File: src/app/containers/StoryPromo/IndexAlsos/index.jsx (hunk 9 above)
Comment (DenisHdz) [reply src/app/containers/StoryPromo/IndexAlsos/index.jsx]: Good spot. It applies to what we talked this morning.

File: src/app/containers/StoryPromo/index.test.jsx (hunk 10 above)
Comment (DenisHdz) [reply src/app/containers/StoryPromo/index.test.jsx]: Same, had to update also this one.

File: scripts/bundleSize.sh [hunk 11]
```diff
@@ -6,7 +6,7 @@
 # - The min value should be 5K less than the smallest service bundle and max should be 5K greater than the largest bundle
 # - Bundle sizes can be viewed by running a production build
 min=511
```
Comment (dr3) [inline scripts/bundleSize.sh]:
```suggestion
min=520
```

Comment (dr3) [reply scripts/bundleSize.sh]: Howcome this PR makes the bundles soooo much bigger?

File: src/app/containers/StoryPromo/IndexAlsos/index.jsx [hunk 12]
```diff
@@ -0,0 +1,102 @@
...
+import MediaIndicator from '@bbc/psammead-media-indicator';
+import {
+  IndexAlsos,
+  IndexAlso,
+  IndexAlsosUl,
+  IndexAlsosLi,
+} from '@bbc/psammead-story-promo/index-alsos';
+import { ServiceContext } from '../../../contexts/ServiceContext';
+
+const NUM_INDEX_ALSOS = 3; // Cap the number of Index Alsos at 3.
```
Comment (dr3) [inline src/app/containers/StoryPromo/IndexAlsos/index.jsx]:
```suggestion
const MAX_NUM_INDEX_ALSOS = 3; // Cap the number of Index Alsos at 3.
```

File: src/app/containers/StoryPromo/IndexAlsos/index.jsx [hunk 13]
```diff
@@ -0,0 +1,102 @@
...
+const getMediaType = (cpsType, mediaType) => {
+  const isPGL = cpsType === 'PGL';
+  const isMedia = cpsType === 'MAP';
+  const media = mediaType || 'Video';
+
+  if (!isPGL && !isMedia) {
+    return null;
+  }
+
+  const type = isPGL ? 'photogallery' : media.toLowerCase();
```
Comment (dr3) [inline src/app/containers/StoryPromo/IndexAlsos/index.jsx]:
```suggestion
  return isPGL ? 'photogallery' : media.toLowerCase();
```

Comment (dr3) [reply src/app/containers/StoryPromo/IndexAlsos/index.jsx]: Need to remove line 26 and 27 too :)

File: src/app/containers/StoryPromo/MediaIndicator/__snapshots__/index.test.jsx.snap [hunk 14]
```diff
@@ -11,6 +11,17 @@ exports[`Story Promo Media Indicator should not render if item media object has
 />
 `;
 
+exports[`Story Promo Media Indicator should render Index Also video indicator correctly 1`] = `
```
Comment (dr3) [inline src/app/containers/StoryPromo/MediaIndicator/__snapshots__/index.test.jsx.snap]: Is this snap reflective of what we want? Perhaps we need a deep snapshot?

**Review by dr3 — COMMENTED** [review]
LGTM, just a couple tweaks, great work :)

File: scripts/bundleSize.sh (hunk 11 above)
Comment (DenisHdz) [reply scripts/bundleSize.sh]: I have no idea 🤷🏻‍♂️

File: src/app/containers/StoryPromo/MediaIndicator/__snapshots__/index.test.jsx.snap (hunk 14 above)
Comment (DenisHdz) [reply src/app/containers/StoryPromo/MediaIndicator/__snapshots__/index.test.jsx.snap]: I replaced it with `shouldMatchSnapshot` and added an assertion test. Let me know if you think that with that is enough :)

**Review by andrew-nowak — APPROVED** [review]

File: scripts/bundleSizeConfig.js [hunk 15]
```diff
@@ -2,5 +2,5 @@ module.exports = {
   // Size limit for all bundles used by each service (K)
   // Keep these +/- 5K and update frequently!
   MIN_SIZE: 511,
-  MAX_SIZE: 544,
+  MAX_SIZE: 555,
```
Comment (dr3) [inline scripts/bundleSizeConfig.js]:
```suggestion
  MAX_SIZE: 552,
```

**Review by dr3 — APPROVED** [review]

**Comment by DenisHdz** [comment]
Blocked on https://github.com/bbc/simorgh/issues/3419

**Comment by jamesbrumpton** [comment]
lgtm
