### PR TITLE
White space below footer fix

### LINKED ISSUE #3613: White space below footer when page contains little content
**Describe the bug**
The footer sits right up underneath the page content, so when a page has little content there is visible white space below the footer.

**To Reproduce**

1. Go to https://www.bbc.com/korean/bbc_korean_radio/liveradio
4. See whitespace below footer

**Expected behavior**
The footer should always sit at the bottom of the page when there is not enough content to fill the page.

**Screenshots**
image

**Testing notes**
Ensure the footer sites at the bottom of the screen and has no white space below when viewing a page with little content i.e. https://www.bbc.com/korean/bbc_korean_radio/liveradio

- [ ] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by oluoluoxenfree**
Resolves #3613

**Overall change:** 
Added `style` tags to implement changes outlined on issue by Andrew.

**Code changes:**
- Three style tags

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [x] This PR requires manual testing

### CODE REVIEW

File: src/server/Document/component.jsx [hunk 1]
```diff
@@ -65,8 +65,16 @@ const Document = ({
...
-        <div id="root" dangerouslySetInnerHTML={{ __html: app }} />
+        <div
+          id="root"
+          // eslint-disable-next-line react/no-danger
+          dangerouslySetInnerHTML={{ __html: app }}
+          style={{
+            minHeight: '100vh',
+            display: 'flex',
+            flexDirection: 'column',
+          }}
```
Comment (andrewscfc) [inline src/server/Document/component.jsx]: I think rather than using the `style` attribute, I think you may want to import `syledComponents` and use a `styled.div`:

```javascript
styled.div`minHeight: '100vh', display: 'flex', flexDirection: 'column'`;
```

That way you are avoiding the use of inline styles as is convention in the codebase

File: src/app/containers/RadioPageMain/index.jsx [hunk 2]
```diff
@@ -37,6 +37,7 @@ const RadioPageMain = ({ pageData }) => {
           group5: 20,
         }}
         enableGelGutters
+        style={{ flexGrow: '1' }}
```
Comment (andrewscfc) [inline src/app/containers/RadioPageMain/index.jsx]: Bit less certain here, but I think you should also use 
```javascript
const StyledGelPageGrid = styled(GelPageGrid)`flexGrow: '1'` 
```
Then replace line 27 with `<StyledGelPageGrid>`

Again to stick with the convention of using styled components

**Review by andrewscfc — COMMENTED** [review]
Being newish to the codebase I'm unsure, but I'd imagine you should be using styled components rather than inline styles to apply these changes.

Also, I'd probably apply `flex-grow` to all the page types in case they end up having a small amount of content or a user has an abnormally large viewport (massively high res monitor!)

**Review by andrewscfc — APPROVED** [review]
LGTM, thanks for changing to `styled-components` :) It may be worth someone who knows the `Article` and `RadioPages` well looking over the snapshot changes to see if anything unexpected has changed. Looks to me there's a lot of changes but just because a style at the root of component tree has changed and bumped all the generated classes.

**Review by rhenshaw56 — APPROVED** [review]

**Comment by andrewscfc** [comment]
@paruchurisilpa we marked this for manual testing because we have changed the layout on ErrorPages, Articles, CPSAssets and Radio Pages, I think we just need to check that:
- They render as before with no changes to the header or footer positioning when they have content that goes beyond the initial viewport
- If possible check the footer has no whitespace below it when these pages have very little content, this may prove difficult though for some page types such as articles
  - You may be able to simulate this by zooming out the browser very far, the footer should still stick to the bottom (I think?)

**Comment by paruchurisilpa** [comment]
Looks good to me..

**Review by jroebu14 — APPROVED** [review]
Looks fine to me. We are going to have to remember to apply this styling to every new page type's `main` element so I think we should either document this or look into refactoring the document component to have this styling in one place and we don't have to think about it again. The former is totally fine for now and the latter would be my preferred option but an improvement for the future.

**Comment by andrewscfc** [comment]
> Looks fine to me. We are going to have to remember to apply this styling to every new page type's `main` element so I think we should either document this or look into refactoring the document component to have this styling in one place and we don't have to think about it again. The former is totally fine for now and the latter would be my preferred option but an improvement for the future.

Annoyingly, the css grid implementation of that pattern doesn't require the `main` have a new declaration, but IE (as always). Where would you suggest documenting @jroebu14? Maybe good fo an opportunistic refactor on the next new page type, perhaps we can do this in ws_stories when we focus on the STY page?

**Comment by jroebu14** [comment]
@andrewscfc possibly document here https://github.com/bbc/simorgh#adding-a-new-page-type ?

That sounds like a plan 👍

**Comment by andrewscfc** [comment]
> @andrewscfc possibly document here https://github.com/bbc/simorgh#adding-a-new-page-type ?
> 
> That sounds like a plan 👍

@jroebu14 added some docs as you suggested

File: README.md [hunk 3]
```diff
@@ -125,6 +125,7 @@ When adding a new page type there are several parts required.
 #### 3) Create a new container for the page type
 
 - Similar to [this](https://github.com/bbc/simorgh/blob/latest/src/app/pages/FrontPage/index.jsx) we require a top level container that will act as the entry point for the page routing. Each page type should have its own container.
+  - The container should have a render a `main` element with a [`flex-grow: 1;` css declaration](https://github.com/bbc/simorgh/blob/8e19f820ec0de4abd18a4d13e62dd5d843a064c0/src/app/containers/ArticleMain/index.jsx#L39), this is to ensure it grows to fill the space betwen the visual header and footer, the [root div](https://github.com/bbc/simorgh/blob/8e19f820ec0de4abd18a4d13e62dd5d843a064c0/src/server/Document/component.jsx#L31) using a [flexbox 'sticky footer' implementation](https://developer.mozilla.org/en-US/docs/Web/CSS/Layout_cookbook/Sticky_footers#Alternate_method).
```
Comment (jroebu14) [inline README.md]:
```suggestion
  - The container should render a top-level `main` element with a [`flex-grow: 1;` css declaration](https://github.com/bbc/simorgh/blob/8e19f820ec0de4abd18a4d13e62dd5d843a064c0/src/app/containers/ArticleMain/index.jsx#L39), this is to ensure it grows to fill the space betwen the visual header and footer, the [root div](https://github.com/bbc/simorgh/blob/8e19f820ec0de4abd18a4d13e62dd5d843a064c0/src/server/Document/component.jsx#L31) using a [flexbox 'sticky footer' implementation](https://developer.mozilla.org/en-US/docs/Web/CSS/Layout_cookbook/Sticky_footers#Alternate_method).
```

**Review by jroebu14 — APPROVED** [review]
Just correcting a typo. Looks great otherwise and thanks for documenting. This will fix our live radio page's layout nicely 🙂
