### PR TITLE
Korean indonesian footer translations

### LINKED ISSUE #3297: Add Footer Translations for Indonesian & Korean
We need to add footer translations for Indonesian and Korean 

Add the translations to the service configs. Translations available on spreadsheet (pinned in ws-media slack channel or WSMEDIA-29)

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by ryanmccombe**
Resolves https://github.com/bbc/simorgh/issues/3297

**Overall change:** Add footer translations for korean and indonesian services

**Code changes:** Add footer translations for korean and indonesian services
---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] This PR requires manual testing

### CODE REVIEW

File: src/app/lib/config/services/korean.js [hunk 1]
```diff
@@ -122,40 +122,32 @@ const service = {
   footer: {
     externalLink: {
       href: 'https://www.bbc.co.uk/help/web/links/',
-      text: 'Read about our approach to external linking.',
+      text: '외부 콘텐츠 링크에 대한 본사 정책 보기',
```
Comment (pjlee11) [inline src/app/lib/config/services/korean.js]:
```suggestion
      text: '외부 콘텐츠 링크에 대한 본사 정책 보기.',
```

It looks like on the other `externalLink.text` values there is a trailing full stop, which would match to the old site https://pal.test.bbc.com/korean

**Review by dr3 — APPROVED** [review]

**Review by rhenshaw56 — APPROVED** [review]

**Review by chris-hinds — APPROVED** [review]

**Review by DemonusPC — APPROVED** [review]
Looks dank to me

**Review by pjlee11 — APPROVED** [review]

**Review by dr3 — APPROVED** [review]
