### PR TITLE
provide privacy banner landmark

### LINKED ISSUE #1707: Landmark for Cookie banner/ Privacy banner
**Describe the bug**
The cookie banner and privacy banner don't have aria landmarks. They should, since they're top-level regions of the page. 

The outer div wrapping these should have a `role="region"` landmark. 

**To Reproduce**

1. Go to an article https://www.bbc.co.uk/news/articles/clldg965yzjo
2. Run the Chrome axe accessibility extension https://chrome.google.com/webstore/detail/axe/lhdoppojpmngadmnindnejefpokejbdd 
3. See error `All page content must be contained by landmarks`

Screen Shot landmark error

**Expected behavior**
There should be no error.

### PR DESCRIPTION
**Pull request by twinlensreflex**
Resolves #1707

**Overall change:** 
Moves ConsentBanner into `role=banner` landmarked container

**Code changes:**
- Moves ConsentBanner into `role=banner` landmarked container
- Updated snapshots

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

File: cypress/integration/frontpageLayoutSpec.js [hunk 1]
```diff
@@ -25,7 +25,10 @@ Object.keys(services).forEach(index => {
         it('should have a visible banner', () => {
           cy.get('header')
             .should('have.lengthOf', 1)
-            .find('a')
+            .find('div[class^="Banner"]')
```
Comment (twinlensreflex) [inline cypress/integration/frontpageLayoutSpec.js:28]: I had to add this because moving the ConsentBanner into this container broke the test because there are now multiple links in the container.

**Review by 12 — APPROVED** [review]

**Review by EinsteinNjoroge — APPROVED** [review]

**Comment by paruchurisilpa** [comment]
Looks good to me..
