### PR TITLE
Fix for full viewport of 375px for potrait images

### LINKED ISSUE #5525: CPS PGL - All images should be full width in viewport below 375px
**Describe the bug**
When visiting a CPS PGL page such as https://www.test.bbc.com/gujarati/india-47512764?renderer_env=live and decreasing the viewport below 375px in width the images do not occupy the fill width of the screen when they should; see expected behaviour for full requirements. ~~Before this breakpoint, we do not have this requirement (Natasha is this correct?)~~

**To Reproduce**
Steps to reproduce the behaviour:

1. Resize your browser window to 375px in width
2. Go to https://www.test.bbc.com/gujarati/india-47512764?renderer_env=live
3. Scroll through the images
4. Observe how they don't take up the full width

**Expected behaviour**
- Below 375px images should occupy the full width of the viewport, this includes Square, Portrait, and 16:9 images
  - There is an exception for images with a width below 375px where they should retain their original width, this is not strictly required to be implemented for this issue though: https://github.com/bbc/simorgh/issues/5525#issuecomment-585863146
- Between 375px -768px -  16:9 images are full width
- At all other breakpoints the images are aligned to the grid:
image
_Revised following @stevencava 's clarifications: https://github.com/bbc/simorgh/issues/5525#issuecomment-585811458_

**Screenshots**
image

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**
Picked up in UX review #5452

### PR DESCRIPTION
**Pull request by rhenshaw56**
Resolves #5525 

**Overall change:** 
- Fix for protrait images not occupying the full width of the viewport below 375px

**N/B:** _This is for just gel group1, portrait Images will still preserve their default grid span of 4 ie ( > 375px)_ 

**Code changes:**
_- Adds grid image span for gel group1 ( ~ 375px)_

---

- [X] I have assigned myself to this PR and the corresponding issues
- [X] I have added labels to this PR for the relevant pod(s) affected by these changes
- [X] I have assigned this PR to the Simorgh project

**Testing:**
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [x] This PR requires manual testing

### CODE REVIEW

File: src/app/containers/ArticleFigure/index.jsx [hunk 1]
```diff
@@ -35,6 +35,7 @@ const ArticleFigure = ({
 }) => {
   const imageSpan = {
     default: '6',
```
Comment (12) [inline src/app/containers/ArticleFigure/index.jsx]: This indicates to me that the `default` prop is not actually doing anything...? Is that correct?

**Review by 12 — APPROVED** [review]
Looks good. Tested locally and appears to be working as expected.

File: src/app/containers/ArticleFigure/index.jsx [hunk 2]
```diff
@@ -35,6 +35,7 @@ const ArticleFigure = ({
...
+    group1: '6',
```
Comment (simonsinclair) [inline src/app/containers/ArticleFigure/index.jsx]: Groups will inherit the `default` value, so setting `group1` to the same value is unnecessary. This change works, because portrait images have a _different_ default value. We should probably apply this rule within the control block on line 47 instead. E.G.:
```js
  if (height > width) {
    ParentWrapper = NestedGridParentSmall;
    ChildWrapper = NestedGridItemChildSmall;
    imageSpan.default = '4';
    imageSpan.group1 = '6';
  }
```

Comment (rhenshaw56) [reply src/app/containers/ArticleFigure/index.jsx]: Great suggestion. Thanks @simonsinclair

**Review by simonsinclair — APPROVED** [review]
👍

**Review by 12 — APPROVED** [review]

**Comment by PriyaKR** [comment]
Looks good the potrait and all images seem to occupy the entire viewport at widths < 375px.
Screen Shot 2020-02-21 at 11 51 56

Tested across browsers and devices only on Samsung galaxy s10(android 10) the images still dont occupy full width tested on BS but on other devices of same viewport as S10 it looks good.

**Comment by PriyaKR** [comment]
May be we should merge it and when on test should look on a real device.
