### PR TITLE
Correct ATI url on .com AMP pages

### LINKED ISSUE #9041: AMP incorrect analytics url for .com
**Describe the bug**
When a user visits a page on .com on AMP, the analytics url is incorrect, always using the GNL variant.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.bbc.com/sport/football/55790817.amp, as a user within the UK
2. Inspect network activity and see that the `s` parameter is a GNL variant, despite being within the UK.

**Expected behaviour**
Expected the `s` parameter to be the PS variant.

**Testing notes**

- [X] This bug fix is expected to need manual testing.

### PR DESCRIPTION
**Pull request by HarryVerhoef**
Resolves #9041

**Overall change:**
Ensures that if a .com page is visited then amp-geo is used to determine location before building the analytics url on amp.

**Code changes:**

- `statsDestination` is a GNL variant if a .com page is visited, and so a switch statement is used to ensure that `getAmpDestination` is called with the correct parameters if `statsDestination` is a GNL variant and the user is on an amp page.

---

- [X] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [X] I have assigned this PR to the Simorgh project

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [X] This PR requires manual testing

### CODE REVIEW

**Comment by andrewscfc** [comment]
I wonder if it might be better to go back to the code where we check what domain we are on and not complete the check if we are on amp? That way we would just send a universal destination into this component and not need the switch statement. We are sort of 'undoing' the logic done elsewhere if that makes sense?

File: src/app/contexts/RequestContext/index.jsx [hunk 1]
```diff
@@ -41,7 +41,7 @@ export const RequestContextProvider = ({
   const env = getEnv(origin);
   const platform = isAmp ? 'amp' : 'canonical';
   const statsDestination = getStatsDestination({
-    isUK,
+    isUk: platform === 'amp' ? true : isUK,
```
Comment (andrewscfc) [inline src/app/contexts/RequestContext/index.jsx]: Thanks for this change @HarryVerhoef 🙂 Perhaps we should add a comment as you suggested here to explain this?

Also, is there anyway we could add a test for this? We could assert that outside the uk on amp the statsdestination defaults to PS?

Comment (HarryVerhoef) [reply src/app/contexts/RequestContext/index.jsx]: Thanks @andrewscfc!
Yeah good ideas, I'll do both now 👍

**Review by andrewscfc — APPROVED** [review]
This looks great @HarryVerhoef could you please raise an issue to refactor our code to move the `statsDestination` out of the requestContext? Happy to help draft it if needed?

**Comment by HarryVerhoef** [comment]
> This looks great @HarryVerhoef could you please raise an issue to refactor our code to move the `statsDestination` out of the requestContext? Happy to help draft it if needed?

Thanks @andrewscfc!
Yeah sure, I'll get started on that issue now 👍

**Review by simonsinclair — APPROVED** [review]
