### PR TITLE
encode x5 and x6 values for ATI

### LINKED ISSUE #6204: Escape values in ATI fields x5 and x6
**Describe the bug**
If the URL of a page or its referrer contains square brackets (such as for marketing tracking), we do not escape them when sending them to ATI.  As custom fields in ATI are wrapped in square brackets when we sent them, this is confusing ATI.

**To Reproduce**
1. Go to https://www.bbc.com/nepali/news-52074214?xtor=AL-73-[partner]-[hamro.patro]-[headline]-[nepali]-[bizdev]-[isapi]
2. Open the console's network tab, and filter on 'a1.'
2. Click the brand image to go to the Nepali Front Page
3. Observe the x6 value sent to ATI is `[https://www.bbc.com/nepali/news-52074214?xtor=AL-73-[partner]-[hamro.patro]-[headline]-[nepali]-[bizdev]-[isapi]]`

**Expected behaviour**
For the x5 and x6 fields, we should URL encode the URLs.
E.g. x6 would become `[https%3A%2F%2Fwww.bbc.com%2Fnepali%2Fnews-52074214%3Fxtor%3DAL-73-%5Bpartner%5D-%5Bhamro.patro%5D-%5Bheadline%5D-%5Bnepali%5D-%5Bbizdev%5D-%5Bisapi%5D]`

**Screenshots**
N/A

**Testing notes**

We should add unit tests for this update.

- [ ] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by itimirichard**
Resolves #6204

**Overall change:**
_URL encode the x5 and x6 values for ATI._

**Code changes:**

- _encoded the canonical values returned from the `getHref` and `getReferrer` functions._
- _decode the value of returned from `getReferrer` for chartbeat so everything stays as is._
- _update tests._

**Additional Info:**
Both ATI and Charbeat use the same `getReferrer` utility function. ~I cannot confirm at the moment whether Chartbeat `virtualReferrer` accepts encoded URLs so~ I have confirmed that the chartbeat `virtualReferrer` should be a non-encoded URL, hence, I am decoding the encoded referrer on the chartbeat side i.e.`containers/ChartbeatAnalytics/utils/index.js`.

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**

- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [x] This PR requires manual testing

### CODE REVIEW

**Review by j-pendlebury — APPROVED** [review]
LGTM 👍

**Review by Bopchy — APPROVED** [review]

File: src/app/containers/ChartbeatAnalytics/utils/index.js [hunk 1]
```diff
@@ -136,7 +136,7 @@ export const getConfig = ({
     sections,
     uid: chartbeatUID,
     title,
-    virtualReferrer: referrer,
+    virtualReferrer: decodeURIComponent(referrer),
```
Comment (thekp) [inline src/app/containers/ChartbeatAnalytics/utils/index.js:139]: I was wondering if we have to add `decodeURIComponent` here since the returned `referrer` value is not encoded?

Comment (itimirichard) [reply src/app/containers/ChartbeatAnalytics/utils/index.js:139]: @thekp the `referrer` value here will be encoded (for canonical) because the `referrer` is returned from the `getReferrer` utility function which encodes the value.

Comment (thekp) [reply src/app/containers/ChartbeatAnalytics/utils/index.js:139]: ah okay

**Review by thekp — APPROVED** [review]

**Comment by amywalkerdev** [comment]
Going to merge this so we can test it properly on the test env

**Comment by PriyaKR** [comment]
On test x5 and x6 looks good.
