### PR TITLE
Fix image and  video captions to use Reith Sans Regular Italic.

### LINKED ISSUE #2207: Image and video captions are not displaying in Reith
**Describe the bug**
In Storybook, when I preview the image and video with a caption, the caption (in both instances) shows Helvetica, not Reith. It should be Reith Sans Regular Italic.

**To Reproduce**
https://bbc.github.io/simorgh/?path=/story/figure--with-a-caption
https://bbc.github.io/simorgh/?path=/story/video-container--video-clip-global-with-guidance-with-caption

**Expected behavior**
It should be Reith Sans Regular Italic.

**Screenshots**
Screen Shot 2019-07-01 at 15 21 27
Screen Shot 2019-07-01 at 15 21 41

**Desktop (please complete the following information):**

- OS: Mac OS Sierra 10.12.6 (16G1918)
- Browser: Chrome 
- Version: 75.0.3770.100

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by RayNjeri**
Signed-off-by: Rachael Njeri <rachael.njeri@andela.com>

Resolves [#2207](https://github.com/bbc/simorgh/issues/2207)

**Overall change:** _Fix simorgh's storybook image and caption to use ReithSans instead of Helvetica ._

**Code changes:**

- _Import the news Service context to enable the appropriate font usage_
 
**Testing notes:**
- _Regression tests across all services_
---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

File: .storybook/config.js [hunk 1]
```diff
@@ -12,8 +13,10 @@ function loadStories() {
 addDecorator(story => (
   /* eslint-disable react/jsx-filename-extension */
   <Fragment>
-    <GlobalStyle />
-    {story()}
+    <ServiceContextProvider service="news">
```
Comment (jamesdonoh) [inline .storybook/config.js]: Will this prevent us from seeing the right typography for Persian captions too?

File: src/app/containers/ArticleFigure/index.jsx [hunk 2]
```diff
@@ -14,10 +14,10 @@ import {
 } from '../../lib/styledGrid';
 
 const renderCopyright = copyright =>
-  copyright ? <Copyright>{copyright}</Copyright> : null;
```
Comment (jamesdonoh) [inline src/app/containers/ArticleFigure/index.jsx:17]: Are this and the following changes required to resolve the issue?

Comment (RayNjeri) [reply src/app/containers/ArticleFigure/index.jsx:17]: Not really, Just noticed i could make those lines much better while investigating the issue. The changes here do not directly affect the issue

File: .storybook/config.js (hunk 1 above)
Comment (RayNjeri) [reply .storybook/config.js]: I believe it shouldn't, But lemmy do a quick test on it.

Comment (dr3) [inline .storybook/config.js]: I dont think service context providers should the set globally (espesh not specifically to news). If we need a `ServiceContextProvider` around a story, it should be done at the story level, or make a new Storybook decorator, like AmpDecorator, that can be added to a single story.

**Review by dr3 — DISMISSED** [review]

File: .storybook/config.js [hunk 3]
```diff
@@ -1,18 +1,26 @@
...
+import { createGlobalStyle } from 'styled-components';
 
 const req = require.context('../src/app', true, /\.stories\.jsx$/);
 
 function loadStories() {
   req.keys().forEach(filename => req(filename));
 }
 
+const styles = Object.keys(fontFaces).reduce(
+  (faces, acc) => fontFaces[faces] + acc,
```
Comment (ghost) [inline .storybook/config.js]:
```suggestion
  (fontStyles, face) => fontFaces[face] +fontStyles,
```

File: src/app/containers/ArticleFigure/index.jsx [hunk 4]
```diff
@@ -103,6 +104,7 @@ ArticleFigure.propTypes = {
   srcset: string,
   width: number.isRequired,
   showCopyright: bool,
+  service: string.isRequired,
```
Comment (ghost) [inline src/app/containers/ArticleFigure/index.jsx]: There is no need to have a `service` prop. This component uses a `Caption` which already gets `service` from `ServiceContext` https://github.com/bbc/simorgh/blob/efe9a3929e017d02a33f7ceac7940c40f465198a/src/app/containers/Caption/index.jsx#L59

File: src/app/containers/ArticleFigure/fixtureData.jsx [hunk 5]
```diff
@@ -166,6 +166,7 @@ const generateFixtureData = ({
         width={width}
         type={type}
         lazyLoad={lazyLoad}
+        service={serviceContextStubNews.service}
```
Comment (ghost) [inline src/app/containers/ArticleFigure/fixtureData.jsx]: This value would have to be dynamic, to allow use switch `Caption` font based on service.

**Review by oluoluoxenfree — APPROVED** [review]

File: .storybook/config.js [hunk 6]
```diff
@@ -1,18 +1,26 @@
...
 function loadStories() {
   req.keys().forEach(filename => req(filename));
 }
 
+const styles = Object.keys(fontFaces).reduce(
+  (fontStyles, face) => fontFaces[face] + fontStyles,
+  '',
+);
+
+const GlobalStyles = createGlobalStyle`${styles}`;
```
Comment (dr3) [inline .storybook/config.js]: This removes the `styledNormalize` and box sizing stuff from https://github.com/bbc/simorgh/blob/latest/src/app/lib/globalStyles/index.jsx which will technically mean css is different between storybook & pages, is that intended?

Could we maybe make https://github.com/bbc/simorgh/blob/latest/src/app/lib/globalStyles/index.jsx reusable? Maybe with
```
const { fonts } = props.fonts ? props : useContext(ServiceContext);
```
Or a better way of writing ^ :P

File: src/app/containers/AudioVideo/index.stories.jsx [hunk 7]
```diff
@@ -10,8 +13,18 @@ import {
   VideoClipGlobalWithoutCaption,
 } from './helpers/fixtureData';
 import AmpDecorator from '../../../../.storybook/helpers/ampDecorator';
+import { ServiceContextProvider } from '../../contexts/ServiceContext';
+import AudioVideoContainer from '.';
 
 storiesOf('Audio Video Container', module)
+  .addDecorator(withKnobs)
+  .addDecorator(dirDecorator)
+  .add('story', ({ service }) => {
```
Comment (ghost) [inline src/app/containers/AudioVideo/index.stories.jsx]: Why do we need this?

**Review by ghost — CHANGES_REQUESTED** [review]

File: src/app/containers/AudioVideo/index.stories.jsx (hunk 7 above)
Comment (RayNjeri) [reply src/app/containers/AudioVideo/index.stories.jsx]: To be able to switch between diff services, unless it is not really necessary?

Comment (ghost) [reply src/app/containers/AudioVideo/index.stories.jsx]: On the storybook I see an empty story. It is not necessary to have it there.
Screenshot 2019-07-18 at 17 32 43

Comment (ghost) [reply src/app/containers/AudioVideo/index.stories.jsx]: You need to update how fixture data is generated

https://github.com/bbc/simorgh/blob/8029cf8284866dc4a6e42b530b61e7b13da4ff9f/src/app/containers/ArticleFigure/fixtureData.jsx#L145-L148

Then create fixture data passing in `service` from `dirDecorator`
https://github.com/bbc/simorgh/blob/8029cf8284866dc4a6e42b530b61e7b13da4ff9f/src/app/containers/ArticleFigure/fixtureData.jsx#L209-L215

I hope this helps
https://github.com/bbc/simorgh/blob/8029cf8284866dc4a6e42b530b61e7b13da4ff9f/src/app/containers/ArticleFigure/index.stories.jsx#L23-L24

**Review by rhenshaw56 — APPROVED** [review]

**Review by twinlensreflex — APPROVED** [review]
looks good to me :D

File: src/app/lib/globalStyles/index.jsx [hunk 8]
```diff
@@ -22,9 +22,11 @@ const GlobalStyleComponent = createGlobalStyle`
...
   `;
 
-const GlobalStyle = () => {
-  const { fonts } = useContext(ServiceContext);
-  return <GlobalStyleComponent fonts={fonts} />;
+// eslint-disable-next-line react/prop-types
+const GlobalStyle = ({ fonts }) => {
+  // eslint-disable-next-line react-hooks/rules-of-hooks
+  const styleFonts = fonts || useContext(ServiceContext).fonts;
+  return <GlobalStyleComponent fonts={styleFonts} />;
```
Comment (jamesdonoh) [inline src/app/lib/globalStyles/index.jsx]: I'm alarmed that we are having to suppress two linter rules just to support this change, esp `rules-of-hooks`. What are the alternatives? Can we refactor to not violate these rules?

**Review by jamesdonoh — CHANGES_REQUESTED** [review]

File: src/app/lib/globalStyles/index.jsx [hunk 9]
```diff
@@ -22,9 +22,10 @@ const GlobalStyleComponent = createGlobalStyle`
     ${({ fonts }) => fonts && createFontStyles(fonts)}
   `;
 
-const GlobalStyle = () => {
-  const { fonts } = useContext(ServiceContext);
-  return <GlobalStyleComponent fonts={fonts} />;
+// eslint-disable-next-line react/prop-types
+const GlobalStyle = ({ fonts }) => {
+  const styleFonts = useContext(ServiceContext).fonts;
```
Comment (12) [inline src/app/lib/globalStyles/index.jsx:27]:
```suggestion
  const { fonts: styleFonts } = useContext(ServiceContext);
```

File: src/app/lib/globalStyles/index.jsx [hunk 10]
```diff
@@ -22,9 +22,10 @@ const GlobalStyleComponent = createGlobalStyle`
     ${({ fonts }) => fonts && createFontStyles(fonts)}
   `;
 
-const GlobalStyle = () => {
-  const { fonts } = useContext(ServiceContext);
-  return <GlobalStyleComponent fonts={fonts} />;
+// eslint-disable-next-line react/prop-types
```
Comment (12) [inline src/app/lib/globalStyles/index.jsx]: Why aren't we validating prop types here?

File: src/app/lib/globalStyles/index.jsx (hunk 9 above)
Comment (12) [reply src/app/lib/globalStyles/index.jsx:27]: Also why didn't we implement @dr3's suggestion here? https://github.com/bbc/simorgh/pull/2425#discussion_r304580081

File: src/app/lib/globalStyles/index.jsx [hunk 11]
```diff
@@ -22,9 +23,17 @@ const GlobalStyleComponent = createGlobalStyle`
...
+const GlobalStyle = ({ fonts }) => {
+  const { fonts: styleFonts } = useContext(ServiceContext);
+  return <GlobalStyleComponent fonts={fonts || styleFonts} />;
+};
+
+GlobalStyle.propTypes = {
+  fonts: string,
+};
+
+GlobalStyle.defaultProps = {
```
Comment (RayNjeri) [inline src/app/lib/globalStyles/index.jsx:35]: @jimjohnsonrollings added this default props to ReithSans and just wanted be sure that it should be the default.
cc: @jamesdonoh @rhell

Comment (jimjohnsonrollings) [reply src/app/lib/globalStyles/index.jsx:35]: @RayNjeri what effect would this have?  Several services will not want to use Reith fonts at all.

File: src/app/lib/globalStyles/index.jsx (hunk 9 above)
Comment (RayNjeri) [reply src/app/lib/globalStyles/index.jsx:27]: This will result to a failuire due to this ```fonts.reduce((fontStyles, fontStyle) => fontStyles + fontStyle, '')```

File: src/app/lib/globalStyles/index.jsx (hunk 11 above)
Comment (RayNjeri) [reply src/app/lib/globalStyles/index.jsx:35]: Yeah i got that, since we are not sure what we want to be the default i opted to turn the Eslint rule on it..

**Review by jamesdonoh — APPROVED** [review]

File: src/app/lib/globalStyles/index.jsx [hunk 12]
```diff
@@ -22,9 +23,17 @@ const GlobalStyleComponent = createGlobalStyle`
     ${({ fonts }) => fonts && createFontStyles(fonts)}
   `;
 
-const GlobalStyle = () => {
-  const { fonts } = useContext(ServiceContext);
-  return <GlobalStyleComponent fonts={fonts} />;
+const GlobalStyle = ({ fonts }) => {
+  const styleFonts = useContext(ServiceContext).fonts;
```
Comment (dr3) [inline src/app/lib/globalStyles/index.jsx:27]: Can we not do 
```jsx
const styleFonts = fonts || useContext(ServiceContext).fonts;
``` 
to avoid calling useContext unnecessarily?

Comment (RayNjeri) [reply src/app/lib/globalStyles/index.jsx:27]: @dr3 do you mean `can we do` the above suggested implementation? am lost at `not`

Comment (RayNjeri) [reply src/app/lib/globalStyles/index.jsx:27]: with the above suggestion, it will violate the rules of hooks as it’s not advisable to use conditionals with hooks.

Comment (dr3) [reply src/app/lib/globalStyles/index.jsx:27]: Ooooh yes good point. Ignore me :)

File: src/app/lib/globalStyles/index.jsx [hunk 13]
```diff
@@ -22,9 +23,17 @@ const GlobalStyleComponent = createGlobalStyle`
...
+  return <GlobalStyleComponent fonts={fonts || styleFonts} />;
+};
+
+GlobalStyle.propTypes = {
+  fonts: string,
```
Comment (ghost) [inline src/app/lib/globalStyles/index.jsx]: `fonts` would be an array of strings.

**Review by ghost — CHANGES_REQUESTED** [review]

File: src/app/lib/globalStyles/index.jsx [hunk 14]
```diff
@@ -22,9 +23,17 @@ const GlobalStyleComponent = createGlobalStyle`
...
+  const styleFonts = useContext(ServiceContext).fonts;
+  return <GlobalStyleComponent fonts={fonts || styleFonts} />;
+};
+
+GlobalStyle.propTypes = {
+  fonts: PropTypes.arrayOf(PropTypes.string),
+};
+
+GlobalStyle.defaultProps = {
+  fonts: [''],
```
Comment (ghost) [inline src/app/lib/globalStyles/index.jsx]: Can this be an empty array without an empty string.

File: src/app/lib/globalStyles/index.jsx [hunk 15]
```diff
@@ -22,9 +23,17 @@ const GlobalStyleComponent = createGlobalStyle`
...
-const GlobalStyle = () => {
-  const { fonts } = useContext(ServiceContext);
-  return <GlobalStyleComponent fonts={fonts} />;
+const GlobalStyle = ({ fonts }) => {
+  const styleFonts = useContext(ServiceContext).fonts;
+  return <GlobalStyleComponent fonts={fonts || styleFonts} />;
+};
+
+GlobalStyle.propTypes = {
+  fonts: PropTypes.arrayOf(PropTypes.string),
```
Comment (ghost) [inline src/app/lib/globalStyles/index.jsx]:
```suggestion
  fonts: arrayOf(PropTypes.string),
```

File: src/app/lib/globalStyles/index.jsx [hunk 16]
```diff
@@ -2,6 +2,7 @@
 import React, { useContext } from 'react';
 import styledNormalize from 'styled-normalize';
 import { createGlobalStyle } from 'styled-components';
+import PropTypes from 'prop-types';
```
Comment (ghost) [inline src/app/lib/globalStyles/index.jsx]:
```suggestion
import { arrayOf } from 'prop-types';
```

File: src/app/lib/globalStyles/index.jsx (hunk 14 above)
Comment (ghost) [inline src/app/lib/globalStyles/index.jsx]:
```suggestion
  fonts: [],
```

**Review by ghost — APPROVED** [review]

**Review by jamesdonoh — APPROVED** [review]

**Comment by jamesbrumpton** [comment]
LGTM
