### PR TITLE
Replace After.JS with Uni

### LINKED ISSUE #277: Simorgh server issues 200 response for URLs that don't exist
**Describe the bug**
When the simorgh server is started and hit with a request for a resource that shouldn't exist, it will issue a 200 response code and html payload

**To Reproduce**
1. Do `npm run dev`
2. curl a url that shouldn't exist, e.g. `curl http://localhost:7080/icecream -I`

for example: 

```curl http://localhost:7080/icecream -I
HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 3188
ETag: W/"c74-2fQtTo3bieUDuHkpvKvVZtUF61w"
Date: Wed, 11 Jul 2018 13:23:58 GMT
Connection: keep-alive
```

**Expected behavior**
I imagine it should return a 404.

### PR DESCRIPTION
**Pull request by jtart**
Resolves #277 

_Replaces `After.JS` with `Uni`, and updates with an appropriate implementation and tests._

_`uni` is less-opinionated than `After.JS` in application render on the server and on the client, and only provides a React component. This React component renders routes and an API for data-fetching; it doesn't provide any utility for rendering._

_This means that Simorgh deals with the rendering of the application, which is **more to maintain**, but provides considerably **more flexibility**._

_Data-fetching has been moved to the route, which enables the `ArticleContainer` to just deal with rendering._

_`ArticleContainer` now handles states of data-fetching, through `loading`, `error`, and `data` props, `uni` allows Simorgh, or the React application, to deal with various states of data-fetching; `After.JS` didn't provide this functionality in any way, which is especially pertinent for error handling, as it just doesn't handle it._

_The Simorgh server can now return non-200 responses to the user, which was far more difficult with an implementation of `After.JS`. This is now possible because Simorgh deals with the granularity of React application rendering._

- [x] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

File: src/app/components/Document/index.jsx [hunk 1]
```diff
@@ -1,15 +1,15 @@
...
 import { C_POSTBOX } from '../../lib/constants/styles';
 
 /* eslint-disable react/prop-types */
-const Document = ({ assets, data, styleTags, helmet }) => {
+const Document = ({ assets, app, data, styleTags, helmet }) => {
   const htmlAttrs = helmet.htmlAttributes.toComponent();
   const meta = helmet.meta.toComponent();
   const title = helmet.title.toComponent();
   const links = helmet.link.toComponent();
+  const serialisedData = JSON.stringify(data).replace(/</g, '\\u003c');
```
Comment (sareh) [inline src/app/components/Document/index.jsx]: `data` here is json, so why are you replacing `<`? The application works correctly without this replace method.

File: src/app/containers/Article/index.jsx [hunk 2]
```diff
@@ -1,72 +1,18 @@
...
-const validateService = service => {
-  const services = ['news', 'persian'];
-  const serviceMatch = services.includes(service);
+const ArticleContainer = ({ loading, error, data }) => {
+  if (loading) return 'Loading...';
+  if (error) return 'Something went wrong :(';
+  if (data) {
+    const { amp, data: articleData } = data;
 
-  if (!serviceMatch) {
```
Comment (sareh) [inline src/app/containers/Article/index.jsx]: I like this separation. Having getInitialData logic pulled out of this Articles container and moved to `/routes/` makes a lot of sense.  This separation enables us to focus here on the application's error & loading states separately to the data fetching error states in `/routes/getInitialData`

**Review by jamesbhobbs — CHANGES_REQUESTED** [review]
I am blocking release with this 'request changes' as I want to sign this off. I'd like others to CR before I look at it though.

File: src/app/components/Document/index.jsx [hunk 3]
```diff
@@ -29,8 +29,14 @@ const Document = ({ assets, data, styleTags, helmet }) => {
         {styleTags}
       </head>
       <body>
-        <AfterRoot />
-        <AfterData data={data} />
+        {/* eslint-disable react/no-danger */
+        /* disabling the rule that bans the use of dangerouslySetInnerHTML until a more appropriate implementation can be implemented */}
```
Comment (jtart) [inline src/app/components/Document/index.jsx:33]: A 'more appropriate implementation' might be refactoring this document to be a string over a React component, which would negate the need for `dangerouslySetInnerHTML`.

There is no need for Document to be a React component anymore. Also, `renderToStaticMarkup` is a slower API than just returning the string, and having Document as a React component removes the ability to render to a node stream, if we wish to implement such.

Refactoring Document to be a string wasn't considered in this PR as I did not want to change underlying implementations, where possible.

File: cypress/integration/dataSpec.js [hunk 4]
```diff
@@ -2,6 +2,6 @@ import { testNonHTMLResponseCode } from '../support/testHelper';
 
 describe('Static Articles data', () => {
   it('should return a 200 status code', () => {
-    testNonHTMLResponseCode('/data/c0000000001o.json', 200);
+    testNonHTMLResponseCode('/data/news/c0000000027o.json', 200);
```
Comment (jtart) [inline cypress/integration/dataSpec.js]: This has to be changed because Simorgh now returns a 404 for incorrect requests, the test would have previously always passed as SImorgh always returned a 200.

File: razzle.config.js [hunk 5]
```diff
@@ -40,7 +40,6 @@ module.exports = {
             // externals means files not generated by webpack
             // an alternative would be html-webpack-plugin
             caches: 'all',
-            externals: ['/'],
```
Comment (jtart) [inline razzle.config.js:45]: This has been removed as now that Simorgh returns non-200 responses, this value was causing the service worker to fail as nothing is served over `/`. We might want to consider adding fonts here.

File: src/app/routes/getInitialData/index.js [hunk 6]
```diff
@@ -0,0 +1,52 @@
...
+    }
+
+    const response = await fetch(url);
+    const data = await response.json();
+    const amp = isAmpPath(path);
+
+    return { amp, data };
+  } catch (error) {
+    console.log(error); // eslint-disable-line no-console
+    return {};
```
Comment (jtart) [inline src/app/routes/getInitialData/index.js]: We need to refactor this to throw the error, so it can be caught [in the component](https://github.com/bbc/simorgh/pull/640/files#diff-d5c925f82e0315a863ea6a24dd59cb60R11), or [on the server](https://github.com/bbc/simorgh/pull/640/files#diff-788dcef7a5e3a2740bf71979cca64a59R57), but I did not want to change the underlying implementation.

File: src/app/routes/getInitialData/index.js [hunk 7]
```diff
@@ -0,0 +1,52 @@
...
+    validateService(service);
+    validateId(id);
+
+    let url = `/data/${service}/${id}.json`;
+
+    if (isServer()) {
+      url = `${process.env.RAZZLE_BASE_PATH}${url}`;
+    }
+
+    const response = await fetch(url);
```
Comment (jtart) [inline src/app/routes/getInitialData/index.js:41]: NB: The `fetch` API does not throw an error if the response returns a non-200/300 response, so we will have to handle it manually.

File: src/server/index.jsx [hunk 8]
```diff
@@ -47,18 +51,34 @@ server
...
+          app={app}
+          data={data}
+          styleTags={styleTags}
+          helmet={helmet}
+        />,
+      );
+
+      res.send(`<!doctype html>${doc}`);
+    } catch ({ message }) {
+      res.status(404).send(message);
```
Comment (jtart) [inline src/server/index.jsx:87]: We would want to handle this with more nuance, but I did not want to change the underlying implementation too much (apart from return a 404 on the catch-all route).

File: package.json [hunk 9]
```diff
@@ -53,7 +53,7 @@
   },
   "homepage": "https://github.com/bbc/simorgh#readme",
   "dependencies": {
-    "@jaredpalmer/after": "^1.3.1",
+    "@jtart/uni": "^1.0.0-alpha.1",
```
Comment (pjlee11) [inline package.json:56]: Is there a particular reason we are running on an alpha pre release version?

File: src/app/components/Document/index.jsx (hunk 1 above)
Comment (pjlee11) [inline src/app/components/Document/index.jsx]: Is there a reason we are only unicode'ing `<` (`u003c`) and not other symbols as well?

File: src/app/components/Document/index.jsx (hunk 3 above)
Comment (pjlee11) [reply src/app/components/Document/index.jsx:33]: Could you elaborate on `render to a node stream`?

File: src/app/components/Document/index.jsx [hunk 10]
```diff
@@ -29,8 +29,14 @@ const Document = ({ assets, data, styleTags, helmet }) => {
...
+        <div id="root" dangerouslySetInnerHTML={{ __html: app }} />
+        <script
+          dangerouslySetInnerHTML={{
+            __html: `window.SIMORGH_DATA=${serialisedData}`,
```
Comment (pjlee11) [inline src/app/components/Document/index.jsx:37]: Why is the serialisedData being set here within a script tag?

File: src/app/containers/Article/index.jsx [hunk 11]
```diff
@@ -1,72 +1,18 @@
...
-import isAmpPath from '../../helpers/isAmpPath';
 
-const validateService = service => {
-  const services = ['news', 'persian'];
-  const serviceMatch = services.includes(service);
+const ArticleContainer = ({ loading, error, data }) => {
+  if (loading) return 'Loading...';
+  if (error) return 'Something went wrong :(';
+  if (data) {
+    const { amp, data: articleData } = data;
```
Comment (pjlee11) [inline src/app/containers/Article/index.jsx]: Would this not mean that `amp === articleData.amp`? Is there a use case for amp being split out here instead of being on line 15? EG: `const { content, metadata, promo } = articleData;`

Update: ignore and see comment below

File: src/app/containers/Article/index.jsx [hunk 12]
```diff
@@ -89,12 +35,19 @@ class ArticleContainer extends Component {
       </Fragment>
     );
   }
-}
 
-ArticleContainer.propTypes = articlePropTypes;
+  return null;
```
Comment (pjlee11) [inline src/app/containers/Article/index.jsx:76]: Could you give an example of when we would receive no `loading`, `error` and `data` meaning we would hit this null statement?

File: src/app/containers/Article/index.jsx (hunk 11 above)
Comment (pjlee11) [reply src/app/containers/Article/index.jsx]: Having looked further I've realised this doesn't make sense and I was confused due to the data object having a direct children also called data. If possible could one of these be renamed? Maybe `payload` or something to help remove the confusion?

**Review by pjlee11 — COMMENTED** [review]
Review still in progress, didn't want to lose multiple comments ...

File: src/app/helpers/isServer.js [hunk 13]
```diff
@@ -0,0 +1,3 @@
+const isServer = () => !!(typeof process !== 'undefined' && process.versions);
```
Comment (pjlee11) [inline src/app/helpers/isServer.js:1]: What is `!!` representing here?

Comment (pjlee11) [reply src/app/helpers/isServer.js:1]: Feels like a horrible prettier thing which will make my skin crawl

File: src/app/routes/getInitialData/index.js (hunk 7 above)
Comment (pjlee11) [reply src/app/routes/getInitialData/index.js:41]: Could we have an issue linked here in the PR comments to capture the handling of this error throw please.

File: src/server/index.jsx [hunk 14]
```diff
@@ -53,18 +57,34 @@ server
...
+      const sheet = new ServerStyleSheet();
+      const data = await loadInitialData(url, routes);
+
+      const app = renderToString(
+        sheet.collectStyles(
+          <ServerUni url={url} routes={routes} data={data} />,
+        ),
+      );
+
+      const helmet = Helmet.renderStatic();
```
Comment (sareh) [inline src/server/index.jsx:71]: I like that Uni doesn't handle all of the static assets like After does. This will enable us to add logging and more granular error handling around each of these parts of the server-side render. 
We can also add custom performance marks before and after each step, which will enable us to more closely understand the performance of our application.

File: src/client.js [hunk 15]
```diff
@@ -16,16 +15,10 @@ if (process.env.NODE_ENV === 'production') {
...
 
-ensureReady(routes).then(data =>
-  hydrate(
-    <BrowserRouter>
-      <After data={data} routes={routes} />
-    </BrowserRouter>,
-    root,
-  ),
-);
+hydrate(<ClientUni data={data} routes={routes} />, root);
```
Comment (sareh) [inline src/client.js:21]: I like that `<ClientUni>` includes the usage of `<BrowserRouter>`, so the API for Uni is simpler than that provided by After. We don't need to separately import `react-router-dom`.

**Review by sareh — DISMISSED** [review]
This looks great.  Thanks for writing `uni` and integrating it into our application.  

It addresses the problems we are having with After.js (it not returning correct status codes) but it retains the useful aspects of After - providing a simple API for routing on the client and the server. 
The logic for handling application data from an object and the handling of stylesheets on the server is now visible to the application, so we can now add more logging around these implementations. 

Looks great. I just have a comments about implementation details below.

**Review by sareh — COMMENTED** [review]
I meant to click 'Comment' instead of 'Approve'. :)

File: src/app/helpers/isServer.js (hunk 13 above)
Comment (sareh) [reply src/app/helpers/isServer.js:1]: @pjlee11 If the value `(typeof process !== 'undefined' && process.versions)` is truthy, then this statement will return `true`.  A single `!` would return false, but a `!!` inverts that once more.

File: src/app/components/Document/index.jsx (hunk 3 above)
Comment (jtart) [reply src/app/components/Document/index.jsx:33]: React v16 released [`renderToNodeStream`](https://reactjs.org/docs/react-dom-server.html#rendertonodestream), which enables a React app to be streamed as a [node stream](https://medium.freecodecamp.org/node-js-streams-everything-you-need-to-know-c9141306be93). Unsure on how this would fit into Mozart, but it would be a possibility from our side if the `Document` was just a string.

File: src/app/routes/getInitialData/index.js (hunk 7 above)
Comment (jtart) [reply src/app/routes/getInitialData/index.js:41]: https://github.com/bbc/simorgh/issues/682

File: package.json (hunk 9 above)
Comment (jtart) [reply package.json:56]: It is the only major version of `uni` that exists, it's fairly stable, I just haven't got round to releasing it as `1.0.0` as I am considering as name change.

File: src/app/components/Document/index.jsx (hunk 1 above)
Comment (jtart) [reply src/app/components/Document/index.jsx]: Thanks, have removed it.

Comment (jtart) [reply src/app/components/Document/index.jsx]: Nope, have removed it.

File: src/app/components/Document/index.jsx (hunk 10 above)
Comment (jtart) [reply src/app/components/Document/index.jsx:37]: When hydrating a client-side React application on a page that was rendered on the server, you need to hydrate the application with the data that was used to render on the server. `SIMORGH_DATA` is used on the [client](https://github.com/bbc/simorgh/blob/75cbfb66839b152bf50e07c8cb9f861c5c336521/src/client.js#L18-L21) for hydration of the client-side React application.

File: src/client.js (hunk 15 above)
Comment (jtart) [reply src/client.js:21]: We do still need `react-router-dom` for the [Link component](https://github.com/bbc/simorgh/blob/75cbfb66839b152bf50e07c8cb9f861c5c336521/src/app/containers/InlineLink/index.jsx#L2) but yes you are right; we don't need to implement other `react-router-dom` APIs.

File: src/app/containers/Article/index.jsx (hunk 12 above)
Comment (jtart) [reply src/app/containers/Article/index.jsx:76]: There shouldn't be one, but if there is we'd _probably_ want to handle it [here](https://github.com/bbc/simorgh/pull/640/files#diff-d5c925f82e0315a863ea6a24dd59cb60R52), but I didn't make that assumption.

File: src/app/routes/index.js [hunk 16]
```diff
@@ -1,15 +1,18 @@
 import Article from '../containers/Article';
+import getInitialData from './getInitialData';
 
 const routes = [
   {
     path: '/:service/articles/:id',
     exact: true,
     component: Article,
+    getInitialData,
```
Comment (pjlee11) [inline src/app/routes/index.js:9]: Could you explain how the match props are passed to the callback of `getInitialData`?

Comment (jtart) [reply src/app/routes/index.js:9]: `uni` calls `react-router-config`'s `matchRoute`, which returns a `route` and `match` object. This is just passed to `getInitialData`. https://github.com/jtart/uni/blob/master/src/loadInitialData.js#L17

Comment (sareh) [reply src/app/routes/index.js:9]: @pjlee11 It's because in the `server/index` we pass the routes array to loadInitialData `const data = await loadInitialData(url, routes);` and here you can see it used in Uni's `loadInitialData` function: https://github.com/jtart/uni/blob/a3b7d204b9e623d6675396e45650ee3fc9a4751e/src/loadInitialData.js#L12-L21

File: src/app/components/Document/index.jsx (hunk 3 above)
Comment (jamesbhobbs) [reply src/app/components/Document/index.jsx:33]: Stream wouldn't be possible with Mozart but this application ought to be able to handle it (not in this PR).

File: razzle.config.js (hunk 5 above)
Comment (jamesbhobbs) [reply razzle.config.js:45]: This is interesting. What about static assets such as svgs? They presumably just are no longer cached by the sw?

**Review by jamesbhobbs — APPROVED** [review]
