### PR TITLE
optionally render skip link in oj container

### LINKED ISSUE #7479: Recommendations skip link needs to be within a landmark region
**Describe the bug**
At the moment, the skip link for the recommendations container sits outside the `section` element which is land marked for the recommendation component an this might be misleading to users as it will be interpreted as being the start of recommendations.

**To Reproduce**

1. Go to 'http://localhost:7080/mundo/23263889'
2. Inspect the recommendations component
3. See that the Skip anchor is placed outside the `section` element.
Screen Shot 2020-08-12 at 17 06 23

**Expected behavior**
The Skip link container should be within the `section` element which signifies the beginning of recommendations as everything inside it is a standalone.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [X] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by rhenshaw56**
Resolves #7479

**Overall change:**
_optionally renders recommendations skip link within the onward journey container._

**Code changes:**

- _optionally renders recommendations skip link within the onward journey container._
- _update snapshots for recommendations container._

---

- [X] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [X] I have assigned this PR to the Simorgh project

**Testing:**

- [X] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`)
- [X] This PR requires manual testing

### CODE REVIEW

File: src/app/containers/CpsRecommendations/index.jsx [hunk 1]
```diff
@@ -126,28 +123,25 @@ const CpsRecommendations = ({ items, parentColumns }) => {
...
+          content={items}
+          parentColumns={parentColumns}
+          singleTransform={singleTransform}
+          listTransform={listTransform}
+          sectionLabelOverrideAs="strong"
+          sectionLabelBar={false}
+          sectionLabelBackground={C_LUNAR}
+          columnType="main"
+          hasSkipLnk
+          endTextId={endTextId}
```
Comment (HarveyPeachey) [inline src/app/containers/CpsRecommendations/index.jsx]: Some of the naming of these props now that they're directly being passed into `CpsOnwardJourney` aren't very clear they're being used for the skip link. Might need to think about renaming them to be more explicit.

File: src/app/containers/CpsOnwardJourney/index.jsx [hunk 2]
```diff
@@ -127,6 +178,11 @@ const CpsOnwardJourney = ({
   sectionLabelBar,
   sectionLabelBackground,
   columnType,
+  hasSkipLnk,
+  endTextId,
+  skipText,
+  endTextVisuallyHidden,
+  skipLinkTerms,
```
Comment (andrewscfc) [inline src/app/containers/CpsOnwardJourney/index.jsx]: As all these props relate to the skip link, could we put them in a nested object to keep them isolated from the other props:
```
skipLinkConfig: {
  endTextId,
  skipText,
  endTextVisuallyHidden,
  skipLinkTerms,
}
```
I've removed `hasSkipLnk` (typo) as the presence of the skipLinkConfig indicates the onward journey has a skip link

File: src/app/containers/CpsOnwardJourney/index.jsx [hunk 3]
```diff
@@ -116,6 +117,56 @@ const SingleContentWrapper = styled.div`
...
+    >
+      {children}
+    </SkipLinkWrapper>
+  ) : (
+    children
+  );
+
+const optionalSkipLinkProps = {
+  hasSkipLnk: bool,
+  skipLinkTerms: shape({}),
```
Comment (andrewscfc) [inline src/app/containers/CpsOnwardJourney/index.jsx]: What does this prop type check for, that it's always an empty object? `{}`

File: src/app/containers/CpsOnwardJourney/index.jsx [hunk 4]
```diff
@@ -116,6 +117,56 @@ const SingleContentWrapper = styled.div`
   `}
 `;
 
+const OptionallyRenderedSkipWrapper = ({
```
Comment (simonsinclair) [inline src/app/containers/CpsOnwardJourney/index.jsx]: Instead of creating another wrapper for the wrapper in an already oversized container, have we considered using the `SkipLinkWrapper` component directly? For example:

```jsx
const Container = ({ skipLink }) => {
  if (skipLink && skipLink.text)
    return (
      <SkipLinkWrapper>
        <CpsOnwardJourneyWrapper></CpsOnwardJourneyWrapper>
      </SkipLinkWrapper>
    );

  return <CpsOnwardJourneyWrapper></CpsOnwardJourneyWrapper>;
};

```

**Review by andrewscfc — COMMENTED** [review]
One stylistic suggestion to group the props for skip link to make it clear what they are for, otherwise looks okay. Again sad we have no tests for `CpsOnwardJourney` as we are just making the problem harder to fix with every PR: https://github.com/bbc/simorgh/issues/6519 :'(

File: src/app/containers/CpsOnwardJourney/index.jsx (hunk 3 above)
Comment (rhenshaw56) [reply src/app/containers/CpsOnwardJourney/index.jsx]: it's usually an `enum` of tokenized string used to find and replace certain terms in the skip text, so it could be anything. Since we're using this for recommendations I will just specify what we're passing in instead.

File: src/app/containers/CpsOnwardJourney/index.jsx (hunk 4 above)
Comment (rhenshaw56) [reply src/app/containers/CpsOnwardJourney/index.jsx]: :thinking_face: we could do that! but wouldn’t it imply we could literally render the Skip link container anywhere and it wouldn’t visually render as far as there’s no `skipText` prop ? @simonsinclair

File: src/app/containers/CpsRecommendations/index.jsx (hunk 1 above)
Comment (rhenshaw56) [reply src/app/containers/CpsRecommendations/index.jsx]: this is now grouped in a `skipLink` object so the relationship is clearer

File: src/app/containers/CpsOnwardJourney/index.jsx (hunk 4 above)
Comment (simonsinclair) [reply src/app/containers/CpsOnwardJourney/index.jsx]: > We could do that! but wouldn’t it imply we could literally render the Skip link container anywhere and it wouldn’t visually render as far as there’s no skipText prop ?

The above example would only render a Skip Link if `skipLink.text` was passed.

I can see you've updated this code, and that it still uses an additional component. The reason I'm adverse to adding a component like this here is because, in my opinion, it makes the container's main render function harder to read. It is a potentially unnecessary abstraction that can be achieved with standard control logic. It also creates another set of defaultProp and propType objects that are unrelated to the component that's exported in this file. Feel free to disagree, because most of these points are stylistic, but they will all play a part in the maintainability of this file in the future.

**Review by andrewscfc — APPROVED** [review]
Approving this based on my comments but I'd take a look at @simonsinclair 's most recent comment, it sounds a good idea. Thanks for addressing my points 👍

File: src/app/containers/CpsOnwardJourney/index.jsx [hunk 5]
```diff
@@ -116,6 +117,35 @@ const SingleContentWrapper = styled.div`
...
+const OptionallyRenderedSkipWrapper = ({ skipLink, service, children }) =>
+  skipLink ? (
+    <SkipLinkWrapper service={service} {...skipLink}>
+      {children}
+    </SkipLinkWrapper>
+  ) : (
+    children
+  );
+
+const optionalSkipLinkProps = {
```
Comment (simonsinclair) [inline src/app/containers/CpsOnwardJourney/index.jsx]: I realise "optional" is coming from the name of the component, but these props are not optional. Can I suggest we rename this variable to `skipLinkProps`?
You also might opt to call it `skipLinkShape` and also include the shared propType function.

File: src/app/containers/CpsOnwardJourney/index.jsx [hunk 6]
```diff
@@ -116,6 +117,35 @@ const SingleContentWrapper = styled.div`
...
+  terms: shape({
+    '%title%': string,
+  }),
+  endTextVisuallyHidden: string,
+  endTextId: string,
+  text: string,
+};
+
+OptionallyRenderedSkipWrapper.propTypes = {
+  service: string,
```
Comment (simonsinclair) [inline src/app/containers/CpsOnwardJourney/index.jsx]: `service` is required. If you pass `skipLink`, but not `service`, this component will throw an error.

File: src/app/containers/CpsOnwardJourney/index.jsx (hunk 4 above)
Comment (simonsinclair) [reply src/app/containers/CpsOnwardJourney/index.jsx]: Simon's PR has gone a long way to simplifying this container, so this pattern is less of a concern _at the moment_. I will resolve this. We can revisit later if needed.

**Review by simonsinclair — APPROVED** [review]

**Comment by paruchurisilpa** [comment]
Done regression around recommendations, LGTM..

**Comment by paruchurisilpa** [comment]
Couldn't test in IE because browserstack is not working..
Screenshot 2020-08-25 at 09 44 23
