### PR TITLE
Synchronously re-render images that fail to load

### LINKED ISSUE #8954: Issue with lazy loading of images on Russian article pages in Portrait mode on Iphone
1. Go to https://www.bbc.com/russian/news-56320777 on an iPhone.
2. There is an issue with lazy loading of images for russian article pages.
3. Some images load only partially and the only way to fix them is to turn the phone to landscape, which reloads the images, and then back to portrait. 
4. This is not hapenning on all article pages though.
IMG_2E3FC0DABAE4-1

4. Attached is the screenshot.

### PR DESCRIPTION
**Pull request by mukama**
Resolves #8954

**Overall change:**
For some reason, Safari browsers on MacOS and iOS struggle with automatically choosing the best suitable way of decoding images to render. In the event that an image fails to loads because of this reason, even loads partially, this PR re-renders it with `decoding="sync"`. By doing so, modern browsers will be forced to decode the image on the main thread avoiding parallelised decoding and rendering which may sometimes cause Safari to load images partially or not at all. 

**Code changes:**
- Adds `onError` event handler that redraws failing images with `decoding="sync"` property

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project
- [ ] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [x] This PR requires manual testing

### CODE REVIEW

File: src/app/containers/ImageWithPlaceholder/index.jsx [hunk 1]
```diff
@@ -38,10 +38,16 @@ const ImageWithPlaceholder = ({
...
   const { isAmp } = useContext(RequestContext);
   const [isLoaded, setIsLoaded] = useState(false);
+  const [syncDecoding, setSyncDecoding] = useState(false);
   const imageProps = { alt, src, sizes, width, srcset, fade };
   const imgType = src.split('.').pop();
   const imageToRender = (
-    <Image onLoad={() => setIsLoaded(true)} {...imageProps} />
+    <Image
+      onLoad={() => setIsLoaded(true)}
+      onError={() => setSyncDecoding(true)}
```
Comment (andrewscfc) [inline src/app/containers/ImageWithPlaceholder/index.jsx:47]: This looks a great approach but just wondering if we could scope this a bit more? Is there any message we can expect in the onError callback when it doesn't load due to decoding issues: https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror

Just concious this change will cause all images that fail to load to try and load again, regardless of the cause

Comment (HarveyPeachey) [reply src/app/containers/ImageWithPlaceholder/index.jsx:47]: Just to add on to this I think we can use [`EncodingError`](https://heycam.github.io/webidl/#encodingerror) to scope this more

Comment (mukama) [reply src/app/containers/ImageWithPlaceholder/index.jsx:47]: Great observation @andrewscfc. Let me explore the error that is returned. I am sure there is a way to scope it down to just this particular use-case.

Comment (mukama) [reply src/app/containers/ImageWithPlaceholder/index.jsx:47]: @andrewscfc It looks like the [`onError`](url) event handler API does not say what kind of error occurred at the moment. All we have privy to is that something went wrong when loading this image. Might I be missing something?

@HarveyPeachey it seems we can only know it was an [EncodingError](https://heycam.github.io/webidl/#encodingerror) when we decode the image manually. Here's [one such example](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/decode#examples). Should we explore decoding and rendering the image ourselves?

Comment (andrewscfc) [reply src/app/containers/ImageWithPlaceholder/index.jsx:47]: I was thinking something like `onError={(event) => event === "decodingError" ? setSyncDecoding(true) : null}`
I don't know exactly what the onError callback receives, this _looks like_ the correct docs: https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror#element.onerror

Might be worth console logging the arguments you get if any?

If you can't scope it, I'd potentially just go with your current solution, it would just mean images attempt to reload once if they fail which isn't that bad I don't think but may give a slightly strange experience I'm not sure?

Comment (mukama) [reply src/app/containers/ImageWithPlaceholder/index.jsx:47]: I tried `console.log(event)` but the `event` recieved is a [generic event](https://developer.mozilla.org/en-US/docs/Web/API/Event). Not sure why the `onError` callback doesn't  receive an [error event](https://developer.mozilla.org/en-US/docs/Web/API/ErrorEvent) instead - it would be much more informative for us.

Comment (andrewscfc) [reply src/app/containers/ImageWithPlaceholder/index.jsx:47]: What value do you get for [event.type](https://developer.mozilla.org/en-US/docs/Web/API/Event/type)? Just wondering if something in the object tells you nature of the event.

Anyway, if we can't scope, more than happy to leave this as it is, it could though do with a unit test actually, so faking an error event and confirming the `decoding` prop is applied correctly.

Comment (mukama) [reply src/app/containers/ImageWithPlaceholder/index.jsx:47]: `event.type` is `"error"`. 

Yeah, I am afraid we can't scope it without increasing the complexity

Comment (HarveyPeachey) [reply src/app/containers/ImageWithPlaceholder/index.jsx:47]: > https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onerror#element.onerror

Looking at the docs could this potentially create a re-render loop?  As `onError` will fire with every single error that an image may produce, for example if the `img` url provided is wrong that will cause a render changing decoding to `sync`, then `onError` will fire again and call `setSyncDecoding(true)`. Does react look at that state hook and prevent a re-render because it is already set to `true`? If it does then we are good and I'm happy with this approach.

Comment (andrewscfc) [reply src/app/containers/ImageWithPlaceholder/index.jsx:47]: You could check some of those scenarios in tests @HarveyPeachey, I suspect because the state is stable you _probably_ won't get a render loop.

Comment (mukama) [reply src/app/containers/ImageWithPlaceholder/index.jsx:47]: Good point @HarveyPeachey but I believe @andrewscfc is right. The component will re-render on the first failure when our `syncDecoding` state changes from `false` to `true`. The second `onError` event will not trigger re-rendering because state will already be the same as before (`true`).

Comment (mukama) [reply src/app/containers/ImageWithPlaceholder/index.jsx:47]: Unit test is ready @andrewscfc and @HarveyPeachey

**Review by HarveyPeachey — APPROVED** [review]
Great work 🚀

**Review by andrewscfc — APPROVED** [review]
Thanks for the unit test, looks great :)

**Comment by mukama** [comment]
I checked our lighthouse score before and after and this implementations seems not to to change the score. It makes sense considering we only re-render failed images which seldom occurs.
