### PR TITLE
Fix images on non-retina

### LINKED ISSUE #5838: Front pages image source setting is borked on non-retina
**Describe the bug**
Non-retina screens use the 240px image on desktop widths

**To Reproduce**
Steps to reproduce the behaviour:

1. Get a non-retina device
2. Go to /nepali
3. Examine the top story image for its filename
4. Check the network tab for that file
5. See that the 240px version is being loaded

**Expected behaviour**
A better image, e.g. 660px, is loaded

**Additional context**
This appears to be because the `sizes` part of our srcset implemention is wrong, saying:
`sizes="(max-width: 600px) 100vw, (max-width: 1008px) 33vw, 237px"`
when it should be
`sizes="(max-width: 600px) 100vw, (max-width: 1008px) 50vw, 496px"`
(This tells the browser how big the image appears in the page: <600 -> 100vw, 601-1008 -> 50vw, >1008 = 496px)

### PR DESCRIPTION
**Pull request by jimjohnsonrollings**
Resolves #5838 

**Overall change:** 
Makes images look nice on non-retina devices

**Code changes:**
- Updates the containers for StoryPromo and Bulletin to have a srcset 'sizes' field with the correct image display sizes for the new desktop layout
- Updates the container for StoryPromo to use the larger image sizes in a 'leading' type as well as a 'top' type
- Renames a constant in StoryPromo to better reflect its usage
- Updates snapshots

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [x] This PR requires manual testing

### CODE REVIEW

**Comment by amywalkerdev** [comment]
Still having issues for large images that are not the top one or a bulletin

**Comment by jimjohnsonrollings** [comment]
> Still having issues for large images that are not the top one or a bulletin

@amywalker1987 I think I've fixed this

File: src/app/containers/StoryPromo/index.jsx [hunk 1]
```diff
@@ -139,7 +139,7 @@ const StoryPromoContainer = ({
     return null;
   }
 
-  const topStory = promoType === 'top';
+  const topStory = promoType === 'top' || promoType === 'leading';
```
Comment (DenisHdz) [inline src/app/containers/StoryPromo/index.jsx]: We shouldn't do this, otherwise, leading promos will be using the same Image and Text styles and number of columns as top stories.
https://github.com/bbc/psammead/blob/latest/packages/components/psammead-story-promo/src/ImageStyles.jsx#L107
https://github.com/bbc/psammead/blob/latest/packages/components/psammead-story-promo/src/ImageStyles.jsx#L107

Comment (DenisHdz) [inline src/app/containers/StoryPromo/index.jsx]: Since this will also be applied to leading promos, shall we rename the constant to something like `useLargeImages` and also inside the `StoryPromoImage`?

**Review by mmcculloch — APPROVED** [review]

File: src/app/containers/StoryPromo/index.jsx (hunk 1 above)
Comment (jimjohnsonrollings) [reply src/app/containers/StoryPromo/index.jsx]: I've updated this :)

**Review by DenisHdz — APPROVED** [review]
LGTM 👍

**Review by mmcculloch — APPROVED** [review]

**Comment by PriyaKR** [comment]
Looks good.The non retina displays at desktop widths seem to be using larger width images ie)660px(Top story,leading story and bulletins).
Also regression tested on retina display.
