### PR TITLE
Topic Pagination - Update Ellipsis Logic

### LINKED ISSUE #10053: Pagination unnecessary ellipsis
**Describe the bug**
For some combinations of page items & screen sizes, we are rendering an unnecessary ellipsis where we could just show a number in it's place. 

From this page - https://www.test.bbc.com/pidgin/new_topics/c1gdqg448w1t
Screenshot 2022-04-20 at 09 27 11

From this page - https://www.test.bbc.com/pidgin/new_topics/c2dwqd1q11qt
Screenshot 2022-04-20 at 09 27 46

We'd like to update the component so this doesn't happen. 

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

### PR DESCRIPTION
**Pull request by RetiredBlob**
Resolves (https://github.com/bbc/simorgh/issues/10053)

**Overall change:**
- Fix bugged media queries
- Update ellipsis logic to not show an ellipsis in place of one number
- Some tidy up and new tests

**Code changes:**

- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [ ] I have assigned this PR to the Simorgh project
- [ ] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

File: src/app/pages/TopicPage/Pagination/buildBlocks.js [hunk 1]
```diff
@@ -54,22 +52,33 @@ const setDynamicVisibility = state => {
...
+  }
+
+  // If page (pagecount - 1) is going to be rendered
+  // it should have the same visibility as page (pagecount - 2)
+  const secondLastElement = state.result[state.result.length - 2];
+  const thirdLastElement = state.result[state.result.length - 3];
+  const secondLastPage = state.pageCount - 1;
+  const activePageIsOnLeft = state.activePage < secondLastPage;
+  if (activePageIsOnLeft && secondLastElement.pageNumber === secondLastPage) {
+    secondLastElement.visibility = thirdLastElement.visibility;
```
Comment (jroebu14) [inline src/app/pages/TopicPage/Pagination/buildBlocks.js:70]: mutating the state here makes returning the state on line 81 unnecessary. might be better to create a new state object and return that

Comment (ryanmccombe) [reply src/app/pages/TopicPage/Pagination/buildBlocks.js:70]: This function is used with `pipe` in the default export (line 165) - it needs to return the reference for use in the next function in the pipe

Comment (jroebu14) [reply src/app/pages/TopicPage/Pagination/buildBlocks.js:70]: ah ok. I just thought we had an eslint rule to prevent us from making side effects in functions. It's one of the core principles in functional programming. It's also something that was brought up in one of the standards sessions so might be good if we can remove examples other devs might copy from

Comment (RetiredBlob) [reply src/app/pages/TopicPage/Pagination/buildBlocks.js:70]: That eslint rule was disabled in this file - re-enabled it and updated all the functions to use clones of state

Comment (jroebu14) [reply src/app/pages/TopicPage/Pagination/buildBlocks.js:70]: Yas. Pure. Thanks for doing that

**Review by jroebu14 — APPROVED** [review]

**Review by rebeccamcginn — APPROVED** [review]
💡

**Comment by ryanmccombe** [comment]
Admin merging because chromatic doesn't work on forks
