### PR TITLE
Error page - Move error code out of h1

### LINKED ISSUE #3079: Error page - Move error code out of h1
**Describe the bug**
The h1 should not include the error code. The error code should come before the h1, see screen reader UX https://zpl.io/brW70G1 

**Expected behaviour**
The error page matches the screen reader UX

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by FK78**
Resolves #3079

**Overall change:** _Moved error code out of h1._

**Code changes:**

- _`ErrorTag` created._
- _`StatusCode` put into `ErrorTag`._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

### CODE REVIEW

File: src/app/components/ErrorPage/index.jsx [hunk 1]
```diff
@@ -27,6 +27,11 @@ const LongGridItemConstrainedMedium = styled(GridItemConstrainedMedium)`
   padding-bottom: 4rem;
 `;
 
+const ErrorTag = styled(Paragraph)`
+  padding-top: 40px;
+  margin-bottom: -60px;
```
Comment (dr3) [inline src/app/components/ErrorPage/index.jsx]: A minus margin is generally not preferred, is there any other way this can be done?

File: src/app/components/ErrorPage/index.jsx [hunk 2]
```diff
@@ -27,6 +27,11 @@ const LongGridItemConstrainedMedium = styled(GridItemConstrainedMedium)`
   padding-bottom: 4rem;
 `;
 
+const ErrorTag = styled(Paragraph)`
+  padding-top: 40px;
```
Comment (dr3) [inline src/app/components/ErrorPage/index.jsx]: Can `rem`s be used here please? 16px = 1rem

**Review by chris-hinds — APPROVED** [review]
LGTM however this this will need a UX and an accessibility review before it can be merged.

**Review by pharingee — APPROVED** [review]
LGTM

**Comment by FK78** [comment]
Accessibility and Supported Assistive Technology Swarm all catagories completed, excluding Dragon NaturallySpeaking as it is not needed for this issue.

The accessibility tests have met the requirements of 404 not being included as a heading.
