### PR TITLE
Remove figure element in MediaPlayer

### LINKED ISSUE #9625: Media player should not be in a figure element
**Describe the bug**
Our media player currently always renders inside a `figure` element:

Screen Shot 2021-11-02 at 15 11 10

Example Asset: https://www.test.bbc.com/thai/23463609

We've been asked to change this as it degrades screen reader experience.

For scenarios where the media player does not have a caption (which is almost always) this wrapping figure should ideally be removed.  If removing is not straightforward, we can change it to a `div` instead.

### PR DESCRIPTION
**Pull request by DarioR01**
Resolves #9625 

**Overall change:**
Added conditional render of a div or Figure element based on if we render a caption.

**Code changes:**
- Added a div styled element with same styling as the Figure from psammead.
- Move conditional render of amp or canonical MediaPlayer to mediaPlayerType function to make code cleaner
- Added logic to wrap content inside a Figure if we show a caption, else wrap content inside the styled div.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project
- [x] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by jroebu14 — DISMISSED** [review]

**Review by HarveyPeachey — DISMISSED** [review]

**Review by andrewscfc — APPROVED** [review]
Nice work LGTM

**Review by HarveyPeachey — APPROVED** [review]

File: src/app/containers/MediaPlayer/index.jsx [hunk 1]
```diff
@@ -173,35 +179,42 @@ const MediaPlayerContainer = ({
       <Caption block={captionBlock} type={mediaInfo.type} service={service} />
     ) : null;
 
+  const mediaPlayerType = () =>
```
Comment (jroebu14) [inline src/app/containers/MediaPlayer/index.jsx]: this doesn't need to be a function

Comment (DarioR01) [reply src/app/containers/MediaPlayer/index.jsx]: I created this function to make the code look better as I would need to have the same block of code twice inside the return. If this is violating any code practice I can quickly fix it :D

Comment (jroebu14) [reply src/app/containers/MediaPlayer/index.jsx]: it can just be a variable

Comment (DarioR01) [reply src/app/containers/MediaPlayer/index.jsx]: I am very dumb 😂. Made the changes 😄. Thank you for the review 👍

Comment (jroebu14) [reply src/app/containers/MediaPlayer/index.jsx]: 😆 you are not dumb! Also, I just realised the `renderCaption` example is doing the same. It can just be a var too called `caption`

File: src/app/containers/MediaPlayer/index.jsx [hunk 2]
```diff
@@ -173,35 +179,41 @@ const MediaPlayerContainer = ({
       <Caption block={captionBlock} type={mediaInfo.type} service={service} />
     ) : null;
 
+  const mediaPlayerType = isAmp ? (
```
Comment (jroebu14) [inline src/app/containers/MediaPlayer/index.jsx]: I think the var name `mediaPlayer` would be more appropriate. I'd expect `mediaPlayerType` to be a string value `amp` or `canonical`

File: src/app/containers/MediaPlayer/index.jsx (hunk 1 above)
Comment (DarioR01) [reply src/app/containers/MediaPlayer/index.jsx]: yep, fixed this too. Luckily that was not on me, feel tiny bit better 😂

File: src/app/containers/MediaPlayer/index.jsx (hunk 2 above)
Comment (DarioR01) [reply src/app/containers/MediaPlayer/index.jsx]: makes sense, I changed this too.
Thank you 👍

File: src/app/containers/MediaPlayer/index.jsx [hunk 3]
```diff
@@ -168,40 +174,45 @@ const MediaPlayerContainer = ({
     translations,
   );
 
-  const renderCaption = () =>
-    captionBlock ? (
-      <Caption block={captionBlock} type={mediaInfo.type} service={service} />
-    ) : null;
+  const renderCaption = captionBlock ? (
```
Comment (jroebu14) [inline src/app/containers/MediaPlayer/index.jsx]:
```suggestion
  const caption = captionBlock ? (
```

File: src/app/containers/MediaPlayer/index.jsx [hunk 4]
```diff
@@ -168,40 +174,45 @@ const MediaPlayerContainer = ({
...
-            service={service}
-            mediaInfo={mediaInfo}
-            noJsMessage={translatedNoJSMessage}
-            noJsClassName="no-js"
-            showLoadingImage={showLoadingImage}
-          />
-        )}
-        {showCaption && renderCaption()}
-      </Figure>
+      {showCaption && renderCaption ? (
```
Comment (jroebu14) [inline src/app/containers/MediaPlayer/index.jsx]:
```suggestion
      {showCaption && caption ? (
```

File: src/app/containers/MediaPlayer/index.jsx [hunk 5]
```diff
@@ -168,40 +174,45 @@ const MediaPlayerContainer = ({
...
+        <Figure>
+          {mediaPlayer}
+          {showCaption && renderCaption}
```
Comment (jroebu14) [inline src/app/containers/MediaPlayer/index.jsx]:
```suggestion
          {showCaption && caption}
```

**Review by jroebu14 — APPROVED** [review]
just some minor var renaming otherwise LGTM! thanks for making these changes

File: src/app/containers/MediaPlayer/index.jsx (hunk 5 above)
Comment (DarioR01) [reply src/app/containers/MediaPlayer/index.jsx]: Thanks @jroebu14 for the detailed review 👍. Also these small renaiming have been taken care of.

**Review by jroebu14 — APPROVED** [review]

**Comment by paruchurisilpa** [comment]
Testing:

Without Captions:

* http://localhost:7080/thai/23463609

    Before - 
Screenshot 2021-11-15 at 14 01 56

  After -
Screenshot 2021-11-15 at 14 02 07

With Captions:

* localhost:7080/afrique/articles/c7yn6nznljdo

Screenshot 2021-11-15 at 14 52 11

LGTM..
