### PR TITLE
Internal Links Transformer

### LINKED ISSUE #4973: Internal Links are broken on stage and test
**Describe the bug**

Links to other CPS assets are not showing rendering properly on LIVE or Stage. 
External links are working as expected. 

See: 
https://www.test.bbc.com/pidgin/media-23259752
Ares: https://ares-broker.test.api.bbci.co.uk/api/asset/pidgin/media-23259752

We are not appending the href to the link so our links just show the end of the URL. 
We will add the href from the link in ares and display the overtyped value in the link. 

Screenshot 2019-12-19 at 17 56 59

**To Reproduce**

1. Go to: https://www.test.bbc.com/pidgin/media-23259752
2. Note the inline links that work. 
3. Note that links to other CPS assets are just showing as "pidgin/tori-23145776"

**Expected behavior**
Links to other CPS assets should be supported and users should be able to navigate to other content on the service. 
The link text should display the overtyped value from the ares payload. 

**Screenshots**
Screenshot 2019-12-19 at 17 54 46

Screenshot 2019-12-19 at 17 54 35

**Desktop (please complete the following information):**

- OS: MacOS 10.14
- Browser: Chrome
- Version: 79

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by ryanmccombe**
Resolves https://github.com/bbc/simorgh/issues/4973

**Problem:**
Any block type from CPS can have a "text" block containing an internal link, ie, a link to another CPS asset

These internal links are denoted by "itemMeta" XML within the text, eg:
`hello world <itemMeta>afrique/23248423</itemMeta> lorem ipsum`

Note there can be multiple internal links within the same blob of text

Any block containing such an <itemMeta> tag has a sibling "meta" array within the same block
That meta array contains a metadata object for each internal link

Example of input data: https://www.test.bbc.com/pidgin/23248703.json
Sample internal links can be seen in blocks[6:7] and blocks[8].items[0:2]
Sample external links can be seen in blocks[8].items[3:5]

Broad strategy here is to find all of the text blocks containing <itemMeta>, and convert them over to the same schema used for external links

We already support CPS external links - a later transformer will take those and convert them into the optimo format

**Overall change:** 
_A very high-level summary of easily-reproducible changes that can be understood by non-devs._

**Code changes:**
- _A bullet point list of key code changes that have been made._
- _When describing code changes, try to communicate **how** and **why** you implemented something a specific way, not just **what** has changed._

---

- [ ] I have assigned myself to this PR and the corresponding issues
- [ ] I have added labels to this PR for the relevant pod(s) affected by these changes
- [ ] I have assigned this PR to the Simorgh project

**Testing:**
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

### CODE REVIEW

File: src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/internalLinks/index.js [hunk 1]
```diff
@@ -0,0 +1,99 @@
+import cloneDeep from 'ramda/src/clone';
+import path from 'ramda/src/path';
+
+// Problem:
```
Comment (karinathomasbbc) [inline src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/internalLinks/index.js]: Can we use `/*
insert comments here
*/`
instead of `//` for each line?

File: data/pidgin/cpsAssets/23248703.json [hunk 2]
```diff
@@ -71,7 +71,7 @@
               {
                 "headlines": {
                   "headline": "Lorem ipsum dolor sit amet, consectetur",
-                  "overtyped": "<Media Asset Page>",
+                  "overtyped": "Media Asset Page",
```
Comment (karinathomasbbc) [inline data/pidgin/cpsAssets/23248703.json]: Any change we could make the link names slightly different for each link? (Or does that have to be done in CPS?) e.g. Media Asset Page 1, Media Asset Page 2 etc

**Review by karinathomasbbc — APPROVED** [review]

File: src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/internalLinks/data.js [hunk 3]
```diff
@@ -0,0 +1,610 @@
+module.exports = {
```
Comment (karinathomasbbc) [inline src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/internalLinks/data.js]: What's the difference between data.js and fixture.js?

File: data/pidgin/cpsAssets/23248703.json (hunk 2 above)
Comment (ryanmccombe) [reply data/pidgin/cpsAssets/23248703.json]: This fixture should ideally map to what is in CPS, but I have updated the fixture we actually use for testing the internal links to be Media Asset Page 1, 2, 3 etc

Can't update this fixture fully as it is what we use for testing CpsMain, and resyncing it with what is in CPS breaks most of those tests.

Out of scope for this PR, but will create an issue to update this Pidgin fixture, and associated unit tests over in the CPS page

File: src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/internalLinks/index.js (hunk 1 above)
Comment (ryanmccombe) [reply src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/internalLinks/index.js]: Done 👍

File: src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/internalLinks/data.js (hunk 3 above)
Comment (ryanmccombe) [reply src/app/lib/utilities/preprocessor/rules/cpsAssetPage/convertToOptimoBlocks/blocks/internalLinks/data.js]: Renamed to `inputFixture` and `outputFixture`

**Review by karinathomasbbc — APPROVED** [review]

**Review by pharingee — APPROVED** [review]
LGTM 👍🏾

**Comment by pharingee** [comment]
@ryanmccombe you need to update the bundle size limits
