### PR TITLE
Hide most read when none exist

### LINKED ISSUE #9297: Hide Most Read H2 on Optimo articles where the component fails to render
**Describe the bug**
When the Most Read component contains no items the H2 "Most Read" and page separator are still visible on an Optimo article page. 

**To Reproduce**

1. Go to 'https://www.test.bbc.com/arabic/articles/cl5m3453w36o'
2. Scroll down to 'Most Read'
4. Note that the H2 is visible 

Screenshot 2021-08-05 at 10 28 08

**Expected behaviour**
In the scenario where most read contains no items the H2 should not be visible on Optimo Article pages. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

### PR DESCRIPTION
**Pull request by nicola-d-bbc**
Resolves #9297

**Overall change:**
Removed 'Most Read' section when no article data is found in response.

Response with no data:
https://www.test.bbc.com/arabic/mostread.json

**Code changes:**

- Added condition to container render if response item length is greater than 0.
- Added new test to check if no container renders if there are no items in the data.

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project
- [ ] (BBC contributors only) This PR follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Testing:**

- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false yarn test:e2e:interactive`)
- [ ] This PR requires manual testing

### CODE REVIEW

File: src/app/containers/MostRead/Canonical/index.jsx [hunk 1]
```diff
@@ -101,52 +101,54 @@ const CanonicalMostRead = ({
...
-            key={item.id}
-            columnLayout={columnLayout}
-            ref={viewRef}
-          >
-            <MostReadRank
-              service={service}
-              script={script}
-              listIndex={i + 1}
-              numberOfItems={items.length}
+    items.length > 0 && (
```
Comment (HarveyPeachey) [inline src/app/containers/MostRead/Canonical/index.jsx]: Just a small thing here, it would make it easier to read if we set this boolean to a named const like `hasMostReadItems` or similar

**Review by HarveyPeachey — COMMENTED** [review]
Looks great!

File: src/app/containers/MostRead/Canonical/index.jsx (hunk 1 above)
Comment (HarveyPeachey) [reply src/app/containers/MostRead/Canonical/index.jsx]: Actually you could just add a check in the above [if statment](https://github.com/bbc/simorgh/blob/1063ca230e06480b887aced1685b235effa667f4/src/app/containers/MostRead/Canonical/index.jsx#L97-L99), (!items || items.length === 0)

Comment (rebeccamcginn) [reply src/app/containers/MostRead/Canonical/index.jsx]: You can remove line 104 as it will always be true due to line 97

**Review by HarveyPeachey — APPROVED** [review]
Just to reiterate on @rebeccamcginn [comment](https://github.com/bbc/simorgh/pull/9304#discussion_r686682633), when this is removed you should be good to go!

**Review by rebeccamcginn — APPROVED** [review]
Nice :)

**Comment by paruchurisilpa** [comment]
Testing:

* Checked using https://localhost:7080/arabic/articles/cl5m3453w36o
* 'Most Read' section is removed when there no article data in the response.

LGTM..
