### PR TITLE
Fix CpsOnwardJourney a11y attributes for most watched

### LINKED ISSUE #7939: Most Watched a11y - remove component region landmark
**Describe the bug**

There should be no region for the component
it should just sit within ‘main’

Remove component region landmark 
the ‘section’ needs changing to a ‘div’ html element, and the role region and the aria-labelledby attributes need removing
Screenshot 2020-09-28 at 10 29 11

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to Most Watched page
2. Inspect the page using lighthouse 
3. Note the errors 

**Expected behaviour**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by RichardPK**
Resolves #7939

**Overall change:**
- Bring in request context to `CpsOnwardJourney` and build a11y object conditionally based on whether the page type is 'mostWatched'

**Code changes:**

- Change `a11yAttributes` depending on whether page is mostWatched or not
- Update snaps

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added the `cross-team` label to this PR if it requires visibility across World Service teams
- [x] I have assigned this PR to the Simorgh project

**Testing:**

- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] This PR requires manual testing

### CODE REVIEW

File: src/app/containers/CpsOnwardJourney/index.jsx [hunk 1]
```diff
@@ -159,12 +160,16 @@ const CpsOnwardJourney = ({
...
-  };
   const { script, service, dir } = useContext(ServiceContext);
+  const { pageType } = useContext(RequestContext);
+
+  const isMostWatched = pageType === 'mostWatched';
+  const a11yAttributes = isMostWatched
+    ? {
+        as: 'div',
+      }
+    : { as: 'section', role: 'region', 'aria-labelledby': labelId };
```
Comment (pharingee) [inline src/app/containers/CpsOnwardJourney/index.jsx:171]: You might want to keep the label since it's used by e2es. You should check with @LilyL0u on that. Otherwise, it looks good to me

**Review by pharingee — APPROVED** [review]

File: src/app/containers/CpsOnwardJourney/index.jsx (hunk 1 above)
Comment (RichardPK) [reply src/app/containers/CpsOnwardJourney/index.jsx:171]: It actually still has the e2e label, so all good there I think! 👍 

Screenshot 2020-09-29 at 09 26 07

**Review by jroebu14 — APPROVED** [review]

File: src/app/containers/CpsOnwardJourney/index.jsx (hunk 1 above)
Comment (LilyL0u) [reply src/app/containers/CpsOnwardJourney/index.jsx:171]: I use 'data-e2e=most-watched-heading' in most watched component tests, as well as 'data-e2e=radio-schedule' in schedule tests. They are useful labels :)
