### PR TITLE
Fixes AMP validation: mandatory attribute 'amp-custom' is missing

### LINKED ISSUE #883: Fix AMP validation: mandatory attribute 'amp-custom' is missing
**Describe the bug**
Styled-components renders an inline `<style>` element which is missing a mandatory `amp-custom` attribute on AMP.

It is a known issue but there is no non-hacky fix at the moment: https://github.com/styled-components/styled-components/issues/1231

**To Reproduce**

1. npm run build
2. npm run start
3. in a separate terminal window, do `npx amphtml-validator http://localhost:7080/news/articles/c9rpqy7pmypo.amp || true`
4. See the following error:

`http://localhost:7080/news/articles/c9rpqy7pmypo.amp:1:3610 The mandatory attribute 'amp-custom' is missing in tag 'style amp-custom'. (see https://www.ampproject.org/docs/guides/author-develop/responsive/style_pages)`

**Expected behavior**
No errors

**Screenshots**
The offending component on AMP:
screen shot 2018-11-01 at 12 15 05

**Additional context**
This issue is a subset of #873 and could not be solved as part of #878.

- [ ] Initially labelled with ["bug"](https://github.com/BBC-News/simorgh/labels/bug)

### PR DESCRIPTION
**Pull request by ChrisBAshton**
Resolves #883. Uses AMP fixture data from #958, so blocked on that.

This PR fixes the AMP validation error "inline styles must have amp-custom attribute".
(NB: There will still be a stray `<style data-styled-components></style>` in the page as this is added by styled-components - but this will go away once #907 is merged - proven by merging #907 into this branch over here: [a523990f7d6ee928d9c79c46935245c828e8649c](https://github.com/BBC-News/simorgh/commit/a523990f7d6ee928d9c79c46935245c828e8649c)).

This seems to be the best solution for the time being, according to [styled-components/styled-components#1231](https://github.com/styled-components/styled-components/issues/1231)"

- [ ] Tests added for new features
- [ ] Test engineer approval

### CODE REVIEW

**Review by bcmn — DISMISSED** [review]

File: src/server/index.jsx [hunk 1]
```diff
@@ -104,14 +104,17 @@ server
 
       const headHelmet = Helmet.renderStatic();
 
-      const styleTags = sheet.getStyleElement();
+      const styles = sheet.getStyleElement()[0];
```
Comment (dr3) [inline src/server/index.jsx]: IMO we should map over this and accumulate them in `inlineCss`, there's likely a reason its an array

**Review by dr3 — DISMISSED** [review]

File: src/app/components/Document/__snapshots__/index.test.jsx.snap [hunk 2]
```diff
@@ -41,9 +41,9 @@ exports[`Document should render correctly 1`] = `
       href="https://www.bbc.com/news/articles/c9rpqy7pmypo"
       rel="canonical"
     />
-    <style>
-      html { color: red; }
-    </style>
+    <style
+      data-styled-components=""
```
Comment (ChrisBAshton) [inline src/app/components/Document/__snapshots__/index.test.jsx.snap]: Phil pointed out that:
1) `<style>` tag probably shouldn't be added if we have no styles (agreed 👍 )
2) And that we need a snapshot with styles added (agreed 👍 )

Comment (ChrisBAshton) [reply src/app/components/Document/__snapshots__/index.test.jsx.snap]: 1. feels like a premature optimisation (how often will we have _no_ styles?) - so ignored.
2. I've re-added the inline styles test in https://github.com/BBC-News/simorgh/pull/921/commits/7c87b10045500c1ed4d8ec94d69bcd2e2aa0c2d8

But now it looks like we need a snapshot test for AMP, where instead of `data-styled-components` we have `amp-custom` as an attribute.

Comment (ChrisBAshton) [reply src/app/components/Document/__snapshots__/index.test.jsx.snap]: Blocked on #958. (Want to test AMP snapshot).

File: src/server/index.jsx [hunk 3]
```diff
@@ -104,14 +104,23 @@ server
 
       const headHelmet = Helmet.renderStatic();
 
-      const styleTags = sheet.getStyleElement();
+      const stylesheets = [...sheet.getStyleElement()];
```
Comment (pjlee11) [inline src/server/index.jsx]: Could you give some context to why this now needs to be an array?

Comment (ChrisBAshton) [reply src/server/index.jsx]: Have added a comment. https://github.com/BBC-News/simorgh/pull/921/commits/bc3d462ef1f938807b80a44775d7e198b9b978db

**Comment by ChrisBAshton** [comment]
Have raised https://github.com/BBC-News/simorgh/issues/976 to look at fixing later.

File: src/server/index.jsx [hunk 4]
```diff
@@ -104,14 +104,20 @@ server
...
       const headHelmet = Helmet.renderStatic();
 
-      const styleTags = sheet.getStyleElement();
+      let inlineCss = '';
+      try {
+        // eslint-disable-next-line prefer-destructuring
+        inlineCss = renderToString(sheet.getStyleElement()).match(
+          /^<style (?:[^>]+)>([\S\s.]+)<\/style>$/,
+        )[1];
+      } catch (e) {} // eslint-disable-line no-empty
```
Comment (ChrisBAshton) [inline src/server/index.jsx]: _Could_ revert back to the original method, if we wanted to avoid a regex:

```js
      let inlineCss = '';
      // `getStyleElement()` doesn't always return an array, so wrap in a try-catch.
      // TODO: fix in https://github.com/BBC-News/simorgh/issues/976
      try {
        inlineCss = sheet.getStyleElement().reduce(
          (inlineStyles, currentStylesheet) =>
            currentStylesheet
              ? `${inlineStyles}${
                  // eslint-disable-next-line no-underscore-dangle
                  currentStylesheet.props.dangerouslySetInnerHTML.__html
                }`
              : inlineStyles,
          '',
        );
      } catch (e) {} // eslint-disable-line no-empty
```

...but the disadvantage of this approach is if `sheet.getStyleElement()` returns a single object instead of an array, we lose the styles of that object (unless we modify the above code even further).

The advantage of the Regex method is that whatever CSS gets rendered, gets captured.

The _disadvantage_ of the Regex method is that it's brittle: if the `renderToString` or internal `render()` method of the Styled Components library changes, there's a risk we'll deliver a page with no styles.

File: src/app/components/Document/__snapshots__/index.test.jsx.snap (hunk 2 above)
Comment (ChrisBAshton) [reply src/app/components/Document/__snapshots__/index.test.jsx.snap]: #958 is merged now. Ready to code review / merge.

File: src/server/index.jsx [hunk 5]
```diff
@@ -104,14 +104,20 @@ server
 
       const headHelmet = Helmet.renderStatic();
 
-      const styleTags = sheet.getStyleElement();
+      let inlineCss = '';
+      try {
+        // eslint-disable-next-line prefer-destructuring
+        inlineCss = renderToString(sheet.getStyleElement()).match(
```
Comment (dr3) [inline src/server/index.jsx]: If `sheet.getStyleElement()` returns an array with 2 elements inside, instead of 1 (which it theoretically can), This regex will break and only catch the opening tag for the 1st one, and closing tag for the second, meaning invalid css

File: src/server/index.jsx [hunk 6]
```diff
@@ -104,14 +104,20 @@ server
...
+          /^<style (?:[^>]+)>([\S\s.]+)<\/style>$/,
+        )[1];
```
Comment (dr3) [inline src/server/index.jsx]: This throws away the styled components ```<style data-styled-components="jLeGVa hmqJYW jHyUsA kzqBtt jNOQvG aJDbs dNlZTz iIqwzV iQnGvB gSfTCk cYVMCV dVfLHk bzGli kVHsaM PDRnW gMmsmd bkhVuy emBiDe dvYMEz diCwNi lbsaqU fUFvnt bwxfrq kSWLHu eqvZjV jvhmFc" data-reactroot="">```
I have no idea what theyre used for, but its probably something

File: src/app/components/Document/index.jsx [hunk 7]
```diff
@@ -20,6 +20,9 @@ const Document = ({ assets, app, data, styleTags, helmet }) => {
       defer
     />
   ));
+  const inlineStyleAttributes = {};
+  inlineStyleAttributes[data.isAmp ? 'amp-custom' : 'data-styled-components'] =
```
Comment (sareh) [inline src/app/components/Document/index.jsx]: It'd be better to pull this into a small method with an explanatory name, because this is difficult to parse. 
```
// If an AMP page, should use amp-custom attribute
// Else if a canonical page, should use the data-styled-components attribute
const inlineAttributes = (isAmp) => {
    if (isAmp) return { 'amp-custom': ''};
    return { 'data-styled'components': ''};
};
```

File: src/server/index.jsx (hunk 5 above)
Comment (ChrisBAshton) [reply src/server/index.jsx]: Good spot. In that case maybe it's worth switching to [.map() method](https://github.com/BBC-News/simorgh/pull/921#discussion_r234702722) as before (with additional hack to force `getStyleElement()` to return an array).

File: src/server/index.jsx (hunk 6 above)
Comment (ChrisBAshton) [reply src/server/index.jsx]: I think it's used for [rehydration](https://github.com/styled-components/styled-components/blob/0aa3170c255a49cd41c3fbeb2b8051b5d132f229/src/test/rehydration.test.js), to avoid injecting more styles than necessary.

i.e. a new component is added to the page, the component ID is checked against the IDs in the `data-styled-components` attribute and the corresponding styles are injected if the ID is missing.

You're right that we probably need to keep both. This PR is deceptively complicated!

File: src/server/index.jsx [hunk 8]
```diff
@@ -104,14 +104,20 @@ server
 
       const headHelmet = Helmet.renderStatic();
 
-      const styleTags = sheet.getStyleElement();
+      let inlineCss = '';
+      try {
+        // eslint-disable-next-line prefer-destructuring
+        inlineCss = renderToString(sheet.getStyleElement()).match(
+          /^<style (?:[^>]+)>([\S\s.]+)<\/style>$/,
```
Comment (sareh) [inline src/server/index.jsx]: We should pull out the regex logic into a method `styleTagRegex` that is in a separate file, e.g. `src/server/styleRegex.js`. It should have unit tests that capture various examples that we would expect to capture, as well as examples that it shouldn't capture.

The reason we should do this is that the regex - in conjunction with the `getStyleElement` function provided by Styled Components - is fundamental to us having correct loading of styles on our article pages.  So having more detailed unit tests could give us confidence that this will not break.

We should also ensure that we have sufficient tests surrounding the `getStyleElement()` method as it is used in our application. To start with, it would be useful to split this into several lines, to make debugging simpler.

```
const styledComponentStyleElements = sheet.getStyleElement();
const allStyles = renderToString(styledComponentsStyleElements).match(styleRegex);
const inlineCss = allStyles[1]; // ((Explanation why only the second style tag is inlined, not all of the style tags))
```
Then, we could have error handling for the case where `allStyles` is empty. 

Splitting up the logic over multiple lines will enhance readability and maintainability.

**Review by sareh — DISMISSED** [review]
Looks good when looking at it locally. I've suggested changes to enhance readability and also suggested adding unit tests around the newly-added style logic.

File: src/server/index.jsx (hunk 8 above)
Comment (ChrisBAshton) [reply src/server/index.jsx]: Thanks. Totally agreed, except that current PR only allows for one style tag, so I need to fundamentally change how it works as per https://github.com/BBC-News/simorgh/pull/921/files#r234940648.

Implemented in https://github.com/BBC-News/simorgh/pull/921/commits/691ebb6bbdf3637954d8809135926b29945bf09e.

File: src/server/index.jsx (hunk 6 above)
Comment (ChrisBAshton) [reply src/server/index.jsx]: I now retain that info by checking if we're AMP, and if we're NOT AMP, then just `return sheet.getStyleTemplate()` without alteration.

File: src/server/styles.jsx [hunk 9]
```diff
@@ -0,0 +1,26 @@
...
+  const styleTags = sheet.getStyleElement();
+  if (!isAmp) return styleTags;
+
+  // `getStyleElement()` doesn't always return an array, so wrap in a try-catch.
+  // TODO: fix in https://github.com/BBC-News/simorgh/issues/976
+  const styleTagsArray = Array.isArray(styleTags) ? styleTags : [styleTags];
+
+  const inlineCss = styleTagsArray.reduce(
+    (inlineStyles, currentStylesheet) =>
+      // sometimes `currentStylesheet.props` is undefined in the tests. TODO: raise an issue
```
Comment (sareh) [inline src/server/styles.jsx]: Could you please remove the TODO comments. 

Just raising an issue and referring to it in the PR description should be sufficient. Removing the lines of TODOs makes the file more readable.

File: src/server/styles.jsx [hunk 10]
```diff
@@ -0,0 +1,26 @@
...
+      currentStylesheet && currentStylesheet.props
+        ? `${inlineStyles}${
```
Comment (sareh) [inline src/server/styles.jsx]: Please remove the multi line ternary. It makes the code difficult to follow. Returning early with `inlineStyles` if there is no `currentStylesheet` would work in this case.


What was the reason you changed the implementation from the regex one to this?

File: src/server/styles.jsx [hunk 11]
```diff
@@ -0,0 +1,26 @@
+import React from 'react';
+
+export const getStyleTag = (sheet, isAmp = false) => {
+  const styleTags = sheet.getStyleElement();
+  if (!isAmp) return styleTags;
```
Comment (sareh) [inline src/server/styles.jsx:5]: I like this early return statement. Makes it clear what is happening for canonical page types.

File: src/server/styles.jsx (hunk 9 above)
Comment (sareh) [reply src/server/styles.jsx]: I understand that you want to explain reasoning for different choices made here. A comment at the top of the file, with numbers as reference points often declutters the code. 
e.g.
```
// [1] getStyleElement() does not an array when ....
// [2] currentStylesheet.props is undefined in tests
```

with a `// [1]` and `// [2]` on the lines of relevant code.

File: src/server/styles.test.jsx [hunk 12]
```diff
@@ -0,0 +1,31 @@
...
+import { getStyleTag } from './styles'; // eslint-disable-line no-unused-vars
+
+// mock up and render a simple styled application
+const sheet = new ServerStyleSheet();
+const StyledHeading = styled.h1`
+  color: teal;
+`;
+const styleWithAttr = inlineAttribute => `<style ${inlineAttribute} data-reactroot="">
+/* sc-component-id: StyledHeading-av5ml9-0 */
+.StyledHeading-av5ml9-0 {} .gDvQnu{color:teal;}</style>`;
```
Comment (sareh) [inline src/server/styles.test.jsx]: Since you've used the StyledComponents outputted styles here, whenever `styled-components` updates their algorithm for generating classes, these unit tests will fail.

File: src/server/styles.jsx (hunk 9 above)
Comment (ChrisBAshton) [reply src/server/styles.jsx]: Is that the team convention? Seems an odd choice. If & when more comments are needed, the ordering would get messed up, so comments may appear like `[1], [3], [5], [4], [2]`...

[Clean Code](https://www.amazon.co.uk/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882) generally suggests keeping comments as closely positioned to the associated code as possible (if a comment is even necessary!)

I'll go in and remove the TODO comments now 👍

File: src/server/styles.jsx (hunk 10 above)
Comment (ChrisBAshton) [reply src/server/styles.jsx]: `sheet.getStyleElement()` returns an array of `<style>` tags, so the old regex method would only catch the first one. See https://github.com/BBC-News/simorgh/pull/921#discussion_r235094598

File: src/server/styles.jsx (hunk 11 above)
Comment (ChrisBAshton) [reply src/server/styles.jsx:5]: Thanks! 👍

File: src/server/styles.test.jsx (hunk 12 above)
Comment (ChrisBAshton) [reply src/server/styles.test.jsx]: true - but feels like a safe test for now. If and when it becomes a problem with new `styled-components` releases, we can look at changing the test to be less specific.

I doubt they update their algorithm often. What's more likely to change the output is if we change the test css (in this case, `color: teal`) - I noticed adding a newline changes the class name completely (think the CSS string is hashed to make a class name).

Happy for me to Resolve this conversation?

File: src/server/styles.jsx (hunk 10 above)
Comment (ChrisBAshton) [reply src/server/styles.jsx]: I'll remove the ternary 👍

File: src/server/styles.test.jsx (hunk 12 above)
Comment (sareh) [reply src/server/styles.test.jsx]: Yes, they hash the CSS for the class names. 
I've seen changes in the order styles are ouptutted, in a minor update to `styled-components`. 
I'd be okay with keeping this as-is and then review as we pull in changes to styled-components.

**Review by sareh — DISMISSED** [review]
👍 Thanks for making those changes. This looks good. 

I went through the steps to reproduce the bug.

```
    npm run build
    npm run start
```
In a separate terminal window, `npx amphtml-validator http://localhost:7080/news/articles/c9rpqy7pmypo.amp || true`

I did not see this error:  `The mandatory attribute 'amp-custom' is missing in tag 'style amp-custom'. (see https://www.ampproject.org/docs/guides/author-develop/responsive/style_pages)`
👍

**Review by dr3 — DISMISSED** [review]
👍 LGTM, great work

**Comment by jamesbrumpton** [comment]
Spoken with Chris about this. Currently, the Reith fonts do not display on an AMP article, which is different to what is happening on `latest`. This will be going back to In Progress for investigation.

**Comment by ChrisBAshton** [comment]
Current implementation URL-encodes quotemarks. We should be seeing:

```css
@font-face {
  font-display: optional;
  font-family: ReithSansNewsRegular;
  font-style: normal;
  font-weight: 400;
  src: url("https://gel.files.bbci.co.uk/r2.302/BBCReithSans_W_Rg.woff2")
      format("woff2"),
    url("https://gel.files.bbci.co.uk/r2.302/BBCReithSans_W_Rg.woff")
      format("woff");
}
```

...but are actually seeing:

```css
@font-face {
  font-display: optional;
  font-family: ReithSansNewsRegular;
  font-style: normal;
  font-weight: 400;
  src: url(&#x27;https://gel.files.bbci.co.uk/r2.302/BBCReithSans_W_Rg.woff2&#x27;)
      format(&#x27;woff2&#x27;),
    url(&#x27;https://gel.files.bbci.co.uk/r2.302/BBCReithSans_W_Rg.woff&#x27;)
      format(&#x27;woff&#x27;);
}
```

File: src/server/styles.jsx [hunk 13]
```diff
@@ -0,0 +1,25 @@
...
+      return `${inlineStyles}${
+        // eslint-disable-next-line no-underscore-dangle
+        currentStylesheet.props.dangerouslySetInnerHTML.__html
+      }`;
+    }
+    return inlineStyles;
+  }, '');
+
+  return (
+    <style amp-custom="" dangerouslySetInnerHTML={{ __html: inlineCss }} />
```
Comment (ChrisBAshton) [inline src/server/styles.jsx:21]: Had to add `dangerouslySetInnerHTML` to not escape quotes.

File: src/server/styles.test.jsx [hunk 14]
```diff
@@ -0,0 +1,45 @@
...
+      const inlineCss = renderToString(getStyleTag(sheet));
+      expect(inlineCss).toBe(
+        expectedOutput('data-styled-components="gDvQnu bKGMUB"'),
+      );
+    });
+  });
+
+  describe('AMP version', () => {
+    const isAmp = true;
+    it('should respond with amp-custom attribute and should not URL-encode quotes', async () => {
```
Comment (ChrisBAshton) [inline src/server/styles.test.jsx:40]: Would have liked to have split these out into multiple fixtures and assertions, but StyledComponents acts as a singleton, so even if we keep making new instances:

`const sheet = new ServerStyleSheet();`

...it just keeps adding styles into its cache (ie we can write tests that pass in isolation but fail when run in sequence).

I then tried splitting out the test.jsx file into multiple test.jsx files but kept getting the `The clone method cannot be used on the client!` error inside styled-components.

Overall, pretty happy with the final solution.

**Review by pjlee11 — APPROVED** [review]

**Review by bcmn — APPROVED** [review]

**Comment by ChrisBAshton** [comment]
James noticed a noJS AMP issue but we've decided to encapsulate this in its own issue and investigate it later: https://github.com/BBC-News/simorgh/issues/1009

**Comment by jamesbrumpton** [comment]
LGTM
