### PR TITLE
Adjust display based on screen size for OD TV

### LINKED ISSUE #7060: Spacings + Padding OD TV
**Describe the bug**

Spacing above the player should be:
240 - 399px. 8px 
400 - 1007px. 16px. 
1008+ 40px

Spacing below the player at 1008+ should be 40px

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.test.bbc.com/somali/bbc_somali_tv/tv_programmes/w13xttqt
2. Inspect element
4. See padding/spacing errors

**Expected behaviour**

**Screenshots**
Implementation to match designs

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**
Consult Ed if questions arise

### PR DESCRIPTION
**Pull request by rebeccamcginn**
Resolves #7060

**Overall change:**
Fixed the spacing above and below the media player. The spacing above the player is now the following:

- 240 - 399px -> 8px
- 400 - 1007px -> 16px
- 1008 -> 40px

The spacing below the player at 1008+ is now 40px

**Code changes:**

- Added media queries to change the spacing based on screen size
- Removed unnecessary `StyledGelWrapperGrid`
---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] I have added labels to this PR for the relevant pod(s) affected by these changes
- [x] I have assigned this PR to the Simorgh project

**Testing:**

- Tested the following behaviour: Each screen size for the video position, the NoJS message position, and the expired episode messge
- [ ] This PR requires manual testing

### CODE REVIEW

**Review by ryanmccombe — APPROVED** [review]

File: src/app/pages/OnDemandTvPage/index.jsx [hunk 1]
```diff
@@ -168,28 +176,21 @@ const OnDemandTvPage = ({ pageData }) => {
           <VisuallyHiddenText as="h1" tabIndex="-1" id="content">
             {brandTitle}, {formattedTimestamp}
           </VisuallyHiddenText>
-          <StyledGelWrapperGrid
```
Comment (RichardPK) [inline src/app/pages/OnDemandTvPage/index.jsx:171]: -1 nested grid?

+1 kudos

**Review by RichardPK — APPROVED** [review]

**Review by karinathomasbbc — APPROVED** [review]
Looks good 👍
