### PR TITLE
Revert "Revert "ATI Non-JS Tracking""

### LINKED ISSUE #4711: Non-JS tracking is not working on new front pages (and maybe other page types?)
**Describe the bug**
Non-js tracking is not tracking any page views of new Simorgh front pages in ATI. 
The existing front pages on PAL are tracking page views in ATI. 

This means it is not tracking anything on the following pages:
igbo.page
pidgin.page
yoruba.page
punjabi.page
thai.page
azeri.page
kyrgyz.page

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by itimirichard**
Resolves #4711

**Overall change:** _Added the `x8` param to the ATI URL parameters for all page types to track js/nonjs requests._

**Code changes:**

- _Created a `getLibraryVersion` util function that returns `simorgh` for both AMP and canonical JS 
 enabled pages and `simorgh-nojs` for nojs pages._
- _modified `buildParams.js` for all page types to accommodate the new `libraryVersion` (`x8`) key and corresponding value _

---

- [x] I have assigned myself to this PR and the corresponding issues
- [x] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [x] This PR requires manual testing

The initial PR was accidentally merged without manual testing
- Initial PR https://github.com/bbc/simorgh/pull/4830
- Revert PR https://github.com/bbc/simorgh/pull/4898

### CODE REVIEW

File: src/app/lib/analyticsUtils/index.js [hunk 1]
```diff
@@ -261,3 +261,7 @@ export const getComponentInfo = ({ result, componentName, componentData }) => {
     },
   };
 };
+
+export const getLibraryVersion = () => {
```
Comment (samora) [inline src/app/lib/analyticsUtils/index.js]: If all this function does is return 'simorgh' string why can't we just make it a string constant called `LIBRARY_VERSION` or so?

**Review by samora — CHANGES_REQUESTED** [review]

File: src/app/lib/analyticsUtils/index.js (hunk 1 above)
Comment (itimirichard) [reply src/app/lib/analyticsUtils/index.js]: @samora This has been refactored

File: src/app/containers/ATIAnalytics/canonical/index.jsx [hunk 2]
```diff
@@ -21,7 +21,7 @@ const CanonicalATIAnalytics = ({ pageviewParams }) => {
         // lazy and didn't want to write a fuzzy matcher for the unit AND e2e
         // tests (you can't predict the class names chosen by styled-components)
         style={{ position: 'absolute' }}
-        src={atiPageViewUrl}
+        src={atiPageViewUrl.replace('x8=[simorgh]', 'x8=[simorgh-nojs]')}
```
Comment (jroebu14) [inline src/app/containers/ATIAnalytics/canonical/index.jsx]: Just realised I think we need to add some logic around this in case the url doesn't have `'x8=[simorgh]'` because if it doesn't then `'x8=[simorgh-nojs]'` won't be switched in. I'd check for the presence of `'x8=[simorgh]'` in the string before replacing. If it doesn't have it in the string then add it on

Comment (itimirichard) [reply src/app/containers/ATIAnalytics/canonical/index.jsx]: @jroebu14  Thats a good suggestion, although the logic is such that an `x8=[simorgh]` value is always present in the url. However I've added this check just as a failsafe.

File: src/app/containers/ATIAnalytics/canonical/index.jsx [hunk 3]
```diff
@@ -21,7 +21,11 @@ const CanonicalATIAnalytics = ({ pageviewParams }) => {
         // lazy and didn't want to write a fuzzy matcher for the unit AND e2e
         // tests (you can't predict the class names chosen by styled-components)
         style={{ position: 'absolute' }}
-        src={atiPageViewUrl}
+        src={
+          atiPageViewUrl.includes('x8=[simorgh]')
+            ? atiPageViewUrl.replace('x8=[simorgh]', 'x8=[simorgh-nojs]')
+            : atiPageViewUrl
```
Comment (jroebu14) [inline src/app/containers/ATIAnalytics/canonical/index.jsx]:
```suggestion
            : `${atiPageViewUrl}&x8=[simorgh-nojs]`;
```

Comment (jroebu14) [reply src/app/containers/ATIAnalytics/canonical/index.jsx]: what about refactoring to be like

```jsx
const getNoJsAtiPageViewUrl = atiPageViewUrl =>
  atiPageViewUrl.includes('x8=[simorgh]')
    ? atiPageViewUrl.replace('x8=[simorgh]', 'x8=[simorgh-nojs]')
    : `${atiPageViewUrl}&x8=[simorgh-nojs]`;

const renderNoScriptTrackingPixel = atiPageViewUrl => (
  <noscript>
    <img
      height="1px"
      width="1px"
      alt=""
      style={{ position: 'absolute' }}
      src={getNoJsAtiPageViewUrl(atiPageViewUrl)}
    />
  </noscript>
);

const CanonicalATIAnalytics = ({ pageviewParams }) => {
  const [atiPageViewUrl] = useState(
    process.env.SIMORGH_ATI_BASE_URL + pageviewParams,
  );

  useEffect(() => {
    sendBeacon(atiPageViewUrl);
  }, [atiPageViewUrl]);

  return renderNoScriptTrackingPixel(atiPageViewUrl);
};
```

Comment (itimirichard) [reply src/app/containers/ATIAnalytics/canonical/index.jsx]: done @jroebu14

**Review by jroebu14 — APPROVED** [review]
thanks Richard

**Comment by itimirichard** [comment]
> thanks Richard

No, thank you Jonathan

File: src/app/lib/analyticsUtils/index.js [hunk 4]
```diff
@@ -261,3 +261,5 @@ export const getComponentInfo = ({ result, componentName, componentData }) => {
     },
   };
 };
+
+export const LIBRARY_VERSION = 'simorgh';
```
Comment (jroebu14) [inline src/app/lib/analyticsUtils/index.js]:
```suggestion
export const LIBRARY_VERSION = 'simorgh';
export const LIBRARY_VERSION_NO_JS = 'simorgh-nojs';
```

**Review by samora — APPROVED** [review]

**Review by mykeels — APPROVED** [review]

**Comment by PriyaKR** [comment]
Looks good to me.The Front pages and the article pages now seem to log the library version `x8` for js and non js pages.
