### PR TITLE
Fixes tigrinya and Amharic translations

### LINKED ISSUE #3410: Add Footer Translations for Tigrinya
We need to add footer translations for Tigrinya 

Add the translations to the service configs. Translations available on spreadsheet (pinned in ws-media slack channel or WSMEDIA-29)

**Testing notes**
[Tester to complete]

**Dev insight**: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

This feature is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by ibMadbouly**
Resolves #3410 #3409 #3411 

this PR to put the correct text at the `callToAction` link  (`404`, `500`) for services `amharic` and `tigrinya`

**Code changes:**

- `src/app/lib/config/services/amharic.js`
- `src/app/lib/config/services/tigrinya.js`

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [x] This PR requires manual testing

### CODE REVIEW

File: src/app/lib/config/services/amharic.js [hunk 1]
```diff
@@ -64,7 +64,7 @@ const service = {
           message: 'የሚፈልጉትን ገፅ ማምጣት ባለመቻላችን እናዝናለን። እባክዎ እንደገና ይሞክሩ',
           solutions: ['በገፅዎ ላይ ያለውን ሪፍሬሽ የሚለውን ቁልፍ ይጫኑ', 'እንደገና ይመለሱ'],
           callToActionFirst: 'እንደ አማራጭም እባክዎ ገፃችን ላይ የሚገኘውን ',
-          callToActionLinkText: '[BBC ድረገፅ ይጎብ]',
+          callToActionLinkText: 'BBC ድረገፅ ይጎብ',
```
Comment (jroebu14) [inline src/app/lib/config/services/amharic.js]: Are you sure this is correct? Looking at the translations sheet it says `BBC News [service] ድረገፅ ይጎብኙ` so swapping out `[service]` would produce `BBC News አማርኛ ድረገፅ ይጎብኙ`

File: src/app/lib/config/services/tigrinya.js [hunk 2]
```diff
@@ -55,8 +55,8 @@ const service = {
             'ነቲ ናይ ቢቢሲ መአለሺ ስፍራ ተጠቒምካ ነዚ ገጽ ክትረኽቦ ፈትን',
           ],
           callToActionFirst: 'ከም ኣማራጺ ከኣ ',
-          callToActionLinkText: '[BBC News ረኣይ።]',
-          callToActionLast: '',
+          callToActionLinkText: 'BBC News',
+          callToActionLast: ' ረኣይ።',
           callToActionLinkUrl: 'https://www.bbc.com/tigrinya',
```
Comment (jroebu14) [inline src/app/lib/config/services/tigrinya.js:64]: I don't think this is correct. From the translation sheet `ከም ኣማራጺ ከኣ  [BBC News [service] homepage] ረኣይ።` so then it should be

```js
callToActionFirst: 'ከም ኣማራጺ ከኣ   ',
callToActionLinkText: 'BBC News ትግርኛ homepage',
callToActionLast: ' ረኣይ።',
```

**Comment by jroebu14** [comment]
@ibMadbouly I've left a couple of comments with my concerns about the translations. The translation sheet isn't great. I'm not even sure if what I've suggested is correct. This reiterates the point I made about the translation sheet being hard to use and open to interpretation @aeroplanejane

File: src/app/lib/config/services/amharic.js (hunk 1 above)
Comment (ibMadbouly) [reply src/app/lib/config/services/amharic.js]: Thanks for pointing

File: src/app/lib/config/services/tigrinya.js (hunk 2 above)
Comment (ibMadbouly) [reply src/app/lib/config/services/tigrinya.js:64]: makes sense, thx

Comment (LilyL0u) [reply src/app/lib/config/services/tigrinya.js:64]: I agree, this is a problem accross the sheet. The service name has not been input in the brackets in many places. I assume it would be the same name as the word that appears at the top next to the BBC logo, but cannot be 100% certain there would not be a contextual language difference. Ideally, the translators would have input the service name into the sheet. It is also different accross the sheet, where the word Homepage is sometimes ommitted, or only the word for News is used.

Comment (jroebu14) [reply src/app/lib/config/services/tigrinya.js:64]: From inspecting the translation sheet, I'm assuming that some languages adopt the word `homepage`

File: src/app/lib/config/services/amharic.js (hunk 1 above)
Comment (LilyL0u) [reply src/app/lib/config/services/amharic.js]: I wonder if we need to make this consistent, or leave the translations that were already tested in the past. Some really do not follow the sheet literally; like Indonesian says 'Sebagai alternatif, coba klik Berita', but says 'Sebagai alternatif, coba klik [BBC News [service] homepage]' in the sheet. So the words BBC, homepage and the name of the service were dropped, and only the translation for the word News was made into the link.

File: src/app/lib/config/services/tigrinya.js (hunk 2 above)
Comment (LilyL0u) [reply src/app/lib/config/services/tigrinya.js:64]: So where the word 'homepage' is not translated, we should use the English word 'homepage' as it appears in the sheet? If we follow the sheet strictly, I think your above comment is correct and probably should be used accross all translations, including inputting the service name. However, this means we would need to go back and change some translations on the page (e.g Korean, Indonesian).

Comment (ibMadbouly) [reply src/app/lib/config/services/tigrinya.js:64]: I agree on this, but I think it is more helpful is to have exact screens as acceptance criteria for translations, so we can validate directly against. cause the sheet is bit tricky

**Comment by LilyL0u** [comment]
After Gavin's comments in the stand-up, we should now remove the word 'homepage'.

**Comment by LilyL0u** [comment]
Fixes made. Tigrinya now reads ከም ኣማራጺ ከኣ BBC News ትግርኛ ረኣይ። (with the service name included) and Amharic now reads እንደ አማራጭም እባክዎ ገፃችን ላይ የሚገኘውን BBC News አማርኛ ድረገፅ ይጎብኙ with the service name included and the translated text inside the brackets.

**Review by ryanmccombe — APPROVED** [review]

File: src/app/lib/config/services/tigrinya.js [hunk 3]
```diff
@@ -58,19 +58,19 @@ const service = {
             'ኣብ መአለሺኻ ንዘሎ ደጊምካ መፈተኒ መልጎም ጠውቕ',
             'ነቲ ናይ ቢቢሲ መአለሺ ስፍራ ተጠቒምካ ነዚ ገጽ ክትረኽቦ ፈትን',
           ],
-          callToActionFirst: 'ከም ኣማራጺ ከኣ ',
-          callToActionLinkText: '[BBC News ረኣይ።]',
-          callToActionLast: '',
+          callToActionFirst: 'ከም ኣማራጺ ከኣ   ',
```
Comment (pjlee11) [inline src/app/lib/config/services/tigrinya.js]:
```suggestion
          callToActionFirst: 'ከም ኣማራጺ ከኣ ',
```

This seems to have 3 spaces (`...`) rather then a single space (`.`) - is this on purpose?

File: src/app/lib/config/services/tigrinya.js [hunk 4]
```diff
@@ -58,19 +58,19 @@ const service = {
...
         },
         500: {
           statusCode: '500',
           title: 'ውሽጣዊ ጸገም ሰርቨር',
           message: 'ይቕረታ፡ ነቲ ዝደለኻዮ ገጽ ክነቕርበልካ ኣይከኣልናን። በጃኻ፡ ነዚ ዝስዕብ ፈትን፡',
           solutions: ['ኣብ መአለሺኻ ንዘሎ ደጊምካ መፈተኒ መልጎም ጠውቕ', 'ጸኒሕካ ደጊምካ ፈትን'],
-          callToActionFirst: 'ከም ኣማራጺ ከኣ ',
-          callToActionLinkText: '[BBC News ረኣይ።]',
-          callToActionLast: '',
+          callToActionFirst: 'ከም ኣማራጺ ከኣ   ',
```
Comment (pjlee11) [inline src/app/lib/config/services/tigrinya.js]: Same as https://github.com/bbc/simorgh/pull/3835/files#r325694762

File: src/app/lib/config/services/tigrinya.js (hunk 3 above)
Comment (ibMadbouly) [reply src/app/lib/config/services/tigrinya.js]: not on purpose , just removed the`homepage` word and kept spaces by mistake

**Review by pjlee11 — APPROVED** [review]

**Review by jroebu14 — APPROVED** [review]
