### PR TITLE
Move trust project link

### LINKED ISSUE #3950: Scotland footer links display error
**Describe the bug**
On a BBC Scotland article page: https://www.test.bbc.co.uk/scotland/articles/czwj5l0n210o
The footer links are not displaying correctly.

**To Reproduce**
1. Go to: https://www.test.bbc.co.uk/scotland/articles/czwj5l0n210o
2. Scroll to the end of the page
3. The 'Terms of Use' link is where the 'Why you can trust the BBC' link usually is. The rest of the footer links are spread along the row below.

Footer1

**Expected behavior**
The footer links should all appear in the same section of the footer. E.g. 
Footer2

Note: There should be no 'Why you can trust the BBC' link. Nothing should take its place when this link is not present.

**Screenshots**
See above.

**Desktop (please complete the following information):**

- iOS and Windows

**Smartphone (please complete the following information):**

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

### PR DESCRIPTION
**Pull request by FK78**
Partially resolves #3950

**Overall change:** _Update the Service configs to have the trust project link listed separately from the list, keeping the trust project link still in the footers array link for now._

**Code changes:**

- _Trust project link moved in all configs._

---

- [x] I have assigned myself to this PR and the corresponding issues
- [ ] Automated (jest and/or cypress) tests added (for new features) or updated (for existing features)
- [ ] If necessary, I have run the local E2E non-smoke tests relevant to my changes (`CYPRESS_APP_ENV=local CYPRESS_SMOKE=false npm run test:e2e:interactive`) 
- [ ] This PR requires manual testing

### CODE REVIEW

File: src/app/lib/config/services/afaanoromoo.js [hunk 1]
```diff
@@ -140,15 +140,15 @@ export const service = {
...
+      },
       externalLink: {
         href: 'https://www.bbc.co.uk/help/web/links/',
         text: 'Gara geessituu alaatti akkaataa itti hojjennu dubbisi.',
       },
       links: [
-        {
-          href: 'https://www.bbc.com/afaanoromoo/institutional-49281861',
-          text: 'BBC News maaliif amanuu dandeessa',
-        },
```
Comment (amywalkerdev) [inline src/app/lib/config/services/afaanoromoo.js]: We need to keep the trust project link in the generic link array for now otherwise it will disappear from all services. Once we have implemented the prop to pull this new config in, we can remove it from links.

File: src/app/lib/config/services/scotland.js [hunk 2]
```diff
@@ -147,7 +147,19 @@ export const service = {
       lastUpdated: 'Last updated: ',
     },
     footer: {
+      trustProjectLink: {
```
Comment (amywalkerdev) [inline src/app/lib/config/services/scotland.js]: Scotland won't have a trust project link, so doesn't need it here or in the links array.

**Review by amywalkerdev — CHANGES_REQUESTED** [review]

File: src/app/lib/config/services/scotland.js (hunk 2 above)
Comment (FK78) [reply src/app/lib/config/services/scotland.js]: `trustProjectLink` for Scotland is now an empty object.

**Review by amywalkerdev — APPROVED** [review]
LGTM 👍

**Review by simonsinclair — COMMENTED** [review]
Nice work, @FK78. I checked the changed out locally. According to https://github.com/bbc/simorgh/issues/3950, "Terms of Use" shouldn't be sat outside the main block of links. I noticed this PR is a partial resolution, so I'm assuming this will be fixed in another?

Screen Shot 2019-10-07 at 08 07 49Screen Shot 2019-10-07 at 08 06 41

**Comment by amywalkerdev** [comment]
@simonsinclair yep if you look at Sareh's comment on the original issue it breaks this down into three stages. This is the first one 👍

**Review by simonsinclair — APPROVED** [review]

**Review by j-pendlebury — APPROVED** [review]

**Review by jroebu14 — APPROVED** [review]
LGTM
